src/Tribe/Attendees_Table.php
src/resources/postcss/tickets-report.pcss

[ETP-479]
Dependency for PR:  https://github.com/moderntribe/event-tickets-plus/pull/1074
[ETP-479]: https://moderntribe.atlassian.net/browse/ETP-479

[ETP-479] Render edit attendee column

---

src/resources/js/v2/tickets-block.js

🎫 [ETP-554]
🎥 https://www.loom.com/share/1f0b038899fa4c8a949fe9e5b575de3a
Added changes requested here: https://www.loom.com/share/1f0b038899fa4c8a949fe9e5b575de3a
[ETP-554]: https://moderntribe.atlassian.net/browse/ETP-554

[ETP-554] Tickets block, add/remove issue when paginating.

---

src/admin-views/editor/panel/ticket.php

[ETP-559]
Dependency for: https://github.com/moderntribe/event-tickets-plus/pull/1073
[ETP-559]: https://moderntribe.atlassian.net/browse/ETP-559

[ETP-559] pass down provider for ETP

---

src/views/v2/tickets/item/extra/available/quantity.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/QuantityTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/QuantityTest__test_should_not_render_quantity_block_if_is_unlimited__1.php

🎫 [ETP-561]
🎥 https://www.loom.com/share/7e9a8e04c7e54284a32ef86ad003b01e
[ETP-561]: https://moderntribe.atlassian.net/browse/ETP-561

[ETP-561] Tickets views > fix unlimited issue

---

src/resources/postcss/tickets-forms.pcss

🎫 [ET-401] 
🎥 https://www.loom.com/share/609cdb8577204f079913d6da1a27fc52?from_recorder=1
Modifying some tickets form styles to enable what we need for IAC unique error messages.

[ET-401] IAC > Unique required meta.

---

src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/container.js
src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/template.js
src/modules/blocks/ticket/container-content/container.js
src/modules/data/blocks/ticket/reducers/tickets/ticket/details.js
src/modules/data/blocks/ticket/reducers/tickets/ticket/temp-details.js

**Ticket:** [GTPLAN-47]
This PR fixes the IAC setting that is set in new tickets. Related PRs: https://github.com/moderntribe/event-tickets-plus/pull/1075, https://github.com/moderntribe/tribe-common/pull/1472
**Artifact:**

fix iac configuration on block editor

---

src/resources/js/v2/tickets-block.js
src/resources/postcss/tickets/_block-quantity.pcss
src/resources/postcss/tickets/_block.pcss
src/views/v2/tickets.php
src/views/v2/tickets/item/quantity/number.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/QuantityTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Quantity/NumberTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_mini__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php

🎫 [ETP-922]
🎥 https://www.loom.com/share/ab2fd2527b7b4ce4a3e5aad05d94eddf
- Fixing specificity for the opt-in checkbox.
- Updating classes.
- Fixing tests.

[ETP-922] Fix checkbox specificity

---

src/resources/js/v2/tickets-block.js

🎫 [ETP-549]
🎥 https://www.loom.com/share/d24f049d79404376a48dd92e8eb8dcdc
[ETP-549]: https://moderntribe.atlassian.net/browse/ETP-549

[ETP-549] Description toggle > Fix check

---

src/Tribe/Commerce/PayPal/Main.php
src/Tribe/Tickets.php

[ETP-562]
📹 🗒️ Dev Screencast http://p.tri.be/GdDkDX
[ETP-562]: https://moderntribe.atlassian.net/browse/ETP-562

[ETP-562] Fix for shared capacity ticket update changing stock issue

---

readme.txt
src/Tribe/Main.php

[ET-929]
[ET-929]: https://moderntribe.atlassian.net/browse/ET-929

[ET-929] Update template path for help section

---

src/Tribe/Commerce/PayPal/Main.php
src/Tribe/Tickets.php

[ETP-546]
Dev screencast: https://share.skc.dev/o0umlBAK
Related to the Event Tickets Plus PR: https://github.com/moderntribe/event-tickets-plus/pull/1084
This PR abstracts email sending process for Tribe Commerce.
[ETP-546]: https://moderntribe.atlassian.net/browse/ETP-546

[ETP-546] Abstract email sending process for tickets

---

src/resources/postcss/tickets-v1.pcss

🎫 [ETP-922]
🎥 https://www.loom.com/share/d3443d4cf5db407b83777226996cce95

[ETP-922] V1 checkbox specificity ar fields

---

src/Tribe/Assets.php
src/Tribe/Editor/Blocks/Rsvp.php

🎫 [ETP-560]
🎥 https://www.loom.com/share/b2f6c8c5b0db4a86a48b479d9634e53a
Using tribe-common-responsive both in Tickets V2 and RSVP V2, so we can rely on the design system.
[ETP-560]: https://moderntribe.atlassian.net/browse/ETP-560

[ETP-560] Include `common-responsive` for Tickets v2 and RSVP v2.

---

src/resources/js/v2/tickets-block.js

🎫 [ET-938]
🎥 https://www.loom.com/share/705d6f3f7b0a420492246db28ec77f8e
[ET-938]: https://moderntribe.atlassian.net/browse/ET-938

[ET-938] Tickets block > Add hidden params to the regular checkout.

---

src/admin-views/tribe-options-display.php

[ETP-569]
Display Tab:
Before:
After:
[ETP-569]: https://moderntribe.atlassian.net/browse/ETP-569

ETP-569 remove IAC acronym

---

src/resources/postcss/tickets-registration-page.pcss

[ET-916]
Reverting the changes made here: https://github.com/moderntribe/event-tickets/pull/1819
As we have altered the v1 template here: https://github.com/moderntribe/event-tickets/pull/1802
[ET-916]: https://moderntribe.atlassian.net/browse/ET-916

[ET-916] Fix suffix typo

---

src/modules/blocks/ticket/container-content/attendee-collection/style.pcss
src/resources/postcss/tickets-admin.pcss

🎫 [ETP-544]
🎥 https://www.loom.com/share/790bf307e3664837b1277c395fded9e1
🗨️ [Slack conversation with document.](https://tribe.slack.com/archives/CETKBUDV3/p1605038248074900)
[ETP-544]: https://moderntribe.atlassian.net/browse/ETP-544

[ETP-544] DQA

---

src/Tribe/Attendees_Table.php
src/resources/postcss/tickets-report.pcss

[ETP-479]
Related PR: https://github.com/moderntribe/event-tickets-plus/pull/1088/
[ETP-479]: https://moderntribe.atlassian.net/browse/ETP-479

[ETP-479] Moved Edit column codes to ETP

---

readme.txt
src/admin-views/tribe-options-tickets.php

[ET-954]
Before:
After:
[ET-954]: https://moderntribe.atlassian.net/browse/ET-954

plural tickets

---

readme.txt
src/Tribe/Assets.php
src/Tribe/Attendee_Registration/Service_Provider.php
src/Tribe/Editor/Provider.php
src/Tribe/Main.php
src/Tribe/Plugin_Register.php
src/views/blocks/tickets/submit.php

Manual Attendees > Sync release branches.

---

src/resources/postcss/tickets-forms.pcss

🎫 [ETP-517]
🎥 https://www.loom.com/share/90f54279d7ac493bbb1c58dfae563ed2
Adding compatibility fix for admin styles (form inputs).
[ETP-517]: https://moderntribe.atlassian.net/browse/ETP-517

Manual Attendees > Add compatibility fix for inputs in admin.

---

readme.txt
src/Tribe/Editor/Configuration.php
src/Tribe/Metabox.php
src/admin-views/editor/fieldset/settings-provider.php

[ET-953]
RSVP not included:
Only Tribe Commerce (so no notice) when WooCommerce is inactive:
Classic Editor:
[ET-953]: https://moderntribe.atlassian.net/browse/ET-953

[ET-953] fix multiple providers

---

src/Tribe/Attendee_Repository.php
src/Tribe/Attendees.php
src/Tribe/RSVP.php
src/Tribe/Repositories/Attendee/RSVP.php

No artifacts required.
I did manual checks for RSVP creation and updates from the frontend and seems to be working fine.

Feature/ Create attendee API for RSVP

---

readme.txt
src/modules/blocks/attendees/index.js
src/modules/blocks/rsvp/index.js
src/modules/blocks/ticket/index.js
src/modules/blocks/tickets/index.js

[ET-960]
Dev screencast: https://share.skc.dev/ApuGj1pd
[ET-960]: https://moderntribe.atlassian.net/browse/ET-960

[ET-960] Remove support for customClassName in the ET blocks

---

readme.txt
src/admin-views/admin-welcome-message.php

[ET-958] 2min demo: https://share.getcloudapp.com/12uKyKpx
[ET-958]: https://moderntribe.atlassian.net/browse/ET-958

open ‘Configure Settings’ in new tab

---

src/modules/blocks/tickets/controls/template.js

[ET-953] Per https://moderntribe.atlassian.net/browse/ET-953?focusedCommentId=92536
[ET-953]: https://moderntribe.atlassian.net/browse/ET-953

add period

---

src/resources/postcss/tickets-admin.pcss

[ET-947]
[ET-969]
[ET-947]: https://moderntribe.atlassian.net/browse/ET-947
[ET-969]: https://moderntribe.atlassian.net/browse/ET-969

[ET-947] Changes made as per DQA suggestion

---

src/admin-views/attendees.php

[ETP-499]
[ETP-499]: https://moderntribe.atlassian.net/browse/ETP-499

[ETP-499] Add action hook to show Add new button for Report page

---

src/Tribe/Editor/Warnings.php

[ET-957]
[ET-970]
[ET-957]: https://moderntribe.atlassian.net/browse/ET-957
[ET-970]: https://moderntribe.atlassian.net/browse/ET-970

[ET-957] - Remove brackets from kb link as per DQA

---

src/Tribe/Editor/Warnings.php

[ET-947]
[ET-947]: https://moderntribe.atlassian.net/browse/ET-947

[ET-947] DQA JS Update - Added dependency conditional support for notices

---

readme.txt
src/views/components/loader.php
src/views/v2/components/loader/loader.php
tests/wpunit/Tribe/Tickets/Partials/Tickets/QuantityTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/__snapshots__/LoaderTest__test_should_render_loader__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/__snapshots__/LoaderTest__test_should_render_loader_with_custom_classes__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_mini__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php

🎫 [ETP-588]
🎥 https://www.loom.com/share/23a1be15e1964181a587d1264950fe82
[ETP-588]: https://moderntribe.atlassian.net/browse/ETP-588

[ETP-588] Loader fix

---

src/admin-views/editor/panel/ticket.php

[ET-950] QA repairs
Before: https://share.getcloudapp.com/qGulvzg6
After: https://share.getcloudapp.com/04uNOOqQ
[ET-950]: https://moderntribe.atlassian.net/browse/ET-950

‘front end’ to ‘frontend’ & move Description under Type

---

src/Tribe/Assets.php

🎫 [ETP-541]
🎥 https://www.loom.com/share/f9f81990787945c284f80e5e75ca6cd2
⚠️ Required for https://github.com/moderntribe/event-tickets-plus/pull/1126
[ETP-541]: https://moderntribe.atlassian.net/browse/ETP-541

[ETP-541] Manual Attendees > form meta validation

---

src/admin-views/editor/panel/ticket.php

[ET-950] Artifact for both Ticket and RSVP editing: https://share.getcloudapp.com/L1uOO205 (1min)
[ET-950]: https://moderntribe.atlassian.net/browse/ET-950

[ET-950] text change

---

src/Tribe/Editor/Warnings.php

[ETP-589]
[ETP-589]: https://moderntribe.atlassian.net/browse/ETP-589

[ETP-589] Fixed showing recurring warning on other post types and article link update

---

src/resources/js/tickets.js

[ET-947]
[ET-947]: https://moderntribe.atlassian.net/browse/ET-947

[ET-947] Fix showing notice on fragment refresh

---

src/Tribe/RSVP.php
src/Tribe/Tickets.php
tests/wpunit/Tribe/Tickets/Email/Email_Test.php

[ET-924]
[ET-924]: https://moderntribe.atlassian.net/browse/ET-924

[ET-924] Modify Ticket Sent counter to track emails

---

src/Tribe/RSVP.php
src/Tribe/Tickets.php
tests/wpunit/Tribe/Tickets/Email/Email_Test.php

[ET-925]
[ET-925]: https://moderntribe.atlassian.net/browse/ET-925

[ET-925] Feature/Attendee Activity logger

---

src/Tribe/Attendee_Registration/Template.php

**Description:** Adds an additional class to the body to target the custom AR page (with shortcode)
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3700

Set body class for when we're on the custom page with the shortcode for AR.

---

readme.txt
src/resources/js/tickets-block.js
src/resources/js/v2/tickets-block.js

[ETP-627]
📹 https://i.bordoni.me/7KubrAky
[ETP-627]: https://theeventscalendar.atlassian.net/browse/ETP-627

[ETP-627] Add compatibility to multiple shortcodes in the same page

---

readme.txt
src/Tribe/Assets.php

🎫 [ETP-629]
🎥 https://www.loom.com/share/e56f4d750347462699a9b8a648ad7dfb?from_recorder=1
[ETP-629]: https://theeventscalendar.atlassian.net/browse/ETP-629

[ETP-629] Localize tribe tickets utils.

---

.travis.yml
dev/functions.sh

**Description:** Updates bucket-customizer-dqa-adjustments branch

Task / update bucket customizer dqa adjustments branch

---

readme.txt
src/resources/postcss/tickets-admin.pcss

🎫 [ETP-624]
🎥 https://www.loom.com/share/8a8d349998d940fe905cf73b96630d61
[ETP-624]: https://theeventscalendar.atlassian.net/browse/ETP-624

[ETP-624] MA > Capitalize `Attendee`

---

src/admin-views/tribe-options-tickets.php

Fix bad merge conflict resolution.

---

src/Tribe/Attendee_Registration/Main.php
src/Tribe/Attendee_Registration/Template.php

🎫 [TEC-3700]
---
📹 https://i.bordoni.me/04uJbwZX
We already have changelogs
[TEC-3700]: https://theeventscalendar.atlassian.net/browse/TEC-3700

Use the correct method to determine if we have a shortcode or not.

---

src/resources/postcss/tickets-forms.pcss

🎫 [ETP-583]
🎥 https://www.loom.com/share/217ac0a23ab7495a9e86fa523e8699c4
[ETP-583]: https://theeventscalendar.atlassian.net/browse/ETP-583

Reset box-shadow for checkboxes and radios on tickets forms.

---

tests/wpunit/Tribe/Tickets/RSVPTest.php
tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set opt-in__1.php
tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set success__1.php

🎫 N/A
📷 https://cloudup.com/cRx6hW6HAX1

Fix wpunit tests.

---

tests/integration/RSVP_Tickets_Test.php

🎫 N/A
📷 https://cloudup.com/cLlTlLc74UL

Fix integration tests - Turn cache off for inventory tests.

---

tests/integration/RSVP_Tickets_Test.php

🎫 N/A
📷 N/A
https://github.com/the-events-calendar/event-tickets/pull/1942/files#r573472170

Remove `codecept_debug` from test

---

readme.txt
src/Tribe/Admin/Views/Ticketed.php

🎫 [ET-1022] 
🎥 https://www.loom.com/share/233fe6da785145e2862710bf83f3cda9
[ET-1022]: https://theeventscalendar.atlassian.net/browse/ET-1022

[ET-1022] Highlight ticketed/unticketed filters when current.

---

readme.txt
src/Tribe/Attendee_Registration/Main.php

🎫 [ETP-360]
🎥 https://www.loom.com/share/b404202d8c6b448b9c94edccf35f22b3
[ETP-360]: https://theeventscalendar.atlassian.net/browse/ETP-360

[ETP-360] Prevent the AR page from using the title from draft pages.

---

readme.txt
src/Tribe/Attendees.php
tests/wpunit/Tribe/Tickets/Attendees_Test.php

[ETP-652]
Screenshot:
Tests Passed:
[ETP-652]: https://theeventscalendar.atlassian.net/browse/ETP-652

Add Columns for Ticket Holder Name and Email for CSV export

---

readme.txt
src/Tribe/Attendee_Repository.php
src/Tribe/Repositories/Traits/Post_Attendees.php

[ET-1021]
[ET-1021]: https://theeventscalendar.atlassian.net/browse/ET-1021

Inverted SQL quotes for MySQL 8.0 compatiblity

---

src/resources/js/v2/tickets-block.js
src/views/v2/tickets/item.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php

🎫 [ETP-516]
🎥 https://www.loom.com/share/1ab48eccfdda447cb1631dae3a9640d5
Some preparation work for what we need in ET+.
[ETP-516]: https://theeventscalendar.atlassian.net/browse/ETP-516

[ETP-516] Show modal if no ar tickets in cart, or submit.

---

readme.txt

Fix ET vimeo video URL for WP.org

---

src/Tribe/Editor/Assets.php
src/Tribe/Editor/Attendee_Registration.php
src/Tribe/Editor/Blocks/Attendees.php
src/Tribe/Editor/Blocks/Rsvp.php
src/Tribe/Editor/Blocks/Tickets.php
src/Tribe/Editor/Blocks/Tickets_Item.php
src/Tribe/Editor/Compatibility/Tickets.php
src/Tribe/Editor/Configuration.php
src/Tribe/Editor/Meta.php
src/Tribe/Editor/Provider.php
src/Tribe/Editor/REST/Compatibility.php
src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
src/Tribe/Editor/Template.php

[ET-982]
Cleaning up the PHP code for the blocks editor implementation.
[ET-982]: https://theeventscalendar.atlassian.net/browse/ET-982

[ET-982] PHP cleanup for blocks editor code.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This is experimental. I'm adding a PR template with what I consider it's the most common things we need in PRs, given our workflow. Also, trying not to super bloat it, keeping it short so we have something consistent that devs can effectively check every time they open a PR.
Open to suggestions.
_Let's discuss here and then we replicate in the other repos_.

[GH]Add initial PR template.

---

readme.txt
src/Tribe/Attendees.php
src/admin-views/attendees.php
src/resources/js/tickets-attendees.js

[ET-981]
Screencast: https://d.pr/v/kq1v2m
[ET-981]: https://theeventscalendar.atlassian.net/browse/ET-981

[ET-981] Add confirmation dialog for bulk deletion of attendees.

---

src/Tribe/Attendee_Repository.php

Added filter on ORM update for future enhancements. 

---

readme.txt
src/resources/postcss/tickets-admin.pcss

[ETP-684] 
Adding border as part of the design/ux improvements.
[ETP-684]: https://theeventscalendar.atlassian.net/browse/ETP-684

[ETP-684] add border

---

src/Tribe/Admin/Settings/Service_Provider.php

N/A
Add the UTM tracker part to KB links, so that we can analyze the link clicks.
N/A
- [] I've included a readme.txt Changelog entry.

Add tracker to KB links for Event Settings Banner

---

package-lock.json
package.json

[ET-1078] 
- Updating the package-lock.json for the packager to work well.
N/A
[ET-1078]: https://theeventscalendar.atlassian.net/browse/ET-1078

[ET-1078] Update package.json and lock for the packager

---

src/resources/postcss/tickets-forms.pcss
src/resources/postcss/tickets/_block-footer.pcss

[ET-1047] 
- Fix compatibility for labels.
- Fix compatibility for tickets button in singular (posts/pages).
https://www.loom.com/share/a435d4fd3c7547faa882af9857446e3c
[ET-1047]: https://theeventscalendar.atlassian.net/browse/ET-1047

Fix compatibility for TwentyTwentyOne.

---

src/Tribe/Attendees_Table.php

[ET-984] 
* Fixed reverted logic during CR changes.
* Remove Check in Action link from action rows for "Not Going" status.
📷 screenshots :
https://d.pr/i/PaeAZC
[ET-984]: https://theeventscalendar.atlassian.net/browse/ET-984

[ET-984] Fixed misplaced logic for Check In button

---

src/Tribe/Admin/Manager/Service_Provider.php

[ET-1079] 
* is_single doesn't work for `pages` type so switched to `is_singular`
N/A
[ET-1079]: https://theeventscalendar.atlassian.net/browse/ET-1079

[ET-1079] Make use of `is_singular` to support pages

---

src/resources/js/tickets.js

[ETP-699] 
- Adding this trigger that have must be erased at some point. ETP is using it on the edit ticket action and it was a miracle that it wasn't working without it.
- No changelog required, as it's part of AR fields improvements and they already have changelogs in place. Started failing since this: https://github.com/the-events-calendar/event-tickets-plus/commit/4332a69cab732345e54960bfefe859f8c37a0546
https://www.loom.com/share/2b8d009ea272459a92ea18f1e3164373
[ETP-699]: https://theeventscalendar.atlassian.net/browse/ETP-699

[ETP-699] AR fields > Fix edit

---

readme.txt
src/resources/postcss/tickets-report.pcss

[ET-768] 
- Set the min width to the fixed value and with to auto so it can play nice with languages where the string is longer.
https://www.loom.com/share/8beea586c3ad4feb8e9cca385604e919
[ET-768]: https://theeventscalendar.atlassian.net/browse/ET-768

[ET-768] Attendee table check-in i18n

---

readme.txt
src/admin-views/editor/list-row.php
src/views/blocks/rsvp/form/quantity-input.php
src/views/blocks/tickets/quantity-number.php
src/views/tickets/rsvp.php
src/views/v2/rsvp/ari/sidebar/quantity/input.php
src/views/v2/tickets/item/quantity/number.php
tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_content__1.php
tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_out_of_stock__1.php
tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_unlimited__1.php
tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Form__test_should_render_form__1.php
tests/wpunit/Tribe/Tickets/Partials/Tickets/QuantityTest.php
tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/Quantity__test_should_render_quantity_available__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/ARI/Sidebar/__snapshots__/QuantityTest__test_should_render_ar_sidebar_quantity__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/ARI/__snapshots__/SidebarTest__test_should_render_ar_sidebar__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Quantity/NumberTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Quantity/__snapshots__/NumberTest__test_should_render_disabled_number_when_must_login_is_true__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Quantity/__snapshots__/NumberTest__test_should_render_number_html__1.php
tests/wpunit/Tribe/Tickets/RSVPTest.php
tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set ari__1.php

[ET-767] 
- Adding label to the quantity input to improve accessibility in the tickets and RSVP forms.
https://www.loom.com/share/47433e15a6e04b7d9b94df9c99b889d4
[ET-767]: https://theeventscalendar.atlassian.net/browse/ET-767

[ET-767] Improve a11y on tickets & rsvp forms

---

readme.txt
src/admin-views/editor/list-row.php
src/resources/postcss/tickets-tables.pcss

[ETP-594] 
- Few small aesthetic changes on the ticket list UI for the classic editor.
- Switching to move cursor so it's more noticeable that the icon is to re-arrange the order of the tickets.
- Adjust width of columns.
- vertical alignment of title and "drag and drop" icon.
- Preparing land for the ET+ inclusion of ARF in this section. https://github.com/the-events-calendar/event-tickets-plus/pull/1206
https://www.loom.com/share/ec55d37caddd4117b63a9bf8fc448a66
[ETP-594]: https://theeventscalendar.atlassian.net/browse/ETP-594

[ETP-594] Aesthetic changes for the ticket ui in classic editor.

---

readme.txt
src/resources/js/v2/tickets-block.js

[ETP-715] 
- Modify the cart footer calculations for the ticket block. Do not account for hidden elements, so it can be used from the AR modal cart and have the right numbers.
https://www.loom.com/share/27f7f6d7906c4b77982123306355a26c
[ETP-715]: https://theeventscalendar.atlassian.net/browse/ETP-715

[ETP-715] Tickets block > Update footer calculations

---

src/resources/postcss/tickets-tables.pcss

[ETP-594] 
- Add `table-layout: fixed` for chrome overflow.
- No changelog entry required. Finding while testing in chrome.
https://cloudup.com/coBb3rwgItp
[ETP-594]: https://theeventscalendar.atlassian.net/browse/ETP-594

[ETP-594] Add `table-layout: fixed` for chrome overflow.

---

src/resources/js/v2/tickets-block.js

[ETP-715] 
- Update the items to cart/checkout to only visible so the removal from the modal, and later submission adds the proper amount to the cart.
- No changelog entry required. This was a QA finding.
https://www.loom.com/share/0ecfad43c32a4e2d8ea8dc8fe83f1e67
[ETP-715]: https://theeventscalendar.atlassian.net/browse/ETP-715

[ETP-715] adjust cart checkout data

---

src/resources/postcss/tickets-tables.pcss

[ETP-594] 
- Updating the icon size to 16px as per David's request.
- No changelog entry needed.
[ETP-594]: https://theeventscalendar.atlassian.net/browse/ETP-594

[ETP-594] DQA for ETP-594

---

.github/workflows/zip.yml

This gives GitHub Actions the ability to zip and upload to Wasabi.

GitHub Action-based zip packaging

---

gulpfile.js
package-lock.json
package.json
webpack.config.js

N/A
This PR installs product taskmaster from npm rather than github.
On hold until https://github.com/the-events-calendar/tut/pull/7 is merged.
`npm run build` runs successfully

Install product taskmaster from npm

---

readme.txt
src/Tribe/Assets.php

[ETP-725] 
* This fixes an issue where the decimal pointer filter for `price_format` localization was not working.
* Also, optimized the loading of Tickets Handler localize data as this is rarely used.
🎥 screencast(s) : https://d.pr/v/A2ke43
[ETP-725]: https://theeventscalendar.atlassian.net/browse/ETP-725

[ETP-725] Using callback for asset data to allow filtering.

---

readme.txt
src/Tribe/Tickets.php

[ET-1135] 
* Add support for HTML tags within Ticket description.
[ET-1135]: https://theeventscalendar.atlassian.net/browse/ET-1135

[ET-1135] - Add support for HTML in ticket description.

---

changelog.txt

[ETP-730] 
HTML entities weren't being correctly decoded. I added a new line on 562 that decodes HTML entities. 
New line of code
Big fix
I have attached a list of HTML entities that you can copy/paste for attendance information to replicate the bug.
[List Of HTML Entities.ods](https://github.com/the-events-calendar/event-tickets/files/6650487/List.Of.HTML.Entities.ods)
https://user-images.githubusercontent.com/12241059/121948996-f7371b80-cd25-11eb-9044-7d35e7a93a1c.mp4
[ETP-730]: https://theeventscalendar.atlassian.net/browse/ETP-730

[ETP-730] special characters not exporting

---

changelog.txt
readme.txt
src/Tribe/Tickets.php

[ETP-112] 
Added new filter `tribe_tickets_attendee_decreases_inventory`. 
New feature
```
function tec_test_attendee_decreases_inventory_filter( $attendees ){                                          
$filterVariable = true;                                                                                   
echo '<hr /> debug script <br /> Attendees: ';                                                            
var_dump( $attendees );                                                                                   
echo '<hr />Filter is set to ' . var_export( $filterVariable , true );                                    
echo '<hr />';                                                                                            
return $filterVariable; …
```

[ETP-112] filter count inventory

---

src/resources/postcss/tickets-tables.pcss

[ET-1107] 
- Updating the width so that it plays well in safari.
- No readme entry required as we're fixing something that came from QA.
https://www.loom.com/share/4a3fcc21b36f46768b305848d796cc8f
[ET-1107]: https://theeventscalendar.atlassian.net/browse/ET-1107

[ET-1107] Remove in classic editor > Update width.

---

tests/_support/Commerce/PayPal/Ticket_Maker.php
tests/wpunit/Tribe/REST/V1/Endpoints/PayPal_Commerce/Payment_Capture_CompletedTest.php
tests/wpunit/Tribe/Tickets/Cache/Transient_CacheTest.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/MainTest.php
tests/wpunit/Tribe/Tickets/Commerce/Tickets_Commerce/Gateways/PayPal_Commerce/GatewayTest.php
tests/wpunit/Tribe/Tickets/Commerce/Tickets_Commerce/Gateways/PayPal_Legacy/GatewayTest.php
tests/wpunit/Tribe/Tickets/Event_RepositoryTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/CreateTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/DeleteTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/FetchTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/UpdateTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
tests/wpunit/Tribe/Tickets/Status/TTPManagerTest.php
tests/wpunit/Tribe/Tickets/Template_Tags/GlobalStockTest.php
tests/wpunit/Tribe/Tickets/Template_TagsTest.php

The artifact for this PR is the passing `wpunit` tests. I'm PR-ing this into master so we can have it from there and merge it into our other branches.

Resolve all outstanding issues with the wpunit tests

---

readme.txt

quick change to remove sale language from readme

remove sale language from readme

---

.github/workflows/tests-php.yml
lang/event-tickets.pot
src/Tribe/Event_Repository.php
src/Tribe/Repositories/Traits/Post_Tickets.php
src/Tribe/Service_Providers/ORM.php
tests/_support/Commerce/PayPal/Ticket_Maker.php
tests/wpunit/Tribe/REST/V1/Endpoints/PayPal_Commerce/Payment_Capture_CompletedTest.php
tests/wpunit/Tribe/Tickets/Cache/Transient_CacheTest.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/MainTest.php
tests/wpunit/Tribe/Tickets/Commerce/Tickets_Commerce/Gateways/PayPal_Commerce/GatewayTest.php
tests/wpunit/Tribe/Tickets/Commerce/Tickets_Commerce/Gateways/PayPal_Legacy/GatewayTest.php
tests/wpunit/Tribe/Tickets/Event_RepositoryTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/CreateTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/DeleteTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/FetchTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/UpdateTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
tests/wpunit/Tribe/Tickets/Status/TTPManagerTest.php
tests/wpunit/Tribe/Tickets/Template_Tags/GlobalStockTest.php
tests/wpunit/Tribe/Tickets/Template_TagsTest.php

Here's a demo of the work in action.
🎥 https://d.pr/v/FuMBQT
Related:
* https://github.com/the-events-calendar/tribe-common/pull/1644
* https://github.com/the-events-calendar/the-events-calendar/pull/3566
* https://github.com/the-events-calendar/events-pro/pull/1787

Calendar Manager Feature -> release/B21.eclair

---

event-tickets.php
src/Tribe/Main.php

N/A 
- Setting release version to unblock QA.
N/A

Set release version number.

---

package-lock.json
package.json
readme.txt

N/A 
- Setting version number so QA can package and test.
N/A

Update version number.

---

src/Tickets/Commerce/Attendee.php
src/Tickets/Commerce/Flag_Actions/Archive_Attendees.php
src/Tickets/Commerce/Flag_Actions/Decrease_Stock.php
src/Tickets/Commerce/Flag_Actions/Flag_Action_Abstract.php
src/Tickets/Commerce/Flag_Actions/Flag_Action_Handler.php
src/Tickets/Commerce/Flag_Actions/Flag_Action_Interface.php
src/Tickets/Commerce/Flag_Actions/Generate_Attendees.php
src/Tickets/Commerce/Gateways/PayPal/Buttons.php
src/Tickets/Commerce/Models/Attendee_Model.php
src/Tickets/Commerce/Models/Order_Model.php
src/Tickets/Commerce/Module.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Repositories/Attendees_Repository.php
src/Tickets/Commerce/Settings.php
src/Tickets/Commerce/Status/Completed.php
src/Tickets/Commerce/Status/Not_Completed.php
src/Tickets/Commerce/Status/Pending.php
src/Tickets/Commerce/Status/Status_Abstract.php
src/Tickets/Commerce/Status/Status_Interface.php
src/views/v2/commerce/checkout/must-login/registration.php
src/views/v2/commerce/gateway/paypal/buttons.php
src/views/v2/commerce/gateway/paypal/checkout-script.php

Things I've handled in this Particular PR:
- Attendee Generation without Attendee data, just to test Stock/Inventory
- Added more data to the Order Meta, specially dates when an order was moved from one status to another and when certain flags were triggered.

Attendee generation is happening + Inventory calculation

---

.github/workflows/tests-php.yml

This tweaks the test workflow so that it skips if no changes to php files AND lets the tests complete successfully.

Skip running PHP tests if no PHP

---

.github/workflows/tests-php.yml
tests/wpunit/Tribe/Tickets/Commerce/PayPal/Stock/SharedCapacityTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_if_has_provider_and_provider_has_same_class_as_ticket_provider__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php

[ET-1155] 
* Fixed test logic for SharedCap tests where Event ID was not getting generated properly.
* Fixed snapshot test logic for Items Test to properly use `setTolerableDifferences` method and remove replacement of HTML. This fixes the unwanted replacements by the GHA for some `POST` and `Event ID`
N/A. Just need to have the `Codeception Tests / test (wpunit --skip-group="capacity")` passed.
[ET-1155]: https://theeventscalendar.atlassian.net/browse/ET-1155

[ET-1155] Sharedcap test fix

---

changelog.txt
readme.txt
src/views/v2/tickets/item.php

[ET-1174] 
🎥 screencast: https://d.pr/v/RgXnlD
[ET-1174]: https://theeventscalendar.atlassian.net/browse/ET-1174

[ET-1174] cast price attribute data to string

---

src/views/v2/tickets/item.php

[ET-1174] 
* Update template versions.
N/A
[ET-1174]: https://theeventscalendar.atlassian.net/browse/ET-1174

[ET-1174] version updated for template

---

src/Tickets/Commerce/Cart.php
src/Tickets/Commerce/Cart/Cart_Interface.php
src/Tickets/Commerce/Cart/Unmanaged_Cart.php

Preventing the cart from having and Additive behavior instead of replacing the whole cart every time.
https://www.loom.com/share/fc976c36b7c04b5f9fd9fc633720e544

Unmanaged cart cannot be additive.

---

src/resources/postcss/rsvp-v1.pcss

[ET-1169] 
Fixes the padding issues when padding is added to the left or right side of the select box to allow for a custom arrow to be shown.
Fixes this issue: https://d.pr/v/fLVO34
[ET-1169]: https://theeventscalendar.atlassian.net/browse/ET-1169

[ET-1169] just remove top and bottom padding

---

src/resources/js/commerce/gateway/paypal/checkout.js

[ET-1212] 
* We reverted back to `Window.Onload` event to fix the triggering of the PayPal button load.
* Using the `$script.load` was not triggering properly as we are using `async` for loading the PayPal script.
N/A
[ET-1212]: https://theeventscalendar.atlassian.net/browse/ET-1212

[ET-1212] Loader not hiding and PayPal buttons not showing up.

---

src/Tickets/Commerce/Settings.php
src/admin-views/settings/tickets-commerce/paypal/connect/inactive.php
src/admin-views/tribe-commerce-settings.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__1.php

[ET-1189] 
- Fix typo on TC payments settings
[ET-1189]: https://theeventscalendar.atlassian.net/browse/ET-1189

[ET-1189] Fix typo on TC payments settings

---

src/Tickets/Commerce/Gateways/PayPal/Buttons.php

[ET-1221] 
- Do not print PayPal buttons if there are no tickets in the cart.
https://cloudup.com/cGymNxbtmEP
[ET-1221]: https://theeventscalendar.atlassian.net/browse/ET-1221

[ET-1221] Avoid printing PayPal buttons if there are no tickets in cart for checkout.

---

src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Repositories/Order_Repository.php

[TICKET_ID] 
* Extend the Order repository to support `cart_hash` meta for Order.
* Create order with `cart_hash` data.
N/A

TC - store cart hash with order

---

src/resources/postcss/tickets-commerce/_checkout.pcss

[ET-1213] 
- Fixing a tribe common override thingy.
[ET-1213]: https://theeventscalendar.atlassian.net/browse/ET-1213

[ET-1213] TC > Checkout notice when no gateway configured

---

src/views/v2/commerce/order/description/order-empty.php
src/views/v2/commerce/order/description/order.php
src/views/v2/commerce/order/header.php
src/views/v2/commerce/order/header/title-empty.php
src/views/v2/commerce/order/header/title.php

[ET-1195] 
- Handle the order page presentation (success shortcode) when there's no order to display.
https://www.loom.com/share/e7e71899be3540f69f48afb9150dc5ed
[ET-1195]: https://theeventscalendar.atlassian.net/browse/ET-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1195] Order page without order.

---

tests/wpunit/Tribe/Tickets/ORM/Tickets/SchemaTest.php

[TICKET_ID] 
* Added tests for the newly added `is_active` schema for Tickets Repository.
📷 screenshot(s): https://d.pr/i/GVkOWL

Added tests for `is_active` schema

---

src/Tribe/Admin/Settings/Service_Provider.php

[ET-1240] 
If Tribe Commerce is disabled, but they've created Tribe Commerce tickets in the past, we want to display a notice about using TIckets Commerce and also link them to an article, explaining how to re-enable Tribe Commerce if they choose to do so.
https://youtu.be/dYY6rCtCqMc

[ET-1240] Tickets Commerce notice banner

---

src/admin-views/admin-welcome-message.php

[ET-1278] 
Updates Setup PayPal links to read Setup Tickets Commerce and point to a new URL
[ET-1278]: https://theeventscalendar.atlassian.net/browse/ET-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TC Update Paypal Link on Setup

---

src/Tribe/Admin/Settings/Service_Provider.php

[ET-1240] 
* Removed redundant logic from upgrade notice.
* Hides general TribeCommerce legacy notice when Tickets Commerce is enabled.
* Added header to TribeCommerce legacy notice to make it relate to TribeCommerce.
📷 screenshot(s)
Before: https://d.pr/i/OkSCpw
After : https://d.pr/i/fcIoqU

[ET-1240] Modify TribeCommerce legacy notice logic.

---

src/Tickets/Commerce/Hooks.php

[TICKET_ID] 
N/A
* Check-In button was showing as disabled as the status label was matched against status slug.
Before: https://d.pr/i/xRoK68
After: https://d.pr/i/89Uqgq

Fixed TicketsCommerce check-in button disabled for Completed attendees.

---

src/admin-views/admin-welcome-message.php

[ET-1278] 
fix typo: Setup -> Set Up in Settings CTA
[ET-1278]: https://theeventscalendar.atlassian.net/browse/ET-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Setup -> Set Up in Settings CTA

---

src/Tickets/Commerce/Order.php

[ET-1300] 
Transform the total price to a numeric string before sending in to PayPal
[ET-1300]: https://theeventscalendar.atlassian.net/browse/ET-1300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Normalize values before sending in to PayPal

---

src/Tribe/Admin/Settings/Service_Provider.php

[ET-1240] 
A quick PR to fix the grammar
N/A

[ET-1240] fix grammar

---

src/resources/postcss/tickets-commerce/_checkout.pcss

N/A 
- Set a fix width to the subtotal so that it works fine with tickets with different prices.

TC > Checkout > Set width for the checkout columns.

---

src/Tribe/Admin/Settings/Service_Provider.php

[ET-1240] 
Adding in the button and link for Tickets Commerce notice banner
https://i.imgur.com/wM0tYA4.png

[ET-1240] Add button and link

---

src/Tribe/Admin/Settings/Service_Provider.php

[ET-1267] 
Per ticket notes, I updated banner text to 'Get started'
[ET-1267]: https://theeventscalendar.atlassian.net/browse/ET-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-1267 - Fix banner text to 'Get started'

---

src/Tickets/Commerce/Flag_Actions/Duplicated_Pending_Orders.php
src/Tickets/Commerce/Flag_Actions/End_Duplicated_Pending_Orders.php
src/Tickets/Commerce/Flag_Actions/Flag_Action_Handler.php
src/Tickets/Commerce/Models/Order_Model.php
src/Tickets/Commerce/Status/Completed.php

See conversation with Sydney here:
https://lw.slack.com/archives/C01T9UJGE2U/p1635885014370700

Move duplicated pending orders to Not Completed once one of them is Completed

---

src/functions/commerce/provider.php

[ET-1267]
[ET-1240]
[ET-1267]: https://theeventscalendar.atlassian.net/browse/ET-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove the version checking piece of Tribe Commerce

---

src/Tickets/Commerce/Admin_Tables/Attendees.php
src/Tickets/Commerce/Reports/Attendees.php

[ET-1316] 
[ET-1316]: https://theeventscalendar.atlassian.net/browse/ET-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1316] revert PHP 5.6 incompatible codes 

---

src/Tickets/Commerce/Gateways/PayPal/Client.php

https://www.loom.com/share/21a62e37f4304f639375005266192a90

Make sure we never pass payee email, merchant ID is enough

---

changelog.txt
readme.txt

N/A 
- Updates on `readme.txt` 
- Updating productstash to loopedin.
- Updating org screenshots, with the new ones David worked on https://theeventscalendar.atlassian.net/browse/ET-1290 
- Sync things to `changelog.txt` - Moving changelog entries there and keeping the most recent versions on `readme.txt`
N/A

Updates on readme. Move entries to changelog.txt

---

readme.txt
src/Tribe/Attendee_Repository.php
tests/_support/Testcases/Html_Partial_Test_Case.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/InactiveTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html

[ET-1320]
https://d.pr/kGuq6R
Fixes a fatal error found by QA
[ET-1320]: https://theeventscalendar.atlassian.net/browse/ET-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1320] fixes fatal error being caused in attendee repo

---

src/Tickets/Commerce/Attendee.php
src/Tickets/Commerce/Flag_Actions/Archive_Attendees.php
src/Tickets/Commerce/Models/Attendee_Model.php
src/Tickets/Commerce/Models/Order_Model.php
src/Tickets/Commerce/Repositories/Attendees_Repository.php
src/Tribe/Tickets_View.php

[ET-1322] 
[ET-1322]: https://theeventscalendar.atlassian.net/browse/ET-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

implement archiving attendees

---

package.json
src/Tribe/Main.php

update version numbers

---

readme.txt
src/Tickets/Commerce/Payments_Tab.php
src/Tickets/Hooks.php

[ET-1232] 
[ET-1233] 
* Auto generate TicketsCommerce Checkout page and Order Success page.
🎥 screencast: https://d.pr/v/ehfkSe
[ET-1232]: https://theeventscalendar.atlassian.net/browse/ET-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-1233]: https://theeventscalendar.atlassian.net/browse/ET-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1232] Auto generate TicketsCommerce Checkout and Order Success page.

---

src/Tickets/Commerce/Legacy_Compat.php
src/Tickets/Commerce/Utils/Price.php

[ET-1330]
[ET-1330]: https://theeventscalendar.atlassian.net/browse/ET-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tickets Commerce should not interact with Tribe Commerce

---

src/Tickets/Commerce/Ticket.php
src/Tickets/Commerce/Utils/Price.php
src/views/v2/commerce/checkout/cart/footer/total.php
src/views/v2/commerce/checkout/cart/item/sub-total.php
src/views/v2/commerce/order/details/total.php

[ET-1330] 
[ET-1330]: https://theeventscalendar.atlassian.net/browse/ET-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Filter currencies on key screens

---

readme.txt
src/Tickets/Commerce/Legacy_Compat.php
src/Tickets/Commerce/Ticket.php
src/Tickets/Commerce/Utils/Price.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/__snapshots__/ItemSubtotalTest__test_should_render_cart_item_subtotal__0.snapshot.html
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/__snapshots__/CartFooterTest__test_should_render_cart__0.snapshot.html
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/__snapshots__/CartTest__test_should_render_cart__0.snapshot.html

[ET-1344] 
Fixes this error:
`( ! ) Error: Maximum function nesting level of '256' reached, aborting! `
It turned out to be an endless loop when currency settings aren't ever set.
https://i.imgur.com/GlqZjnh.png
[ET-1344]: https://theeventscalendar.atlassian.net/browse/ET-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1344] Fix 'Maximum function nesting' error

---

src/Tickets/Commerce/Utils/Value.php

[N/A] 
📷 screenshot: https://d.pr/i/8Vf3px

Avoid fatal error on PHP < 7.3

---

src/Tribe/Editor/Assets.php

Fixes the inadvertently deleted `app/blocks.css` asset.

Fix Iguanodon!

---

src/Tribe/Tickets_Handler.php

[ETP-497] 
* QA repair to fix saving shared cap data.
[ETP-497]: https://theeventscalendar.atlassian.net/browse/ETP-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-497] - Fixed initial saving of shared capacity data

---

src/resources/postcss/tickets-tables.pcss

[ET-1349] 
Since we are using an SVG file as a BG image for the icon, I used the `mask-image` property so that we could change the colors of the icon when hovering over it. It is supported by all browser except for IE (which we do not support).
N/A
[ET-1349]: https://theeventscalendar.atlassian.net/browse/ET-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1349] Duplicate Ticket - one more DQA change

---

src/Tickets/Commerce/Legacy_Compat.php

[GTRIA-726] 
TC already had a cost formatting reset feature for legacy formatting functions in ET. We're now applying that same filter to the cost formatting functions in TEC (only when it applies to Tickets Commerce).
[GTRIA-726]: https://theeventscalendar.atlassian.net/browse/GTRIA-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

apply TC cost reset to a TEC filter

---

src/admin-views/editor/list-row.php

[ET-1349] 
Change the way we detect if we're editing a CE event on the front end.
N/A
[ET-1349]: https://theeventscalendar.atlassian.net/browse/ET-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1349] Duplicate Ticket - remove duplicate button on CT (attempt #2)

---

src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
src/Tickets/Commerce/Gateways/Manager.php
src/Tickets/Commerce/Payments_Tab.php
src/admin-views/settings/tickets-commerce/gateways/button.php
src/admin-views/settings/tickets-commerce/gateways/item.php
src/admin-views/settings/tickets-commerce/gateways/status.php
src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss

[ET-1356] 
This ticket pertains to the style and functionality of the gateways list at the top of the page when you go to Events -> Settings -> Payments. 
https://youtu.be/AIGWxAYuvwA
[ET-1356]: https://theeventscalendar.atlassian.net/browse/ET-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1356] gateways list

---

src/Tickets/Commerce/Gateways/Stripe/Assets.php
src/Tickets/Commerce/Gateways/Stripe/Client.php
src/resources/js/commerce/gateway/stripe/checkout.js
src/views/v2/commerce/gateway/stripe/card-element.php
src/views/v2/commerce/gateway/stripe/form.php
src/views/v2/commerce/gateway/stripe/payment-element.php

Took a stab at the Code from to make the JS follow the ES6 standards that we are trying to move to and some small fixes that were triggering Notices.

Modify the Stripe JS to better adhere to our Standards

---

readme.txt

N/A 
- Bump version number on `readme.txt`
N/A

Bump version number on `readme.txt`

---

src/Tickets/Commerce/Gateways/Stripe/Client.php
src/Tickets/Commerce/Gateways/Stripe/Settings.php

[ET-1368] 
do not merge before #2273 
[ET-1368]: https://theeventscalendar.atlassian.net/browse/ET-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add placeholder for statement descriptor

---

src/Tickets/Commerce/Gateways/Stripe/Settings.php
src/resources/js/commerce/gateway/stripe/checkout.js

remove settings check for collecting billing details

---

readme.txt
src/Tribe/Editor/Blocks/Tickets.php
src/Tribe/Editor/Provider.php

https://github.com/the-events-calendar/events-virtual/pull/370
https://github.com/the-events-calendar/event-tickets/pull/2275
https://github.com/the-events-calendar/events-pro/pull/1889
https://github.com/the-events-calendar/tribe-common/pull/1708 
https://github.com/the-events-calendar/the-events-calendar/pull/3763

Performance improvements for the Blocks Assets

---

src/Tickets/Commerce/Gateways/Stripe/Status.php

fix missing requires_source status

---

src/Tickets/Commerce/Gateways/Stripe/Hooks.php
src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
src/Tickets/Commerce/Gateways/Stripe/Settings.php
src/resources/js/commerce/gateway/base.js

Stripe Minor Fixes

---

src/Tickets/Commerce/Gateways/Stripe/Client.php

[ET-1368] 
[ET-1368]: https://theeventscalendar.atlassian.net/browse/ET-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

get statement descriptor in different forms

---

src/Tribe/Editor/Blocks/Tickets.php

Use proper formatting for JS data on tickets block

---

changelog.txt

N/A 
- Sync changelog, wasn't in sync.
N/A

Sync changelog.

---

tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/ARI/__snapshots__/SidebarTest__test_should_render_ar_sidebar__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/TicketsTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php

Fix snapshot tests for juravenator branch

---

src/resources/js/commerce/gateway/paypal/checkout.js

N/A 
Fixes the notice that keeps appearing on checkout page when paypal isn't active/enabled.
https://i.imgur.com/0EP0gOo.png

Fix for Notice on Checkout

---

src/Tickets/Commerce/Gateways/PayPal/REST/On_Boarding_Endpoint.php
src/Tickets/Commerce/Gateways/PayPal/Settings.php
src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-access-token.php
src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-connection.php
src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-user-info.php
src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-webhook.php
src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/ActiveTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/ActiveTest__test_should_render__0.snapshot.html

[ET-1355] 
- Added space above submit button
- Redirect to PayPal section after connecting to PayPal
DQA: https://www.figma.com/file/TvIXoUEJAGb0AptZI260UO/TicketsCommerce?node-id=1732%3A307
[ET-1355]: https://theeventscalendar.atlassian.net/browse/ET-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1355] DQA Modifcations: PayPal Section

---

src/Tickets/Commerce/Gateways/Stripe/Client.php
src/Tickets/Commerce/Gateways/Stripe/Gateway.php
src/Tickets/Commerce/Gateways/Stripe/Hooks.php
src/Tickets/Commerce/Gateways/Stripe/Merchant.php
src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php

Deny Connections to Accounts we can't serve

---

src/resources/js/commerce/gateway/stripe/checkout.js

[ET-1396] 
- Implement the loader for Stripe's checkout.
https://user-images.githubusercontent.com/252415/153622551-4757d8ff-35ca-4eef-b907-1f3bac2e9e34.mov
[ET-1396]: https://theeventscalendar.atlassian.net/browse/ET-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1396] TC > Stripe > Implement the loader for the stripe checkout.

---

src/resources/js/v2/tickets-commerce.js

N/A 
- Fixing the npm lint problem for mixed es5/6 on `v2/tickets-commerce.js`
- N/A

Fix npm lint problem.

---

src/Tickets/Commerce/Gateways/Stripe/Assets.php
src/resources/js/commerce/gateway/stripe/checkout.js
src/resources/postcss/tickets-commerce/gateway/stripe/_stripe.pcss

[ET-1390] 
Added text color to card element inputs.
DQA COmment: https://i.imgur.com/PSuO5Of.png
[ET-1390]: https://theeventscalendar.atlassian.net/browse/ET-1390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1390] DQA Modifications: Card Element Styling

---

src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-status.php

Spotfix -  Fixed fatal typo on stripe settings title

---

src/resources/js/commerce/gateway/stripe/checkout.js

[ET-1413] 
* Display stripe errors on checkout notice component.
📷 screenshot(s): https://d.pr/i/kQSr7s || https://d.pr/i/42nEdb
[ET-1413]: https://theeventscalendar.atlassian.net/browse/ET-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1413] Fix/et 1413 stripe checkout error display

---

src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete.php

[ET-1410] 
Corrects the class for the paypal modal.
DQA Finding: https://www.figma.com/file/TvIXoUEJAGb0AptZI260UO/TicketsCommerce?node-id=1842%3A256
After fix: https://i.imgur.com/h0ZCpDU.png
[ET-1410]: https://theeventscalendar.atlassian.net/browse/ET-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1410] DQA Modifications: Fix Modal Styling

---

src/resources/js/commerce/gateway/stripe/checkout.js

[ET-1390] 
Adds error handling to individual CardElement fields
N/A
[ET-1390]: https://theeventscalendar.atlassian.net/browse/ET-1390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1390] Add Error Messages for Separate CardElement Fields

---

src/Tickets/Commerce/Gateways/Contracts/Webhook_Event_Interface.php
src/Tickets/Commerce/Gateways/Stripe/Provider.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Events.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php

[ET-1415] 
[ET-1415]: https://theeventscalendar.atlassian.net/browse/ET-1415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce webhook handles for charge events

---

src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Events.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
src/Tickets/Commerce/Order.php

[ET-1409] 
[ET-1409]: https://theeventscalendar.atlassian.net/browse/ET-1409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix charge webhooks

---

src/Tickets/Commerce/Gateways/Stripe/Assets.php
src/Tickets/Commerce/Gateways/Stripe/Hooks.php
src/Tickets/Commerce/Gateways/Stripe/Settings.php

N/A 
- Align styles for payment elements with our form styles.
- Only throw settings error for the empty value of payment methods if saving the payments element.

DQA - Stripe

---

src/resources/postcss/tickets-commerce/_checkout.pcss
src/views/v2/commerce/checkout/footer/gateway-error.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Footer/GatewayErrorTest.php

N/A 
- Show checkout alert when no gateways are enabled and active
- Add space above the default payments toggle
N/A

DQA Mods: Disabled Gateways Alert and Toggle Spacing

---

src/Tickets/Commerce/Gateways/Stripe/Payment_Intent.php
src/resources/js/commerce/gateway/stripe/checkout.js
src/views/v2/commerce/checkout/header/title.php

[TICKET_ID] 
Before the Fix: https://d.pr/i/81ebXk
After the Fix: https://d.pr/i/AYTm00

Spotfix - Empty cart showing error from Stripe gateway

---

src/Tickets/Commerce/Gateways/Stripe/Settings.php
src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-currency.php

- N/A 
- Adjusting the currency mismatch messages.

Adjust currency messages

---

src/Tickets/Commerce/Status/Denied.php
src/Tickets/Commerce/Status/Pending.php
src/Tickets/Commerce/Status/Refunded.php
src/Tickets/Commerce/Status/Reversed.php
src/Tickets/Commerce/Status/Status_Abstract.php
src/Tickets/Commerce/Status/Status_Interface.php
src/Tickets/Commerce/Status/Voided.php

[ET-1423] 
[ET-1423]: https://theeventscalendar.atlassian.net/browse/ET-1423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce the concept of a "final" post status

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Settings.php

Readme updates.

---

readme.txt

[TICKET_ID] 
I updated the readme.txt to include copy from Magenta team regarding the latest Stripe updates

udpate readme.txt with stripe info

---

tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_if_has_provider_and_provider_has_same_class_as_ticket_provider__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemsTest__test_should_render_if_not_empty_tickets_on_sale__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_mini__1.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php

[ET-1449] 
[ET-1449]: https://theeventscalendar.atlassian.net/browse/ET-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1449] Fixing failed tests

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Status/Pending.php
src/Tickets/Commerce/Status/Status_Abstract.php
src/Tickets/Commerce/Status/Status_Interface.php

[ET-1446] 
[ET-1446]: https://theeventscalendar.atlassian.net/browse/ET-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1446] Fixed sending duplicate emails for TC Stripe Webhooks.

---

src/Tribe/Main.php
src/Tribe/Theme_Compatibility.php

[ETP-784] 
QA Repair:
* Body classes from Theme compatibility were missing.
📷 screenshot(s) : https://d.pr/i/zOLKi9
[ETP-784]: https://theeventscalendar.atlassian.net/browse/ETP-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-784] Fix theme compatibility issues for AR pages

---

readme.txt
src/Tribe/Commerce/Currency.php
src/Tribe/Main.php
src/template-tags/commerce.php

[ET-1450] 
- Respect the currency selection for Tickets Commerce when using the blocks editor.
https://user-images.githubusercontent.com/252415/157713870-5bae9668-6354-4b2c-9df7-60e78203ce84.mov
[ET-1450]: https://theeventscalendar.atlassian.net/browse/ET-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1450] TC currency settings block editor

---

readme.txt
src/Tribe/Status/Manager.php
tests/wpunit/Tribe/Tickets/Status/ManagerTest.php

[ET-1436] 
* Add Tickets Commerce `Completed` status slugs in the status manager class to verify order status during check-in.
[ET-1436]: https://theeventscalendar.atlassian.net/browse/ET-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1436] Fixed Tickets Commerce App check-in.

---

readme.txt
src/Tickets/Commerce/Settings.php
src/Tickets/Commerce/Utils/Currency.php
src/Tribe/Commerce/Currency.php

[ET-1438] 
We're adding the option of South African Rand to the list of currencies that are supported by Tickets Commerce.
https://i.imgur.com/SC0tHzT.png
[ET-1438]: https://theeventscalendar.atlassian.net/browse/ET-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1438] Tickets Commerce: Add South African Rand as Currency Option

---

readme.txt
src/Tribe/Repositories/Post_Repository.php
src/Tribe/Ticket_Repository.php

[ET-1458]
[ET-1461] 
[ET-1458]: https://theeventscalendar.atlassian.net/browse/ET-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-1461]: https://theeventscalendar.atlassian.net/browse/ET-1461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Display TC Tickets in REST API

---

readme.txt
src/Tickets/Commerce/Admin/Notices.php
src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
src/Tickets/Commerce/Gateways/PayPal/Gateway.php
src/Tickets/Commerce/Gateways/PayPal/Hooks.php
src/Tickets/Commerce/Gateways/Stripe/Gateway.php
src/Tickets/Commerce/Gateways/Stripe/Hooks.php

[ET-1392] 
If an enabled gateway doesn't support the selected currency in TC, we want to show a notice.
https://i.imgur.com/ZOarrLA.png
[ET-1392]: https://theeventscalendar.atlassian.net/browse/ET-1392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1392] Tickets Commerce: Unsupported Currency Notice for Gateways

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

Release versions bumped

---

readme.txt
src/Tickets/Commerce/Gateways/Manual/Order.php

[ETP-781] 
https://d.pr/i/YUh8X8
[ETP-781]: https://theeventscalendar.atlassian.net/browse/ETP-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TicketsCommerce set 0 for manual orders

---

readme.txt
src/views/blocks/tickets/opt-out-hidden.php
src/views/blocks/tickets/registration/summary/content.php
src/views/registration-js/attendees/fields/number.php
src/views/v2/tickets/commerce/fields/tribe-commerce.php
src/views/v2/tickets/item/extra/description-toggle.php
src/views/v2/tickets/submit/must-login.php

[ET-1491] 
Details are added as comments in the Ticket.
N/A
[ET-1491]: https://theeventscalendar.atlassian.net/browse/ET-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1491] Fix template override path headers

---

readme.txt
src/Tickets/Admin/Upsell.php
src/admin-views/attendees.php
src/resources/postcss/tickets-report.pcss

[ET-1492] 
Added a Manual Attendees upsell notice on the attendees page in the admin area.
https://i.imgur.com/F0YYYwK.png

[ET-1492] Upsell Notice - Manual Attendees

---

readme.txt
src/Tickets/Admin/Hooks.php
src/Tickets/Admin/Provider.php
src/Tickets/Admin/Upsell.php
src/Tickets/Provider.php
src/admin-views/attendees.php
src/resources/postcss/tickets-admin.pcss
src/resources/postcss/tickets-report.pcss

[ET-1492] 
[ET-1493] 
If ET+ not activated, display an upsell notices about manual attendees, advanced capacity settings and ARF features in ET+. This PR also adds the new framework of any work that will be done within the admin area of ET.
Advanced Capacity and ARF: https://i.imgur.com/QdATTWh.png
Manual attendees: https://i.imgur.com/F0YYYwK.png
[ET-1493]: https://theeventscalendar.atlassian.net/browse/ET-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1493] [ET-1492] Upsell Notices - Manual Attendees, Advanced Capacity and ARF

---

changelog.txt
event-tickets.php
package-lock.json
package.json
readme.txt
src/Tribe/Main.php
src/Tribe/Plugin_Register.php

[ET-1335] 
- Setting version number.
- Adding dependencies.
- Adding readme entry.

[Events/Tickets menu] Set version number, dependencies, readme.

---

src/Tribe/Assets.php

[ET-1335] 
- Using new method to check if we're on the tickets settings.

Fix check to include assets in the tickets settings.

---

src/resources/postcss/tickets-admin.pcss
src/resources/postcss/tickets-report.pcss

[ET-1492] 
[ET-1493] 
CSS Tweaks for DQA
N/A
[ET-1493]: https://theeventscalendar.atlassian.net/browse/ET-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tweaks to Upsell CSS

---

readme.txt
src/Tribe/Admin/Settings.php

[ET-1335] 
- Fixing network settings hijack.
https://cloudup.com/cg0ZH33ryhM

Fixing network settings for ET/TEC (and all the suite)

---

src/Tickets/Commerce/Gateways/Stripe/Application_Fee.php
src/Tickets/Commerce/Settings.php

Related
https://github.com/the-events-calendar/event-tickets-plus/pull/1335
https://github.com/the-events-calendar/tribe-common/pull/1748

Modify ET PUE checker to validade license method

---

src/admin-views/tribe-options-tickets.php

[ET-1335] 
- Removing trailing comma.

Remove trailing comma.

---

readme.txt

[ET-1335] 
- Adding `Version` readme entry.

Adding `Version` readme entries.

---

readme.txt
src/Tickets/Admin/Hooks.php
src/Tickets/Admin/Plugin_Action_Links.php

[ET-1525] 
- Add plugin action links.
https://user-images.githubusercontent.com/252415/170536257-cdbe1483-020f-452c-aa25-daffffa716e1.mov
[ET-1525]: https://theeventscalendar.atlassian.net/browse/ET-1525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1525] Add plugin action links

---

readme.txt

[TICKET_ID] 
* Updated readme to reflect currency list changes.

Readme update

---

readme.txt
src/admin-views/settings/getting-started.php
src/admin-views/settings/tickets-commerce/banner.php
src/admin-views/settings/tickets-commerce/banner/footer.php
src/admin-views/settings/tickets-commerce/banner/footer/button.php
src/admin-views/settings/tickets-commerce/banner/footer/link.php
src/admin-views/settings/tickets-commerce/banner/new-badge.php
src/resources/postcss/tickets-admin/settings/_banners.pcss

[ET-1536] 
Find all instances of classes that use `.event-tickets__admin` and change them to `.tec-tickets__admin`. This mainly affects the page at Tickets > Settings > General.
N/A
[ET-1536]: https://theeventscalendar.atlassian.net/browse/ET-1536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1536] Admin - Unify CSS Naming

---

readme.txt
src/modules/blocks/ticket/container-header/price/style.pcss
src/modules/blocks/ticket/container-header/style.pcss
src/modules/elements/container-panel/style.pcss

[ET-1530] 
This fixes some CSS issues caused by widths being set without taking into account the padding.
[ET-1530]: https://theeventscalendar.atlassian.net/browse/ET-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1530] Block Editor - Tickets Block CSS Issues

---

readme.txt
src/Tickets/Commerce/Settings.php

[ET-1529] 
Sort settings with proper headings.
Before: https://d.pr/i/CRSaxL
After: https://d.pr/i/4b2pCu
[ET-1529]: https://theeventscalendar.atlassian.net/browse/ET-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1529] Reorganizing Tickets Commerce settings with heading label

---

readme.txt
src/Tribe/Editor/Compatibility/Tickets.php

[ET-1538] 
TEC events weren't able to be edited using Elementor with ET activated. This PR resolves that issue.
N/A
[ET-1538]: https://theeventscalendar.atlassian.net/browse/ET-1538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1538] Elementor - Unable to Edit Events with ET Actived

---

readme.txt
src/Tribe/Tickets_Handler.php

[ETP-800] 
🎥 screencast(s): https://d.pr/v/D4eRwB
[GTRIA-770]: https://theeventscalendar.atlassian.net/browse/GTRIA-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ETP-800]: https://theeventscalendar.atlassian.net/browse/ETP-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-800] Fixed shared capacity getting updated when single capacity ticket is updated

---

src/modules/blocks/ticket/container-content/duration/style.pcss

[ET-1530] 
This fixes the alert overflow issue that was found during DQA.
[ET-1530]: https://theeventscalendar.atlassian.net/browse/ET-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1530] Blocks Editor - Fix Alert Styling for Edit Ticket Block

---

readme.txt
src/Tickets/Commerce/Admin_Tables/Orders.php

[ET-1527] 
* This PR is just reverting the changes made by #2436 as we are not releasing these changes in current sprint.
[ET-1527]: https://theeventscalendar.atlassian.net/browse/ET-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1527] Reverted changes made.

---

changelog.txt
readme.txt
src/Tribe/Editor/Compatibility/Tickets.php

[ET-1554] 
[ET-1554]: https://theeventscalendar.atlassian.net/browse/ET-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

only query elementor on known posts

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

updated version according to release schedule changes

---

event-tickets.php
readme.txt
src/Tribe/Main.php

[TEC-4430]
[TEC-4430]: https://theeventscalendar.atlassian.net/browse/TEC-4430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hotfix: Freemius update

---

readme.txt
src/Tribe/Attendee_Repository.php

[ET-1543] 
* Search by name and email for attendees were not working for TicketsCommerce tickets which is now fixed.
🎥 screencast: https://d.pr/v/AJhqOi
[ET-1543]: https://theeventscalendar.atlassian.net/browse/ET-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1543] - Fix searching attendees using purhcaser name and email for TicketsCommerce

---

readme.txt

Sync - master to oviraptor

---

readme.txt
src/Tribe/Editor/Blocks/Rsvp.php
src/Tribe/RSVP.php
tests/wpunit/Tribe/Tickets/RSVPTest.php

[ET-1506] 
* Fixed RSVP requests that were made at the same time but went out of stock not showing the proper error messages.
* Re-factored RSVP process functions to generate WP_Errors instead of sending just `true` or `false`. 
🎥 screencast(s): https://d.pr/v/OAFRoH
[ET-1506]: https://theeventscalendar.atlassian.net/browse/ET-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1506] Fixed RSVP confirmation error messages.

---

readme.txt
src/Tickets/Commerce/Admin_Tables/Orders.php
src/Tickets/Commerce/Repositories/Order_Repository.php

[ET-1527] 
Added sorting support for Tickets Commerce Order pages columns.
* Order
* Purchaser
* Purchaser Email
* Date
* Gateway
* Gateway ID
* Status
* Total
🎥 screencast(s): https://d.pr/v/1sGsrS
[ET-1527]: https://theeventscalendar.atlassian.net/browse/ET-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1527] TicketsCommerce Orders column sorting

---

readme.txt
src/views/v2/tickets/item/inactive.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/InactiveTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/__snapshots__/InactiveTest__test_should_render_if_has_tickets_on_sale_is_false__1.php

[ET-1146] 
📷 screenshot: https://d.pr/i/p1ae2x
[ET-1146]: https://theeventscalendar.atlassian.net/browse/ET-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1146] Fix - Show proper unavailable message for Past events

---

readme.txt
src/admin-views/admin-welcome-message.php

[ET-1539] 
Added a Tickets Commerce section to the Tickets home page.
[ET-1539]: https://theeventscalendar.atlassian.net/browse/ET-1539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1539] Add TC to Tickets Home Page

---

readme.txt
src/resources/js/v2/__tests__/tickets-utils.test.js
src/resources/js/v2/tickets-block.js
src/resources/js/v2/tickets-utils.js

[ETP-801] 
* Refactored shared capacity calculations.
* Fixed shared capacity calculation for capped ticket scenario.
* Added JS tests to validate different scenarios.
screencast(s): https://d.pr/v/6ALNoO
[ETP-801]: https://theeventscalendar.atlassian.net/browse/ETP-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-801] - Fix shared capacity calculation issues for Ticket Block

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Payment_Intent_Handler.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Ticket.php

[ET-1542] 
* Added some extra fields in meta data for Stripe.
* Now it shows `purhcaser_name`, `purhchaser_email`, `event_name`, `event_url` and `ticket_names` in meta data section in Stripe dashboard.
[ET-1542]: https://theeventscalendar.atlassian.net/browse/ET-1542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1542] Enhancement - TicketsCommerce Stripe Dashboard now shows additional meta data.

---

readme.txt
src/Tribe/Attendee_Repository.php
src/Tribe/Attendees_Table.php
src/Tribe/Tickets.php
src/resources/postcss/tickets-report.pcss
tests/wpunit/Tribe/Tickets/Attendees_TableTest.php

[ET-1526] 
Sorting support was added for the following columns:
* Ticket
* Security Code
* Status
Dependent on this PR: https://github.com/the-events-calendar/tribe-common/pull/1778
🎥 screencast(s): https://d.pr/v/nIK1xa
[ET-1526]: https://theeventscalendar.atlassian.net/browse/ET-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1526] Add sorting support for Attendee Report page colums

---

readme.txt
src/Tribe/RSVP.php
src/Tribe/Tickets.php

[ETP-819] 
- Save the check-in details on check-in, for all providers.
- Remove the check-in details on uncheckin.
https://user-images.githubusercontent.com/252415/188155745-9c9c3818-6e26-41ab-8d61-c260a3e7b7de.mov
[ETP-819]: https://theeventscalendar.atlassian.net/browse/ETP-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-819] Properly save the check-in details for attendees on check-in.

---

readme.txt
src/template-tags/tickets.php

[ETP-820] 
- Add a template tag function to properly check if The Events Calendar is active.
[ETP-820]: https://theeventscalendar.atlassian.net/browse/ETP-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-820] Add template tag to properly check if The Events Calendar is active.

---

readme.txt

Add missing readme entry

---

src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
src/Tribe/REST/V1/Post_Repository.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html

[TICKET_ID] 
🎥 screencast(s): https://d.pr/v/PYS3rI

Spotfix - Fixed Attendee REST API orderby not working.

---

src/Tribe/REST/V1/Endpoints/Single_Attendee.php
src/Tribe/REST/V1/Post_Repository.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html

N/A 
- Unifying the way we return attendees on the endpoint (we need to return the same format on get, update, create)
https://user-images.githubusercontent.com/252415/191791330-e059c927-5dcb-4429-b8b5-75b769dc9522.mov

Unify the way we return attendee information on the REST API endpoint.

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html

Parksosaurus > update version numbers

---

src/Tribe/REST/V1/Main.php

[ET-1580] 
- Use array instead of obj.
[ET-1580]: https://theeventscalendar.atlassian.net/browse/ET-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1580] Use array value to populate attendance

---

src/Tribe/Main.php
src/Tribe/Plugin_Register.php

N/A 
- Setting dependencies for panoplausarus

🍍🦖 > Set dependencies versions.

---

src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
src/Tribe/REST/V1/Endpoints/Ticket_Archive.php

[TICKET_ID] 
* Wrong error messages were sent if the last page of pagination data was requested.
🎥 screencast(s): https://d.pr/v/yyioBF

Spotfix - Fix REST Attendee archive last page pagination error

---

src/admin-views/settings/emails/message-templates/list-title.php
src/resources/postcss/tickets-admin/settings/_emails.pcss

[ET-1549] 
Turned email template titles into links and adjusted `onhover` colors.
N/A
[ET-1549]: https://theeventscalendar.atlassian.net/browse/ET-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1549] DQA adjustments

---

src/Tribe/Main.php

[TICKET_ID] 
* Added the missing version update for the upcoming release.

Fixed current version to 5.5.5

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
src/resources/js/admin/gateway/stripe/webhooks.js

[ET-1614] 
🎥 screencast(s):  https://d.pr/i/tYO1jQ
[ET-1614]: https://theeventscalendar.atlassian.net/browse/ET-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1614] - Display the Webhook validation response from Stripe for TicketsCommerce.

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Hooks.php
src/Tickets/Commerce/Gateways/Stripe/Payment_Intent.php
src/Tickets/Commerce/Gateways/Stripe/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
src/resources/js/admin/gateway/stripe/webhooks.js

[ET-1508] 
[ET-1508]: https://theeventscalendar.atlassian.net/browse/ET-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1508] Fix - Stripe platform controls bug 

---

readme.txt
src/views/v2/tickets/item.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block with data set 0__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block with data set 1__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block with data set 2__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 0__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 10__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 11__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 15__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 16__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 17__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 1__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 20__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 21__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 22__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 25__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 26__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 27__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 5__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockV2Test__test_should_render_ticket_block_after_update with data set 6__1.php

[ETP-841] 
- Add the `tribe-tickets__tickets-item--shared-capacity` wrapper class for tickets having shared capacity.
[ETP-841]: https://theeventscalendar.atlassian.net/browse/ETP-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-841] Add the `tribe-tickets__tickets-item--shared-capacity` wrapper class for tickets.

---

readme.txt
src/Tickets/Commerce/Admin_Tables/Orders.php
src/Tickets/Commerce/Repositories/Order_Repository.php
src/admin-views/commerce/reports/orders.php
src/admin-views/commerce/reports/orders/search-options.php
src/resources/postcss/tickets-report.pcss

[ET-1259] 
* Added a dropdown to select columns and filter results using search box.
🎥 screencast(s): https://d.pr/v/ifMZll
[ET-1259]: https://theeventscalendar.atlassian.net/browse/ET-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1259] Enhance - Search capability added for Tickets Commerce Order reports.

---

src/Tickets/Commerce/Settings.php

[ET-1603] 
* This is a follow-up for QA feedback. So, no changelog entry needed.
[ET-1603]: https://theeventscalendar.atlassian.net/browse/ET-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1603] PQA update - Update text for Pending order stock handler

---

tests/commerce_integration/TEC/Tickets/Attendees_ListTest.php
tests/wpunit/Tribe/Tickets/Attendees_ListTest.php

[ETP-850] 
* The main changes are done here: https://github.com/the-events-calendar/event-tickets-plus/pull/1383
* No need for readme as this is Test only PR.
[ETP-850]: https://theeventscalendar.atlassian.net/browse/ETP-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-850] Add tests for attendance counts

---

src/Tickets/Emails/Admin/Preview_Modal.php
src/Tickets/Emails/Assets.php
src/Tickets/Emails/Email_Template.php
src/Tickets/Emails/Emails_Tab.php
src/Tickets/Emails/Hooks.php
src/Tickets/Emails/Provider.php
src/Tickets/Emails/Settings.php
src/admin-views/settings/emails/email-template/body.php
src/admin-views/settings/emails/email-template/body/add-links.php
src/admin-views/settings/emails/email-template/body/date.php
src/admin-views/settings/emails/email-template/body/event-description.php
src/admin-views/settings/emails/email-template/body/event-image.php
src/admin-views/settings/emails/email-template/body/event-location.php
src/admin-views/settings/emails/email-template/body/event-title.php
src/admin-views/settings/emails/email-template/body/footer-content.php
src/admin-views/settings/emails/email-template/body/footer-credit.php
src/admin-views/settings/emails/email-template/body/footer.php
src/admin-views/settings/emails/email-template/body/greeting.php
src/admin-views/settings/emails/email-template/body/header-image.php
src/admin-views/settings/emails/email-template/body/header.php
src/admin-views/settings/emails/email-template/body/qr-image.php
src/admin-views/settings/emails/email-template/body/recipient-name.php
src/admin-views/settings/emails/email-template/body/ticket-info.php
src/admin-views/settings/emails/email-template/body/top-link.php
src/admin-views/settings/emails/email-template/main.php
src/admin-views/settings/emails/email-template/preview.php
src/admin-views/settings/emails/email-template/style.php
src/resources/js/admin/tickets-emails.js
src/resources/postcss/tickets-admin/settings/_emails.pcss

[ET-1547] 
- *WIP*, building on top of https://github.com/the-events-calendar/event-tickets/pull/2518
https://user-images.githubusercontent.com/252415/214598732-9687174f-3671-4ddd-b104-14fa49222e5c.mov
[ET-1547]: https://theeventscalendar.atlassian.net/browse/ET-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1547] Tickets Emails > Modal Preview

---

.github/workflows/zip.yml
composer.json
composer.lock
readme.txt
src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss

[TEC-4598](https://theeventscalendar.atlassian.net/browse/TEC-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Updates dealerdirect/phpcodesniffer-composer-installer to ^0.7.2
Removes explicit Codeception 4.0 - it's required by `lucatume/wp-browser`
Fixes deprecated pcss variables.
Includes/requires:
https://github.com/the-events-calendar/tribe-common/pull/1813
https://github.com/the-events-calendar/tribe-common-styles/pull/91
[TEC-4598]: https://theeventscalendar.atlassian.net/browse/TEC-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade Composer to v2

---

readme.txt
src/Tribe/Admin/Settings.php

[ET-1645] 
- Fixing the placeholder for the Tickets Settings title string.
[ET-1645]: https://theeventscalendar.atlassian.net/browse/ET-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1645] Fix placeholder for translation on the Tickets Settings title.

---

src/views/v2/emails/template-parts/body/footer.php

This fixes the logic that was causing the footer not to appear in the email template.

Fix Tickets Emails Missing Footer

---

readme.txt
src/Tickets/Admin/Glance_Items.php
src/Tickets/Admin/Hooks.php
src/Tribe/Assets.php
src/resources/postcss/tickets-admin-wp.pcss

[ET-1654] 
- Add the Attendee count for the site to the `At a Glance` admin widget.
[ET-1654]: https://theeventscalendar.atlassian.net/browse/ET-1654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1654] Add the Attendee count for the site to the `At a Glance` admin widget.

---

package-lock.json
src/Tribe/Main.php

Fix race condition. Update version in package lock

---

readme.txt
src/Tribe/Tickets.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/EventStockTest.php

[ET-1678] 
https://lw.slack.com/archives/C01T9UJGE2U/p1678439824557809
Before: https://share.cleanshot.com/tqsF3yzT
After: https://share.cleanshot.com/j9HkdpY0
[ET-1678]: https://theeventscalendar.atlassian.net/browse/ET-1678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1678] Fix - Fixed showing unlimited tickets as sold out on calendar views

---

readme.txt
src/Tribe/Attendees_Table.php

[ET-1679] 
[ET-1679]: https://theeventscalendar.atlassian.net/browse/ET-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prevent fatal for non-admin users.

---

src/Tickets/Emails/Admin/Preview_Modal.php
src/resources/js/admin/tickets-emails.js

[ET-1547] 
- Add a handler for the header image in the email preview modal.
https://user-images.githubusercontent.com/252415/225650401-b733a944-ef5b-4d96-bf07-4d1ceb725275.mov
[ET-1547]: https://theeventscalendar.atlassian.net/browse/ET-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1547] Tickets Emails: Add a handler for the header image in the email preview modal.

---

src/Tickets/Emails/Email/Ticket.php
src/Tribe/Tickets.php

N/A 
- Deliver tickets emails with the new system (if enabled).
- Add logic so that there's one email per event.
https://user-images.githubusercontent.com/252415/225644049-15123c8b-552a-478f-92a7-61aff254be56.mov

Deliver tickets emails with new system (if enabled).

---

src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email_Handler.php

[ET-1623] 
Adds the RSVP email and settings to the Tickets Emails system.
[ET-1623]: https://theeventscalendar.atlassian.net/browse/ET-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1623] Add RSVP Email

---

src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Failed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/Ticket.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php

N/A 
- Deliver RSVP emails with the new system (if enabled). Fallback to the tickets email, if selected.
- Linting on the RSVP class.
https://user-images.githubusercontent.com/252415/226400705-940c4f42-6e33-4de7-bdde-1c993e16fa61.mov

Deliver rsvp emails with new system

---

src/Tickets/Emails/Email/RSVP_Not_Going.php
src/Tickets/Emails/Email_Handler.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php
src/views/v2/emails/rsvp-not-going.php
src/views/v2/emails/rsvp-not-going/body.php

N/A 
- Adding the `RSVP "Not Going"` email.
- Needs [this PR](https://github.com/the-events-calendar/event-tickets-plus/pull/1403) for the "Re-send" functionality.
https://user-images.githubusercontent.com/252415/227274498-f1e37520-8624-4ea3-bdff-9614fa773921.mov

Tickets Emails > RSVP "Not Going" email.

---

readme.txt
src/Tickets/Commerce/Attendee.php
src/Tickets/Commerce/Hooks.php
src/Tickets/Commerce/Module.php
src/Tickets/Commerce/Ticket.php
src/Tribe/Attendees_Table.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/UpdateTest.php

[ETP-860] 
* Properly restock Tickets Commerce tickets after deleting corresponding attendee.
🎥 screencast(s): https://share.cleanshot.com/4Z4m7k5w
[ETP-860]: https://theeventscalendar.atlassian.net/browse/ETP-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-860] - Enhancement - Add ticket restock functionality upon attendee deletion for TicketsCommerce 

---

src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/Ticket.php
src/Tickets/Emails/Email_Abstract.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php

- N/A 
- Add methods to manage context data.
- Include the class on the filters, so that the data (tickets, post_id, order) is available for all filters.

Tickets Emails > Abstract email data & context

---

src/Tickets/Commerce/Flag_Actions/Send_Email_Completed_Order.php
src/Tickets/Commerce/Flag_Actions/Send_Email_Purchase_Receipt.php
src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Failed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/RSVP_Not_Going.php
src/Tickets/Emails/Email/Ticket.php
src/Tickets/Emails/Email_Abstract.php
src/Tickets/Emails/Email_Handler.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php
src/admin-views/settings/emails/message-templates/list-recipient.php

N/A 
- Re-architecture the email abstract recipient.
-Move sending logic to class so that we can handle placeholders better.

Tickets Emails > Re-architecture the email abstract recipient.

---

src/Tickets/Commerce/Flag_Actions/Send_Email_Completed_Order.php
src/Tickets/Commerce/Flag_Actions/Send_Email_Purchase_Receipt.php
src/Tickets/Emails/Admin/Preview_Data.php

N/A 
- Adding order data to TC emails
https://user-images.githubusercontent.com/252415/230912554-10503743-d2a4-4843-8c7f-22af3c2f6c0b.mov

Add order data to emails.

---

src/Tickets/Emails/Admin/Preview_Data.php
src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Failed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/RSVP_Not_Going.php
src/Tickets/Emails/Email/Ticket.php
src/Tickets/Emails/Email_Abstract.php
src/Tickets/Emails/Email_Template.php

N/A 
- Organize preview data and make it filterable per email, so that we can populate the preview data from TEC or other places per email.
N/A

Tickets Emails > Organize preview data and make it filterable per email.

---

src/Tickets/Emails/Provider.php

[ET-1617] 
- Removing the conditional to load the feature as we'll be introducing it in escarole.
[ET-1617]: https://theeventscalendar.atlassian.net/browse/ET-1617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tickets Emails > Remove conditional, introducing the feature.

---

src/Tickets/Emails/Email_Abstract.php
src/Tickets/Emails/Email_Sender.php
src/Tickets/Emails/Hooks.php
src/Tickets/Emails/Legacy.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php

I noticed that the changes we made in Tickets Emails were adding more code to the legacy Modules, which we want to avoid as they are already impossible to read, 3000 lines each.
📹 https://i.bordoni.me/2BwGnstc

Update to avoid creating more bloat on main Module files

---

codeception.dist.yml
src/Tickets/Emails/Dispatcher.php
src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/RSVP_Not_Going.php
src/Tickets/Emails/Email/Ticket.php
src/Tickets/Emails/Email_Abstract.php
src/Tickets/Emails/Email_Handler.php
src/Tickets/Emails/Email_Sender.php
src/Tickets/Emails/Hooks.php
src/Tickets/Emails/Legacy.php
src/Tickets/Emails/Legacy_Hijack.php
src/Tickets/Emails/Post_Type.php
src/Tickets/Emails/Provider.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php
tests/_bootstrap.php
tests/_support/Emails/Email/Dummy_Email.php
tests/_support/Traits/With_Uopz.php
tests/acceptance.suite.dist.yml
tests/commerce_integration.suite.dist.yml
tests/functional.suite.dist.yml
tests/integration.suite.dist.yml
tests/integration/TEC/Tickets/Emails/DispatcherTest.php
tests/integration/TEC/Tickets/Emails/Post_TypeTest.php
tests/restv1.suite.dist.yml
tests/views_integration.suite.dist.yml
tests/wpunit.suite.dist.yml
tests/wpunit/Tribe/Tickets/Attendees_TableTest.php

📹 https://i.bordoni.me/RZX5ZMww
Depends on #2619

Move towards the Dispatcher nomenclature.

---

src/Tickets/Emails/Dispatcher.php

Resolve the code review requests added by @juanfra on #2621

Address code review requests to Dispatcher from Original PR #2621

---

src/Tickets/Commerce/Order.php
src/Tickets/Emails/Hooks.php
src/Tickets/Emails/Legacy_Hijack.php
src/Tribe/RSVP.php
tests/commerce_integration/_bootstrap.php
tests/integration/Tribe/Tickets/Commerce/PayPal/PayPalTest.php

This PR addresses the last method (hopefully) for Tickets Emails that was not in that codebase.
📹 https://i.bordoni.me/Rr5KTQ0m
Tests are passing just GA has some caching.

Move non-attendance email to Tickets Emails codebase

---

src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/RSVP_Not_Going.php
src/Tickets/Emails/Email/Ticket.php

Updating emails descriptions and use the link that'll contain documentation for Tickets Emails.

Update emails descriptions, use new link for the tickets emails docs.

---

src/Tickets/Commerce/Flag_Actions/Send_Email_Completed_Order.php
src/Tickets/Commerce/Flag_Actions/Send_Email_Purchase_Receipt.php
src/Tickets/Commerce/Module.php

For Item `TE-E834` we just needed to pass the correct order ID here.

On the Completed Email and Purchase Receipt pass the correct order ID.

---

src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php

[ET-1734] 
This PR contains a collection of various modifications that arose from a recent DQA. Specific TE IDs can be found in the artifact section.
- `TE-1160` - https://i.bordoni.me/K4ZTKQ7H
[ET-1734]: https://theeventscalendar.atlassian.net/browse/ET-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1734] Tickets Emails: Various DQA CSS Tweaks - Part 2

---

src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/RSVP_Not_Going.php
src/Tickets/Emails/Email/Ticket.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_rsvp_without_using_ticket_settings__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php

[ET-1734] 
During a Tickets Emails DQA pass, it was found that the 'Enabled' toggles we're intuitive enough, so we're changing some wording around to make things more clear.
- `TE-B110` - https://share.cleanshot.com/pvlY0Lpq
Demo: https://www.loom.com/share/5fe2d2749cdf41be8edc0c774bfe8121
[ET-1734]: https://theeventscalendar.atlassian.net/browse/ET-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1734] Tickets Emails: Modify Enabled Labels

---

src/resources/js/admin/tickets-emails.js

[TICKET_ID] 
**Before:** 
https://share.cleanshot.com/p0ggHDg4
**After:**
https://share.cleanshot.com/SmntrTVf

Fix - Include ARF and QR Code into general email preview.

---

src/Tickets/Emails/Admin/Emails_Tab.php

- N/A 
- Adding link to KB article for Tickets Emails.
- Update the description to avoid talking about losing customizations for fresh installs.

Tickets Emails > Adjust description and add missing link to KB

---

.github/workflows/tests-php.yml
tests/restv1/PayPal/SingleTicketCest.php
tests/restv1/PayPal/TicketArchiveByPostCest.php
tests/restv1/RSVP/SingleTicketCest.php
tests/restv1/RSVP/TicketArchiveByPostCest.php

The restV1 tests were failing for Fennel. Gustavo fixed them in Escarole. Porting the changes into Fennel so tests pass.

Fixing RestV1 tests

---

src/resources/postcss/tickets-admin/settings/_emails.pcss

n/a 
On mobile the preview button was displaying a little higher than the "Save Changes" button.
Before:
After:

Tickets Emails: Preview Button Styling Tweaks

---

src/resources/js/admin/tickets-emails.js

[TE-6DB9] 
🎥 screencast: https://www.loom.com/share/9a594720af8a4738b03baf127f91722c

[TE-6DB9] Fix -Ticket Emails settings live preview for Footer content and additional content.

---

src/Tickets/Emails/Email_Abstract.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

[ET-1746]
[ET-1746]: https://theeventscalendar.atlassian.net/browse/ET-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Replace placeholders everywhere in the Email

---

src/Tickets/Emails/Admin/Preview_Modal.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Hooks.php

[TE-EC26] 
🎥 screencast(s): https://www.loom.com/share/fdacf03247794695a08c435b4bb8b661

[TE-EC26] Fix - Toggling Use Ticket Email option should not remove other field's data.

---

tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

[ET-1757] 
[ET-1757]: https://theeventscalendar.atlassian.net/browse/ET-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1757] Snapshots update.

---

src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/RSVP_Not_Going.php
src/Tickets/Emails/Email/Ticket.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_rsvp_without_using_ticket_settings__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php

TE-9B0C 
To decrease confusion, we're removing the 'Enabled' wording from the right of the toggle and adding 'Enable' before the title of the email.
Before:
After:

Tickets Emails: Modify Enabled Toggle for all Emails

---

src/Tickets/Emails/Admin/Preview_Modal.php
src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

TE-667E
Fixes size and color of additional content in all emails. Also fixed an issue that I saw when previewing. We needed to `wp_unslash()` the preview content for additional content, too.
https://www.loom.com/share/5f0519c85c0f419189506b5c85592c2f

Tickets Emails: Additional Content Fixes

---

src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

- TE-24C0
- TE-4F5D 
Trying to squeeze in a few minor mobile styling modifications before release. This one fixes the gutters and heading text size on mobile devices.

Tickets Emails: Mobile Styling Tweaks

---

readme.txt
src/Tribe/Attendee_Registration/Service_Provider.php
src/Tribe/Attendee_Registration/Template.php

[ET-1767] 
When using Astra theme, the attendee registration form on the attendee registration page is being generated infinite times(on loop), and the page keeps loading. This issue seems to mostly occur with Astra version 4.x.  
Mike found the original snippet that I have used https://gist.github.com/codingmusician/da909aa95bc08e80baaab3456f586014. 
Original Issue - 
Fixed -
[ET-1767]: https://theeventscalendar.atlassian.net/browse/ET-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1767] Attendee Registration Loop issue on certain themes.

---

src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

n/a 
After the latest changes made and testing things out, I noticed that the QR code was no longer aligned to the right. Adding 100% width to the name holder cell fixes this issue.
Before:
After:

Tickets Emails: CSS Tweak

---

src/Tickets/Commerce/Abstract_Order.php
src/Tickets/Commerce/Admin_Tables/Orders.php
src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
src/Tickets/Commerce/Gateways/Contracts/Gateway_Interface.php
src/Tickets/Commerce/Gateways/Manual/Gateway.php
src/Tickets/Commerce/Gateways/PayPal/Gateway.php
src/Tickets/Commerce/Gateways/PayPal/Order.php
src/Tickets/Commerce/Gateways/Stripe/Gateway.php
src/Tickets/Commerce/Gateways/Stripe/Order.php
src/views/emails/template-parts/body/order/order-gateway-data.php

[ET-1729]
Resolves a problem @rafsuntaskin and I found while working on the Order data for Emails, but the fix it related to how commerce generate certain links for the admin. The fixes are from a Innovation day PR we merged into Escarole, so it needs to be merged before release.
Original PR: #2583

[ET-1729] Refactor - Move the methods from the Gateway into the Order controller

---

tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

Changes were made to TEC that affected the snapshots. The PR simply fixes the integration test.

Updating Snapshots to Fix Tests

---

src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

TE-40EB 
Styling of excerpt needed to be updated after it was added.
Before:
After:

TE-40EB Tickets Emails: Update Excerpt Styling

---

readme.txt
src/Tickets/Commerce/Gateways/PayPal/Assets.php
src/Tickets/Commerce/Gateways/PayPal/Client.php

Resolves the problem with Sandbox not properly fetching the tokens due to not using the Modal UI.

Ensure that Sandbox JS also uses the production JS

---

src/Tickets/Telemetry/Telemetry.php

if one has already been interacted with.
Requires https://github.com/the-events-calendar/tribe-common/pull/1941

Tweak the logic for showing the modal 

---

readme.txt
src/Tickets/Emails/Email_Template.php

[ET-1780] 
- Fixing template overrides for ET email templates.
https://github.com/the-events-calendar/event-tickets/assets/252415/398cb08c-4ea0-4732-bef5-8bbe9a1564e3
[ET-1780]: https://theeventscalendar.atlassian.net/browse/ET-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix event tickets emails overrides not working.

---

readme.txt
src/Tribe/Admin/Notices.php

[ET-1764] 
[ET-1765] 
We're currently Partnering with Paystack and cross-promoting products. We will display a notice if the time zone for the WordPress site is set to `Lagos`, `Accra` or `Johannesburg` (Africa) and if the TEC - Paystack plugin isn't already active. It will also only be displayed within the Tickets Settings pages.
[ET-1764]: https://theeventscalendar.atlassian.net/browse/ET-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-1765]: https://theeventscalendar.atlassian.net/browse/ET-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1764] Add notice and documentation for Paystack

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Hooks.php

[ET-1736] 
There were unnecessary error checks occurring during ajax requests in the admin section. This will improve performance for some sites.
n/a
[ET-1736]: https://theeventscalendar.atlassian.net/browse/ET-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1736] Check Ajax Before Stripe Errors

---

readme.txt
src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

[ET-1802]
We found that there were several issues when using CSS classes in Gmail, but I found out that many of the issues were due to including two selectors per definition. This PR removes the redundant selectors. Everything has been tested and the styling looks no different than it did in the escarole release.
[ET-1802]: https://theeventscalendar.atlassian.net/browse/ET-1802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1802] Tickets Emails: Refactor CSS for Emails

---

src/Tribe/Tickets_View.php

Adds some last minute code changes Juan suggested.

 [ETP-623] Attendees list not displaying when using "classic" editor

---

src/Tickets/Telemetry/Provider.php
src/Tickets/Telemetry/Telemetry.php
src/Tribe/Admin/Settings.php
src/Tribe/Commerce/PayPal/Main.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

[ET-1806]
Related: https://github.com/the-events-calendar/the-events-calendar/pull/4319
[ET-1806]: https://theeventscalendar.atlassian.net/browse/ET-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify the hook so telemetry can load on all required pages

---

tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

Fixes snapshots due to changes in TEC

fix snapshots

---

readme.txt
src/Tribe/Events/Views/V2/Models/Tickets.php

[ET-1768] 
🎥 screencast(s): https://share.cleanshot.com/l13MkD8V
[ET-1768]: https://theeventscalendar.atlassian.net/browse/ET-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1768] Fix - Get tickets anchor link not working from event listing.

---

readme.txt
src/Tickets/Commerce/Ticket.php
src/Tribe/Admin/Move_Tickets.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php

[ET-1577] 
🎥 screencast(s): https://www.loom.com/share/ed5676f7fb8745528cdcbf1e0cf9d035
[ET-1577]: https://theeventscalendar.atlassian.net/browse/ET-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1577] Allow moving attendees for deleted tickets to same provider tickets.

---

readme.txt
src/Tribe/Tickets_Handler.php
tests/wpunit/Tribe/Tickets/Template_Tags/GetPostTotalsTest.php

[ETP-854]
[ETP-817]
🎥 screencast(s): https://www.loom.com/share/df8cde8bd1ce47dc99cc32f2cc9f6d0e
Take 2: https://www.loom.com/share/3dabb0bf45a44264aace734a53540e54
[ETP-854]: https://theeventscalendar.atlassian.net/browse/ETP-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ETP-817]: https://theeventscalendar.atlassian.net/browse/ETP-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-854] Fix - Updating total shared capacity should update ticket capacity properly.

---

src/Tickets/Commerce/Gateways/Stripe/Hooks.php
src/Tribe/Admin/Settings.php

[ET-1736] 
[artifact-et-1736.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/07ffd763-5a7a-4a53-82fc-fd414f9dd2c3)
[ET-1736]: https://theeventscalendar.atlassian.net/browse/ET-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1736] Stripe Endpoint runs to much

---

src/Tickets/Commerce/Gateways/Stripe/Hooks.php

[ET-1736]
Romine found a fatal when enabling the block editor. This fixes the issue.
[Screencast from 07-12-2023 01:55:33 PM.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/644f7bd9-c04e-41d3-b489-97f450760931)
[ET-1736]: https://theeventscalendar.atlassian.net/browse/ET-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1736] Aliased the Tribe settings class to avoid conflict.

---

src/Tickets/Commerce/Ticket.php
src/Tribe/RSVP.php
tests/wpunit/Tribe/Cache/AbstractCacheTest.php

[ET-1577] 
[ET-1577]: https://theeventscalendar.atlassian.net/browse/ET-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1577] - Make use of wp_trash instead of wp_delete.

---

readme.txt
src/views/emails/template-parts/body/footer.php
src/views/emails/template-parts/body/footer/content.php
src/views/emails/template-parts/body/footer/credit.php
src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

[ET-1784] 
The footer link was not visible for the Tickets Emails template. I found that many of the footer styles were still inline, so I moved them to the stylesheet and ensured that the footer link color would override any other CSS that may be interfering.
[ET-1784]: https://theeventscalendar.atlassian.net/browse/ET-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1784] Tickets Emails: Footer Link Not Visible

---

readme.txt
src/Tribe/Tickets.php

[ET-1820] 
* Update to a previously made changes in common here: https://github.com/the-events-calendar/tribe-common/pull/1960
* Common PR for reverting the changes: https://github.com/the-events-calendar/tribe-common/pull/1967
* Slack discussion thread: https://lw.slack.com/archives/C01T9UJGE2U/p1691730315859199
🎥 screencast(s): https://www.loom.com/share/578d211f756b48b5803e53f09b32851e
[ET-1820]: https://theeventscalendar.atlassian.net/browse/ET-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1820] Apply date format i18n for Ticket form available message.

---

readme.txt
src/Tickets/Commerce/Ticket.php
src/Tribe/Commerce/PayPal/Main.php

[ET-1800] 
* Changes are covered by existing tests.
[ET-1800]: https://theeventscalendar.atlassian.net/browse/ET-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1800] Tweak - Replace FILTER_SANITIZE_STRING.

---

readme.txt
src/Tribe/Attendee_Repository.php
tests/commerce_integration/TEC/Tickets/Attendees_ListTest.php

[ET-1863] 
[ET-1863]: https://theeventscalendar.atlassian.net/browse/ET-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1863] Fix - Add support to filter by order status for TC attendees.

---

readme.txt
src/Tribe/REST/V1/Endpoints/Single_Attendee.php

[ET-1863] 
🎥 screencast(s): https://www.loom.com/share/50d8cd0c08b6405db5848ca4ef5da3de
[ET-1863]: https://theeventscalendar.atlassian.net/browse/ET-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1863] Fix - validate REST `check_in` data before updating

---

src/Tickets/Commerce/Gateways/PayPal/REST/Order_Endpoint.php

[ET-1865] 
Juan pointed out in a previous PR that the variables needed to be snake case. This fixes it, no readme needed.
[ET-1865]: https://theeventscalendar.atlassian.net/browse/ET-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1865] Spotfix, fix variable naming

---

src/resources/postcss/tickets-admin/attendees/_table.pcss

[ET-1840] 
[ET-1842] 
DQA noted a couple of changes that needed to made for mobile view. This PR addresses those.
[ET-1840]: https://theeventscalendar.atlassian.net/browse/ET-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-1842]: https://theeventscalendar.atlassian.net/browse/ET-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Attendees Page: DQA Tweaks

---

readme.txt
src/Tribe/Editor/Assets.php
src/modules/blocks/rsvp/inactive-block/template.js
src/modules/blocks/rsvp/style.pcss

[ET-1818] 
- Re-styled Inactive empty RSVP Block.
- Added `tribe-common-full-style` as an asset
https://www.loom.com/share/a0ffb081931e405f8d248ec140af43f4
[ET-1818]: https://theeventscalendar.atlassian.net/browse/ET-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added tribe-common-full-style to tickets editor and re-styled inactive RSVP block

---

src/resources/postcss/tickets-admin/attendees/_table.pcss

[ET-1840] 
Fixes a padding issue that was found in the attendance overview table
With Fix in place:
[ET-1840]: https://theeventscalendar.atlassian.net/browse/ET-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1840] Fix attendance overview padding

---

src/Tickets/Flexible_Tickets/Base.php
src/Tickets/Flexible_Tickets/template-tags.php
src/admin-views/flexible-tickets/ticket-types-column/default.php
src/resources/postcss/tickets-admin.pcss
tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has recurring event with series pass__1.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with RSVP and ticket__1.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with RSVP ticket__1.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with RSVP, ticket and series pass__1.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with no tickets__1.php

[ET-1791] 
* Change the column heading to `Attached Tickets` from `Attached Ticket Types`.
* Change the default label to say `Single Ticket` from `Ticket`.
[ET-1791]: https://theeventscalendar.atlassian.net/browse/ET-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1791] Tweak - Adjustments as per feedback.

---

src/admin-views/flexible-tickets/series-pass-event-notice.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Templates/__snapshots__/Admin_ViewsTest__should_render_template_correctly__series-pass-event-notice__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Templates/__snapshots__/Admin_ViewsTest__should_render_template_correctly_when_filtering_series_pass_labels__series-pass-event-notice__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html

[TICKET_ID] 
* Update according to bug tracker sheet item #26.
* Update the notice text to: `This event is part of the Series [linked Series name]. Create and manage Series Passes from the Series admin. `

Tweak - Update series prompt notice

---

src/admin-views/flexible-tickets/series-pass-event-notice.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Templates/__snapshots__/Admin_ViewsTest__should_render_template_correctly__series-pass-event-notice__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Templates/__snapshots__/Admin_ViewsTest__should_render_template_correctly_when_filtering_series_pass_labels__series-pass-event-notice__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html

[ET-1722] 
📷 screenshot(s)
**Before:**
**After**
[ET-1722]: https://theeventscalendar.atlassian.net/browse/ET-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1722] Update Series notice text.

---

event-tickets.php
readme.txt
src/Tribe/Main.php

Companion to https://github.com/the-events-calendar/tribe-common/pull/1981

Telemetry common fix

---

src/Tickets/Telemetry/Telemetry.php

https://github.com/the-events-calendar/the-events-calendar/pull/4388

Ensure telemetry opt-in works across TEC and ET

---

readme.txt
src/Tribe/Editor/Warnings.php

[ECP-1538] 
* Avoid showing Ticket not supported for recurrence on the event submission page.
🎥 screencast(s): https://www.loom.com/share/d420f9f71bde4a00bf63cf96f6d745f0
[ECP-1538]: https://theeventscalendar.atlassian.net/browse/ECP-1538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ECP-1538] Fix - Remove showing duplicate warning for new event submission.

---

readme.txt
src/modules/blocks/ticket/container-header/price/style.pcss
src/modules/blocks/ticket/container-header/quantity/style.pcss
src/modules/blocks/tickets/availability/style.pcss
src/modules/blocks/tickets/container/template.js
src/modules/blocks/tickets/header-image/style.pcss
src/modules/blocks/tickets/header-image/template.js
src/modules/elements/settings-dashboard/__tests__/__snapshots__/element.test.js.snap
src/modules/elements/settings-dashboard/__tests__/element.test.js
src/modules/elements/settings-dashboard/element.js
src/modules/elements/settings-dashboard/style.pcss
src/modules/icons/close.svg
src/modules/icons/index.js

[ET-1834] 
- Re-styled Settings in Block Editor
https://www.loom.com/share/3c7bab5022004be98f15ec790432e7d8
[ET-1834]: https://stellarwp.atlassian.net/browse/ET-1834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Re-styled settings block

---

readme.txt
src/Tribe/Main.php

[ET-1886] 
No artifacts in this case, it just works. Nothing changes.
[ET-1886]: https://stellarwp.atlassian.net/browse/ET-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move the location of service provider to avoid problems with ECP

---

tests/_support/Testcases/TicketsBlock_TestCase.php

N/A
Recent ticket block tests have been breaking due to random dialog ids in the code. This PR adds a filter to normalize that ID.
N/A

Fix Tests: Normalize Dialog ID

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

Tweak - G23.junsai version bumped

---

readme.txt
src/Tickets/Commerce/Shortcodes/Success_Shortcode.php
src/resources/postcss/tickets-commerce/_success.pcss
src/views/v2/commerce/order/attendees.php
src/views/v2/commerce/order/attendees/attendee.php
src/views/v2/commerce/order/attendees/title.php

[ETWP-30] 
- Add attendees to Tickets Commerce success page.
[ETWP-30]: https://stellarwp.atlassian.net/browse/ETWP-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETWP-30] Add attendees to Tickets Commerce success page.

---

tests/_support/Testcases/TicketsBlock_TestCase.php

Tests - Fix snapshots

---

readme.txt
src/Tickets/Commerce/Admin_Tables/Attendees.php

Tweak - WP 6.4 compatibility, avoid deprecation notices.

---

src/admin-views/commerce/reports/orders/summary.php

[ET-1810] 
[ET-1810]: https://stellarwp.atlassian.net/browse/ET-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat - Add new hook on new order report design.

---

readme.txt
src/views/tickets/orders-tc-tickets.php

[ET-1909] 
There was a bug/typo in the My Tickets code when ETP is disabled/deactivated.
Before:
After:
[ET-1909]: https://stellarwp.atlassian.net/browse/ET-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1909] My Tickets: Fix Section Titles

---

codeception.dist.yml
src/Tickets/Commerce/Reports/Data/Order_Summary.php
tests/integration/Tribe/Admin/OrderReportTest.php
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with multiple tickets in same order__0.snapshot.html

[ET-1810] 
Before: https://share.cleanshot.com/hSrnT8Qh
After: https://share.cleanshot.com/L3mvFDLW
[ET-1810]: https://stellarwp.atlassian.net/browse/ET-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat - Show status slug as `Unlimited` instead of `-1` for unlimited tickets.

---

src/Tickets/QR/Connector.php
src/Tickets/QR/Observer.php
src/Tribe/Data_API.php
src/Tribe/REST/V1/Documentation/QR_Definition_Provider.php
src/Tribe/REST/V1/Endpoints/QR.php
src/Tribe/REST/V1/Post_Repository.php
src/Tribe/REST/V1/Service_Provider.php
tests/_data/classes/Dummy_Endpoint.php
tests/_support/Factories/QR.php
tests/_support/Factories/REST/V1/QR_Response.php
tests/_support/Testcases/QR_TestCase.php
tests/_support/Testcases/REST/V1/QR_TestCase.php
tests/restv1/QR/ScanCest.php
tests/wpunit/Tribe/REST/V1/Endpoints/Single_QRTest.php
tests/wpunit/Tribe/REST/V1/Post_RepositoryTest.php

[ETWP-39] 
- Move QR endpoint.
[ETWP-39]: https://stellarwp.atlassian.net/browse/ETWP-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETWP-39] Move QR endpoint

---

src/modules/blocks/ticket/container-content/capacity/template.js
src/modules/blocks/ticket/container-header/quantity/style.pcss
src/modules/blocks/ticket/container-header/quantity/template.js
src/modules/blocks/ticket/container-header/title/attendee-registration-icons/style.pcss
src/modules/blocks/tickets/availability/__tests__/__snapshots__/template.test.js.snap
src/modules/blocks/tickets/availability/style.pcss
src/modules/blocks/tickets/availability/template.js

[ET-1816] 
- Fixed validation in limit input.
- Fixed tooltips
[ET-1816]: https://stellarwp.atlassian.net/browse/ET-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed validation in limit input. Fixed tooltips

---

src/modules/blocks/rsvp/title/template.js
src/modules/blocks/ticket/container-header/quantity/template.js
src/modules/blocks/ticket/container-header/title/attendee-registration-icons/container.js
src/modules/blocks/tickets/availability/template.js

[ET-1816] 
- Fixed appearance of icons when the block is selected.
- Set the focus to the first input in RSVP
https://www.loom.com/share/d33ca52843c94d3e87b4b539cb89bcfe
[ET-1816]: https://stellarwp.atlassian.net/browse/ET-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed appearance of icons when the block is selected. Set the focus to the first input in RSVP

---

src/resources/postcss/components/attendees-list/_attendees.pcss
src/views/components/attendees-list/attendees.php
src/views/components/attendees-list/attendees/attendee.php
src/views/components/attendees-list/title.php

- N/A
- Fix stylesheet to be compatible with the design system and be wrapped around the wrapper classes (`tribe-common`, `event-tickets`)
- Update names to be more generic.
- Moved title template out of the attendee, as it's general to the template.
- Fix spacing for the block.

Attendees list with BEM, misc fixes.

---

src/Tickets/Flexible_Tickets/Base.php
src/Tickets/Flexible_Tickets/Series_Passes.php
src/admin-views/editor/panel/header-image.php
src/admin-views/editor/panel/settings.php
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html

[ET-1899] 
[ET-1899]: https://stellarwp.atlassian.net/browse/ET-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1899] Feat- Remove header image from series pass settings.

---

readme.txt

Add ETWP to readme.

---

readme.txt
src/Tickets/Commerce/Reports/Attendees_Tab.php
src/Tickets/Commerce/Reports/Orders.php
src/Tickets/Commerce/Reports/Orders_Tab.php
src/Tickets/Commerce/Reports/Tabbed_View.php
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with 1 pending and 1 completed order__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with multiple tickets and orders__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with multiple tickets in same order__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with no orders__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with one order__0.snapshot.html

[ET-1867] 
- Added tabs for Ticket Commerce
[ET-1867]: https://stellarwp.atlassian.net/browse/ET-1867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added tabs for ticket commerce

---

src/resources/postcss/my-tickets/_orders.pcss
src/resources/postcss/rsvp-v1.pcss
src/resources/postcss/tickets-admin.pcss
src/views/tickets/my-tickets/tickets-list.php

N/A 
DQA came back with a few requests for the tooltip colors within the settings pages and the My Tickets page. This PR accounts for both.
N/A

Wallet Plus: DQA Fixes: CSS styling for My Tickets page and "Tooltip" color

---

src/Tribe/Events/Views/V2/Models/Tickets.php

N/A
- Fix PHP8.1 deprecation notices.

Fix PHP8.1 deprecation notices.

---

src/resources/postcss/components/attendees-list/_attendees.pcss
src/resources/postcss/my-tickets/_orders.pcss

DQA 11 & DQA 13 & DQA 14
This is an extension to my main PR https://github.com/the-events-calendar/event-tickets-wallet-plus/pull/77
This adds the setup to be able to use a container query.
Video of the "My Tickets" page.
[artifact_dqa_13.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/e6cf9f07-44c2-4992-94d0-1db6e0d1cbde)

DQA 11,13,14 My Tickets & Your Tickets button stacking

---

src/admin-views/editor/fieldset/settings-provider.php
src/resources/js/tickets.js

[TICKET_ID] 
* Saving settings were breaking the provider value.
* The fix properly saves the selected provider.
🎥 screencast(s): https://www.loom.com/share/c052ddf8fd84426ba9fc1f6ce8bab0ca
Fixed selcting the saved provider: https://www.loom.com/share/0171492aa2d74d4d87354323febe8761

Fix - Updating ticket provider data from ticket settings for classic editor.

---

src/resources/postcss/my-tickets/_orders.pcss
src/resources/postcss/rsvp-v1.pcss

N/A
Fixes some DQA issues that came up for the My Tickets Page.

Wallet Plus: My Tickets CSS fixes

---

src/Tickets/Blocks/Tickets/app/editor/container/container.js
src/Tickets/Blocks/Tickets/app/editor/container/style.pcss
src/Tickets/Blocks/Tickets/app/editor/container/template.js
src/Tickets/Blocks/Tickets/app/editor/inactive/inactive.js

[ET-1789] 
- Added ticket management helper text and link
[ET-1789]: https://stellarwp.atlassian.net/browse/ET-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added ticket management helper text and link

---

src/Tickets/Admin/Upsell.php

[TICKET_ID] 
Received request to update the link to ETWP on the Tickets Emails settings page.
n/a

Quick Fix: Link Update

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
src/resources/js/admin/gateway/stripe/webhooks.js

[ET-1511] 
Not a great candidate to include tests due to the nature of the supporting code.
https://i.bordoni.me/y28mM5v0
[ET-1511]: https://stellarwp.atlassian.net/browse/ET-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce a polling system for the valid keys for stripe

---

src/Tickets/Blocks/app/flexible-tickets/block-editor/hooks/filters.js
src/modules/blocks/rsvp/style.pcss

[ET-1787] 
- Displaying warning message when there are no tickets or series passes even if the block is selected or not
- Fixed RSVP styles
Scenario 5
https://www.loom.com/share/f4c454e2f1dc4b10812c203970e60358
RSVP Fixed styles
https://www.loom.com/share/4dab6ef12ebc4081ac0cd57ac3e7a60a
[ET-1787]: https://stellarwp.atlassian.net/browse/ET-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Displaying warning message when there are no tickets or series passes even if the block is selected or not

---

src/Tickets/Admin/Provider.php
src/Tickets/Flexible_Tickets/Series_Passes.php
src/admin-views/editor/panel/fields/dates.php
src/admin-views/editor/panel/fields/description.php
src/admin-views/editor/panel/fields/name.php
src/admin-views/editor/panel/ticket.php
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event without ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html

[ET-1944] 
🎥 screencast(s): https://www.loom.com/share/0746c2fd9c94439bafe149820a23d53d
[ET-1944]: https://stellarwp.atlassian.net/browse/ET-1944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1944] Moved ticket type label for ticket editor.

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

Bump ET Version Num

---

readme.txt
src/Tickets/Commerce/Admin_Tables/Orders.php
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with 1 pending and 1 completed order__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with multiple tickets and orders__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with multiple tickets in same order__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with no orders__0.snapshot.html
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with one order__0.snapshot.html

[ET-1873] 
- Added Print button to TC Orders
[ET-1873]: https://stellarwp.atlassian.net/browse/ET-1873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added Print button to TC Orders

---

src/Tickets/Flexible_Tickets/Series_Passes/Reports.php
tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event in a series with no orders__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event in a series with one order__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__recurring event with no order__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__recurring event with one order__0.snapshot.html

[ET-1812] 
[ET-1812]: https://stellarwp.atlassian.net/browse/ET-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat - Hide attendee/order report linka for series without passes.

---

.github/workflows/tests-php.yml
src/Tickets/Flexible_Tickets/Series_Passes/Series_Passes.php
src/Tribe/Tickets_Handler.php
tests/commerce_integration/TEC/Admin/MoveTicketsTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/SharedCapacity/SharedCapacityTest.php

Follow-up to FT issue 137 fix to align tests.

fix(Tickets_Handler) clean Ticket cache after cap. sync

---

readme.txt
src/admin-views/editor/column-body-price.php
src/views/blocks/tickets/footer.php
src/views/registration-js/content.php
src/views/registration/button-cart.php
src/views/v2/tickets/footer/return-to-cart.php

[ET-1759] 
We found some instances where we weren't passing either a string or object into `method_exists()`. It is now required in PHP 8.1
N/A
[ET-1759]: https://stellarwp.atlassian.net/browse/ET-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1759] Audit of `method_exists()`

---

src/Tribe/Tickets_View.php

Correctly check if the current page is a ticket order edits page.
[Demo](https://share.cleanshot.com/LwTrHw5m)

fix(Tickets_View) check if edit page correctly

---

.env
.env.testing.tric
composer.json
composer.lock
phpcs.xml

This updates our code to use the new standards library.
Also updates the PHP version used in testing.

Swap out the TEC coding standards for the new StellarWP one.

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

Update version number

---

src/Tickets/Flexible_Tickets/Metabox.php
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event by Occurrence provisional ID__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__event__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__post__0.snapshot.html

[ET-1963] 
[ET-1963]: https://stellarwp.atlassian.net/browse/ET-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1963] - Fixed KB links for series pass article.

---

src/Tickets/Site_Health/Info_Section.php
src/Tickets/Site_Health/Provider.php

While going through code found use statements that were no longer needed.

Removed old use statements.

---

readme.txt

Release: Update pot file and readme.

Release: Pot file changes

---

changelog.txt
readme.txt
src/Tickets/Commerce/Admin_Tables/Orders.php
src/Tickets/Commerce/Gateways/Stripe/Payment_Intent_Handler.php
src/Tickets/Flexible_Tickets/Series_Passes/Base.php
src/Tickets/Site_Health/Abstract_Info_Subsection.php
src/Tickets/Site_Health/Info_Section.php
src/Tickets/Site_Health/Subsections/Features/Tickets_Commerce_Subsection.php
src/Tickets/Site_Health/Subsections/Plugins/Plugin_Data_Subsection.php

Update changelog and readme
Replace TBD with version num

Release: Changelog

---

readme.txt

date change

---

src/Tickets/Flexible_Tickets/Series_Passes/Attendees.php
src/Tribe/Attendees_Table.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/AttendeesTest.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/AttendeesTest__should_remove_checkin_row_action_from_series_page__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/AttendeesTest__should_remove_checkin_row_action_from_series_passes_attendeees_not_yet_cloned_to_event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/AttendeesTest__should_remove_move_row_action_from_series_page__0.snapshot.html

[TICKET_ID] 
📷 screenshot(s): https://share.cleanshot.com/fLnF0Ld0
demo: https://share.cleanshot.com/jcbs2JHD

Feat - Remove checkin row action for series attendees page.

---

.github/workflows/link-project.yml

Includes a new Workflow that will create or add a project based on the Base branch of the PRs.

Innovation: Project Link to Release workflow

---

src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php

[GTRIA-865] 
- Fixing typo, no need for artifacts, QA or readme entry.
[GTRIA-865]: https://stellarwp.atlassian.net/browse/GTRIA-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GTRIA-865] fix typo

---

readme.txt
src/Tickets/Commerce/Ticket.php
tests/commerce_integration/TEC/Admin/MoveTicketsTest.php

[ET-2009]
🎥 screencast(s): https://www.loom.com/share/e1d70e0f8a2545ebbff1461a146d668d
[ET-2009]: https://stellarwp.atlassian.net/browse/ET-2009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2009] Fix - Sync TicketsCommerce ticket stock on moving attendees.

---

readme.txt
src/Tribe/Admin/Columns/Tickets.php
src/Tribe/Attendees.php
tests/wpunit/Tribe/Tickets/Attendees_Test.php

Added capability check.

---

readme.txt
src/Tickets/Site_Health/Subsections/Plugins/Plugin_Data_Subsection.php

[ET-2017]
As part of a previous MR we added `Average Ticket Price`,`Maximum Ticket Price`, and `Minimum Ticket Price`. However, when TEC was disabled the Site Health page would fatal. I found that switching the ORM to `tickets.ticket-repository` from using `tickets.event-repository` fixed the issue.
[artifact_et-2017.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/1aca7acf-ca93-4c48-90c2-11ad35e46eac)
[ET-2017]: https://stellarwp.atlassian.net/browse/ET-2017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2017] Added additional fields to the Event Tickets Site Health section.

---

readme.txt

Moving release date from 3/11/2024 to 3/12/2024

Release date bump

---

lang/event-tickets.pot
readme.txt
src/Tickets/Commerce/Reports/Orders.php
src/Tickets/Commerce/Reports/Report_Abstract.php
src/Tickets/Commerce/Ticket.php
src/Tickets/Emails/Dispatcher.php
src/Tickets/Flexible_Tickets/Series_Passes/Attendees.php
src/Tribe/Admin/Columns/Tickets.php
src/Tribe/Admin/Move_Tickets.php
src/Tribe/Attendees.php
src/Tribe/Metabox.php
src/Tribe/Repositories/Traits/Post_Tickets.php
src/Tribe/Tickets.php
tests/wpunit/Tribe/Tickets/Attendees_Test.php

Sync - with master

---

changelog.txt
readme.txt
src/Tickets/Admin/Upsell.php
src/Tickets/Blocks/Controller.php
src/Tickets/Commerce/Reports/Report_Abstract.php
src/Tickets/Commerce/Settings.php
src/Tickets/Emails/Admin/Emails_Tab.php
src/Tickets/Emails/Email/Purchase_Confirmation_Email_Interface.php
src/Tickets/Emails/JSON_LD/Event_Schema.php
src/Tickets/Emails/JSON_LD/Reservation_Schema.php
src/Tickets/Emails/Legacy_Hijack.php
src/Tickets/Flexible_Tickets/Series_Passes/Emails.php
src/Tickets/Flexible_Tickets/Series_Passes/Emails/Mock_Event_Post.php
src/Tickets/Flexible_Tickets/Series_Passes/Emails/Mock_Preview_Post.php
src/Tickets/Flexible_Tickets/Series_Passes/Emails/Mock_Series_Post.php
src/Tickets/Flexible_Tickets/Series_Passes/Emails/Series_Pass.php
src/Tickets/Flexible_Tickets/Series_Passes/Emails/Upcoming_Events.php
src/Tickets/Flexible_Tickets/Series_Passes/Emails/Upcoming_Series_Events_List.php
src/Tickets/Site_Health/Subsections/Plugins/Plugin_Data_Subsection.php
src/Tribe/Attendees.php
src/Tribe/Attendees_Table.php
src/Tribe/Repositories/Traits/Post_Tickets.php
src/views/emails/series-pass.php
src/views/emails/template-parts/body/additional-content.php
src/views/emails/template-parts/body/post-description.php
src/views/emails/template-parts/body/series-events-list.php
src/views/emails/template-parts/body/series-pass-dates.php
src/views/emails/template-parts/body/thumbnail.php
src/views/emails/template-parts/header/head/series-pass-styles.php

Cocker Spaniel Changelog Updates for ET

Cocker Spaniel Changelog Updates for ET

---

event-tickets.php
src/resources/postcss/tickets-admin.pcss
src/resources/postcss/tickets/_block.pcss

Sale Price: Fix lint tests

---

src/Tickets/Commerce/Ticket.php
src/modules/data/blocks/ticket/reducers/tickets/ticket/details.js
tests/commerce_integration/TEC/Tickets/Commerce/TicketTest.php

Fix -  Fix on sale not showing in block editor list and same day sale date validation

---

src/resources/postcss/tickets/_block-extras.pcss
src/resources/postcss/tickets/_block.pcss
src/views/v2/tickets/item/content/sale-label.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/TitleTest__test_should_render_sale_label__1.php

[ET-2038]
Fixes alignment issues that were found during DQA
Before:
After:
[ET-2038]: https://stellarwp.atlassian.net/browse/ET-2038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2038] Sale Price: Front-end Tickets Block - DQA Adjustments

---

src/Tickets/Blocks/Ticket/app/editor/container-content/sale-price/container.js
src/Tickets/Blocks/Ticket/app/editor/container-content/sale-price/style.pcss
tests/integration/Tribe/Tickets/MetaboxTest.php

[TICKET_ID]
📷 screenshot(s): https://share.cleanshot.com/lcTSzvJb

Fix - Block editor DQA updates.

---

src/Tickets/Commerce/Reports/Data/Order_Summary.php
tests/integration/Tribe/Admin/OrderReportTest.php
tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with sale price enabled tickets and orders__0.snapshot.html

[TICKET_ID]
* Order sales summary is now calculated from order info instead of using the ticket price directly. Therefore, sale price total is properly reflected. 
📷 screenshot(s): https://share.cleanshot.com/JGGD9jYQ

Feat - Calculate sales info using order data for TicketsCommerce.

---

event-tickets.php
readme.txt

Add changelog for Collie

---

src/Tickets/Blocks/Ticket/app/editor/container-content/sale-price/container.js
src/Tickets/Blocks/Ticket/app/editor/container-content/sale-price/template.js
src/Tickets/Commerce/Editor/Metabox.php
src/Tickets/Commerce/Hooks.php
src/Tickets/Commerce/Models/Ticket_Model.php
src/Tickets/Commerce/Reports/Data/Order_Summary.php
src/Tickets/Commerce/Ticket.php
src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
src/Tribe/REST/V1/Post_Repository.php
src/admin-views/commerce/metabox/sale-price.php
src/admin-views/editor/fieldset/price.php
src/modules/data/blocks/ticket/actions.js
src/views/v2/commerce/ticket/price.php
src/views/v2/commerce/ticket/regular-price.php
src/views/v2/commerce/ticket/sale-price.php
src/views/v2/tickets/item/content/sale-label.php
src/views/v2/tickets/item/content/title.php
src/views/v2/tickets/item/extra/price.php

Replace TBDs

---

readme.txt
src/Tribe/Main.php

Added pot file changelog.

---

src/Tribe/Main.php
vendor/phpqrcode/qrencode.php

Rafsun pointed out a few areas we could cast as integers https://github.com/the-events-calendar/event-tickets/pull/2983

[ET-2062] Added casts in a few more spots.

---

src/Tribe/Main.php

Bumping version to 5.9.1

---

readme.txt
src/Tribe/Main.php

Release date update.

---

src/Tickets/Admin/Attendees/Modal.php
src/Tickets/Flexible_Tickets/Series_Passes/Editor.php

[ET-1707]
- Fix conditional to avoid enqueueing series passes assets in the attendees page.
- Include modal in the attendees page.
[ET-1707]: https://stellarwp.atlassian.net/browse/ET-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix conditionals for the attendees page.

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

Update version number for Dachshund release

---

readme.txt
src/Tribe/Main.php

Readme changes, updated `Main.php` to get tests to run.

Readme changes, updated `Main.php` to get tests to run.

---

event-tickets.php
lang/event-tickets.pot
readme.txt
src/Tribe/Admin/Settings.php
src/Tribe/Main.php

Corgi 1 into Master

---

readme.txt
src/Tickets/Commerce/Admin_Tables/Orders.php

[GTRIA-1264]
🎥 screencast(s): https://www.loom.com/share/d955582721a249e6bf3b66d17eaac2a0
[GTRIA-1264]: https://stellarwp.atlassian.net/browse/GTRIA-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix - Order report export causing fatal with deleted tickets.

---

src/Tickets/Integrations/Plugins/Events_Pro/Duplicate_Post.php

[ET-2073] 
This ticket is a fix to my original PR. When you have RSVP + Another provider you technically have multiple providers. Therefore it's important to check the provider for each ticket. No readme needed.
[ET-2073]: https://stellarwp.atlassian.net/browse/ET-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2073] Duplicate tickets with multiple providers

---

src/Tickets/Commerce/Utils/Value.php
src/views/v2/commerce/ticket/regular-price.php
src/views/v2/commerce/ticket/sale-price.php

[ET-2077]
We want to show the ticket price as "Free" instead of "$0.00"
[ET-2077]: https://stellarwp.atlassian.net/browse/ET-2077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2077] Free Tickets: Show "Free" instead of "$0.00"

---

src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
tests/restv1/PayPal/SingleTicketCest.php

[ET-2078]
We found that when creating a new ticket, it was rejecting the price of '0.00'. Updating an existing ticket to '0.00' works fine.
N/A
[ET-2078]: https://stellarwp.atlassian.net/browse/ET-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2078] Update V1 REST API to Accept Free Ticket Price

---

src/Tickets/Commerce/Gateways/Free/Gateway.php

[TICKET_ID]
[Report](https://lw.slack.com/archives/C01T9UJGE2U/p1714749885306399?thread_ts=1714749852.542769&cid=C01T9UJGE2U)
* Hide generating connection button for Free gateway.
📷 screenshot(s): https://share.cleanshot.com/YBn3VLLQ

Spotfix - Hide free gateway settings button

---

src/Tribe/Main.php
src/functions/soft-disable.php

Add a function file to provide called functions for older plugin versions that call some functions incorrectly.

Modify the "soft disable" process.

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Hooks.php
src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
src/Tickets/Commerce/Gateways/Stripe/Signup.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
src/admin-views/settings/tickets-commerce/stripe/webhook-description.php

Prep for final release: asag

---

src/Tickets/Commerce/Admin/Orders_Page.php
src/Tickets/Commerce/Hooks.php
src/Tickets/Commerce/Order.php

[ET-2124]
The minimum amount needed to add "Orders" to the ticket menu. Note: Still a work in progress, because I think we want to hide this if TC isn't enabled.
[ET-2124]: https://stellarwp.atlassian.net/browse/ET-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Order Management: Add Orders Submenu

---

readme.txt
src/Tribe/Main.php

Update readme for language

---

readme.txt
src/Tribe/Main.php

Update readme's language entry for 5.11.0.2

Update readme's language

---

readme.txt

Update language changelog

---

src/Tickets/Commerce/Admin/Orders_Page.php
src/Tickets/Commerce/Admin_Tables/Orders_Table.php
src/Tickets/Commerce/Hooks.php
src/Tickets/Commerce/Status/Status_Handler.php
tests/_support/Commerce/TicketsCommerce/Order_Maker.php
tests/_support/Traits/With_Globals.php
tests/integration/TEC/Tickets/Commerce/Admin/Orders_PageTest.php
tests/integration/TEC/Tickets/Commerce/Admin_Tables/Orders_TableTest.php
tests/integration/TEC/Tickets/Commerce/Repositories/Order_RepositoryTest.php
tests/integration/TEC/Tickets/Commerce/Status/Status_HandlerTest.php

[ET-2117]
Adding tests to introduced code and fixing small issues that came up after testing
[ET-2117]: https://stellarwp.atlassian.net/browse/ET-2117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

make testing easier

---

src/Tickets/Seating/Service/Maps.php
src/Tickets/Seating/Service/Service.php
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing__0.snapshot.html
tests/slr_integration/Frontend_Test.php
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__layouts tab__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__five tickets__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__one ticket__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__two tickets__0.snapshot.html

Explicitly provide the Layout ID in the iFrame request for the service.
[Related to this service PR](https://github.com/the-events-calendar/event-tickets-seating-service/pull/37).
[Screenshot](https://share.cleanshot.com/msNN5JJs)

SLR - explicitly provide the Layout ID in the iFrame request URL

---

src/Tickets/Seating/Assets.php
src/Tickets/Seating/Service/Layouts.php
src/Tickets/Seating/Service/Service.php
src/Tickets/Seating/app/admin/layouts/actions.js
src/admin-views/seating/components/layouts/card.php
tests/slr_integration/Admin/Ajax_Test.php
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing_with_1_layout__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__layout edit tab__0.snapshot.html
tests/slr_integration/__snapshots__/Assets_Test__test_get_utils_data__0.snapshot.json

[SL-147](https://stellarwp.atlassian.net/browse/SL-147)
SLR PR [here](https://github.com/the-events-calendar/event-tickets-seating-service/pull/45) 
Show a confirmation pop-up when a user is attempting to edit a layout that has associated events.
[SL-147]: https://stellarwp.atlassian.net/browse/SL-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show confirm if necessary

---

composer.lock
event-tickets.php
readme.txt
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/ActiveTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/ActiveTest__test_should_render__0.snapshot.html

[ET-2117]
Changelog addition for Order Management p1.
[ET-2117]: https://stellarwp.atlassian.net/browse/ET-2117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2117] Provide changelog entry for Order Management P1

---

src/Tickets/Seating/Assets.php
src/Tickets/Seating/app/admin/layouts/actions.js
src/Tickets/Seating/app/service/api/externals.js
src/Tickets/Seating/app/service/api/index.js
tests/slr_jest/_bootstrap.js
tests/slr_jest/admin/layouts/actions.spec.js

Fix some logic issues and cover with tests the Layouts card list edit/delete actions.:

SLR - Cover edit/delete layout JS with tests

---

src/Tickets/Commerce/Gateways/Stripe/Settings.php

[ETP-934]
Follow up to https://github.com/the-events-calendar/event-tickets/pull/3125
[ETP-934]: https://stellarwp.atlassian.net/browse/ETP-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Address fields for stripe payment

---

readme.txt
src/Tribe/Attendees.php

[ET-2094]
In our previous CSV export functions we expected an associated `event_id`, that would exist as a query parameter. In our main attendees table we are now exporting all of them instead ( `event_id=all` ).
[ET-2094]: https://stellarwp.atlassian.net/browse/ET-2094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Attendees CSV Export

---

.github/workflows/lint.yml
.github/workflows/tests-js.yml
.github/workflows/zip.yml
src/Tribe/Main.php

No ticket
Fixing Node set up on GH workflows
-->

Fixes node set up for GH workflows

---

src/Tickets/Admin/All_Tickets/Hooks.php
src/Tickets/Admin/All_Tickets/Page.php
src/Tickets/Admin/All_Tickets/Provider.php
src/Tickets/Admin/Provider.php
src/admin-views/all-tickets.php
src/admin-views/all-tickets/tickets.php
tests/integration/TEC/Tickets/Admin/All_Tickets/PageTest.php
tests/integration/TEC/Tickets/Admin/All_Tickets/__snapshots__/PageTest__test_render_tec_tickets_all_tickets_page__0.snapshot.html

[ET-2174]
Creates a menu item and page for the All Tickets feature
[ET-2174]: https://stellarwp.atlassian.net/browse/ET-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2174] All Tickets Screen > Create menu item and page

---

src/Tickets/Commerce/Ticket.php

[ETP-920]
At some point, my changes in https://github.com/the-events-calendar/event-tickets/pull/3151 got overwritten. This PR fixes it.
If the `commerce_integration` tests are passing, it's fixed correctly.
[ETP-920]: https://stellarwp.atlassian.net/browse/ETP-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-920] Fix logic back to where it was

---

src/Tickets/Seating/app/frontend/session/style.pcss
src/Tickets/Seating/app/frontend/ticketsBlock/index.js
src/Tickets/Seating/app/frontend/ticketsBlock/style.pcss
src/Tickets/Seating/app/postcss/_iframe.pcss
src/views/seating/iframe-view.php
src/views/seating/seat-selection-timer.php
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__five tickets__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__one ticket__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__two tickets__0.snapshot.html
tests/slr_jest/_bootstrap.js
tests/slr_jest/frontend/__snapshots__/ticketsBlock.spec.js.snap
tests/slr_jest/frontend/ticketsBlock.spec.js

[SL-156](https://stellarwp.atlassian.net/browse/SL-156)
Brought the desktop modal design up to the current state of the design and added the responsive design so the modal will work as expected on mobile devices.
[https://www.loom.com/share/2d748e0ad8c64207aaa3cc9b2e4c0265?sid=b0c9f936-cb24-40f2-8fb9-413796404385](https://www.loom.com/share/2d748e0ad8c64207aaa3cc9b2e4c0265?sid=b0c9f936-cb24-40f2-8fb9-413796404385)
[SL-156]: https://stellarwp.atlassian.net/browse/SL-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLR: Frontend modal styles

---

src/Tickets/Seating/app/postcss/_iframe.pcss

[TICKET_ID]
📷 screenshot(s): https://share.cleanshot.com/wBcryxhr

[Spotfix] - Set min height for Layout edit view.

---

src/Tickets/Seating/Admin/Tabs/Layout_Card.php
src/Tickets/Seating/app/admin/layoutEdit/index.js
src/Tickets/Seating/app/utils/index.js
src/admin-views/seating/components/layouts/card.php
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing__0.snapshot.html
tests/slr_jest/frontend/__snapshots__/ticketsBlock.spec.js.snap
tests/slr_jest/utils/utils.spec.js

[SL-68]
📷 screenshot(s): https://share.cleanshot.com/nS6ZfFlC
[SL-68]: https://stellarwp.atlassian.net/browse/SL-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-68] - Open associated post link in new tab and display link inside the layout card.

---

src/Tickets/Commerce/Order.php
tests/integration/TEC/Tickets/Commerce/Admin/Singular_Order_PageTest.php
tests/integration/TEC/Tickets/Commerce/Admin/__snapshots__/Singular_Order_PageTest__it_should_match_order_actions_as_admin__0.snapshot.html

[ET-2182]
Fixes delete order caps
[ET-2182]: https://stellarwp.atlassian.net/browse/ET-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix delete order caps

---

src/Tickets/Seating/app/admin/layouts/style.pcss
src/Tickets/Seating/app/admin/maps/style.pcss

[Issues Sheet](https://docs.google.com/spreadsheets/d/1ZMmZZj4gc9-eBbktRM34Vmr6ROs33M7bfSXezqCMJjc/edit?gid=0#gid=0) #45
The seat map thumbnails should be be contained in their wrapper so the entire image is displayed.

Seat map thumbnails 

---

src/Tickets/Seating/Orders/Cart.php
src/Tickets/Seating/Orders/Controller.php
tests/slr_integration/Orders/Cart_Test.php

[SL-160]
[SL-160]: https://stellarwp.atlassian.net/browse/SL-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-160] Feat - Clear cart properly when session is expired to block purchases for invalid session with seated tickets.

---

src/Tickets/Seating/Orders/Attendee.php
src/Tickets/Seating/Orders/Controller.php
src/resources/postcss/tickets-commerce/_success.pcss

[SL-122]
📷 screenshot(s): https://share.cleanshot.com/c6M0J6hB
[SL-122]: https://stellarwp.atlassian.net/browse/SL-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-122] - Display seat label in Order Success page for TicketsCommerce when available.

---

src/resources/postcss/tickets-commerce/admin/orders/single.pcss

[ET-2208]
[ET-2208]: https://stellarwp.atlassian.net/browse/ET-2208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Temporary hide

---

src/Tickets/Seating/app/blockEditor/capacity-table.js
tests/slr_jest/blockEditor/__snapshots__/capacity-table.spec.js.snap
tests/slr_jest/blockEditor/capacity-table.spec.js

Fix capacity totals for ECP table

---

src/Tickets/Seating/app/blockEditor/filters.js
src/Tickets/Seating/app/blockEditor/store/selectors.js

Fixing capacity totals in the block editor

---

src/Tickets/Seating/app/blockEditor/availability-overview.js
tests/slr_jest/blockEditor/availability-overview.spec.js

Fixing bug related to issue 90

Unknown seat type case

---

src/Tickets/Blocks/Ticket/app/editor/container-content/capacity/style.pcss
src/Tickets/Blocks/Ticket/app/editor/template.js
src/Tickets/Seating/app/blockEditor/filters.js
src/Tickets/Seating/app/blockEditor/ticket-is-asc.js
tests/slr_jest/blockEditor/ticket-is-asc.spec.js

Hide progress bar quantity when ticket is ASC

---

src/Tickets/Blocks/Ticket/app/editor/container-header/template.js
src/Tickets/Seating/app/blockEditor/filters.js
src/Tickets/Seating/app/blockEditor/header-details.js
tests/slr_jest/blockEditor/header-details.spec.js

Fix ticket type displayed in header initially

---

src/Tickets/Seating/Editor.php
src/Tickets/Seating/app/blockEditor/add-seating-params-to-ajax-save-ticket.js
src/Tickets/Seating/app/blockEditor/filters.js
tests/slr_jest/admin/layouts/__snapshots__/add-new-modal.spec.js.snap
tests/slr_jest/blockEditor/add-seating-params-to-ajax-save-ticket.spec.js

Fix gac tickets capacity on first save

---

src/Tickets/Seating/Admin/Embed_Test.php
src/Tickets/Seating/Admin/Tabs/Layout_Edit.php
src/Tickets/Seating/Admin/Tabs/Map_Edit.php
src/Tickets/Seating/Frontend.php
src/Tickets/Seating/Orders/Seats_Report.php
src/Tickets/Seating/Service/Ephemeral_Token.php
src/Tickets/Seating/Service/Service.php
tests/slr_integration/Admin/Maps_Layout_Homepage_Test.php
tests/slr_integration/Frontend_Test.php
tests/slr_integration/Orders/Seats_Report_Test.php
tests/slr_integration/Service/Ephemeral_Token_Test.php

Ticket: [SL-161](https://stellarwp.atlassian.net/browse/SL-161)
[Related service PR](https://github.com/the-events-calendar/event-tickets-seating-service/pull/64)
This updates the code requesting ephemeral tokens to the service to include scopes.
Read more about the reasons and scopes in the Service PR linked above.
Artifacts:
* tests - updated and new
* demo - see in the service PR
[SL-161]: https://stellarwp.atlassian.net/browse/SL-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SL-161 Ephemeral tokens scope

---

src/Tickets/Seating/app/blockEditor/store/selectors.js
tests/slr_jest/blockEditor/store/__snapshots__/selectors.spec.js.snap
tests/slr_jest/blockEditor/store/selectors.spec.js

Fixed bleeding state - added more tests

---

src/Tickets/Seating/app/frontend/ticketsBlock/index.js
src/Tickets/Seating/app/frontend/ticketsBlock/style.pcss
src/modules/data/blocks/ticket/__tests__/__snapshots__/constants.test.js.snap
src/modules/data/blocks/ticket/__tests__/__snapshots__/types.test.js.snap
src/resources/js/v2/rsvp-block.js
src/views/seating/iframe-view.php
src/views/seating/seat-selection-timer.php
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_from_cookie_data__0.snapshot.html
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_to_sync__0.snapshot.html
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_to_sync_with_previous_render__0.snapshot.html
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_with_args__0.snapshot.html
tests/slr_integration/Orders/Seats_Report_Test.php
tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__1_ticket_1_attendee__0.snapshot.html
tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__2_tickets_3_attendees__0.snapshot.html
tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__no_tickets__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__five tickets__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__one ticket__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__two tickets__0.snapshot.html
tests/slr_jest/frontend/__snapshots__/ticketsBlock.spec.js.snap
tests/slr_jest/frontend/ticketsBlock.spec.js
tests/wpunit/Tickets/Seating/Libraries/UplinkTest.php
tests/wpunit/Tickets/Seating/Libraries/__snapshots__/UplinkTest__it_should_have_the_fields_for_seating_licenses_with_incorrect_permissions_snapshot__1.php
tests/wpunit/Tickets/Seating/Libraries/__snapshots__/UplinkTest__it_should_have_the_fields_for_seating_licenses_with_no_license_snapshot__1.php
tests/wpunit/Tickets/Seating/Libraries/__snapshots__/UplinkTest__it_should_have_the_fields_for_seating_licenses_with_valid_license_snapshot__1.php

[Issues Sheet](https://docs.google.com/spreadsheets/d/1ZMmZZj4gc9-eBbktRM34Vmr6ROs33M7bfSXezqCMJjc/edit?gid=0#gid=0)
Related to issues 83, 142, 82, and 85 on the issues sheet.  
Fixes to the mobile version of the SLR seat purchasing modal for customers.
All SLR specific test are passing locally.

Mobile SLR Purchase Modal

---

changelog/fix-ET-2223-email-attendees-list-function
readme.txt
src/Tribe/Attendees.php

[ET-2223]
The "Email" button on the individual event attendees page was not working correctly. This fixes a few bugs that were found to ensure that both a user and email will be accepted and that the status will show correctly and at the appropriate time.
Kudos to @masoodahmed For getting started on the fix in https://github.com/the-events-calendar/event-tickets/pull/3038
| Error showing when you first open the modal | Success message being shown even though email is never attempted to be sent |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/adf833f2-8850-428e-8a3f-c4c10dd2a041) | ![image](https://github.com/user-attachments/assets/a3496cef-3fe7-4b5e-8dcc-dc7ff1d888a9) |
No error when modal first opens:
| Email success message when using user | Email successfully sent …

[ET-2223] Fix email attendees list functionality

---

src/Tickets/Seating/Assets.php
src/Tickets/Seating/app/postcss/_tabs.pcss
src/admin-views/seating/components/maps/card.php
src/admin-views/seating/tabs/maps.php
src/views/seating/iframe-view.php
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_empty_layouts__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_empty_seating_configurations__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_maps_tab_card_listing__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_maps_tab_card_listing_with_1_map__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__maps tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__no tab__0.snapshot.html
tests/slr_integration/__snapshots__/Assets_Test__test_get_utils_data__0.snapshot.json
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__five tickets__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__one ticket__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__two tickets__0.snapshot.html
tests/slr_jest/_bootstrap.js
tests/slr_jest/frontend/__snapshots__/ticketsBlock.spec.js.snap

Issues: 158, 46, 50, 51, 52, 80
Styling fixes for the admin screens for SLR.

Styling fixes for SLR admin

---

changelog/fix-Attendees_Export_Admin_Only
src/Tribe/Attendees.php
tests/wpunit/Tribe/Tickets/Attendees_Test.php

[ET-2226]
Allow the Attendees CSV export for Admin and Editor roles and add a filter if customization is needed.
[ET-2226]: https://stellarwp.atlassian.net/browse/ET-2226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow Attendees CSV export per role

---

src/Tickets/Seating/Frontend.php
src/Tickets/Seating/app/frontend/ticketsBlock/style.pcss
src/views/seating/tickets-block.php
tests/slr_integration/Frontend_Test.php
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__sold out event__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__test_get_ticket_block_data__sold out event__0.snapshot.json

[issue-123]
📷 screenshot(s): https://share.cleanshot.com/Y62cTytx

Feat - Add sold out view for seating ticket block.

---

src/Tickets/Seating/Admin/Ajax.php
src/Tickets/Seating/Admin/Tabs/Map_Card.php
tests/slr_integration/Admin/Ajax_Test.php
tests/slr_integration/Admin/Events/__snapshots__/Controller_Test__test_associated_events_list__Events with varying status with pagination__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_maps_tab_card_listing__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_maps_tab_card_listing_with_1_map__0.snapshot.html

[TICKET_ID]
* Added a new flag while loading the embed layout for editing layouts to determine new layouts.

Tweak - Add isNew flag while adding new layouts.

---

tests/commerce_integration/TEC/Admin/MoveTicketsTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/SharedCapacity/SharedCapacityTest.php

N/A
This PR is focused on repairing the Move Tickets Test

Repair move tickets test

---

src/Tickets/Seating/Orders/Attendee.php
tests/slr_integration/Orders/Controller_Test.php
tests/slr_integration/Orders/__snapshots__/Controller_Test__test_ticket_emails_has_seat_info_for_multiple_attendees__0.snapshot.html

[Issue-117]
📷 screenshot(s): https://share.cleanshot.com/yJlh66Jd

Fix - Issue 117 seat label not showing properly in multiple ticket emails.

---

src/Tickets/Seating/Service/Maps.php
tests/slr_integration/Admin/Ajax_Test.php

Fix - Issue 173, added protection to avoid deletion of maps with layouts.

---

changelog.md
event-tickets.php
readme.txt

Updating changelogs

---

changelog/fix-Missed_Translations
src/admin-views/editor/list-row/available-dates.php

[TEC-4873]
Some dates in admin tables where not i18n formatted.
[TEC-4873]: https://stellarwp.atlassian.net/browse/TEC-4873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missed translations for dates

---

src/Tickets/Seating/Service/Reservations.php
tests/slr_integration/Service/Reservations_Test.php

[issue-88]
🎥 screencast(s): https://share.cleanshot.com/7n1RZG5J

Fix - Remove seat label info when seat assignment removed from Seat report tab,

---

src/Tickets/Seating/Admin.php
tests/slr_integration/Admin_Test.php

Fixes woo incompatibility notice appearance logic

---

src/Tickets/Seating/Tables/Custom_Table_Query_Methods.php
src/Tickets/Seating/app/blockEditor/hook-callbacks.js
tests/slr_jest/blockEditor/hook-callbacks.spec.js

Fixing initial display of seat type on ticket block

---

src/Tickets/Seating/Frontend/Timer.php
tests/slr_integration/Frontend/Timer_Test.php

Issue 174 from gsheet
https://www.loom.com/share/55f9e9a99933411996555b171c4daee9

Interrupt sessions when event is sold out

---

readme.txt
src/admin-views/admin-welcome-message.php

[ET-2241] [TEC-5242]
As you review this, please make sure you keep in mind this is for a Black Friday.
Still haven't touched the existing tests here, so I am expecting them to break, will fix them tomorrow.
https://i.bordoni.me/GqsJbYmj
[ET-2241]: https://stellarwp.atlassian.net/browse/ET-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TEC-5242]: https://stellarwp.atlassian.net/browse/TEC-5242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include new Black Friday Banner

---

src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/Localization.php
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_ajax_interrupt__event with no tickets available and custom calendar slug__0.snapshot.json
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_ajax_interrupt__event with no tickets available__0.snapshot.json
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_ajax_interrupt__post with no tickets available__0.snapshot.json
tests/slr_integration/__snapshots__/Assets_Test__test_get_utils_data__0.snapshot.json

Text updates

---

src/Tickets/Seating/Health.php
src/Tickets/Seating/Service/Error_Content.php
src/Tickets/Seating/app/blockEditor/capacity-form/service-error.js
src/Tickets/Seating/app/blockEditor/settings/outage.js
tests/slr_integration/__snapshots__/Health_Test__it_should_check_slr_can_see_sass_when_sass_unavailable__0.snapshot.json
tests/slr_integration/__snapshots__/Health_Test__it_should_check_slr_valid_license_with_invalid_license__0.snapshot.json

Rename seat builder to seating builder

---

tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php

fixing gi tests after merge with master

Fixing GI tests

---

src/Tickets/Seating/Commerce/Controller.php
src/Tickets/Seating/Service/Seat_Types.php
src/Tribe/Ticket_Object.php

Fixing phpcs

---

src/Tickets/Seating/Controller.php
src/Tickets/Seating/Delete_Operations.php
src/Tickets/Seating/app/blockEditor/store/selectors.js
tests/slr_integration/Delete_Operations_Test.php

Fix issue 221: remove ASC lock when last ASC ticket removed from post
- **fix(Seating) layout is locked only if using assigned seating**
- **fix(Seating) remove ASC lock on last ASC ticket trash delete**

SLR - fix issue 221

---

src/Tickets/Seating/Admin/Events/Controller.php

Feat - Block adding series for seated events

---

src/Tickets/Blocks/Ticket/app/editor/container-content/capacity/container.js
src/Tickets/Blocks/Ticket/app/editor/container-content/capacity/template.js
src/Tickets/Seating/app/blockEditor/filters.js

[TICKET_ID]
Issue sheet: 223
🎥 screencast(s): https://share.cleanshot.com/gmylYC0Q

Fix - Only show ASC ticket options on block editor for TicketsCommerce provider.

---

src/Tickets/Seating/Service/Layouts.php
src/Tickets/Seating/Service/Maps.php
src/Tickets/Seating/app/service/api/localized-data.js
tests/slr_integration/Truncates_Custom_Tables.php

Fixes issue 230 from the sheet where creating a new Layout from the Layouts tab would break.

SLR - fix new Layout issue

---

src/admin-views/order_modifiers/coupon-edit.php
src/admin-views/order_modifiers/fee-edit.php
src/resources/postcss/tickets-admin/settings/_all.pcss
src/resources/postcss/tickets-admin/settings/_order_modifiers.pcss

Updated Styles form the Coupon And Fee edit pages.

---

src/Tickets/Seating/Admin.php

https://lw.slack.com/archives/C05QHBFKYCA/p1729547378657969
[TICKET_ID]
* Move the seating menu item from bottom to in between Orders and Settings.
📷 screenshot(s): https://share.cleanshot.com/vgGDFKWq

Fix - Moved seating menu item to correct position.

---

src/Tickets/Seating/Admin.php
src/Tickets/Seating/Orders/Seats_Report.php
src/Tickets/Seating/Service/Error_Content.php
src/Tickets/Seating/Service/Service_Status.php
src/Tickets/Seating/app/blockEditor/capacity-form/service-error.js
src/Tickets/Seating/app/blockEditor/filters.js
src/Tickets/Seating/app/blockEditor/hook-callbacks.js
tests/slr_integration/Admin_Test.php
tests/slr_integration/Commerce/Controller_Test.php
tests/slr_integration/Editor_Test.php
tests/slr_integration/Frontend_Test.php
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page_when_license_exists__no tab - expired license__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page_when_license_exists__no tab - invalid license__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page_when_license_exists__no tab - not connected__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page_when_license_exists__no tab - service down__0.snapshot.html
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__no license__0.snapshot.json
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__no license__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__test_get_ticket_block_data__no license__0.snapshot.json
tests/slr_jest/admin/layouts/__snapshots__/add-new-modal.spec.js.snap

Adding no license state - amending text and functionality when on that state

---

changelog/feat-update-seating-requirements
changelog/feat-update-seating-requirements-2
src/Tribe/Main.php
src/Tribe/Plugin_Register.php

Update ET requirements for seating

---

src/Tickets/Seating/Orders/Attendee.php
src/Tickets/Seating/Orders/Controller.php
src/Tribe/Attendees.php
tests/slr_integration/Admin/Maps_Layout_Homepage_Test.php
tests/slr_integration/Orders/Controller_Test.php

Filter and fix the totals in the Attendees page in Seating context.
[SL-200](https://stellarwp.atlassian.net/browse/SL-200)
[SL-200]: https://stellarwp.atlassian.net/browse/SL-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(Seating) correct totals in Attendees page

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

Fext Version Update

---

changelog/feat-seating-changelogs
changelog/feat-seating-changelogs-10
changelog/feat-seating-changelogs-11
changelog/feat-seating-changelogs-12
changelog/feat-seating-changelogs-13
changelog/feat-seating-changelogs-14
changelog/feat-seating-changelogs-2
changelog/feat-seating-changelogs-3
changelog/feat-seating-changelogs-4
changelog/feat-seating-changelogs-5
changelog/feat-seating-changelogs-6
changelog/feat-seating-changelogs-7
changelog/feat-seating-changelogs-8
changelog/feat-seating-changelogs-9

Added Seating changelog

---

changelog.md
changelog/feat-seating-changelogs
changelog/feat-seating-changelogs-10
changelog/feat-seating-changelogs-11
changelog/feat-seating-changelogs-12
changelog/feat-seating-changelogs-13
changelog/feat-seating-changelogs-14
changelog/feat-seating-changelogs-2
changelog/feat-seating-changelogs-3
changelog/feat-seating-changelogs-4
changelog/feat-seating-changelogs-5
changelog/feat-seating-changelogs-6
changelog/feat-seating-changelogs-7
changelog/feat-seating-changelogs-8
changelog/feat-seating-changelogs-9
changelog/feat-update-seating-requirements
changelog/feat-update-seating-requirements-2
changelog/fix-ET-2256-duplicate-attendees-created
readme.txt

process changelogs

---

.github/workflows/phpcs.yml
.github/workflows/tests-js.yml
.github/workflows/tests-php.yml

Based on a conversation with @lucatume earlier today we need to fix this particular piece of the test since it was breaking all of our tests.

Update tests-php.yml to skip any SLIC step when PHP files are not involved

---

src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layout_edit__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_map_edit__0.snapshot.html
tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__1_ticket_1_attendee__0.snapshot.html
tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__2_tickets_3_attendees__0.snapshot.html
tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__no_tickets__0.snapshot.html
tests/slr_integration/Service/Service_Test.php
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__layout edit tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__map edit tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__map new tab__0.snapshot.html
tests/slr_integration/__snapshots__/Assets_Test__test_service_bundle_data__0.snapshot.json

Before calling function, ensure it exists.

fix(deactivation) ensure function exists before call

---

src/Tickets/Seating/app/blockEditor/capacity-form/style.pcss

[TICKET_ID]
* https://lw.slack.com/archives/C05QHBFKYCA/p1730141253928909
* 
📷 screenshot(s): 
With seating enabled: https://share.cleanshot.com/FJt6K1g5
With seating disabled: https://share.cleanshot.com/sLQB4rYh
Without seating with ETP: https://share.cleanshot.com/Yx8wwNp0
With seating with ETP: https://share.cleanshot.com/kNKWHZWw

Fix - Capacity Input box CSS updated.

---

src/Tickets/Seating/Controller.php
src/Tickets/Seating/app/frontend/ticketsBlock/index.js

Replace TBDs with appropriate version

---

changelog/fix-prevent-fatal-with-index-on-4-byte-collations
src/Tickets/Seating/Tables/Sessions.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/Checkout_ShortcodeTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php

[ET-2262]
[ET-2262]: https://stellarwp.atlassian.net/browse/ET-2262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prevent fatal while creating Sessions table for Seating on environments with limited character length on indexes

---

src/Tribe/Admin/Notices.php
src/Tribe/Tickets.php
tests/integration/Tribe/Admin/NoticeTest.php

[ET-2261]
Adds a notice if the site is using an FSE theme and a custom AR Page with Shortcode hasn't been set up.
https://share.zight.com/4guGGBpL
[ET-2261]: https://stellarwp.atlassian.net/browse/ET-2261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2261] FSE Theme Notice

---

changelog.md
readme.txt

Update changelog for fext

---

changelog/feat-sl-213-time-settings
src/Tickets/Seating/Controller.php
src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/Settings.php
tests/slr_integration/Settings_Test.php
tests/slr_integration/__snapshots__/Settings_Test__test_seating_reservation_setting_is_included_after_login_requirements__0.snapshot.json

[SL-213]
* Add a settings option to control the seating selection reservation timer.
🎥 screencast: https://share.cleanshot.com/Lp2fjfYK
[SL-213]: https://stellarwp.atlassian.net/browse/SL-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-213] Feat - Add reservation timer settings for seating.

---

changelog/slr-fix-sl-233-pass-3
src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/Tables/Sessions.php
tests/slr_integration/Frontend/Timer_Test.php
tests/slr_integration/Service/Tables/Sessions_Test.php

[SL-233](https://stellarwp.atlassian.net/browse/SL-233)
Fix another issue with timer and session found out during QA pass.
More details and demo in the issue.
[SL-233]: https://stellarwp.atlassian.net/browse/SL-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SL-233 - pass 3

---

src/Tickets/Seating/Admin/Ajax.php
src/Tickets/Seating/Editor.php
src/Tickets/Seating/Frontend.php
src/Tickets/Seating/Frontend/Session.php
src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/Orders/Cart.php
src/Tickets/Seating/Orders/Controller.php
src/Tickets/Seating/Service/Layouts.php
src/Tickets/Seating/Service/Service_Status.php
src/Tickets/Seating/Settings.php
src/Tickets/Seating/Tables/Sessions.php
src/Tickets/Seating/Uplink.php
src/Tickets/Seating/app/admin/layouts/actions.js
src/Tickets/Seating/app/admin/maps/actions.js
src/Tickets/Seating/app/frontend/session/index.js
src/Tribe/Admin/Notices.php
src/Tribe/Attendee_Registration/Template.php
tests/_data/mu-plugins/slr-test.php

Replace TBDs for freybug

---

changelog/tweak-analyze

Analyze for freybug

---

src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifier_Relationships.php
src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers.php
src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers_Meta.php

Changed the schema version to 0.1.0-dev

Booking Fees - Change custom table schema version

---

changelog.md
readme.txt

Update tested up to header for freybug
Update release date for freybug

Update release date and tested up to header

---

.github/workflows/tests-php.yml
src/Tickets/Commerce/Models/Order_Model.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Order_Modifiers/Admin/Order_Modifier_Fee_Metabox.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Abstract_Fees.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Gateway/Stripe/Fees.php
src/Tickets/Commerce/Repositories/Order_Repository.php
tests/order_modifiers_integration.suite.dist.yml
tests/order_modifiers_integration/Orders/Orders_Test.php
tests/order_modifiers_integration/_bootstrap.php

This fixes an issue where we were storing the items with a serialized class. This was due to us not calling `get()` on the precision value object.

Booking Fees - Fixed issue with serialized class.

---

src/Tickets/Commerce/Order_Modifiers/API/Fees.php

remove get_selected_fees_for_ticket and replace with get_selected_fees

---

src/Tickets/Commerce/Order_Modifiers/API/Fees.php

[TICKET_ID]
Remove the `tec_tickets_commerce_add_fees_to_ticket_data` filter, as this could lead to errors in the block editor.

Remove the 'tec_tickets_commerce_add_fees_to_ticket_data' filter

---

src/Tickets/Commerce/Order_Modifiers/Checkout/Gateway/Stripe/Fees.php
tests/order_modifiers_integration/Checkout/Gateway/Stripe/Stripe_Fees_Test.php

Making sure metadata of fees is being passed correctly to stripe.

Make sure stripe metadata is being passed correctly

---

tests/order_modifiers_integration/Checkout/Fees_Test.php
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_not_calculate_fees_for_free_tickets__0.snapshot.html

Making sure that fees are not being calculated for free tickets

Make sure no fees are added for free tickets

---

composer.lock

Fix composer.lock file with php faker package included

Fix lock with faker package included

---

.github/workflows/tests-php-ct1.yml
.github/workflows/tests-php-ft.yml
.github/workflows/tests-php.yml

Update wp version for tests

---

changelog.md
readme.txt

Tweak - change log updated

---

src/Tickets/Commerce/Order.php

Specify status any on upsert query

---

.prettierrc.js
package-lock.json
package.json
src/Tickets/Blocks/Controller.php
src/Tickets/Blocks/Tickets/Block.php
src/Tickets/Blocks/Tickets/app/editor/controls/template.js
tests/integration/TEC/Tickets/Blocks/Tickets/BlockTest.php

Registers Ticket Blocks Assets through stellarwp/assets.
Also adds a root path for them.

Register ticket blocks assets through stellarwp/assets

---

src/Tickets/Admin/Tickets/Screen_Options.php
src/Tickets/Commerce/Attendee.php
src/Tickets/Commerce/Cart.php
src/Tickets/Commerce/Flag_Actions/Increase_Sales.php
src/Tickets/Commerce/Gateways/Stripe/Hooks.php
src/Tickets/Commerce/Gateways/Stripe/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Order_Modifiers/Modifier_Admin_Handler.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Modifier_Abstract.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Modifier_Manager.php
src/Tickets/Commerce/Order_Modifiers/Repositories/Order_Modifiers.php
src/Tickets/Commerce/Order_Modifiers/Table_Views/Order_Modifier_Table.php
src/Tickets/Commerce/Order_Modifiers/Traits/Meta_Keys.php
src/Tickets/Commerce/Order_Modifiers/Traits/Status.php
src/Tickets/Commerce/Status/Refunded.php
src/Tickets/Commerce/Status/Status_Abstract.php
src/Tickets/Commerce/Status/Trashed.php
src/Tickets/Flexible_Tickets/WP_Cli.php
src/Tickets/Seating/Frontend.php
src/Tickets/Seating/REST.php
src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
src/views/v2/tickets/item.php
tests/_support/Traits/Order_Modifiers.php
tests/order_modifiers_integration/Repositories/Fees_Test.php

TBDs for imp

---

changelog.md
readme.txt

Update changelog for imp

---

changelog.md
readme.txt

Update Jira tickets in changelog

---

src/modules/blocks/attendees/template.js
src/modules/elements/action-button/element.js

N/A
For some reason, the lint tests were failing in antman. This PR fixes them.

Fix all linting errors

---

tests/_support/Commerce/Ticket_Maker.php

Clear cache on ticket creation in tests context

Clear ticket and parent event cache on ticket creation

---

.github/workflows/tests-php-ct1.yml
.github/workflows/tests-php-ft.yml
.github/workflows/tests-php.yml
.github/workflows/zip.yml

Fix - updated deprecated actions cache version.

---

changelog/feat-process-waitlist-subscribers
src/views/emails/confirmation.php
src/views/emails/spot-available.php

[ETP-957]
Adds ETP waitlist email templates here. The ticket emails is built in a way that does NOT allow extensibility from other plugins. The scope of my task is not to fix that, even though i would like that. Unfortunately there is no time for that currently.
As a result, i have to include ETP email templates in here.
[ETP-957]: https://stellarwp.atlassian.net/browse/ETP-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Process subscribers functionality

---

src/Tickets/Seating/Frontend.php

[SL-267]
[SL-267]: https://stellarwp.atlassian.net/browse/SL-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-267] Feat - Currency format update for seating tickets.

---

src/Tickets/Seating/Service/Layouts.php
src/Tickets/Seating/Service/Maps.php
src/Tickets/Seating/Service/Seat_Types.php
src/Tickets/Seating/Uplink.php
tests/_support/Commerce/OrderModifiers/Fee_Creator.php
tests/slr_ecp_integration/_bootstrap.php
tests/slr_integration/Admin/Ajax_Test.php
tests/slr_integration/Admin/Maps_Layout_Homepage_Test.php
tests/slr_integration/Orders/Cart_Test.php
tests/slr_integration/Service/Seat_Types_Test.php
tests/slr_integration/_bootstrap.php

[ETP-974]
Updates because of stellarwp/schema update.
[ETP-974]: https://stellarwp.atlassian.net/browse/ETP-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Changes because of stellarwp/schema update

---

tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_preview_series_pass_email__changed subject, heading, additional content__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_preview_series_pass_email__default values__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_preview_series_pass_email__no series excerpt, no upcoming events list__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__changed subject, heading, additional content__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__default settings__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__no series excerpt, no upcoming events list__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__no upcoming events__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__setting upcoming events count to 2__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__setting upcoming events count to 6__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__with images__0.snapshot.html

This PR accompanies PR #3564 to update the snapshots to match the CSS changes.

Update snapshots for PR #3564

---

src/resources/postcss/tickets-admin.pcss

CSS order of properties

---

changelog.md
event-tickets.php
lang/event-tickets.pot
readme.txt
src/Tickets/Commerce/Module.php
src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
src/Tribe/Main.php
src/Tribe/Metabox.php
src/Tribe/Status/Manager.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/EventStockTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/UpdateTest.php

Task/merge helper/waitlist

---

changelog/enhancement-ET-2295-Include_virtual_event_link_in_series_pass_email
src/views/emails/template-parts/body/series-events-list.php
src/views/emails/template-parts/header/head/series-pass-styles.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_preview_series_pass_email__changed subject, heading, additional content__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_preview_series_pass_email__default values__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_preview_series_pass_email__no series excerpt, no upcoming events list__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__changed subject, heading, additional content__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__default settings__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__no series excerpt, no upcoming events list__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__no upcoming events__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__setting upcoming events count to 2__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__setting upcoming events count to 6__0.snapshot.html
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__test_send_series_pass_email__with images__0.snapshot.html

Reverts the-events-calendar/event-tickets#3564 and #3565
[ET-2295]
[ET-2295]: https://stellarwp.atlassian.net/browse/ET-2295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "Included link to virtual events in Series Pass email when the event i…"

---

tests/slr_integration/Commerce/Controller_Test.php

Fix - Add admin user for test case to avoid permission isssue.

---

changelog/task-run-analyze-batman-1
changelog/task-run-analyze-batman-2

added analyze changelog

---

changelog/fix-delete-ticket-API
src/Tickets/Commerce/Flag_Actions/Decrease_Stock.php
src/Tickets/Commerce/Flag_Actions/Increase_Stock.php
src/Tickets/Commerce/Module.php
src/Tribe/Attendees_Table.php
src/Tribe/Metabox.php
tests/commerce_integration/TEC/Tickets/Commerce/Order_Test.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/UpdateTest.php

[ET-2313]
Fixes broken API `delete_ticket` by not directly checking capabilities in the API method itself but `a level higher`. e.g. in the REST controller, or in the admin list table action handler etc...
Previously broken tests passing and SVUL-14 still patched are enough artifacts.
[ET-2313]: https://stellarwp.atlassian.net/browse/ET-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix delete ticket API

---

changelog/fix-ticket-preset-ticket-group-table-creation-mysql
changelog/fix-ticket-preset-ticket-query
src/Tickets/Flexible_Tickets/Custom_Tables.php
src/Tickets/Flexible_Tickets/Custom_Tables/Ticket_Groups.php
src/Tickets/Flexible_Tickets/Provider.php
src/Tribe/Tickets.php
src/Tribe/Tickets_Handler.php

Prep for [ETP-986]
Small cleanup and tweaks moving toward adding some hooks to templates and such. Cherry picks some existing fixes that will be needed to proceed.
Includes:
https://github.com/the-events-calendar/event-tickets/pull/3596
https://github.com/the-events-calendar/event-tickets/pull/3594
[ETP-986]: https://stellarwp.atlassian.net/browse/ETP-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ticket presets admin alterations prep.

---

src/Tickets/Seating/Orders/Seats_Report.php

[TICKET_ID]
[skip-changelog]
* Make sure the `seats` link to seats report is available for both TicketsCommerce and WooCommerce events.
📷 screenshot: https://share.cleanshot.com/bBVJDhzm

Fix - QA updates.

---

src/Tickets/Commerce/Flag_Actions/Decrease_Stock.php
src/Tickets/Commerce/Flag_Actions/Increase_Stock.php

Resolve problems with Global/Capped positions

---

src/views/v2/commerce/order/details.php
src/views/v2/commerce/order/details/coupons.php
src/views/v2/commerce/order/details/fees.php

QA issue spreadsheet – Item `#005`
This PR adds Coupon and Booking Fee data to the Order success page.
**Before:**
**After:**

Add Coupons and Booking Fees to order success page

---

phpcs.xml
src/Tickets/Commerce/Order_Modifiers/Models/Coupon.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Coupon.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Fee.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Modifier_Abstract.php
src/admin-views/order_modifiers/coupon-edit.php
src/admin-views/order_modifiers/fee-edit.php
src/admin-views/order_modifiers/modifier-status-dropdown.php
src/admin-views/order_modifiers/modifier-table.php
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_with_no_data__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_edit_screen_render_correctly__Fee - Emojis in Name and Slug__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_edit_screen_render_correctly__Fee - Excessively Large Amount__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_edit_screen_render_correctly__Fee - Long Decimal Value__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_edit_screen_render_correctly__Fee - Special Characters__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_edit_screen_render_correctly__Flat Fee__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_edit_screen_render_correctly__Percent Fee__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_edit_screen_render_with_no_data__0.snapshot.html

QA issue – `#014`.
This updates the behavior of the "Amount" input field. After this change, it is no longer necessary to clear the default value from the field when the field is empty.
**Before:**
https://github.com/user-attachments/assets/c912a63e-1b08-4974-96ff-ff453e7ce401
**After:**
https://github.com/user-attachments/assets/2d928378-8ebb-4c3e-9306-5f38be26a147

Update amount input field behavior

---

changelog/et-2189-add-coupons

*Self-explanatory: Just adding the changelog entry.*

Add coupons changelog entry

---

src/Tickets/Seating/app/frontend/session/index.js

Fix - Unwanted interruption on TC Checkout page,

---

src/Tickets/Commerce/Order_Modifiers/API/Coupons.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Gateway/Stripe/Coupons.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Gateway/Stripe/Fees.php

QA Issue `#35`
This PR updates the Stripe checkout process to ensure any discounts are correctly applied.
The reason this wasn't working correctly was because #3665 added a new method `is_using_stripe()` to the Coupons API class. This method relied on checking against `Gateway_Manager::get_current_gateway()` to see if Stripe's gateway key was returned. However, `get_current_gateway()` seems to **always** return PayPal as the current gateway.
Upon searching through the codebase, I realized that the result of `get_current_gateway()` isn't relied upon anywhere to actually validate which gateway is in used. Thus, I changed the `is_using_stripe()` method to look and see whether stripe is enabled and active.
The reason this specific change was so impactful is that it prevented the Stripe …

Fix coupons applied to Stripe gateway

---

src/resources/js/admin/order-modifiers/amount-field.js

QA Issue `40`
Follow-up to #3683. The JS logic there was bad, and caused flat amounts to always fail validation.

Fix logic in copon amount validation

---

src/admin-views/editor/metabox.php
src/admin-views/editor/panel/ticket.php
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event by Occurrence provisional ID__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__event__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__post__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket and sale price__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event without ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket and sale price__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__event__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__post__0.snapshot.html

[ETP-985]
[ETP-985]: https://stellarwp.atlassian.net/browse/ETP-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding needed hooks in ticket form for preset work

---

composer.json

...so that "Tweak" (which gets used heavily) is after "Fix"

Alter changelog order 

---

changelog/fix-tc-checkout-and-cart-shouldnt-idenitfy-when-tc-off
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/AttendeesTest.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/EditorTest.php
tests/ft_integration/Tribe/Tickets/MetaboxTest.php

[TEC-5440]
This updates minimum supported version of TEC to be: 6.11.0!
Why?
The reason is that 6.11.0 is the version that includes TCMN >= 6.5.3 which is the version that supports the updated of stellarwp/schema to its latest version. Resulting to the change of static truncate to dynamic truncate.
read more relevant info here https://github.com/the-events-calendar/the-events-calendar/pull/5040
[TEC-5440]: https://stellarwp.atlassian.net/browse/TEC-5440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updates TEC dependencies

---

src/Tickets/Admin/Onboarding/API.php
src/Tickets/Admin/Onboarding/Controller.php
src/Tickets/Admin/Onboarding/Data.php
src/Tickets/Admin/Onboarding/Steps/Optin.php
src/Tickets/Admin/Onboarding/Steps/Settings.php
src/Tickets/Admin/Onboarding/Tickets_Landing_Page.php
src/Tickets/Admin/Provider.php
src/Tribe/Commerce/Currency.php

Working, if not complete, landing page.
[ET-2360]
Sets up the landing page in preparation for designs.
Requires https://github.com/the-events-calendar/tribe-common/pull/2474
[ET-2360]: https://stellarwp.atlassian.net/browse/ET-2360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Working Landing page.

---

src/modules/data/blocks/ticket/selectors.js

Fix - Cast to price to string for TicketsCommerce to render block properly from presets.

---

src/Tickets/Commerce/Order_Modifiers/app/rest/index.js
src/resources/js/commerce/gateway/paypal/checkout.js
src/resources/js/commerce/gateway/stripe/checkout.js
src/resources/js/v2/tickets-loader.js

Fixing checkouts.
The zip workflow is fixed here https://github.com/the-events-calendar/tribe-common/pull/2502

Fixing object exposure

---

src/Tickets/Admin/Onboarding/API.php
src/resources/packages/wizard/data/settings/constants.ts

[ET-2363] [ET-2362] [ET-2367]
- The rest endpoint for ET onboarding wizard.
- Dismissing the wizard.
- Consent checkbox
https://github.com/user-attachments/assets/c2ec0602-de57-40ad-ba66-c6a9a33fc86a
https://github.com/user-attachments/assets/741f36a3-d2ba-45da-97a6-5c4ddd0a16ed
[ET-2363]: https://stellarwp.atlassian.net/browse/ET-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-2362]: https://stellarwp.atlassian.net/browse/ET-2362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-2367]:https://stellarwp.atlassian.net/browse/ET-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-2367]: …

ET Onboarding REST API

---

src/modules/data/blocks/ticket/index.js

* We are here exposing the ticket data store attributes as global window object to be used in ETP.

Feat - Export data blocks for tickets modules to be used in ETP.

---

src/resources/packages/wizard/components/tabs/settings/tab.tsx

[ET-2339]
Fixing issues found during QA of our ET Onboarding Wizard. This PR fixes:
- On Step-1 the `Connect to Stripe` button needs to save settings (especially currectStep) so that we land properly after our journey to Stripe and back
- The conditional to show the Currencies dropdown was adjusted as in designs.
[ET-2339]: https://stellarwp.atlassian.net/browse/ET-2339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QA - ET Onboarding Wizard

---

changelog/release-T25.doctorstrange

[TCMN-186]
Updates the Telemetry library in common.
[TCMN-186]: https://stellarwp.atlassian.net/browse/TCMN-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Common Telemetry library to more secure version.

---

src/Tickets/Commerce/Abstract_Order.php
src/Tickets/Commerce/Gateways/Square/Order.php
src/Tickets/Commerce/Gateways/Square/Payment.php
src/Tickets/Commerce/Gateways/Square/Payment_Handler.php
src/Tickets/Commerce/Gateways/Square/REST/Order_Endpoint.php
src/Tickets/Commerce/Gateways/Square/Requests.php
src/Tickets/Commerce/Gateways/Square/Syncs/Remote_Objects.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Ticket.php
src/Tickets/Ticket_Data.php

[ET-2412]
For every TC order created through Square - a Square order is also created.
https://www.loom.com/share/9d4dce0b069640a8b0aa6c98b53fac2e
[ET-2412]: https://stellarwp.atlassian.net/browse/ET-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

handle square order creation

---

src/Tickets/Commerce/Gateways/Contracts/Abstract_WhoDat.php
src/Tickets/Commerce/Gateways/Square/Assets.php
src/Tickets/Commerce/Gateways/Square/Notices/Webhook_Notice.php
src/Tickets/Commerce/Gateways/Square/Order.php
src/Tickets/Commerce/Gateways/Square/REST/On_Boarding_Endpoint.php
src/Tickets/Commerce/Gateways/Square/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Gateways/Square/Webhooks.php
src/Tickets/Commerce/Gateways/Square/WhoDat.php
src/admin-views/settings/tickets-commerce/square/connect/webhook-status.php

[[ET-2399](https://stellarwp.atlassian.net/browse/ET-2399)]
[ET-2399]: https://stellarwp.atlassian.net/browse/ET-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve the webhooks to function with the Requirements from Square.

---

src/Tickets/Commerce/Admin_Tables/Orders_Table.php
src/Tickets/Commerce/Gateways/Contracts/Abstract_WhoDat.php
src/Tickets/Commerce/Gateways/Square/Ajax.php
src/Tickets/Commerce/Gateways/Square/Merchant.php
src/Tickets/Commerce/Gateways/Square/Order.php
src/Tickets/Commerce/Gateways/Square/REST/Events.php
src/Tickets/Commerce/Gateways/Square/REST/Order_Endpoint.php
src/Tickets/Commerce/Gateways/Square/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Gateways/Square/Requests.php
src/Tickets/Commerce/Gateways/Square/Status.php
src/Tickets/Commerce/Gateways/Square/Syncs/Controller.php
src/Tickets/Commerce/Gateways/Square/Syncs/Inventory_Sync.php
src/Tickets/Commerce/Gateways/Square/Syncs/Listeners.php
src/Tickets/Commerce/Gateways/Square/Syncs/Objects/Inventory_Change.php
src/Tickets/Commerce/Gateways/Square/Syncs/Objects/NotSyncableItemException.php
src/Tickets/Commerce/Gateways/Square/Syncs/Regulator.php
src/Tickets/Commerce/Gateways/Square/Syncs/Remote_Objects.php
src/Tickets/Commerce/Gateways/Square/WhoDat.php
src/Tickets/Commerce/Meta.php
src/Tickets/Commerce/Order.php

[TICKET_ID]
Added webhook handler for customer deleted.
Added webhook handler for inventory count changed
Fixed webhook handler for order created/updated
Removed webhook handler for payment created/updated.

Add more webhooks handlers

---

src/Tickets/Commerce/Gateways/Square/Order.php
src/Tickets/Commerce/Gateways/Square/REST/Events.php
src/Tickets/Commerce/Models/Order_Model.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Repositories/Order_Repository.php

minor naming updates

---

src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss

QA spreadsheet 10
Fixes an issue where padding was inconsistent on different viewports.
https://github.com/user-attachments/assets/c1fc6555-1a64-44be-98b5-89ee13a2aecd

Settings - Fix padding around Payment Gateways

---

src/Tickets/Commerce/Gateways/Square/Merchant.php
src/Tickets/Commerce/Gateways/Square/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Gateways/Square/Webhooks.php

Look at the WhoDat PR for more context.

Include a second layer of security around received WhoDat Webhooks

---

src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
tests/wpunit/TEC/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint_Redirect_Test.php
tests/wpunit/TEC/Tickets/Commerce/Gateways/Stripe/REST/__snapshots__/Return_Endpoint_Redirect_Test__it_should_redirect_to_disconnect_url_on_connection_terminated__0.snapshot.txt
tests/wpunit/TEC/Tickets/Commerce/Gateways/Stripe/REST/__snapshots__/Return_Endpoint_Redirect_Test__it_should_redirect_to_error_url_on_connection_error__0.snapshot.txt
tests/wpunit/TEC/Tickets/Commerce/Gateways/Stripe/REST/__snapshots__/Return_Endpoint_Redirect_Test__it_should_redirect_to_success_url_on_connection_established__0.snapshot.txt

QA Spreadsheet 6
Corrects an issue where after signing up to Stripe, the redirect was going to the old page.

Settings - Fixed issue with Stipe redirecting to the old settings page.

---

src/Tickets/Commerce/Gateways/Square/WhoDat.php

Fix return type of register_webhook_endpoint

Fix return type of register_webhook_endpoint

---

src/Tickets/Commerce/Gateways/Square/Syncs/Tec_Event_Details_Provider.php

Dont sync data not yet confirmed by Square

Dont sync event related data with square

---

src/Tickets/Admin/Onboarding/Tickets_Landing_Page.php

[ET-2339]
This PR resolves issues [reported during QA](https://docs.google.com/spreadsheets/d/1NzXAjMpzE7Cum9rOix2ctIjEsdpR_YgFLLMKvnGtzkk/edit?gid=619168414#gid=619168414) of our Onboarding Wizard. Issues resolved:
- 48 fix settings link
[ET-2339]: https://stellarwp.atlassian.net/browse/ET-2339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Onboarding QA fixes

---

.github/workflows/tests-php-ct1.yml
.github/workflows/tests-php-ft.yml
.github/workflows/tests-php.yml
src/Tribe/Main.php

Update Help Hub branch to newer verions of WP for slic.

Help Hub Fix Slic WP Version.

---

.github/workflows/tests-php-ct1.yml
.github/workflows/tests-php-ft.yml
.github/workflows/tests-php.yml

Merge hotfix into `bucket/commerce-maintenance`

Manually merging the commerce-maintenance forward

---

src/resources/postcss/tickets-admin/settings/_banners.pcss

Elektra - Fix TBD

---

src/Tickets/Commerce/Gateways/Contracts/Merchant_Interface.php
src/Tickets/Commerce/Gateways/PayPal/Assets.php
src/Tickets/Commerce/Gateways/PayPal/Hooks.php
src/Tickets/Commerce/Gateways/PayPal/Merchant.php
src/Tickets/Commerce/Gateways/PayPal/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Gateways/PayPal/WhoDat.php
src/resources/js/commerce/gateway/paypal/signup.js

Fixing some PP issues

---

src/Tickets/Commerce/Gateways/Square/REST/Events.php
src/Tickets/Commerce/Gateways/Square/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Gateways/Square/Syncs/Regulator.php

Listen for payment created/updated events as well!

Listen for payment related events

---

src/Tickets/Admin/Help_Hub/ET_Hub_Resource_Data.php
src/Tickets/Configuration/Provider.php
src/Tribe/Main.php
tests/integration/TEC/Tickets/Admin/Help_Hub/Template_Test.php
tests/integration/TEC/Tickets/Admin/Help_Hub/__snapshots__/Template_Test__overall_template__0.snapshot.html
tests/integration/TEC/Tickets/Admin/Help_Hub/__snapshots__/Template_Test__section_rendering__0.snapshot.html

DQA Issues 9,10,11,12
- Fixes:
- When ET was only enabled, the manage consent URL was going to TEC
- When ET was only enabled, the configuration manage was missing
- [] Code is covered by **NEW** `wpunit` or `integration` tests.

Help Hub - DQA issue

---

src/resources/postcss/tickets-admin-tickets.pcss

📷 screenshot(s): 
Before: https://share.cleanshot.com/Q8WXWXb1
After: https://share.cleanshot.com/HjQR5pNm

Fix - restore default padding for tickets page.

---

src/Tickets/Commerce/Gateways/Square/Hooks.php
src/Tickets/Commerce/Gateways/Square/Order.php
src/Tickets/Commerce/Gateways/Square/REST/Webhook_Endpoint.php
src/Tickets/Commerce/Models/Webhook.php
src/Tickets/Commerce/Provider.php
src/Tickets/Commerce/Tables.php
src/Tickets/Commerce/Tables/Webhooks.php
src/Tickets/Exceptions/DuplicateEntryException.php

Wrapping the select and insert queries in a single transaction, minimizing (actually zeroing) the possibility of attempting to insert a duplicate key.

Wrap queries in transaction

---

src/Tickets/Commerce/Tables/Webhooks.php

Issue [35](https://docs.google.com/spreadsheets/d/1NzXAjMpzE7Cum9rOix2ctIjEsdpR_YgFLLMKvnGtzkk/edit?gid=156968658#gid=156968658)

fix fatal during new table creation

---

changelog/fix-build
package-lock.json
package.json
webpack.config.js

Ticket: [TCMN-188]
Requires: https://github.com/the-events-calendar/tribe-common/pull/2619
Before:
After:
[TCMN-188]: https://stellarwp.atlassian.net/browse/TCMN-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update to properly use svg-inline in our build process

---

src/Tickets/Blocks/Controller.php
src/Tribe/Editor.php
src/Tribe/Editor/Template/Overwrite.php
src/Tribe/Events/Attendees_List.php
src/Tribe/Tickets.php
src/Tribe/Tickets_Handler.php
tests/integration/TEC/Tickets/Blocks/ControllerTest.php

[TICKET_ID]
This updates any files that are using the incorrect namespace for the backwards-compatible `Editor` instance, and updates to the newer version of `common`.

(Classy) ET adjustments to work with Classy

---

src/resources/js/commerce/gateway/square/checkout.js
src/views/v2/commerce/gateway/square/container.php

Fix square card container size.

Fixed size of square card container

---

changelog.md
changelog/fix-et-2542-sca-square-payments
changelog/task-i18n-43a3993
event-tickets.php
lang/event-tickets.pot
readme.txt
src/Tickets/Commerce/Gateways/Square/Assets.php
src/Tickets/Commerce/Gateways/Square/Hooks.php
src/Tickets/Commerce/Gateways/Square/Syncs/Objects/Ticket_Item.php
src/Tribe/Main.php
src/resources/js/commerce/gateway/square/checkout.js
src/resources/postcss/tickets-commerce/_checkout.pcss
src/views/v2/commerce/checkout/purchaser-info.php
src/views/v2/commerce/gateway/square/container.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/ItemDetailsTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_not_on_sale_should_match_html__1.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php
tests/integration/Settings/Payments_Tab_Test.php
tests/order_modifiers_integration/Checkout/__snapshots__/Coupons_Test__it_should_calculate_coupons_simple_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_complex_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_simple_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $10, Fee $5, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $15, Fee $2, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $20, Fee $3, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $50, Fee $10, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_not_calculate_fees_for_free_tickets__0.snapshot.html
tests/square_integration/__snapshots__/Assets_Test__it_should_get_square_checkout_data__0.snapshot.json

Release Greanarrow 1 -  Sanity check

---

src/Tickets/REST/TEC/V1/Documentation/Ticket_Definition.php
src/Tickets/REST/TEC/V1/Documentation/Ticket_Request_Body_Definition.php

- Update Ticket_Definition.php to include proper event association fields
- Enhance Ticket_Request_Body_Definition.php with better parameter handling
- Improve ticket creation workflow for MCP server integration

Fix ticket association and improve REST API documentation

---

src/Tickets/REST/TEC/V1/Endpoints/Ticket.php
src/Tickets/REST/TEC/V1/Endpoints/Tickets.php
src/Tickets/REST/TEC/V1/Traits/With_Filtered_Ticket_Params.php
src/Tickets/REST/TEC/V1/Traits/With_Parent_Post_Read_Check.php
src/Tickets/REST/TEC/V1/Traits/With_TC_Provider.php
src/Tickets/REST/TEC/V1/Traits/With_Ticket_Upsert.php
tests/rest_tec_v1_integration/Endpoints/Ticket_Test.php
tests/rest_tec_v1_integration/Endpoints/Tickets_Test.php
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Ticket_Test__test_read_responses__0__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Ticket_Test__test_read_responses__1__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Ticket_Test__test_read_responses__2__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Ticket_Test__test_read_responses__3__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Ticket_Test__test_read_responses__4__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Tickets_Test__test_read_responses__0__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Tickets_Test__test_read_responses__1__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Tickets_Test__test_read_responses__2__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Tickets_Test__test_read_responses__3__0.snapshot.json
tests/rest_tec_v1_integration/Endpoints/__snapshots__/Tickets_Test__test_read_responses__4__0.snapshot.json

This pull request:
- Introduces a new `With_TC_Provider` trait.
- Updates `Ticket` and `Tickets` endpoints to utilize this trait.
- Modifies `With_Ticket_Upsert` to retrieve the ticket provider using the new trait.
The purpose is to centralize ticket provider access and improve code extensibility for other modules and plugins in the future.

Uses TC provider trait for ticket retrieval

---

changelog/fix-ETP-1021-pass-2
src/Tribe/Events/Views/V2/Hooks.php
src/Tribe/Events/Views/V2/Models/Tickets.php
tests/integration/Tribe/Tickets/Events/Views/V2/Models/Tickets_Test.php

Ticket: [ETP-1021](https://stellarwp.atlassian.net/browse/ETP-1021)
This PR builds on the discover of #3944 and [Common PR](https://github.com/the-events-calendar/tribe-common/pull/2681) to leverage the KV-Cache for the Ticket model.
WIP
[ETP-1021]: https://stellarwp.atlassian.net/browse/ETP-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ETP-1021 - pass 2

---

changelog.md
changelog/fix-update-shepherd-0.0.5
event-tickets.php
readme.txt
src/Tribe/Main.php

Sanity PR for t25.hawkeye.1

---

changelog/feat-add-square-fee-notice
src/Tickets/Commerce/Gateways/Square/Settings.php
tests/wpunit/TEC/Tickets/Commerce/Gateways/Square/SettingsTest.php

[ET-2548]
Adds a notice informing users about the 2% fee associated with the free Square payment gateway integration.
https://www.loom.com/share/6a9d2165f0734f94bbcf33ab925a71d5
[ET-2548]: https://stellarwp.atlassian.net/browse/ET-2548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds Square fee notice

---

src/admin-views/admin-tickets/no-tickets.php

[ET-2545]
Missed updating the template version to TBD.
[ET-2545]: https://stellarwp.atlassian.net/browse/ET-2545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-2545 TBD on template

---

changelog/tut-analyze
event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

[skip-phpcs][skip-changelog][skip-lint]

 Invisiblewoman Version Checks, Analyze
