readme.txt
src/admin-views/list.php

We have an `original_stock()` method. Let's use that instead.
Related: https://github.com/moderntribe/event-tickets-plus/pull/51
See: https://central.tri.be/issues/42355

Rather than computing stock in the tpl, let's use the pre-computed value

---

readme.txt
src/admin-views/attendees.php
src/template-tags/tickets.php

See: https://central.tri.be/issues/42355

Twiddle stock handling on the attendees report so it reads accurately

---

src/Tribe/Main.php
src/Tribe/RSVP.php

Turns out this was causing the following reported issue: https://central.tri.be/issues/43666
Related: https://github.com/moderntribe/event-tickets-plus/pull/82

Prevent RSVP recursion on RSVPing for an event with custom meta

---

src/admin-views/attendees-email.php
src/resources/js/tickets-attendees.js

_Ref:_ [#43155](https://central.tri.be/issues/43155)
This change works for both Community Tickets Attendees List and Admin Attendees List
Change script to only hide the form instead of the entire content too.

Add Loading Image to Attendees Send Email Modal

---

src/Tribe/Tickets.php

Better defaults for global stock data.
[C#18656](https://central.tri.be/issues/18656)

Tickets should use their own 'independent' stock by default

---

src/Tribe/Global_Stock.php
src/admin-views/meta-box.php

Implementing a count of global stock sales - simple helper function plus linking it to the global stock field in the event meta box.
[C#43020](https://central.tri.be/issues/43020)

Global sales count helper | 43020

---

src/Tribe/Attendees_Table.php

See: https://central.tri.be/issues/44194

Fix the broken warning icon for cancelled/refunded orders

---

src/Tribe/RSVP.php
src/Tribe/Tickets.php

_Ref:_ [C#42327](https://central.tri.be/issues/42327)
This is a PR for both ET and ET+
Please see the ticket for the explanation as there are better ways to do this, but that might be for a ticket involved with upgrading the whole checkin system.

Prevent Multiple Checkins when using QR Codes

---

src/Tribe/Global_Stock.php

When getting the total sales of global stock for an event, do not count sales from independent stocks.
[C#44569](https://central.tri.be/issues/44569)

Only count global stock sales | #44569

---

src/Tribe/RSVP.php
src/Tribe/Tickets.php

Rolling back the signature change that we attempted in the last MR in favor of an uglier backward compatible change.
Related: https://github.com/moderntribe/event-tickets-plus/pull/130
See: https://central.tri.be/issues/44831

Maintain the original checkin() method signature

---

src/Tribe/Tickets.php

If a stock of `0` is provided, then ticket quantities above `0` are not allowed. That's inconvenient for tickets with unlimited stock.
See: https://central.tri.be/issues/44939

Only pass a stock quantity to the front end if stock is being managed

---

src/Tribe/RSVP.php

Whenever we are dealing with Redirects we cannot do stuff on `init`
_Use:_ `template_redirect`
Was running into an issue of `get_permalink( $event_id )` returning he wrong url because it was too early on the execution.

Remove redirect from the `init` this will throw 404 on some cases

---

readme.txt
src/Tribe/RSVP.php
src/Tribe/Tickets.php
src/admin-views/tribe-options-tickets.php

Makes it easier to stop sales/RSVPs for logged-out users. Setting can be selectively applied to individual ticket modules (ie, so we can disable RSVPing but still allow sales for logged out users, etc).
[#44347](https://central.tri.be/issues/44347)

Options to hide ticket form from logged out users (per module basis)

---

readme.txt
src/Tribe/RSVP.php
src/Tribe/Tickets.php

When attendee posts are created, let's associate the current user ID (if any) with them. Coverage for providers besides RSVP will be added in a subsequent PR.
[#44347](https://central.tri.be/issues/44347)

Record the user ID associated with the creation of a new attendee

---

src/Tribe/Tickets.php
src/admin-views/tribe-options-tickets.php

Expands on earlier work to add some items detailed in the user stories that initially were missed:
* Add advice about reviewing WP's users_can_register setting to the tickets setting screen
* Ensure we link to the registration URL (in place of the tickets form) when appropriate
[C#44347](https://central.tri.be/issues/44347)

Enhance login requirements for Event Tickets (Plus) | #44347

---

src/views/shortcodes/my-attendance-list-logged-out.php
src/views/shortcodes/my-attendance-list.php

Modifies wording of you-need-to-login message per feedback.
https://central.tri.be/issues/44363

Adjust verbiage per QA feedback | #44363

---

src/Tribe/Tickets.php

Change how we form the login link.
https://central.tri.be/issues/44347#note-14

Login link is not an admin link | #44347

---

src/Tribe/Tickets.php

Don't just send the user to the login page, add a redirect param to bring them back to where they started.
[C#44347](https://central.tri.be/issues/44347)

Add 'redirect_to' - take user back to event page | #44347

---

src/Tribe/Attendance.php
src/Tribe/RSVP.php
src/Tribe/Ticket_Object.php
src/admin-views/attendees.php

Fixes the attendee screen arithmetic. Replaces method of reckoning how many attendees were deleted with actual tracking of that figure.
https://central.tri.be/issues/45538

'Total sold' should equal the sum of 'finalized' and 'pending' | #45538

---

src/views/shortcodes/my-attendance-list.php

The usage of `tribe_get_start_date` created by #159 was throwing some notices when The Events Calendar was not active. This PR will resolve that problem.
_Rel:_ moderntribe/tribe-common#92

Prevent Empty () to show up when TEC is inactive

---

src/Tribe/Main.php

Use actions to signal when the plugin has finished initial loading, or when it has decided to bail out of loading (such as if there are compatibility problems with The Events Calendar). These actions can then be used by dependants like Event Tickets Plus.
https://central.tri.be/issues/61156

Use actions to signal when ET has loaded/failed to load | #61156

---

src/Tribe/Attendees_Table.php
src/resources/js/tickets-attendees.js

This keeps the Thickbox working on the Community Tickets front end as well as in the Dashboard.
See related pull request: https://github.com/moderntribe/tribe-common/pull/101
See ticket: https://central.tri.be/issues/61823

allow parent page to be passed and fix JS error

---

readme.txt
src/admin-views/meta-box.php

The proximity of this line to the punctuated paragraph below makes it appear odd without a period. This is especially true in the context of Community Events.
See: https://central.tri.be/issues/44797

adding a period

---

readme.txt
src/Tribe/RSVP.php
src/views/tickets/email-non-attendance.php

Instead of sending an email full of tickets to someone who indicated they will not be attending an event, send an acknowledgement (that they RSVP'd) instead. If they later amend the status of one or more attendees to _"Going",_ send the appropriate number of tickets at that point.
https://central.tri.be/issues/62549

Send out "you are not attending" emails | 62549

---

src/Tribe/Main.php

The `GLOB_BRACE` flag for `glob()` is not available on all systems. Most notably it's not supported on Solaris and Alpine (a quite popular lightweight linux distribution used mostly for running docker containers). On this PR I propose a way of achieving the same result which doesn't use such flag and hence improves compatibility.
Related: https://github.com/moderntribe/the-events-calendar/pull/750
See: https://central.tri.be/issues/63172

Stop using the GLOB_BRACE flag

---

src/Tribe/Admin/Move_Ticket_Types.php
src/Tribe/Admin/Move_Tickets.php
src/Tribe/Main.php

Separates out the process of adding actions/filters from object construction, so we can still inherit methods but don't double up on callbacks unnecessarily.
[C#61724](https://central.tri.be/issues/61724)

Bugfixes for moving tickets/ticket types

---

src/Tribe/Main.php
src/Tribe/Metabox.php
src/resources/js/ticket-delete-alert.js
src/resources/js/ticket-delete-alert.min.js
src/resources/js/tickets.js

Additionally, I've moved the contents of the ticket alert JS file into the larger tickets.js file to:
1. Avoid extra JS files
2. Avoid having the file (and event) executed on every admin page - we only need it for the meta box
See: https://central.tri.be/issues/46623

Fix targeting of ticket deletion confirmation

---

src/Tribe/Tickets_Handler.php

Following some reworking of the attendee screen, we still need to maintain the expected set of export columns.
[#61993](https://central.tri.be/issues/61993)

Maintain expected set of attendee export columns

---

src/Tribe/RSVP.php

I added it for 3rd party plugins can hook to this action.
I customized error_handler to achieve what i need, but should consider to create a global error handler on Main class, so internally or 3rd party plugins can throw that specific error. 
So IMO it should be like this
do_action( 'tribe_tickets_rsvp_before_tickets_generated', $event_id, $_POST);
/*check tribe_tickets_global_error after this line and redirect to page if there is any error*/

Action for 3rd Party plugins

---

readme.txt
src/Tribe/RSVP.php

In the case of recurring events (child posts) we deliberately load the parent event's tickets - however this same logic should not apply to other post types such as pages.
[#45008](https://central.tri.be/issues/45008)

Don't allow recurring events safeguard to impact non-events | #45008

---

src/admin-views/ticket-type-history.php

Per QA, remove square bullets from ticket history.
[#61724](https://central.tri.be/issues/61724)

Remove .ul-square class from ticket history list | #61724

---

src/Tribe/Admin/Move_Tickets.php

The move tickets/ticket type dialog is generated quite early on in the request and the `$current_screen` global is not yet set. This creates some problems which we can resolve by setting it ourselves.

Set current screen to avoid notices/warnings | spotfix

---

readme.txt
src/Tribe/Tickets.php
src/views/tickets/rsvp.php

Introduce a system for displaying "tickets unavailable" messages that can be shared by multiple active ticket providers. We should only ever see one "tickets are unavailable" message per event.
[#65687](https://central.tri.be/issues/65687)

Revise "tickets unavailable" messaging, prevent duplicates when multiple ticket providers are active

---

src/Tribe/Main.php

Builds on tribe-common pr 210: moves the task of loading tribe-common's deprecated classes from the dependent plugin to tribe-common itself.
https://github.com/moderntribe/tribe-common/pull/210
https://central.tri.be/issues/66872

Event Tickets should let tribe-common handle its own deprecated classes

---

src/Tribe/RSVP/Attendance_Totals.php

Removes unused var. 
Discussion [here](https://github.com/moderntribe/event-tickets/pull/259#discussion_r80913711) and [here](https://tribe.slack.com/archives/products-dev/p1475069038003538) (basically - safe to remove).

Remove unused var | spotfix

---

src/Tribe/RSVP.php

Previous behaviour: `total_sales` was being reduced by one every time an attendee was deleted (this was done to re-stock RSVP tickets). New behaviour: it is only reduced if configured to do so - by default this means if the deleted attendee was 'Going' we re-stock, but not otherwise.
https://central.tri.be/issues/61992
https://central.tri.be/issues/64669

Optionally adjust total_sales following deletion of an RSVP ticket/attendee

---

src/Tribe/Metabox.php

`tribe-bumpdown` is registered (by tribe-common) but won't always be automatically enqueued, ie if Event Tickets is running standalone and support for pages/posts is enabled.
https://central.tri.be/issues/67895

Ensure tribe-bumpdown is enqueued when the tickets meta box is required

---

src/Tribe/Tickets.php
src/admin-views/tribe-options-tickets.php

Ticket: https://central.tri.be/issues/46168
This PR:
* adds two location settings in the Events > Settings > Tickets tab to set the distinct location of tickets forms for RSVP and commerce provided tickets.
* uses that settting to hook the front-end forms accordingly

Added ticket form location settings

---

package-whitelist.json

This PR whitelists the composer and di52 dependencies we need in production.
Please check my globbing is correct:
* `vendor/composer` only contains files
* `vendor/lucatume/di52/src` contains folders

whitelist composer dependencies

---

src/Tribe/Admin/Columns/Tickets.php
src/Tribe/Main.php
src/Tribe/Tickets_Handler.php

Ticket: https://central.tri.be/issues/67176
This PR:
* fixes a check that was preventing the display
* links the content to the Attendees report (in a new tab)
* registers the `Tribe__Tickets__Tickets_Handler` as a singleton
* finally replaces that class `instance` method to use the container (as a service locator)
* replaces all calls to `Tribe__Tickets__Tickets_Handler::instance()` in this plugin code to use the container

Link report column content to Attendees report

---

src/Tribe/Admin/Screen_Options.php
src/Tribe/Admin/Screen_Options/Attendees.php
src/Tribe/Attendees_Table.php
src/Tribe/Main.php
tests/integration/Tribe/Tickets/Admin/Screen_Options/AttendeesTest.php

Ticket: https://central.tri.be/issues/66016
This PR registers the Attendees table columns in the screen options to allow those to be hidden on a per-user base.

Attendees report Screen Options

---

readme.txt
src/resources/js/tickets.js

_Ref:_ [C#68557](https://central.tri.be/issues/68557)
_Rel:_ #285

Ensure response data is always passed when edit-ticket.tribe is triggered 

---

src/Tribe/Tickets.php
src/admin-views/meta-box.php

Adding `tribe_tickets_get_modules` filter that allows a customization like removng a specific ticketing module for Community. Example: https://gist.github.com/969a61a8217cb705b7864ae2b5b3fec6
Also, fixed the existing `tribe_events_tickets_module_name` filter so it works with community events as originally intended. https://central.tri.be/issues/45042
And... a couple code sniffer fixes

adding a filter and fixing a filter

---

src/Tribe/Admin/Views/Ticketed.php
src/Tribe/Cache/Abstract_Cache.php
src/Tribe/Cache/Cache_Interface.php
src/Tribe/Cache/Transient_Cache.php
src/Tribe/Main.php

Ticket: https://central.tri.be/issues/67175
This PR:
* fixes the count of ticketed/unticketed to not lag, when on the admin screen, due to cache
* hence adds some control on the cache
* fixes an initial state issue where the events post type was misspelled

Fix lagging ticket count and initial state

---

src/Tribe/Admin/Views/Ticketed.php

If a user is browsing the admin events list and is currently viewing page 10, then the `ticketed` and `unticketed` view links will try to take them to page 10 of those views.
We don't actually want to do this, though, because it's inconsistent with regular views like `published`, `draft` etc and also because there may not be 10 pages of ticketed or unticketed events.
https://central.tri.be/issues/70694

'Subsubsub' admin view links should always take users to 'page 1'

---

src/Tribe/Admin/Columns/Tickets.php

Avoid division-by-zero errors where `$stock` is `0`.
https://central.tri.be/issues/67176

Avoid division-by-zero errors when calculating sales percentage | #67176

---

src/Tribe/Tickets_Handler.php

The meta details column (which contains the _view details_ link but not the submitted details themselves) is superfluous during CSV/email export of attendee data.
https://central.tri.be/issues/71251

Remove meta details column during attendee export

---

readme.txt

Pretty sure the adjusted entries should be under 4.4, but would appreciate confirmation.
Entries moved from under 4.3.1:
* Original PR that added them: https://github.com/moderntribe/event-tickets/pull/292
* Relevant Central ticket: https://central.tri.be/issues/66003
Entry moved out from under 4.3:
* Original PR that added it https://github.com/moderntribe/event-tickets/pull/286
* Relevant Central ticket: https://central.tri.be/issues/66004

Adjust changelog - some entries appear to have been 'misfiled' | #66768

---

src/template-tags/tickets.php

Originally reported in https://theeventscalendar.com/support/forums/topic/tribe_events_ticket_is_on_sale-returning-wrong-result/.
This assigns `$now` to WordPress' `current_time()` which returns the local time (`time()` returns UTC) and fixes the broken comparison that was taking place in `tribe_events_ticket_is_on_sale`.
This is my first PR for this project (or any other PHP codebase) so please let me know if I've missed anything here. I've tested it thoroughly against our staging instance of WordPress/Event Tickets.
🎫 [#71959](https://central.tri.be/issues/71959)

Compare ticket {start,end}_date against current_time() in tribe_events_ticket_is_on_sale

---

readme.txt

Link to The Events Calendar from the full description, since this isn't allowed in the short description.

No markup allowed in readme description | spotfix

---

readme.txt
src/Tribe/Tickets.php

Switch to using `tribe_tickets_get_template_part()` for cleaner code and greater flexibility (themers/3rd party devs can then take advantage of sundry hooks and other goodies).
:ticket: [#69660](https://central.tri.be/issues/69660)

Switch to tribe_tickets_get_template_part() for increased flexibility

---

readme.txt
src/views/tickets/email-non-attendance.php

The use of `$break` in the `tickets/email-non-attendance.php` template appears to be a result of it being based upon `tickets/email.php` - however in the case of the former template it is not required and serves no purpose.
:ticket: [#77421](https://central.tri.be/issues/77421)

Remove unneeded and undefined var

---

src/Tribe/Admin/Move_Tickets.php

Strips duplicate 'moved to' text (the `%3$s` placeholder/`$moved_to`) already contains either 'moved to' or 'assigned to' as appropriate.
:ticket: [#68432](https://central.tri.be/issues/68432)

Fix the way "moved to/assigned to" strings are composed | #68432

---

src/views/tickets/email.php

Due to a space in a CSS code the page break didn't render into the final html markup in some email clients like Thunderbird for Windows. Surprisingly without the space it does. :)

Removed a space

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php
src/Tribe/RSVP.php

Avoid PHP 7 and Strict STD problems with Class Extending

Remove WP_Query from the Param on get_attendees for RSVP

---

src/Tribe/RSVP.php

`get_post_meta( $ticket_id, '_stock', true )` can and will return an empty string at times - cast to an int to avoid warnings before performing arithmetic with it.

Avoid doing arithmetic with types that are not numeric | spotfix

---

src/template-tags/tickets.php

Similar to bug #82684, stock for tickets using global stock was being counted with each iteration, causing a multiple of the global stock to be returned for the count. Added in condition so that the ticket is "ignored" during the loop if it's using global stock, then the global stock is added to the total count at the end.

Update tickets.php for Bug #81967

---

src/Tribe/Tickets.php

Stock for tickets with global stock enabled were being counted each time through the loop, resulting in a multiplied final stock count being displayed next to the "buy now" button in list view. Added in a condition to skip tickets with global stock during the loop, then added in the global stock count at the end.

Update Tickets.php for Bug #82684

---

src/Tribe/Tickets.php

* In the case of RSVPs `$stock_level` may not be defined/no need for it anyway
* No further changelog entry, one was already added via #82684
:ticket: [#83703](https://central.tri.be/issues/83703)

Use correct var to obtain ticket stock | #83703

---

readme.txt
src/template-tags/tickets.php

Modifies two functions (below) so that they don't try to do arithmetic with strings, which can happen when dealing with unlimited stock and triggers notice-level errors under modern runtimes. Behaviour of both functions should be unchanged.
* tribe_events_partially_soldout()
* tribe_events_count_available_tickets()
:ticket: [#78685](https://central.tri.be/issues/78685)

Tidy unlimited stock arithmetic

---

readme.txt
src/Tribe/Admin/Move_Ticket_Types.php
src/Tribe/Admin/Move_Tickets.php
src/Tribe/Tickets.php

Ticket: https://central.tri.be/issues/80200
Turns out we have an attendee cache, that's news to me. It was not clearing when we moved a ticket, now it will.

Add clear_attendees_cache(), and used it when moving tickets

---

readme.txt
src/Tribe/Tickets.php

This changes the way we deprecate the `tribe_events_tickets_modules` hook, to avoid generating deprecation notices even when no custom or 3rd party code utilizes the filter in question.
Instead, I've added a `@deprecated` tag and extra changelog entry to highlight the change.

Remove deprecation notice | spotfix

---

src/Tribe/Commerce/PayPal/Gateway.php
src/Tribe/Commerce/PayPal/Handler/IPN.php
src/Tribe/Commerce/PayPal/Handler/PDT.php

This does not, however, cause the sandbox to _observe_ the [invoice number](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/) despite it being passed/regenerated after successful completion. The issue in the PayPal sandbox that is causing subsequent attempts at checking out to fail appears to be a bug. A quick clearing of Domain Cookies on the PayPal side resolves the issue.
See: https://central.tri.be/issues/81566

Generate a cookie-based invoice number (and purge it after complete)

---

src/admin-views/meta-box.php

Ticket: https://central.tri.be/issues/81217
in the `bucket/ticket-editor-refresh` the `Tribe__Tickets__Tickets::get_default_module` method is added and in this code is used.

Use default module information to check correct option

---

src/admin-views/rsvp-metabox-capacity.php

🎫 https://central.tri.be/issues/80651
Field ID got changed and label did not.

Fix incorrect "for" on label

---

src/Tribe/Ticket_Object.php

Ticket: https://central.tri.be/issues/94124
When [reading the stock to show it on the front-end](https://github.com/moderntribe/event-tickets/blob/bcb2c923440f0a91cdca25f855428c378b987dc4/src/Tribe/Tickets.php#L997) the [implicit `__get` call](https://github.com/moderntribe/event-tickets/blob/7da2fc653b9490edbfffe575bc9480c8052a9b9b/src/Tribe/Ticket_Object.php#L701) would re-fetcht the `stock` property from the database disrupting all the stock interpolation happened so far on the ticket object.

Do not re-read the stock from meta if prop set

---

readme.txt
src/Tribe/Attendees.php
src/admin-views/attendees.php

**Ticket:** [**#93339**](http://central.tri.be/issues/93339)
**Code Review Note:** Other changelog entries exist for this ticket.
Just adding a note about new filter in _this_ PR.
---
**Related PR:** https://github.com/moderntribe/events-community-tickets/pull/102

#93339 Make Edit-Event Link Filterable for Community Tickets

---

src/Tribe/Cache/Abstract_Cache.php

MySQL treats underscores as a single-character wildcard in LIKE comparisons. Starting a search with a wildcard prevents MySQL from using any indexes on the column being compared.
This change enables MySQL to use the index on meta_key for this query and better reflects the intended behavior of the query.
In our case, we have a very large wp_postmeta table so this query was taking a long time to complete since it had to scan every row.
References:
https://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html#operator_like
https://dev.mysql.com/doc/refman/5.7/en/index-btree-hash.html

Escape underscores in LIKE query parameter so the column's index can be used properly

---

src/Tribe/Commerce/PayPal/Main.php
src/Tribe/RSVP.php
src/admin-views/tribe-options-tickets.php

🎫 https://central.tri.be/issues/96857
Moves existing email settings to their own section and adds a new one for RSVP subject.
Note I've removed "paypal" from the filter names because these should get used no matter the commerce plugin used.
Related/required by: https://github.com/moderntribe/event-tickets-plus/pull/490

TC Email settings

---

src/Tribe/Commerce/PayPal/Links.php
src/Tribe/Commerce/PayPal/Notices.php
src/Tribe/Commerce/PayPal/Order.php
src/Tribe/Commerce/PayPal/Oversell/Admin_Notice_Decorator.php
src/Tribe/Commerce/PayPal/Oversell/Policy.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/LinksTest.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/LinksTest__test_order_link_snapshot with data set #0__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/LinksTest__test_order_link_snapshot with data set #1__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/LinksTest__test_order_link_snapshot with data set #2__1.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/LinksTest__test_order_link_snapshot with data set #3__1.php

Ticket: https://central.tri.be/issues/98563#note-8
This PR:
* remakes the oversell notice look and behaviour to make it (kinda) stick to the mock (https://cl.ly/14383c1B2x34)
* fixes a bug that would prevent oversell
Note: the notice contains HTML and CSS code; the former generated by a number of `sprintf` and the latter as there is no good place to style it.
As for the inline CSS:
1. it would be custom to the notice
2.  the notice might/should display *anywhere* in the admin area and I did not want to burde the common-admin file with its style; think React

Rework Oversell notice look and behaviour, fix bug

---

src/Tribe/Commerce/Currency.php

Ticket: https://central.tri.be/issues/99367
By default, the cost will be formatted using the site locale, but I've put in place code to allow for an option to be exposed in the future.

format the price according to locale settings

---

src/Tribe/Tickets_Handler.php

Ticket: https://central.tri.be/issues/99380
Unlimited capacity might be represented, in the db, by an empty string (`''`) or by  a `-1`; the casting that would happen later than this added check (line 969) would cast en empty string to a `0` thus incorrectly marking the ticket as without capacity.
This fixes it.

Check for empty string too to find capacity

---

src/Tribe/Commerce/PayPal/Main.php
src/Tribe/Commerce/PayPal/Orders/Report.php
src/Tribe/Commerce/PayPal/Orders/Sales.php
src/Tribe/Commerce/PayPal/Oversell/Attendee_Handling_Decorator.php
src/Tribe/Commerce/PayPal/Oversell/No_Oversell.php
src/Tribe/Commerce/PayPal/Oversell/Policy.php
src/Tribe/Commerce/PayPal/Oversell/Sell_All.php
src/Tribe/Commerce/PayPal/Oversell/Sell_Available.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_available_tickets__1.php

Ticket: https://central.tri.be/issues/98563
This PR fixes the sales reoport numbers when choosing one oversell option or the other.

Fix the display and calculation of sales for oversold orders

---

src/Tribe/Commerce/Currency.php
src/admin-views/editor/button-view-orders.php

Ticket: https://central.tri.be/issues/70361
Related: https://github.com/moderntribe/event-tickets-plus/pull/497
This PR:
1. makes sure that the currency symbol will be provided by the ticket provider in the Orders report
2. removes (see ET+ PR) the Orders link for EDD tickets

Fix the Orders and currency display

---

src/Tribe/Tickets_Handler.php

Ticket: https://central.tri.be/issues/99616
This PR fixes the issue where an additional PayPal ticket, with empty details and thus unlimited in capacity, would be created when submitting a Community Event.

try to fetch the tickt provider from the new settings first'

---

src/Tribe/Commerce/PayPal/Orders/Table.php

Ticket:  n/a
Make sure Tribe Commerce currency code is used to format line totals in Tribe Commerce reports.

pass the post ID when formatting the line total entry

---

src/Tribe/Tickets_Handler.php

Ticket: https://central.tri.be/issues/99616 
More work to actually remove the deprecated ticket saving code; the tickets are saved via Ajax and we were just runnig the save twice with side effects.

remove deprecated ticket saving code

---

readme.txt
src/Tribe/Attendees.php

**Ticket** https://central.tri.be/issues/94293
There was an error during migration of this class as `attendees_table` was
ot referenced correct, as `page_id` is a string reference when
`attendees_table` is a class reference.
It also makes sure the values used on `array_map` are the expected
values.

Update references to the correct class

---

src/Tribe/Commerce/Currency.php

Ticket: https://central.tri.be/issues/100322
This PR adds a check in the Currency class to make sure that not only the commerce provider bridge (ET+) class exists but that the functions do too.

Check for woo and edd functions existence before trying to use them

---

src/Tribe/Commerce/PayPal/Endpoints.php
src/Tribe/Commerce/PayPal/Errors.php
src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
src/Tribe/Commerce/PayPal/Gateway.php
src/Tribe/Tickets.php
src/admin-views/tribe-options-tickets.php

Ticket: https://central.tri.be/issues/100461
Also: https://central.tri.be/issues/100254
This PR fixes three auto-return issues:
1. the `select` in the ticket settings was being populated with an `array_merge`, the keys (the page IDs) would be lost thus making the ID to title relation totally inaccurate
2. when no success page is selected the user would be returned to the wrong post
3. when finally returned to the correct post no message would indicate to the user that she came back after a purchase
4. fixes an issue where the ticket front-end form would display the wrong number of remaining tickets

Fix auto-return issues

---

composer.json
composer.lock
src/Tribe/Commerce/PayPal/Main.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php

Ticket: https://central.tri.be/issues/100879
This PR modifies the code of the `Tickets` class to make sure extending classes defined  in ET+ (Woo, EDD) that might still be one version behind will not generate fatals or warnings. 
This **does** create duplicate code (the `generate_security_code` method is now defined in all classes) and makes the inheritance tree a little less "stable" but avoids issues during upgrades.

Fix back-compat with out of date ET+ plugin

---

src/Tribe/Commerce/PayPal/Main.php
src/views/tickets/tpp.php

Ticket: https://central.tri.be/issues/101101
Related to: https://github.com/moderntribe/event-tickets-plus/pull/506
This PR puts in place the code to support the attendee list opt-out option on PayPal tickets as it's currently supported on EDD and Woo.
The option, rendered on the ET+ side, is registered in the PayPal custom information for each ticket when adding it to the cart (currently just one) and read back when PayPal sends the order confirmation back.

Support attendee list display optout option

---

src/Tribe/Attendees_Table.php

*Ticket*: https://central.tri.be/issues/101217

Prevent fatal errors if `get_current_screen` is null

---

readme.txt
src/template-tags/tickets.php

**Ticket**: https://central.tri.be/issues/96640
In order to send the params as the type of Request is $_GET and all the
values that are on the permalink as $query params are not consider when
doing the request.

Add query params as input values to the form

---

readme.txt
src/Tribe/Commerce/PayPal/Main.php
src/Tribe/Tickets.php

Ensures Tribe Commerce does not take priority over other ticketing modules, and makes it readily possible to set it as the default via the `tribe_tickets_get_default_module` hook.
:ticket: [♯96538](https://central.tri.be/issues/96538)

Make it easier to set Tribe Commerce as default module

---

src/Tribe/Commerce/Currency.php

There a very edge scenario if an event is created with EDD as the
provider and then the plugin is disabled when calling `edd_get_option`
will trigger an error.
In order to prevent this we need to make sure the function does exists
before use it.

Make sure function exists before call it.

---

readme.txt
src/views/tickets/rsvp.php

Ticket #93027
https://central.tri.be/issues/93027
Fixes a glitch, where adding an RSVP results in "NaN" in the counter when using ET, Enfold and WooCommerce.

Fixes glitch with Event Tickets + Enfold + WooCommerce 

---

readme.txt
src/Tribe/JSON_LD/Order.php
src/Tribe/JSON_LD/Type.php
src/Tribe/Tickets.php

**Ticket**: https://central.tri.be/issues/95034
Does not require a changelog entry as this one was already added.
The following PR introduces / changes the following items for the ticket
described above.
- Adds priceCurrency
- Adds Product as generic type
- Fixes the problem when the ticket is unlimited to be in stack all the
time

Use a generic type for all other types for JSON-LD

---

src/Tribe/Ticket_Object.php

This is an edge case when TEC is disabled and a user visits the event
page with tickets.
As the Events post type will be disabled from the BE if the plugin is
disabled it might be worth to check before using
`Tribe__Events__Timezones`

Make sure `Tribe__Events__Timezones` is present

---

readme.txt
src/Tribe/JSON_LD/Order.php

Use ISO8601-compliant datetime formatting as expected within our JSON LD feed (previously we used `DateTime::ISO8601` formatting which despite its name was not compliant). No customer props, this was an internal find.
:ticket: [♯43349](https://central.tri.be/issues/43349)

Switch to DateTime::ATOM for truly ISO8601 compliant datetimes | #43349

---

src/Tribe/Ticket_Object.php

Ticket: https://central.tri.be/issues/103787
This PR fixes an issue that would prevent post, not events, with assigned tickets from correctly rendering of the site front-end

fallback on the site timezone if the post does not define one

---

src/Tribe/Tickets.php
src/resources/js/frontend-ticket-form.js

Ticket: https://central.tri.be/issues/102497
Make sure next calls that are tickets to the FE overwrite the initial data
localized to have all tickets on the page on the FE.

Overwrite initial localized data if more tickets are present

---

readme.txt
src/Tribe/Tickets.php

https://central.tri.be/issues/100340
Couldn't find a more elegant way to fix this. Basically, the shared capacity was adding to the stock when an event had all tickets with their own stock. Added a helper function and modified the addition for that special case.

Display the correct number of available tickets on list and day view

---

readme.txt

Since we haven't yet merged the 18.08 branch into master, slipping in this correction. I'll take care of updated ET via SVN.

Strip changelog entry that was applicable to ET+ | #41649

---

readme.txt
src/Tribe/Cache/Transient_Cache.php

https://central.tri.be/issues/105802
Make sure wp flushes cache when creating tickets to make it compatible with object cache.

Make sure the ticket creation is compatible with object cache.

---

readme.txt
src/Tribe/Tickets.php

https://central.tri.be/issues/73272
https://central.tri.be/issues/104355
Purge attendees transient when checkin or uncheckin is performed. By having this in the main events, will be compatible with the different e-commerce tickets.

Purge attendees transient on checkin/uncheckin

---

readme.txt
src/Tribe/RSVP.php

🎫 https://central.tri.be/issues/102634
RSVPs were subtracting sold from stock when grabbing from the database - bad RSVP, bad!

Don't manipulate stock when we shouldn't

---

src/Tribe/RSVP.php

_Ref:_ [C#109115](https://central.tri.be/issues/109115)
no readme entry as it modifies to enable the qr code to work with RSVP, which has not been released as a feature yet. 
The existing coding was checking if a user could modify, but the qr process does not have a user.

#109115- Fix RSVP Check In with QR App

---

readme.txt
src/Tribe/Query.php

🎫 https://central.tri.be/issues/71122
Figured out that the "ticketed events" list was sometimes not including the "past" events.

Fix Issues with calculating and displaying ticketed events on the admin list

---

readme.txt
src/admin-views/tribe-options-tickets.php

🎫 https://central.tri.be/issues/73599
As requested on the ticket:
> The settings behavior should be consistent. Since the pages and posts options are not checked by default when you first activate Event Tickets by itself, the events option should also not be checked when The Events Calendar is first activated.

Do not enable tickets on events by default when activating TEC

---

src/admin-views/tribe-options-tickets.php

Spotfix. The 'You have tickets!' string was not translatable.

Spotfix. Making string translatable.

---

src/admin-views/tribe-options-tickets.php

String was not picked up by the POT file, likely due to curly brackets.
https://central.tri.be/issues/109638

Spotfix: string didn't make it to POT

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php
src/Tribe/REST/V1/Headers/Base.php

This fatal occurs when The Events Calendar is not active.

#110248 - fix tribe_is_event fatal if the events calendar is not active

---

readme.txt
src/Tribe/Commerce/PayPal/Stati.php

🎫 https://central.tri.be/issues/102184
I was hesitant at first about how to fix this one, and I ended up deciding to change the wording. The pending post status is reserved and we shouldn't mess with that. It's better to change it now and provide a snippet in case somebody has an issue with their paypal orders where the status was pending.

Stop showing posts with "pending review" status in the blog page.

---

readme.txt
src/admin-views/tribe-options-tickets.php

Fixes the Tribe Commerce settings area so we display the correct shortcode name.
:ticket: [#111011](https://central.tri.be/issues/111011)

Correct shortcode reference (spotfix) | #111011

---

readme.txt
src/Tribe/Main.php

🎫 https://central.tri.be/issues/102815
The origin of the problem is in the validation script in common. Bumping version and adding readme entry to log that we solved this one.
Related: https://github.com/moderntribe/tribe-common/pull/750

Fixed datepicker formats validation error on ticket start sale date

---

src/Tribe/Commerce/PayPal/Gateway.php
src/Tribe/Commerce/PayPal/Main.php

Ticket: https://central.tri.be/issues/109421
It looks like sending an `invoice` argument will block further payments; it's supposed to be a passthru argument for the benefit of the merchant but it appears not.
Since we use it, in reality, to identify the cart I've modified the code to send, and consume, the same information in the `custom` argument instead.

Do not send an invoice number, send it in the custom arguments

---

src/Tribe/RSVP.php

🎫 https://central.tri.be/issues/112585
Changing required protected methods to public, making it Gutenberg compatible.

Gutenberg compatibility for RSVPs

---

event-tickets.php
package.json
readme.txt
src/Tribe/Main.php

Due to the order of operations around loading ET and ET+, we have to hackily detect if ET+ is running and include the Main class file in order to inspect the VERSION constant.
See: https://central.tri.be/issues/115510

Prevent fatal with latest ET alongside ET+ < 4.8

---

readme.txt
src/Tribe/Commerce/Currency.php
src/Tribe/REST/V1/Post_Repository.php

🎫 https://central.tri.be/issues/116352
We need to return the currency symbol of the ticket, not the general.
So, if the currency symbol for WooCommerce is EUROS and we're checking a WooTicket, then we have to return EUROS. The same with the currency position.
This one is needed in order to fix this one: https://central.tri.be/issues/115649

REST API > Make the currency values dependants on the ticket provider

---

src/Tribe/Main.php

🎫 https://central.tri.be/issues/118816
Tried to make this via the regex alternative and had no luck, given the conditions we have. I created a method. If we decide to go this way, perhaps we can include the method in common.
Open to suggestions. Didn't wanted to spend hours fighting against a regex.

Fix version compare for versions containing a hash within the string

---

src/modules/blocks/ticket/container-content/capacity/container.js

Make sure action called to set the shared capacity is the right one

Update reference to the right action

---

readme.txt
src/Tribe/Commerce/PayPal/Main.php

Use `call_user_func()` to call static method of an object obtained via DI52.
Also adjusted the readme, since our PHP-compat fixes are no longer just inside of Common.
:ticket: [♯119073](https://central.tri.be/issues/119073)

Static call syntax 

---

src/modules/data/blocks/rsvp/sagas.js
src/modules/data/blocks/ticket/sagas.js

This will prevent to fail on cases where tickets or RSVP is required to
be injected into other types that are not events.
Ticket: https://central.tri.be/issues/117612

Remove dependency from TEC for tickets

---

src/Tribe/Editor/Compatibility/Tickets.php

Make sure `Tribe__Events__Main' is called if the class is present.
Ticket: https://central.tri.be/issues/119319

Ensure 'Tribe__Events__Main' is called if exists

---

src/Tribe/REST/V1/Endpoints/Base.php
src/modules/blocks/tickets/container.js
src/modules/blocks/tickets/template.js

Prevent to render the `<TicketsDashboard />` if there are no providers
active.
Ticket: https://central.tri.be/issues/119340

Render <TicketsDashboard> only if has providers

---

src/Tribe/Editor/Provider.php

The new action is fired by `common` instead of `TEC`
Ticket: https://central.tri.be/issues/119362

Register blocks on `tribe_editor_register_blocks`

---

src/Tribe/Attendees.php
src/Tribe/Editor/Blocks/Attendees.php

Prevent false positives on the cache created by RSVP when the attendees
list is generated.
Ticket: https://central.tri.be/issues/119398

Prevent the creation of q cache on empty $post_id

---

src/Tribe/Editor/Blocks/Rsvp.php
src/views/blocks/rsvp.php

When debugging a problem with @mitogh we found that tickets and RSVP blocks are sharing a variable, which in the current state of how we do blocks is bad because they share the template context, on release 19.1 I will fix this template context sharing, but for now, we are changing the variable
_Ref:_ [C#119726](http://central.tri.be/issues/119726)
---

RSVP block shouldn't use Tickets as context variable

---

src/Tribe/Status/Abstract.php
src/Tribe/Status/Abstract_Commerce.php

_Ref:_ [C#121937](https://central.tri.be/issues/121937)
Remove int type hinting that is PHP 7.0...

#121937 - remove PHP 7.0 type hinting for integers

---

src/Tribe/Commerce/PayPal/Main.php
src/Tribe/Commerce/PayPal/Orders/Report.php

_Ref:_ [C#122099](https://central.tri.be/issues/122099)

#122099 - disable PayPal Orders page and links if TPP is inactive

---

readme.txt
src/Tribe/Main.php

_Ref:_ [C#122368](https://central.tri.be/issues/122368)
Prevents all extensions from loading on action tribe_plugins_loaded priority 10 if TEC on an older version.

#122368 - update release date and prevent most extensions from running

---

src/Tribe/Attendee_Registration/Template.php
src/admin-views/tribe-options-tickets.php

🎫 https://central.tri.be/issues/120195
Adds a dropdown to the admin Tickets tab to set a template for the AR page.
Chooses the template used based on that - falls back to `page.php` then to `index.php`
On hold for Strategy QA

Add template chooser for attendee registration page

---

src/Tribe/Attendee_Registration/Template.php

🎫 https://central.tri.be/issues/119777
Targets the Genesis setting itself, as the other approach appears to be less reliable.

Change to targeting Gensis directly

---

readme.txt
src/Tribe/Attendees_Table.php
src/admin-views/attendees.php

🎫 https://central.tri.be/issues/123070
This is a compromise solution:
The user can activate the email form for non-admins via a filter as it works but it throws notices as it's still trying to load admin stuff on the FE. Once we have the notices corrected, we can add the filter as always-on in CT.

Add filter to show email form for non-admins

---

readme.txt
src/styles/rsvp/frontend.pcss

https://central.tri.be/issues/123136

Remove CSS that hides RSVP forms when Event Blocks are disabled

---

readme.txt
src/Tribe/Admin/Move_Ticket_Types.php

Ticket: https://central.tri.be/issues/124164
----
Variable `$src_post_id` is used here:
- https://github.com/moderntribe/event-tickets/blob/910b6883a79935b56f09b4f90174ade582087c2f/src/Tribe/Admin/Move_Ticket_Types.php#L116
But is not defined nowhere inside of this method: https://github.com/moderntribe/event-tickets/blob/910b6883a79935b56f09b4f90174ade582087c2f/src/Tribe/Admin/Move_Ticket_Types.php#L85-L121

Add variable not defined

---

src/Tribe/Attendee_Registration/Main.php
src/Tribe/Attendee_Registration/Shortcode.php
src/Tribe/Attendee_Registration/View.php
src/resources/postcss/tickets-registration-page.pcss

🎫 https://central.tri.be/issues/123044
While doing the video for QA I noticed that the other content was still being overridden when using the shortcode.

Allow content on page with shortcode - even if it's the AR page

---

readme.txt
src/Tribe/RSVP.php

Add a check to RSVP.php to test if the user has enabled the MT blocks editor, and the post has blocks. If so, bail before adding the classic front-end RSVP form.
:ticket: https://central.tri.be/issues/124394

feat(RSVP): Prevent classic rsvp form showing on blocks posts.

---

src/Tribe/RSVP.php

Test the post content for blocks and for the tribe-block class before allowing the RSVP classic form to display.
:ticket: https://central.tri.be/issues/124394

fix(RSVP): Check for block content and don't show classic form if present.

---

readme.txt
src/template-tags/tickets.php

Add a check to tribe_events_count_available_tickets() for unlimited tickets so it returns -1 when
one is found.
🎫 https://central.tri.be/issues/119844

 fix(capacity): Add a check for unlimited tickets 

---

src/Tribe/Shortcodes/User_Event_Confirmation_List.php

Modify the query - needed for backward compat. We should also consider doing something to remove this data from the dB?
:ticket: https://central.tri.be/issues/123609
Props to Dan Bramer for his help with the query!

fix(tribe-user-event-confirmations): Modify query to exclude deleted attendees.

---

readme.txt
src/views/registration/content.php

Remove comment that was breaking `wp_kses` escaping when the shortcode was run.
:ticket: https://central.tri.be/issues/125964

fix(attendee registration shortcode): Remove extraneous comment

---

readme.txt
src/modules/blocks/ticket/container-header/quantity/template.js
src/modules/blocks/tickets/availability/style.pcss
src/modules/blocks/tickets/availability/template.js

Add tooltips to the sold and available numbers explaining them (and their differences)
🎫 https://central.tri.be/issues/121992
Notes: I hard-coded the tooltips as they are only using the title for now (clicking on icons in blocks is...tricksy, and there is an overlay at one point 🤢 )
Required tweaking the styles for the block to accommodate the icon.

 feat(admin ticket block): Add sold/available tooltips

---

readme.txt
src/Tribe/Attendee_Registration/Shortcode.php

Use the `doing_cron` function from tribe.context to be backward compatible with WP versions before
4.8
:ticket: https://central.tri.be/issues/126111
see: https://github.com/moderntribe/tribe-common/blob/f8f3ec8aca567b84a37629d036a8181cd9e2dc22/src/Tribe/Context.php#L242

fix(attendee registration shortcode): Use tribe context for cron discovery.

---

src/modules/blocks/rsvp/container-header/template.js

Ticket tooltip shows, make sure the RSVP one shows as well. This DOES NOT fix the missing tooltip before the block is open.
:ticket: https://central.tri.be/issues/126038#note-12
Corrects issue with 126038 fix, no additional changelog needed.

fix(rsvp block): Ensure tooltip shows for RSVP as well

---

src/Tribe/Abstract_Attendance_Totals.php

Correct message. No changelog needed, it's accounted for in original PR.
:ticket: https://central.tri.be/issues/126342

fix(report tooltips): Correct one message that was C&P wrong.

---

readme.txt
src/Tribe/Attendee_Registration/Shortcode.php
src/Tribe/Attendee_Registration/Template.php

Correct issue where Tribe Comerce would not submit on clicking "Save and Checkout". 
Also orrect missing checked attribute on checkboxes and radios upon submit/refresh when using shortcode.
Wound up being `wp_kses_post` filtering out the form/input attributes.
:ticket: https://central.tri.be/issues/126779

fix(attendee registration shortcode): Correct issue with TC

---

readme.txt
src/views/blocks/rsvp/form/submit-login.php
src/views/registration/attendees/fields/select.php

Correct two places where we had `events-tickets` instead of `event-tickets`, preventing correct
string translations.
:ticket: https://central.tri.be/issues/128193
Ref: https://github.com/moderntribe/event-tickets/pull/1263

fix(translations): Fixed domain in string to be translated.

---

event-tickets.php
readme.txt
src/Tribe/Main.php
src/admin-views/admin-welcome-message.php

Parallels what is essentially the [same change but for TEC](https://github.com/moderntribe/the-events-calendar/pull/2551): instead of submitting directly to createsend.com, the newsletter signup form will now submit to our own service.
:warning: Important! As with [TEC PR 2551]((https://github.com/moderntribe/the-events-calendar/pull/2551)) this change depends on [Support API PR 28](https://github.com/moderntribe/support-api.tri.be/pull/28), which introduces the endpoint we need for this to work. That change must be approved and be deployed before this work ships.
:ticket: [♯129034](https://central.tri.be/issues/129034)

Update embedded newsletter signup form | #129034

---

readme.txt
src/Tribe/Attendee_Repository.php

Fixes a hardcoded reference to `wp_posts` (otherwise, for installs that use a different prefix, the query will break):
> Unknown column 'wp_posts.ID' in 'on clause'
Targeting `master` since I wasn't sure which branch would be best given where we are in the release cycle, feel free to update as needed.
https://central.tri.be/issues/129053

Don't assume a `wp_` prefix for db tables | spotfix

---

readme.txt
src/Tribe/Main.php

This moves the tribe-common registration back to `__construct()` so that it happens _before_ `plugins_loaded` priority `0` as per the Plugin Dependency spec.
See: https://central.tri.be/issues/129479
Related: https://github.com/moderntribe/the-events-calendar/pull/2561

Ensure common version is declared early to make decisions on loading

---

src/Tribe/Main.php

**Background**
The `maybe_set_common_lib_info()` method was in `plugins_loaded()` inappropriately. Once relocated _out_ of `plugins_loaded()` and back to `__construct()` where it belongs, a problem reared its head with regards to plugin validation and bailing. 
Before the Plugin Dependency work, we never checked for out-of-date versions from _both_ TEC and ET. When Plugin Dependency was completed, we added a new check to support this desired validation at the expense of moving the common bootstrap to the wrong place.
**The fix**
In a previous PR for this hotfix, `maybe_set_common_lib_info()` was relocated back to `__construct()`. This PR follows along with some more changes of note:
1. There is now a class property that holds a boolean that allows plugins_loaded() to bail if we determine …

Bail out of bootstrapping non-destructively if older TEC is present

---

src/Tribe/Main.php

This is a change based on feedback from https://github.com/moderntribe/the-events-calendar/pull/2572#discussion_r294592807
See: https://central.tri.be/issues/129478 and https://central.tri.be/issues/129479

Don't attempt to reset common back if Tribe__Events__Main isn't present

---

readme.txt
src/Tribe/Tickets.php
src/Tribe/Tickets_View.php
src/views/blocks/tickets.php
src/views/blocks/tickets/item.php
src/views/blocks/tickets/submit-button-modal.php
src/views/blocks/tickets/submit.php

Add functions to call block ticket template out of context so it is usable in non-Gutenberg views.
Does NOT implement for RSVP or TPP at this time.
Adds a check for `ticket-attendee-modal` and queues the modal via a new submit button template.
:ticket: https://central.tri.be/issues/132568

feat(tickets block): Implement tickets block in classic view.

---

readme.txt
src/views/blocks/tickets.php

By bailing for no tickets here, we never get to the `else` part of this template.
🎫 https://central.tri.be/issues/134821

Template tweak to correct missing message

---

readme.txt
src/Tribe/RSVP.php

:ticket: https://central.tri.be/issues/134408
Somehow the attendee ID was getting out of sync - no reason for the extra var anyway.

Correct bad attendee #s getting passed.

---

src/template-tags/tickets.php

Test the ticket's provider against the event's provider and skip tickets that don't match to avoid issues.
🎫 https://central.tri.be/issues/136194

fix(provider in template): Add check for incorrect provider `tribe_events_has_tickets_on_sale`

---

composer.json
composer.lock

> Deprecation warning: require-dev.moderntribe/TribalScents is invalid, it should not contain uppercase characters. Please use moderntribe/tribalscents instead. Make sure you fix this as Composer 2.0 will error.

update repo names to be lowercase | spotfix

---

composer.lock
src/resources/js/tickets-block.js

and convert decimals so we can pass numbers to `parseFloat` and the like.
🎫 https://central.tri.be/issues/136300
Don't hide items when qty drops to zero.
Pass all tickets, even those with qty 0.
🎫 https://central.tri.be/issues/136295 && https://central.tri.be/issues/136250

Adds a "clean" function to strip separators 

---

src/resources/js/tickets-block.js

Fixes two tickets:
https://central.tri.be/issues/136250 (removes `fadeOut` where inappropriate)
and https://central.tri.be/issues/135008 (incorrect calculations - mixing forms)

Prevent fadeout in modal. Fix calcs.

---

src/Tribe/Editor/Blocks/Tickets.php

Mistakenly set to 0 - now set correctly to 60 seconds.

Set interval to 60 seconds

---

src/Tribe/Commerce/Cart.php

The `json_stringify`-d value gets escaped along the way - we need to `stripslashes` or `json_decode` fails.

Add stripslashes so data is parsed correctly.

---

readme.txt
src/Tribe/Editor/Meta.php
src/Tribe/Editor/Provider.php
src/Tribe/Tickets_Handler.php

WP 5.3 fixes:
Force null values to 0 for `_tribe_ticket_capacity` so RSVPs save correctly.
Tell REST to not update/delete `_tribe_tickets_list` so events save correctly.
🎫 https://central.tri.be/issues/137383

Fix ticketed event saves.

---

readme.txt
src/Tribe/Editor/Meta.php
src/Tribe/Tickets_Handler.php

https://central.tri.be/issues/137383
* Implements _or_null methods for capacity and a few other fields
* Also avoids updating/deleting certain meta fields we don't store/update/delete meta for

Implement _or_null methods and don't update/delete fake meta fields

---

src/resources/js/tickets-block.js

Unintended whitespace in a regex = failing regex.
🎫 https://central.tri.be/issues/133179
📷 http://p.tri.be/0N0fOQ

Whitespace fail.

---

src/Tribe/Commerce/Cart.php

https://central.tri.be/issues/137719
Screencast showing you no longer get sent back to AR page (if you go to AR page from EDD checkout): https://p199.p4.n0.cdn.getcloudapp.com/items/7KuxO9lx/Screen+Recording+2019-11-22+at+12.09+PM.mov

Fix additive handling of meta saves from AR page

---

readme.txt
src/Tribe/Tickets.php
src/Tribe/Tickets_Handler.php

Ensure that the ticket end date (classic editor) is set to the event start date, not the event end
date.
🎫  https://central.tri.be/issues/135218
🎫 https://central.tri.be/issues/125969
📹 http://p.tri.be/8ekMnh

fix(ticket end date): Correct the automatic generation of ticket end dates.

---

readme.txt
src/Tribe/Commerce/PayPal/Main.php

Add logic to test provider against event default provider. Prevent iterating through those tickets
that are not from the event provider on the front end.
🎫 https://central.tri.be/issues/137925
Related: https://github.com/moderntribe/event-tickets-plus/pull/914

 fix(tickets block): Prevent duplicate blocks on provider change.

---

readme.txt
src/Tribe/Tickets.php

Make get_tickets() protected to avoid errors with it not being public before upgrading ET+
https://central.tri.be/issues/138385

Make get_tickets() protected again

---

readme.txt
src/resources/js/tickets.js

https://central.tri.be/issues/136451
Screencast: https://p199.p4.n0.cdn.getcloudapp.com/items/P8uYRnn5/Screen+Recording+2019-12-14+at+12.26+PM.mov
Tested against:
```
Johnny's `~!@#$%^&*()_+-={}|[]:";'<>?,.\/ yes
```
Only character not saving correctly is backslash but it gets stripped out and does not effect the rest of the text (previously single quotes would break everything on save).

Handle special characters for Event Ticket field labels like single quotes and colons so they don't break the saving

---

src/Tribe/Assets.php
src/Tribe/Commerce/PayPal/Main.php
src/Tribe/Editor/Blocks/Rsvp.php
src/Tribe/Editor/Blocks/Tickets.php
src/Tribe/RSVP.php

jQuery Datepicker was conflicting with bootstrap datepicker causing our views navigation to break.
:movie_camera: http://p.tri.be/wpGQRj

Removing jquery-ui-datepicker from the frontend because it is unused

---

readme.txt
src/template-tags/tickets.php
src/views/v2/day/event/cost.php
src/views/v2/list/event/cost.php
src/views/v2/map/event-cards/event-card/actions/cost.php
src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
src/views/v2/photo/event/cost.php
src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
src/views/v2/week/mobile-events/day/event/cost.php

This adds a new function that looks at the current default provider OR RSVPs to determine if the current datetime falls within the date window of the tickets on the post. The function was added because `tribe_events_has_tickets_on_sale()` _only_ looks at the default provider and doesn't care about RSVP if Woo/EDD/TC are also being used.
:movie_camera: http://p.tri.be/lwB29E
:ticket: [TEC-3033]
[TEC-3033]: https://moderntribe.atlassian.net/browse/TEC-3033

Use new func to verify tickets are available for current date window | TEC-3033

---

readme.txt
src/modules/data/blocks/rsvp/sagas.js
src/modules/data/blocks/ticket/sagas.js

The block editor always used the event REST API for adding ticket(and RSVP) images - this fails if we're not editing an event. 
This code changes it to detect the post type and use the appropriate endpoint (`tribe_events` for events, `posts` otherwise).
Code changes are only to update and delete for both RSVP and Ticket.
:ticket: [ET-54]
📸   http://p.tri.be/E6sYH4

fix(ticket header image): Allow adding ticket header image on non-event posts.

---

readme.txt
src/views/tickets/rsvp.php

THe rsvp form had a variable carried through the loop to check for "product available" - but if the
last RSVP was sold out then it would be set to `false` - resulting in the meta row no showing up.
We've updated that to rely on _two_ variables - one for the specific rsvp and one for all rsvps.
:movie_camera: http://p.tri.be/iRhxoL
:ticket: [ET-603]
BTW: 603 is the area code for NH :tada:
[ET-603]: https://moderntribe.atlassian.net/browse/ET-603

fix(RSVP stock): Correct front end form when one RSVP becomes sold out.

---

readme.txt
src/Tribe/RSVP.php
src/views/blocks/attendees.php
src/views/tickets/orders.php

Add logic to comprehensively respond to events with or without tickets or RSVP, and users with or
without tickets or RSVPs.
:camera_flash:
ticket-only, no purchase: http://p.tri.be/TFyuxu
ticket-only, with purchase: http://p.tri.be/sqYmvx
rsvp-only, no rsvp: http://p.tri.be/NBUFAO
rsvp-only, "going": http://p.tri.be/bdTWRs
rsvp-only, "not going": http://p.tri.be/YouQXd
mix, no tickets or RSVP: http://p.tri.be/WoQJtQ
mix, RSVP "going" no ticket: http://p.tri.be/d1otvQ
mix, RSVP "not going" no ticket: http://p.tri.be/XaROBz
mix, RSVP "not going" with ticket: http://p.tri.be/fpvq0R
mix, RSVP "going" (and not going) with ticket: http://p.tri.be/k24eVR
mix, ticket, no RSVP: http://p.tri.be/bQcNEd
mix, ticket, RSVP "not going": http://p.tri.be/MFOSux
mix, ticket, RSVP "going"  (and not going): …

feat(no tickets notice): Refine logic for the notice on the "my tickets" page. ETP-612, ETP-46

---

readme.txt
src/Tribe/Commerce/PayPal/Main.php
src/Tribe/Ticket_Object.php

When saving tickets initially, we weren't updating the event meta value we check on the front end,
resulting in new shared tickets appearing sold out. This adds that update.
🐫 http://p.tri.be/iZdLbf
📷 http://p.tri.be/6geO8s
Requires: https://github.com/moderntribe/event-tickets-plus/pull/944
[ET-614]
[ET-614]: https://moderntribe.atlassian.net/browse/ET-614

fix(global stock): Incorrect global stock on new tickets.

---

readme.txt
src/Tribe/Tickets.php
src/resources/js/tickets-block.js

Some themes do not follow the standards of official themes and alter where they put either the post ID or the publish status. We were relying on those to find the post ID - now we make it available via localize_script().
:ticket: [ET-640]
[ET-640]: https://moderntribe.atlassian.net/browse/ET-640

fix(tickets block js): Ensure we have the post ID. ET-640

---

readme.txt
src/resources/postcss/tickets-registration-page.pcss
src/resources/postcss/tickets.pcss
src/styles/tickets/frontend.pcss
src/views/blocks/tickets/extra-price.php

Put in a check for `$ticket->on_sale` and show the original price before it on the tickets block.
Add `tribe_tickets_show_original_price_on_sale` filter to turn off if desired.
Also sneak in a few style tweaks for Mr. Randall.
:ticket: [ETP-47]
[ETP-47]: https://moderntribe.atlassian.net/browse/ETP-47
Requires https://github.com/moderntribe/event-tickets-plus/pull/946 for correct calculations!
📷 📸 
mobile: http://p.tri.be/3RijFK
desktop: http://p.tri.be/c3h7gU

feat(ticket price): Show original price on ticket block if ticket is on sale.

---

src/Tribe/Events/Views/V2/Hooks.php

When including files from themes the `Tribe__Templates` class was looking into the incorrect file path depending on how the class was instantiated.
If we wanted to include an Event Tickets file from a class that was using the Origin as The Events Calendar, it would point to `[your-theme]/events/v2/event.php` instead of  `[your-theme]/tickets/v2/event.php`.
This PR is just the compatibility for Views V2 with the changes on Common, which have no impact on any other part of our codebase besides Views.
https://github.com/moderntribe/tribe-common/pull/1268
📹 https://i.bordoni.me/Koue8qN5

Add the methods for the templates in Tickets

---

composer.lock
src/views/blocks/rsvp/form/opt-out.php
src/views/blocks/tickets/opt-out-hidden.php

~Change `&&` to `||` - as the conditions are mutually exclusive.~
Remove the checks for the list - we always show it now.
Caught while doing testing instructions for the ticket.
🎫 [ET-615]
[ET-615]: https://moderntribe.atlassian.net/browse/ET-615

fix(optout logic): Correct the logic for hiding the optout.

---

readme.txt
src/resources/postcss/components/_all.pcss
src/resources/postcss/components/buttons/_link.pcss
src/resources/postcss/components/buttons/_small.pcss
src/resources/postcss/tickets.pcss

The styles associated with the small buy now button are not being applied correctly. The TEC
skeleton styles override them, as do the theme styles. This fix enforces our button size and color choice styles.
:ticket: [ETP-210]
📸 http://p.tri.be/sWmhl9
[ETP-210]: https://moderntribe.atlassian.net/browse/ETP-210

fix(buy button): Tickets block buy button style overridden by theme.

---

readme.txt
src/admin-views/editor/fieldset/advanced.php

[ET-727]
Screencast: https://share.getcloudapp.com/jkuKoPny
[ET-727]: https://moderntribe.atlassian.net/browse/ET-727

Use the default `datepickerFormat` value if the option hasn't been set yet when setting up validation rules for the ticket add/edit admin form

---

readme.txt
src/Tribe/Promoter/Observer.php

Improve the support for Tribe Commerce Provider when used alongside Promoter, add listeners to individual attendees and tickets of this provider.
Tickets: 
- [ET-746]
- [PRMTR-171]
Requires: https://github.com/moderntribe/event-tickets/pull/1607
[ET-746]: https://moderntribe.atlassian.net/browse/ET-746
[PRMTR-171]: https://moderntribe.atlassian.net/browse/PRMTR-171

PRMTR-171, ET-746: Improve support for TPP on ET for Promoter

---

tests/_data/dump.sql

This PR updates the dump.sql to work well with the most recent versions of WordPress. It was last updated in 2018, and using a database with an old schema in a recent version of WordPress might cause unexpected issues in tests, especially functional and acceptance.
Changes to the dump:
- `wp core update-db`, to update it to the latest WordPress database schema
- `wp user update admin --user_pass="password"`, so the password matches what's on the `.env` file (admin/password)
- Manually tweaked the option `admin_email_lifespan` so the "Site Admin Email Verification Screen" that was [introduced](https://make.wordpress.org/core/2019/10/17/wordpress-5-3-admin-email-verification-screen/) in WordPress 5.3 doesn't show up when running tests  (well, at least until 2050)
There's no ticket for this. …

Update dump sql

---

src/Tribe/Admin/Display_Settings.php
src/Tribe/Admin/Notices.php
src/Tribe/Editor/Blocks/Rsvp.php
src/Tribe/Query.php
src/Tribe/RSVP.php
src/Tribe/Service_Provider.php
src/Tribe/Tickets_View.php
src/admin-views/tribe-options-display.php
src/template-tags/tickets.php
tests/_function-mocker-bootstrap.php
tests/acceptance.suite.dist.yml

[ET-796]
[ET-797]
This PR accomplishes:
- New opt-in setting in admin area (not shown unless dev constant is enabled)
- New opt-in setting method check with support for our dev constant `TRIBE_TICKETS_RSVP_NEW_VIEWS`
- New opt-in notice (commented out from being called for now as it will ship enabled in G20.07)
- RSVP classic now renders new abstracted block render function (if opt-in enabled)
- RSVP block now renders new abstracted block render function
- RSVP abstracted block render function will render the new `v2/rsvp` view if opt-in enabled, otherwise it will render the old `blocks/rsvp` view
- RSVP abstracted block render function now supports new temporary preview constant `TRIBE_TICKETS_RSVP_NEW_VIEWS_PREVIEW` which will show static kitchen sink for themers and customers to use as …

[ET-796] [ET-797] Handle RSVP admin notice, constant, setup opt-in setting, and start handling RSVP rendering

---

src/Tribe/Editor/Blocks/Rsvp.php
src/Tribe/RSVP.php
src/Tribe/Tickets_View.php

Screenshot of it only showing once: https://p199.p4.n0.cdn.getcloudapp.com/items/nOueWq5A/Screen%20Shot%202020-06-11%20at%204.38.28%20PM.png?v=ec8cbb12e96ef4a06c76f277ab703fb9
When blocks are enabled, it would echo and return the content (so it would appear twice).

Fix RSVP multiple echo

---

src/Tribe/Admin/Display_Settings.php

Prevent `constant(): Couldn’t find constant TRIBE_TICKETS_RSVP_NEW_VIEWS` PHP warnings
[ET-856]
[ET-856]: https://moderntribe.atlassian.net/browse/ET-856

[ET-856] Comment out code instead of checking constant for now

---

src/Tribe/Admin/Display_Settings.php
src/Tribe/Admin/Notices.php
src/template-tags/tickets.php

[ET-797]
Screencast: https://p199.p4.n0.cdn.getcloudapp.com/items/mXuAQJ9Q/Screen%20Recording%202020-07-10%20at%2005.01.51%20PM.mp4
We should hold on this PR until we know the feature will be complete in time for G20.07 to ship. If it doesn't make it, we can just put this PR forward for G20.08.
This PR is based against https://github.com/moderntribe/event-tickets/pull/1712 so the diff on this PR is specific to just showing the notice.
[ET-797]: https://moderntribe.atlassian.net/browse/ET-797

[ET-797] Enable the opt-in update notice

---

src/Tribe/Editor/Blocks/Rsvp.php

ET-827
We need WP to load utils, for underscores, on the ARI library, so we can use underscores for templating.

RSVP > Add `wp-util` dependency

---

src/admin-views/tribe-options-display.php
src/template-tags/tickets.php

[ET-841]
Per Jeff's strategy, we're enabling RSVP FE 2020 views for new installs by default and not showing the opt-in option.
[ET-841]: https://moderntribe.atlassian.net/browse/ET-841

[ET-841] Default RSVP FE to enabled for new installs and don't show the opt-in option

---

readme.txt
src/modules/blocks/rsvp/attendee-registration/template.js
src/modules/elements/attendees-registration/element.js

**Ticket:** [GTRIA-275]
This PR passes the `shouldCloseOnClickOutside` property down to the WordPress modal component which disables closing by clicking outside.
**Screencast:** https://drive.google.com/file/d/10EeJFXlGK3ahvDx3LGVQI1XEHl5Rilo9/view?usp=sharing
[GTRIA-275]: https://moderntribe.atlassian.net/browse/GTRIA-275

[GTRIA-275] Fix/modal button props

---

src/Tribe/Events/Attendees_List.php
src/Tribe/Tickets_View.php

[ET-809]
Screenshot: https://p199.p4.n0.cdn.getcloudapp.com/items/2NuyEDXJ/Screen%20Shot%202020-08-18%20at%209.44.54%20PM.png?v=90c7323246a06cb816b10d343240cb86
Typo intentional, to show it's using the block even though the event had the classic attendees showing option enabled.
[ET-809]: https://moderntribe.atlassian.net/browse/ET-809

[ET-809] Ensure content for RSVP action is returned and not output

---

readme.txt
src/views/blocks/tickets/submit-button-modal.php

🎫 https://moderntribe.atlassian.net/browse/ET-907
🎥 not-required.
Thanks @justlevine for the fix! This is a follow-up of https://github.com/moderntribe/event-tickets/pull/1733, where we couldn't push more changes because the head ref was unknown.

[ET-907] Remove duplicate `button_id`

---

src/views/v2/tickets/commerce/fields.php
tests/_support/Partials/V2TestCase.php

[ETP-473]
Updated abstract V2Testcase class to simplify calling 
`
$driver = new WPHtmlOutputDriver( home_url(), 'http://wordpress.test' );                                                                             
$this->assertMatchesSnapshot( $html, $driver );
` 
to only:
`$this->assertMatchesSnapshot( $html );`
[ETP-473]: https://moderntribe.atlassian.net/browse/ETP-473

[ETP-473] Abstract WPHtmlOutputDriver usage for most cases

---

src/Tribe/Assets.php

🎫 ETP-457
🎥 not required.
Only use the v1 JS for the v1 views. Scripts for v2 will live in ET+.

Move AR page JS to ET+ for V2.

---

src/resources/postcss/tickets-registration-page.pcss

[ET-916]
[ET-916]: https://moderntribe.atlassian.net/browse/ET-916

Revert changed class name to keep compatibility with V1 templates

---

src/Tribe/Commerce/PayPal/Main.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php

[ETP-436]
Dev screencast in use: https://share.skc.dev/GGur1rRj
This abstracts the security code generation and the security code meta key property so that it can better be reused. Right now, all providers have their own implementation and this makes sure they get generated more randomly and secured.
[ETP-436]: https://moderntribe.atlassian.net/browse/ETP-436

[ETP-436] Abstract the security code generation

---

readme.txt
src/Tribe/Tickets_View.php

[ET-943]
Dev screenshot: https://p199.p4.n0.cdn.getcloudapp.com/items/geuqLROk/Screen%20Shot%202020-11-12%20at%207.23.42%20PM.png?v=11304a0b7bace2b3564b652616941b0a
$going wasn't set and isn't passed to any of the main areas of the v1 templates, this adds it so it can be utilized further down in the templates without modifying any views
[ET-943]: https://moderntribe.atlassian.net/browse/ET-943

[ET-943] Prevent PHP notices about $going not being set

---

src/Tribe/Admin/Manager/Service_Provider.php
src/Tribe/Assets.php
src/Tribe/Main.php
src/resources/js/admin/tickets-manager.js

🎫 [ETP-523]
🎥 https://www.loom.com/share/a73f13d3e38847bbbda1e6d8f7b5a618
**Adding the admin manager.**
- This will allow us to have one AJAX handler in the admin side. 
- We could extend this and use it for different containers (for example in a dashboard).
- This will be the engine that will serve the Manual Attendees modal content (when opening on edit / submitting).
- In the screencast, for example, I'm just extending the response from the theme functions.php file.
[ETP-523]: https://moderntribe.atlassian.net/browse/ETP-523

[ETP-523] Tickets > Admin manager.

---

event-tickets.php
readme.txt
src/Tribe/Assets.php
src/Tribe/Attendee_Registration/Service_Provider.php
src/Tribe/Editor/Attendee_Registration.php
src/Tribe/Editor/Provider.php
src/Tribe/Main.php
src/Tribe/Plugin_Register.php
src/Tribe/Tickets.php
src/template-tags/tickets.php
src/views/blocks/tickets/submit.php

[ET-964]
Require Event Tickets Plus 5.1.0.1+ for compatibility purposes on certain areas in Event Tickets that have direct calls to Event Tickets Plus functionality
[ET-964]: https://moderntribe.atlassian.net/browse/ET-964

[ET-964] Require Event Tickets Plus 5.1.0.1+

---

readme.txt
src/Tribe/Editor/Configuration.php
src/modules/data/blocks/rsvp/reducers/details.js
src/modules/data/blocks/rsvp/sagas.js
src/modules/data/blocks/ticket/reducers/tickets/ticket/details.js
src/modules/data/blocks/ticket/reducers/tickets/ticket/temp-details.js

[ET-952]
For the Non-event post type, we are adding 1 year + 2 hours to the ticket end date changing from the old 100 years value.
Screenshot:
[ET-952]: https://moderntribe.atlassian.net/browse/ET-952

[ET-952] Adjust Sale End time for tickets and RSVPs

---

readme.txt
src/views/registration-js/content.php
src/views/registration-js/mini-cart.php

[ET-955]
This fixes a php notice and removes the save and checkout text based on the ticket needs.
Screenshot: https://p199.p4.n0.cdn.getcloudapp.com/items/2Nu0XkQ4/Screen%20Shot%202020-12-03%20at%204.03.35%20PM.png?v=19c123d5f7d268d4509b1c9c8ff1243b
[ET-955]: https://moderntribe.atlassian.net/browse/ET-955

[ET-955] Remove extraneous "Save and checkout" heading from the registration-js/content.php view

---

readme.txt
src/Tribe/Commerce/PayPal/Main.php

[ETP-599]
This PR prevents PHP notices when tickets are provided already per-formatted in ET.
[ETP-599]: https://moderntribe.atlassian.net/browse/ETP-599

[ETP-599] ET > Prevent php notices from interacting with tickets not prepared by current commerce provider

---

src/modules/data/blocks/rsvp/sagas.js

[ET-952]
[ET-952]: https://moderntribe.atlassian.net/browse/ET-952

[ET-952] Fixed showing 2 years buffer for RSVP block

---

src/resources/postcss/tickets-admin.pcss

[ET-947]
The warning notice has a class that uses `display:flex` but it gets a bit messy when involving Tribe dependency and AJAX loading too. This resolves those issues.
Dev screencast: https://share.skc.dev/OAuWgl20
[ET-947]: https://moderntribe.atlassian.net/browse/ET-947

[ET-947] Resolve CSS display conflict with Tribe Dependency for Warning notice

---

src/Tribe/Tickets.php

[ET-599]
This fixes one more PHP notice happening on the AR page, some sites experience the cache value to not be an array in certain circumstances.
This goes towards the pre-existing ET-599 changelog
[ET-599]: https://moderntribe.atlassian.net/browse/ET-599

[ET-599] Fix one more AR page notice appearing

---

readme.txt
src/resources/js/tickets-registration-page.js

[ETP-601]
This prevents potential event conflicts with other scripts like Avada which manually `.trigger( 'ready' )` and cause problems for things that use `.on( 'ready', ... )`
Tested on customer staging and proven to work, this even matches the same implementation we use for the new AR page JS code that's in ET+ for the new Tickets views we revamped.
[ETP-601]: https://moderntribe.atlassian.net/browse/ETP-601

[ETP-601] Use jQuery.ready() and prevent potential event conflicts

---

readme.txt
src/Tribe/Commerce/PayPal/Gateway.php

[ET-995]
This error isn't encountered often and it's quite difficult to reproduce. But there are edge cases which can cause a fatal error. The fix involves confirming the `$ticket` response is in fact an object as expected, before calling it like an object.
[ET-995]: https://theeventscalendar.atlassian.net/browse/ET-995

[ET-995] Prevent problems with fatal errors from tickets that no longer exist

---

src/Tribe/Attendee_Repository.php
src/Tribe/Repositories/Order.php

[ET-926]
These tweaks help abstract some of the stuff needed for Orders by https://github.com/the-events-calendar/event-tickets-plus/pull/1146/
Screenshot of the tests passing that depend on the code for this:
[ET-926]: https://theeventscalendar.atlassian.net/browse/ET-926

[ET-926] ET MA BE Part 3: Clean up logic for order creation and rely less on $ticket object

---

src/Tribe/Attendee_Repository.php
src/Tribe/Tickets.php

[ETP-490]
[ETP-522]
[ETP-509]
[ETP-485]
This handles the email send / resend functionality for Attendees ORM.
It also moves the cache clearing into the trigger create/update method to abstract better.
Dev screencast: https://share.skc.dev/geu4ZBwG
[ETP-490]: https://theeventscalendar.atlassian.net/browse/ETP-490
[ETP-522]: https://theeventscalendar.atlassian.net/browse/ETP-522
[ETP-509]: https://theeventscalendar.atlassian.net/browse/ETP-509
[ETP-485]: https://theeventscalendar.atlassian.net/browse/ETP-485

[ETP-490] [ETP-522] [ETP-509] [ETP-485] Handle email send / resend functionality for Attendees ORM

---

src/Tribe/Commerce/PayPal/Main.php
src/Tribe/RSVP.php
src/Tribe/Tickets.php
src/Tribe/Tickets_Handler.php
src/views/tickets/orders.php

[ET-926]
This PR handles preventing spam by limiting how many email resends can happen per attendee.
This ensures that the ticket sent counter is provided for the attendee and that the counter is functioning as expected with reduced complexity.
[ET-926]: https://theeventscalendar.atlassian.net/browse/ET-926

[ET-926] ET > Handle email resend limitations for spam prevention

---

src/Tribe/Attendee_Repository.php
src/Tribe/Commerce/PayPal/Main.php
src/Tribe/RSVP.php
src/Tribe/Repositories/Attendee/Commerce.php
src/Tribe/Repositories/Attendee/RSVP.php
src/Tribe/Tickets.php

[ETP-640]
Dev screencast: https://share.skc.dev/GGu60Ypn
This PR handles increasing/decreasing sales/stock for RSVPs in a more abstracted way.
The Attendees ORM now clears ticket cache properly.
The stock increase/decrease handling prevents negative numbers for sales and stock counts.
[ETP-640]: https://theeventscalendar.atlassian.net/browse/ETP-640

[ETP-640] Update sales/stock for RSVPs

---

src/Tribe/Assets.php
src/Tribe/Tickets.php
tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
tests/wpunit/Tribe/Tickets/TicketsTest.php

[ETP-487]
[ETP-517]
Dev Screencast: https://share.skc.dev/5zuAADwN
This PR addresses a need by ET+ to only get providers for a post that are active. Other functions return the current provider set for a post but does not take into account whether it's active and available at the code level.
This PR also fixes a problem with the tribe-tickets-loader asset not being registered when it's needed by ET+ even when new rsvp/ticket views are not enabled.
[ETP-487]: https://theeventscalendar.atlassian.net/browse/ETP-487
[ETP-517]: https://theeventscalendar.atlassian.net/browse/ETP-517

[ETP-487] [ETP-517] Add function to get active providers for a post

---

readme.txt
src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
src/Tribe/Ticket_Object.php
tests/_support/Commerce/PayPal/Ticket_Maker.php
tests/restv1/PayPal/CartCest.php
tests/restv1/PayPal/CartUpdateCest.php
tests/restv1/PayPal/TicketArchiveByPostCest.php

[ET-1023]
This PR implements the caching work from common https://github.com/the-events-calendar/tribe-common/pull/1553 and addresses three areas:
* `Tribe__Tickets__Ticket_Object` now correctly checks against `false` values instead of `isset()` for whether a cached key has a proper value to return.
* Set default `'iac'` value to `'none'` when adding a ticket from REST API since the value is optional in the REST API interface.
* Fixed restv1 tests so they pass and skipped some that are for future Tribe Commerce cart expansion.
[ET-1023]: https://theeventscalendar.atlassian.net/browse/ET-1023

[ET-1023] ET > Resolve restv1 tests and fix Tribe__Tickets__Ticket_Object caching problems

---

readme.txt
src/Tribe/Tickets_View.php

[ETP-639]
Before the fix, within any WP Query loop like the posts loop, the first ticket was shown for all posts:
After the fix, it is now showing the associated Ticket for each post:
[ETP-639]: https://theeventscalendar.atlassian.net/browse/ETP-639

[ETP-639] Set local vars for ticket template to fix showing same ticket for all posts within Query loop

---

readme.txt
src/Tribe/Tickets.php

[ET-1042]
This PR disables creating new users for new attendees.
[ET-1042]: https://theeventscalendar.atlassian.net/browse/ET-1042

[ET-1042] Disable creating users by default for new attendees

---

src/resources/postcss/tickets-admin-settings.pcss

[ET-959]
Screenshot:
[ET-959]: https://theeventscalendar.atlassian.net/browse/ET-959

[ET-959] Adjusted banner content area

---

package.json
readme.txt
src/modules/blocks/rsvp/container-header/style.pcss
src/modules/blocks/rsvp/container-header/template.js
src/modules/blocks/ticket/container-content/advanced-options/move-delete/style.pcss
src/modules/blocks/ticket/container-header/description/style.pcss
src/modules/blocks/ticket/container-header/description/template.js
src/modules/blocks/ticket/container-header/price/style.pcss
src/modules/blocks/ticket/container-header/title/style.pcss
src/modules/elements/container-panel/style.pcss
src/modules/elements/inactive-block/style.pcss
src/modules/elements/settings-dashboard/style.pcss

[ET-1078] 
- Switching the tickets and RSVP blocks to have an autosize textarea so it doesn't break the block when using long descriptions.
- Few aesthetics amendments (i.e.: using the design system black)
https://www.loom.com/share/6c943f7a82034284b134eef49551054a
[ET-1078]: https://theeventscalendar.atlassian.net/browse/ET-1078

[ET-1078] Blocks > Fix RSVP & Tickets block description

---

readme.txt
src/Tribe/Admin/Manager/Service_Provider.php

[ET-1079] 
* Show a Nav button in the WP Admin bar linking to the Attendee Reports Page.
* If Admin view -> It's only shown on the Event/Post type Editor view.
* For frontend -> It's only shown if the current page is a single view page.
* In both cases, it should be shown only if the Event/Post has any tickets.
🎥  https://d.pr/v/ajByTQ
[ET-1079]: https://theeventscalendar.atlassian.net/browse/ET-1079

[ET-1079] Add Attendees nav button on Admin bar

---

readme.txt
src/Tribe/RSVP/Status/Going.php
src/Tribe/RSVP/Status/Not_Going.php

[ET-1056] 
On the My Tickets page, there is a selection of Going vs Not Going status which were not translation supported before: https://d.pr/i/Fggxqp
Now they should support translations.
N/A
[ET-1056]: https://theeventscalendar.atlassian.net/browse/ET-1056

[ET-1056] Add translation support for going/not going status labels

---

readme.txt
src/Tribe/Attendees_Table.php
src/admin-views/attendees-table/check-in-button.php

[ET-984] 
* Fixed checked in button issue where it was possible to check-in for disabled buttons.
* Moved button html to a separate admin template for better logic structure.
🎥 https://d.pr/v/SePCTk
[ET-984]: https://theeventscalendar.atlassian.net/browse/ET-984

[ET-984] moved check in button to new template and added disabled attribute

---

readme.txt
src/Tribe/Assets.php
src/resources/js/admin/tickets-manager.js

[ETP-719] 
- use independent var to localize the tribe admin manager to prevent conflicts.
https://www.loom.com/share/688288a71bf54fb099ea7da0f00b6bea
[ETP-719]: https://theeventscalendar.atlassian.net/browse/ETP-719

[ETP-719] Fix localize for tickets admin manager  (manual attendees problem)

---

src/Tribe/Tickets.php
tests/wpunit/Tribe/Tickets/Tickets/CostRangeTest.php

[ET-1053] 
* Enable hiding of inactive tickets price from the TEC cost range for Event.
🎥 screencast:
https://d.pr/v/rzmC0e
[ET-1053]: https://theeventscalendar.atlassian.net/browse/ET-1053

[ET-1053] Hide past/future tickets from showing up in TEC cost range for Events.

---

readme.txt
src/Tribe/Editor/Blocks/Attendees.php
src/Tribe/Events/Attendees_List.php
src/views/blocks/attendees/description.php

[ET-791] 
* Previously it used to show only the number of purchasers instead of the total number of confirmed attendees.
* Now it should show the proper number of attendees as the title.
**Before**
**After the fix showing proper attendee count as 4:**
[ET-791]: https://theeventscalendar.atlassian.net/browse/ET-791

[ET-791] Fix Attendee List block's shown attendance count

---

readme.txt
src/resources/js/tickets-block.js
src/resources/js/v2/tickets-utils.js

[ET-1114] 
We weren't accounting for the cases where they sell tickets:
- With the price above a thousand.
- And a thousand separator
- And no decimals
Whenever the number has no decimal we were returning the number and not cleaning it, to make the proper calculations.
https://www.loom.com/share/29144cdfc2f748f989145f2119d229a8
[ET-1114]: https://theeventscalendar.atlassian.net/browse/ET-1114

[ET-1114] Fix number calculation for prices with thousands separator and no decimals

---

readme.txt
src/Tribe/RSVP.php
src/Tribe/Tickets.php

Unless, of course, it should be free :D
[ET-1133]
This resolves an issue caused by the ticket dates being constructed without the start/end times being factored in.
https://d.pr/v/b5GOXb
[ET-1133]: https://theeventscalendar.atlassian.net/browse/ET-1133

Prevent events being listed as Free on the day of the event

---

readme.txt
src/Tribe/Tickets.php

[ET-1133] 
Here we have a "Fix", since this is reverting a behavior we introduced on version 5.1.4, where we added a filter to exclude past items from the list of 
https://i.bordoni.me/qGu5gLKx
[ET-1133]: https://theeventscalendar.atlassian.net/browse/ET-1133

Make sure we revert to false by default for excluding

---

readme.txt

[ET-1143] 
- We are including new, revamped screenshots for our WP.org page 🎉 
- We needed a small adjustment on the list of screenshots before we push them.
N/A
[ET-1143]: https://theeventscalendar.atlassian.net/browse/ET-1143

[ET-1143] Update wp org screenshots.

---

readme.txt
src/Tribe/Attendees.php
src/Tribe/Attendees_Table.php
src/admin-views/attendees.php

[ET-1145] 
- Added the export button next to the page title on the Attendees page
- Updated the action `tribe_report_page_after_text_label` to include `$attendees` variable
- Moved the export button generating script to it's own function so it can be reused
Showing export button next to page title
Showing export button on table
Showing no export button with no attendees
[ET-1145]: https://theeventscalendar.atlassian.net/browse/ET-1145

[ET-1145] Feature/et 1145 add export button attendees title

---

readme.txt
src/admin-views/editor/list-row.php
src/resources/postcss/tickets-tables.pcss

[ET-1107] 
- Adding the delete functionality for the list of tickets in the classic editor.
- Hooking onto existing functionality, keeping the classes and such so the JS works out of the box. We could possibly improve this in the future.
https://www.loom.com/share/1601bd8ecf75476e8b64a7972c4d4b01
[ET-1107]: https://theeventscalendar.atlassian.net/browse/ET-1107

[ET-1107] Add delete functionality for the tickets area in the classic editor.

---

src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/template.js

[ETP-739] 
[ETP-739]: https://theeventscalendar.atlassian.net/browse/ETP-739

RadioControl needs to be type='radio' shockingly... not type='text'

---

src/Tribe/Event_Repository.php
src/Tribe/Repositories/Traits/Post_Tickets.php
src/Tribe/Service_Providers/ORM.php
tests/_support/Commerce/PayPal/Ticket_Maker.php
tests/wpunit/Tribe/REST/V1/Endpoints/PayPal_Commerce/Payment_Capture_CompletedTest.php
tests/wpunit/Tribe/Tickets/Cache/Transient_CacheTest.php
tests/wpunit/Tribe/Tickets/Commerce/PayPal/MainTest.php
tests/wpunit/Tribe/Tickets/Commerce/Tickets_Commerce/Gateways/PayPal_Commerce/GatewayTest.php
tests/wpunit/Tribe/Tickets/Commerce/Tickets_Commerce/Gateways/PayPal_Legacy/GatewayTest.php
tests/wpunit/Tribe/Tickets/Event_RepositoryTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/CreateTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/DeleteTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/FetchTest.php
tests/wpunit/Tribe/Tickets/ORM/Tickets/UpdateTest.php
tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
tests/wpunit/Tribe/Tickets/Status/TTPManagerTest.php
tests/wpunit/Tribe/Tickets/Template_Tags/GlobalStockTest.php
tests/wpunit/Tribe/Tickets/Template_TagsTest.php

A non-ideal solution to the multi-decorated event repository. This avoids the overriding of ET's Event Repository additions by Events Virtual and ECP.
:ticket: [TEC-3917]
:movie_camera: https://d.pr/v/wMYWNo
[TEC-3917]: https://theeventscalendar.atlassian.net/browse/TEC-3917

Add support for Ticketed/Unticketed filters for the Admin Manager

---

readme.txt
src/modules/blocks/rsvp/container-header/style.pcss
src/modules/blocks/rsvp/container-header/template.js
src/modules/blocks/ticket/container-header/title/style.pcss
src/modules/blocks/ticket/container-header/title/template.js

[ET-1089] 
When editing an RSVP or ticket in the block editor, we want to allow titles to wrap to multiple lines instead of stretching things out.
https://youtu.be/aV-wDYw-TiQ
[ET-1089]: https://theeventscalendar.atlassian.net/browse/ET-1089

[ET-1089] enable multiline input for ticket rsvp titles in block editor

---

readme.txt
src/resources/postcss/rsvp-v1.pcss

[ET-1169] 
In the Twenty Twenty One theme, when users go to view their RSVPs on the front end, the "Going/Not Going" dropdown isn't sized appropriately to show all of the text. It gets cut-off. This PR fixes it by removing the padding that Twenty Twenty One adds to all select boxes.
https://youtu.be/X7ieTyXy0bU
[ET-1169]: https://theeventscalendar.atlassian.net/browse/ET-1169

[ET-1169] tweak padding for going dropdown

---

src/Tickets/Commerce/Hooks.php
src/Tickets/Commerce/Legacy_Compat.php
src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
src/Tribe/Commerce/PayPal/Main.php
src/admin-views/tribe-options-tickets.php
src/functions/commerce/provider.php

[TICKET_ID] 
* Reverted disabling TribeCommerce while Ticket Commerce is enabled, as we need to allow users to show and manage existing Tickets with TribeCommerce.
* Added a label to highlight TribeCommerce as Not Recommended but didn't remove completely for older installs.
* For new installs TribeCommerce is fully disabled and only Ticket commerce is shown.
* I was able to use both TribeCommerce and TicketCommerce in parallel.
* Existing tickets from TribeCommerce are not affected by changes from Ticket Commerce.
🎥 screenshot:
https://d.pr/i/QtTnoW

TribeCommerce and Ticket Commerce parallel fixes.

---

readme.txt
src/resources/postcss/rsvp-v1.pcss

[ET-1169] 
We've added a fix within ticket ET-1169 to also keep the background image (if theme sets one) from being hidden.
https://youtu.be/Yt_-7MIJxKI
[ET-1169]: https://theeventscalendar.atlassian.net/browse/ET-1169

[ET-1169] ensure arrow shows if set by theme

---

src/Tickets/Commerce/Hooks.php
src/Tickets/Commerce/Legacy_Compat.php
src/Tickets/Commerce/Settings.php

[ET-1205] 
* When the Ticket Settings update is clicked we trigger the `save_form_settings` method that makes use of `update_post_meta` for saving the provider data.
* For the new Ticket Commerce our provider class is namespaced which should be saved like this as meta: `TEC\\Tickets\\Commerce\\Module` but as it is running through `wp_unslash` it's getting saved as `TECTicketsCommerceModule`.
🎥 screencast(s): https://d.pr/v/kOMioC
[ET-1205]: https://theeventscalendar.atlassian.net/browse/ET-1205

[ET-1205] Fix ticket settings update breaking provider meta data.

---

readme.txt
src/Tribe/Editor.php
src/admin-views/editor/fieldset/price.php

[ET-1201] 
* We don't allow tickets with a $0 price for PayPal.
* Previously it was only showing errors for $0 price when the Event/Post was saved and not for new events.
* We have updated the `price` meta box template to show JS error for $0 price ticket on new events/posts.
* This applies for both TribeCommerce and TicketCommerce.
📷 screenshot(s): https://d.pr/i/6anTeX
[ET-1201]: https://theeventscalendar.atlassian.net/browse/ET-1201

[ET-1201] Disable free ticket for TicketCommerce and TribeCommerce

---

src/Tickets/Commerce/Gateways/PayPal/Client.php
src/Tickets/Commerce/Gateways/PayPal/WhoDat.php
src/Tickets/Commerce/Shortcodes/Success_Shortcode.php
src/resources/postcss/tickets-commerce/_all.pcss
src/resources/postcss/tickets-commerce/_success.pcss
src/views/v2/commerce/checkout/footer.php
src/views/v2/commerce/checkout/header/links/back.php
src/views/v2/commerce/checkout/header/title.php
src/views/v2/commerce/order/description.php
src/views/v2/commerce/order/details.php
src/views/v2/commerce/order/details/date.php
src/views/v2/commerce/order/details/email.php
src/views/v2/commerce/order/details/order-number.php
src/views/v2/commerce/order/details/payment-method.php
src/views/v2/commerce/order/details/total.php
src/views/v2/commerce/order/footer.php
src/views/v2/commerce/order/footer/links.php
src/views/v2/commerce/order/footer/links/back-home.php
src/views/v2/commerce/order/footer/links/browse-events.php
src/views/v2/commerce/order/header.php
src/views/v2/commerce/success.php

[ET-1177] 
- Adding templates and styles for the success/order page.
- Adding implementation so that we can demo the complete flow.
- I couldn't set up TC w/Paypal locally, so I ended up working on this like the old days, assuming, pushing to the sandbox, and updating a few items via sFTP.
**Things that we need to revisit**
- After strategy we need to check the naming here, to see if we keep with "success" for the shortcode or we do something more oriented to "order".
- Snapshot tests will come in a later PR.
- See if we can abstract order methods to use them directly (like for method, or total which is not including the currency symbol right now).
[ET-1177]: https://theeventscalendar.atlassian.net/browse/ET-1177

[ET-1177] Success/order page

---

src/Tickets/Commerce/Ticket.php

[ET-1214] 
* We were not using the proper action hook for saving ticket data that triggers the saving of Ticket Plus Meta.
🎥 screencast: https://d.pr/i/Z7lrJb
[ET-1214]: https://theeventscalendar.atlassian.net/browse/ET-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1214] AR Fields are not being saved with Ticket Commerce tickets.

---

readme.txt
src/Tribe/Tickets.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__1.php

[ETP-703] 
**This ticket is part of https://github.com/the-events-calendar/event-tickets-plus/pull/1271 and must be merged together to function.**
This PR incorporates a bunch of changes to the logic behind the scenes. As well  as adds a new function `allow_resending_email` into WooCommerce/EDD for cancelled or refunded orders.
This logic will most likely need to be added into Paypal as well.
Added a new filter  called `tribe_tickets_manual_attendee_allow_email_resend`. This filter will allow uses to alter the logic for allowing emails to send.
```function tec_customize_manual_attendee_email_by_status($allow_email, $ticket, $attendee)
{
//Logic here based off of $attendee['order_status'].
//For testing return either true (to allow) or false (to disable).
return false;
} …
```

[ETP-703] Cancelled Tickets checkbox not hiding from manual attendee editing

---

src/Tickets/Commerce/Gateways/PayPal/Hooks.php
src/Tickets/Commerce/Gateways/PayPal/Signup.php
src/Tickets/Commerce/Hooks.php

[ET-1287] 
Flushes the transients whenever the Sandbox option is toggled on/off.
[ET-1287]: https://theeventscalendar.atlassian.net/browse/ET-1287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Flush transients whens saving plugin options

---

src/resources/js/commerce/gateway/paypal/checkout.js

[TICKET_ID] 
Slack: https://lw.slack.com/archives/C01T9UJGE2U/p1635885014370700
* I was able to replicate the loader stuck issue once and saw the JS error that causes it. This PR resolves that error.

avoid JS errors on default `obj.showNotice` calls

---

src/Tickets/Commerce/Shortcodes/Success_Shortcode.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html

[ET-1314] 
- Do not enqueue the assets in rest context. This was causing the block editor to return an error
https://www.loom.com/share/b6e183d726ae4df8b3ee0c770d7b0876
Without the patch:
[ET-1314]: https://theeventscalendar.atlassian.net/browse/ET-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1314] TC > Success shortcode block editor

---

readme.txt
src/Tribe/Tickets_View.php

[ETP-763] 
We added the ability to filter by ticket id within the shortcodes for ETP. It required a tweak to the code in order to pass the tickets that needed to be filtered.
https://youtu.be/rBs2xo3QIxc
[ETP-763]: https://theeventscalendar.atlassian.net/browse/ETP-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-763] Add ability to filter ticket ids within the RSVP template block handler

---

src/Tribe/Editor/Blocks/Rsvp.php

[ETP-763] 
We found that in some instances, the `tribe` object wasn't being initialized until after the rsvp-ari js script. It causes errors when this happens. Adding `tribe-common` as a dependency will prevent this from happening.
https://i.imgur.com/BzRhnaY.png
[ETP-763]: https://theeventscalendar.atlassian.net/browse/ETP-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-763] RSVP ARI needs tribe common dependency

---

src/resources/postcss/tickets-tables.pcss

[ET-1349] 
Icons were being pushed out of bounds on mobile. This CSS fix allows them to wrap instead. It's ugly, but at least they can access them.
https://i.imgur.com/fnqsINb.png
[ET-1349]: https://theeventscalendar.atlassian.net/browse/ET-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1349] Duplicate Ticket - fix for wrapping icons on mobile

---

src/admin-views/editor/list-row.php

[ET-1349] 
This PR makes sure that we're only showing the duplicate ticket button on an admin page. CT is using the same templates as the admin views for tickets.
N/A
[ET-1349]: https://theeventscalendar.atlassian.net/browse/ET-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1349] Duplicate Ticket - remove duplicate button from CT

---

readme.txt
src/modules/blocks/ticket/index.js
src/modules/blocks/tickets/container/template.js
src/modules/blocks/tickets/index.js

Remove the `wp.editor.InnerBlocks` gutenberg component in the ticket block in favor of `wp.blockEditor.InnerBlocks` which was deprecated since version 5.3. 
Ticket : [[ET-1367]](https://theeventscalendar.atlassian.net/browse/ET-1367)
[ET-1367]: https://theeventscalendar.atlassian.net/browse/ET-1367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://www.loom.com/share/47487d027fce416789d024163ac58ddc

Remove deprecated wp.editor.InnerBlocks component in favor of wp.blockEditor.InnerBlocks [ET-1367]

---

package-lock.json
package.json

Fixes failing tests on the bucket branch i.e. [bucket/wp-inner-block-component-deprecation](https://github.com/the-events-calendar/event-tickets/tree/bucket/wp-inner-block-component-deprecation)
Note : I'm bumping up the version of react we use in order to fix the failing tests. It turns out that the tests were failing due to a bug in @16.3.0 that was fixed in @16.3.1.
Original Ticket : https://theeventscalendar.atlassian.net/browse/ET-1367

Fix failing tests on the bucket branch `bucket/wp-inner-block-component-deprecation`

---

src/Tickets/Commerce/Gateways/Stripe/Settings.php

[ET-1400] 
- [Stripe's documentation](https://stripe.com/docs/payments/payment-methods/integration-options) is wrong. They're listing that klarna is available for USD, but when testing we faced the following error: 
N/A
[ET-1400]: https://theeventscalendar.atlassian.net/browse/ET-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1400] Remove usd from klarna

---

readme.txt
src/Tickets/Commerce/Admin/Notices.php

[ET-1379] 
- Removing the notice now that we have implemented the purchaser info functionality for anonymous purchases (ET-1378)
- N/A
[ET-1379]: https://theeventscalendar.atlassian.net/browse/ET-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1379] Remove anonymous purchase notice after ET-1378 was implemented.

---

tests/wpunit/Tribe/Tickets/Commerce/PayPal/Main/Inventory/UTCTest.php
tests/wpunit/Tribe/Tickets/Main/Post/UTCTest.php

Some ET tests ended up broken after https://github.com/the-events-calendar/event-tickets/commit/7e594102154c5f112549d159aa5c4392c0cc7517 so we're skipping them and @bordoni will fix them later.

skip faulty tests due to an change in tribe-common

---

src/admin-views/settings/tickets-commerce/stripe/connect/active.php
src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-currency.php
src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-status.php
src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss

- N/A 
- After meeting with David he liked the idea to implement the stripe currency info section on the active connection box. https://www.figma.com/file/TvIXoUEJAGb0AptZI260UO/TicketsCommerce?node-id=1823%3A255
https://user-images.githubusercontent.com/252415/153714026-5be1057b-2eeb-46be-9806-fd6e1a4cd6bd.mov

Implement the stripe currency section with messaging.

---

src/Tickets/Commerce/Gateways/Stripe/Settings.php

[ET-1408] 
We do not want to show the non-connection settings until they are connected to Stripe.
https://i.imgur.com/f1kaIey.png
[ET-1408]: https://theeventscalendar.atlassian.net/browse/ET-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1408] Stripe: Hide Settings if Not Connected

---

src/resources/postcss/tickets-commerce/_checkout.pcss

N/A 
There were some overrides added into the checkout styling for the Twenty Twenty theme that removed the spacing below some of the section headers on the checkout page. This adds them back in for one specific heading.
N/A

Fix for Checkout Headers in Twenty Twenty theme

---

src/Tickets/Commerce/Payments_Tab.php
src/admin-views/settings/tickets-commerce/gateways/status.php

N/A 
I saw that there were some changes to how `is_active` and `is_connected` behave. To keep consistency, we need to use `is_connected` when determining whether or not a gateway can be enabled or not.
N/A

Fix: Use `is_connected()` instead of `is_active()`

---

src/Tickets/Commerce/Module.php
src/Tickets/Commerce/Payments_Tab.php
src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
src/views/v2/commerce/checkout/footer/gateway-error.php
src/views/v2/commerce/checkout/gateways.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Footer/GatewayErrorTest.php

[ET-1418] 
* `gateways_enabled` logic was flawed as it was only counting the enabled gateways irrespective of the individual gateway.
* We had the generic `Checkout Unavailable` notice already in place but it was not showing for the following case:
If you have Stripe _Connected_ but _not_ _enabled_ and PayPal _not connected_ but _enabled_ then the `gateways_enabled` was returning `1` which should have been 0.
* So, I renamed the `get_gateways_connected` method to `get_available_gateways` for clarity and modified the logic to check for `is_enabled` as well.
* Remove the redundant `gateways_enabled` argument.
[ET-1418]: https://theeventscalendar.atlassian.net/browse/ET-1418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1418] TicketsCommerce Checkout unavailable notice logic fixed for 0 available gateways.

---

readme.txt
src/Tickets/Commerce/Gateways/PayPal/Assets.php
src/Tickets/Commerce/Gateways/Stripe/Assets.php
src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
src/Tribe/Shortcodes/Tribe_Tickets_Checkout.php

[ET-1426] 
It was found that the PayPal and Stripe JS assets were loading on the checkout page even when they were disabled or disconnected. It was found that loading assets using `tribe_asset_enqueue_group()` was the culprit and was bypassing the `conditionals` parameter. Using an action filter and adding an `is_enabled()` check in the `conditionals` function solved the issue. 
https://i.imgur.com/F5B5rnA.png
[ET-1426]: https://theeventscalendar.atlassian.net/browse/ET-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1426] Tickets Commerce - Fix JS Errors on Checkout due to Assets Loading Improperly

---

readme.txt
src/Tickets/Commerce/Gateways/Stripe/Payment_Intent.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php

[ET-1474] 
Before discarding a PI validation as an error, check that it was indeed created in ET so we don't throw errors for PIs created in other applications.
[ET-1474]: https://theeventscalendar.atlassian.net/browse/ET-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Validate webhook transactions before erroring out

---

readme.txt
src/Tribe/Service_Providers/Customizer.php

[ET-1437]
[ET-1453]
The `@keyframes tribe-common-c-loader-bounce` animation doesn't animate color, [it animates opacity](https://github.com/the-events-calendar/tribe-common/blob/master/src/resources/postcss/components/full/_loader.pcss#L39).
This was breaking the loader animation in instances where it was triggered. (FSE compatibility is in flux and triggered it)
There is also some question in my mind about the way this is implemented - there's no v2 check although the comments appear to indicate there should be.
[ET-1437]: https://theeventscalendar.atlassian.net/browse/ET-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-1453]: https://theeventscalendar.atlassian.net/browse/ET-1453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …

Don't change the animation via customizer, change the dot color.

---

readme.txt
src/views/blocks/attendees/view-link.php
src/views/tickets/view-link.php

[ETP-775] 
When using the `[tribe_tickets]` shortcode, we want to hide the 'view link'. We're also adding a `tec_tickets_hide_view_link` filter to allow users to override this decision, too, in case they want it back.
This ticket requires work both in ET and ETP. The ETP PR is here:
https://github.com/the-events-calendar/event-tickets-plus/pull/1323
https://i.imgur.com/KnxpBeM.png
[ETP-775]: https://theeventscalendar.atlassian.net/browse/ETP-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-775] Hide View Link in Tickets Shortcode

---

readme.txt

[ET-1459] 
We want to have all links point to our shortened `evnt.is` links. With exception to the link to the `License URI` which Wordpress.org uses.
N/A
[ET-1459]: https://theeventscalendar.atlassian.net/browse/ET-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1459] Update Links in `readme.txt` File

---

src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php

[ET-1474] 
[ET-1474]: https://theeventscalendar.atlassian.net/browse/ET-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1474] Make Stripe webhooks to be responded for TC orders only

---

readme.txt
src/resources/postcss/tickets/_block-footer.pcss

[ET-1435] 
When using the Genesis theme, the "Get Tickets" button text is too dark when it is disabled.
Before: https://d.pr/i/QhTAas
After: https://i.imgur.com/KsbIVtZ.png
[ET-1435]: https://theeventscalendar.atlassian.net/browse/ET-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1435] Theme compatibility tweak with Genesis

---

readme.txt
src/modules/data/blocks/rsvp/thunks.js

[ET-1478] 
When using quotes or apostrophes in the title of an RSVP, the block editor is displaying the encoded characters instead of the raw characters.
https://i.imgur.com/HnNSCIs.png
[ET-1478]: https://theeventscalendar.atlassian.net/browse/ET-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1478] Block Editor - RSVP - Title Encoding Issue

---

src/resources/postcss/tickets-report.pcss

[ET-1492] 
During a demo of the upsell feature, it was found that the "Deleted Attendees" column spacing was a bit off. This PR fixes that.
Issue shown here: https://i.imgur.com/AqTFHfX.png

[ET-1492] Fix margin for deleted attendees

---

readme.txt
src/Tribe/Attendees.php

[ET-1502] 
There was a fatal error being thrown when trying to export attendees in PHP 8. This PR fixes it by using `array_key_exists()` instead of `isset()`.
N/A
[ET-1502]: https://theeventscalendar.atlassian.net/browse/ET-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1502] Fix Fatal Error When Exporting Attendees in PHP 8

---

readme.txt
src/Tickets/Commerce/Utils/Value.php

[ET-1504] 
Quick and simple typo fix. Missing `=`.
N/A
[ET-1504]: https://theeventscalendar.atlassian.net/browse/ET-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1504] Fix Typo in Value Utility for Tickets Commerce

---

src/resources/postcss/tickets-report.pcss

[ET-1492] 
There was a large space below the top section for some events. It was found to be some CSS that WordPress had put into their "Welcome Page" code and it was conflicting with the attendees page. This PR unsets that `min-height` setting for the attendees page.
N/A

Remove Minimum Height on Attendees Page

---

readme.txt
src/Tickets/Commerce/Gateways/PayPal/Assets.php

[ET-1520] 
* PayPal's signup partner JS asset was getting loaded on every page of the admin.
📷 screenshot: https://d.pr/i/vrKRq2
[ET-1520]: https://theeventscalendar.atlassian.net/browse/ET-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1520] Fix - Avoid loading partner JS everywhere on WP Admin

---

changelog.txt
readme.txt
src/Tickets/Commerce/Admin/Notices.php

[ET-1521] 
- Adding a notice that they need to use their permalinks setting to something different than "Plain" in order to use Tickets Commerce.
- Updating conditionals to yoda.
- Adding link to `Tickets > Settings > Payments` in other notices.
- Sync `changelog.txt` and add missing version, and trim versions from `readme.txt`
https://user-images.githubusercontent.com/252415/170278165-737068df-076f-4760-8de0-987fc8c44658.mov
[ET-1521]: https://theeventscalendar.atlassian.net/browse/ET-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1521] Settings > Add permalinks configuration notice

---

src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
src/resources/postcss/tickets-commerce/admin/gateway/stripe/webhooks.pcss

[ET-1497] 
* Avoid saving the webhook secret signing key if validation failed.
* Add colors to dashicons to provide better UX.
🎥 screencast(s): https://d.pr/v/tWrtCT
[ET-1497]: https://theeventscalendar.atlassian.net/browse/ET-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1497] Fix saving webhook secret on failed validation.

---

readme.txt
src/admin-views/editor/total-capacity.php

[ET-1535] 
ET is referencing a template that only exists in ET+. ET+ is also referencing that same template. This causes the template to appear twice when ET+ is activated.
[ET-1535]: https://theeventscalendar.atlassian.net/browse/ET-1535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1535] Remove Duplicate Total Event Capacity

---

readme.txt
src/Tickets/Commerce/Settings.php
src/Tickets/Commerce/Utils/Currency.php

[ET-1534] 
Allow users to choose where they want to currency symbol to show on their site while using Tickets Commerce.
[ET-1534]: https://theeventscalendar.atlassian.net/browse/ET-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1534] Tickets Commerce - Add Currency Position Setting

---

readme.txt
src/Tribe/Tickets.php

[ET-1524] 
The price block doesn't "play nice" with ET when you enter your own value into it. It takes the value you enter, mixes it in with other ticket values, then creates a string based on all values. This fix allows you to enter in a value into the price block to override the dynamic price that is created based on ticket values alone.
https://www.screencast.com/t/ldO2PKamtI7p
[ET-1524]: https://theeventscalendar.atlassian.net/browse/ET-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1524] Let Price Block Value Override Ticket Range String

---

readme.txt
src/Tickets/Commerce/Assets.php

[ET-1531] 
When TEC is deactivated and ET is used as a standalone plugin, we noticed that the dropdowns on the TC settings pages weren't using SelectWoo. We need to load these as dependencies in ET and not just TEC.
Before fix: https://www.screencast.com/t/DC507CcDRKO
After fix: https://www.screencast.com/t/8v2SOZFtGb
[ET-1531]: https://theeventscalendar.atlassian.net/browse/ET-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1531] Tickets Commerce - SelectWoo Asset Missing When TEC is Deactivated

---

src/Tribe/Commerce/Currency.php
src/template-tags/commerce.php

[ET-1534] 
It was found, with the new currency position setting, that the tickets block wasn't honoring that position and this was due to the API not returning the position information correctly. Instead, it was always returning 'prefix' and showing the currency symbol before the value. This PR resolves that issue.
[ET-1534]: https://theeventscalendar.atlassian.net/browse/ET-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1534] Fix Currency Position in API

---

src/Tribe/Tickets_Handler.php

Warning on the CE Submit page when ET is active:
```
Warning: array_merge(): Expected parameter 2 to be an array, string given in /var/www/public/relieved-leopard/wp-content/plugins/event-tickets/src/Tribe/Tickets_Handler.php on line 522
```

Make sure before array_merge we cast as array both ends of the merge

---

readme.txt
src/Tribe/Editor/Template/Overwrite.php

[ET-1544] 
When TEC and ET installed and activated and the blocks editor is deactivated in TEC, Tickets and RSVP blocks that are added into Pages or Posts appear in the wrong place. Using `has_blocks()` on non-Event post types fixes the problem.
https://drive.google.com/file/d/1737NkxDyV5iNwOq0X2IKWCl5mGjPZ6b1/view?usp=sharing
[ET-1544]: https://theeventscalendar.atlassian.net/browse/ET-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1544] ET Blocks Appear in Wrong Place in Non-Event Posts

---

src/Tribe/Tickets.php

[ET-1544] 
QA found that after a previous fix, the RSVP block was showing twice. Once in the correct place and again after the content. I found that there were checks that are relying on the block editor setting in events, which is unnecessary in the case of anything other than events.
https://share.getcloudapp.com/7Ku69NLZ
[ET-1544]: https://theeventscalendar.atlassian.net/browse/ET-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1544] RSVP Appears Twice on Front End

---

tests/_bootstrap.php
tests/wpunit/Tribe/Tickets/Event_RepositoryTest.php
tests/wpunit/Tribe/Tickets/Template_Tags/GetPostTotalsTest.php
tests/wpunit/Tribe/Tickets/Template_Tags/GlobalStockTest.php

[ET-1581] 
* The newly introduced Custom Tables query needed to be disabled for the test suites, otherwise it overrides the SQL queries for `tribe_events` causing the results to fail.
[ET-1581]: https://theeventscalendar.atlassian.net/browse/ET-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1581] Fix conflict with Custom Table query overriding ET queries for `tribe_events`

---

readme.txt
src/Tribe/REST/V1/Main.php

[ET-1580] 
- Add `attendance` information to the events REST API endpoint.
[ET-1580]: https://theeventscalendar.atlassian.net/browse/ET-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1580] Add `attendance` information to the `events` REST API endpoint.

---

readme.txt
src/Tickets/Custom_Tables/V1/Provider.php

[ET-1582]
in PHP8, type-hinted params will fail when passed null unless you specifically make them nullable.
Also corrected a couple typos in a docblock and a (private) function name.
[ET-1582]: https://theeventscalendar.atlassian.net/browse/ET-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix nullable param in function signature.

---

.github/workflows/tests-php.yml
readme.txt
src/Tribe/Repositories/Traits/Post_Tickets.php

[ET-1567] 
* Fixes the query issue where making a query for `ticketed` events were not showing Events with TicketsComommerce tickets.
🎥 screencast(s): https://d.pr/v/aQmAkg
[ET-1567]: https://theeventscalendar.atlassian.net/browse/ET-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1567] Fix - TicketsCommerce ticketed events not showing up for Events ORM query.

---

readme.txt
src/Tickets/Commerce/Module.php
src/Tribe/Attendee_Repository.php
src/Tribe/REST/V1/Endpoints/Single_Attendee.php
tests/wpunit/Tribe/Tickets/ORM/Attendees/RSVP/CreateTest.php
tests/wpunit/Tribe/Tickets/ORM/Attendees/RSVP/UpdateTest.php

[ET-1588] 
* Added support for `check_in` data update within Attendees ORM.
* Added support for `check_in` data update within TicketsCommerce ( `tec_tc_attendees` ) ORM.
* Added Create and Update Test for newly added argument for RSVP ORM.
* Added REST API documentation for the `check_in` param.
🎥 screencast(s): https://d.pr/v/v2KGiK
[ET-1588]: https://theeventscalendar.atlassian.net/browse/ET-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1588] Enhancement - Check IN or Check out attendee using attendee REST API endpoints.

---

readme.txt
src/Tribe/Attendee_Repository.php
src/Tribe/REST/V1/Attendee_Repository.php
src/Tribe/REST/V1/Endpoints/Attendee_Archive.php

[ET-1591] 
* orderby -> title param used to search against `post_title` by default but that data is not uniform in all attendee post types.
* We have now pointed the `title` param to search against `full_name` meta which is available within all attendees.
* Added search by Name support where if `name` parameter is set then it should look against `holder_name` of the attendee.
* Added search by Email support where if `email` parameter is set then it should look against `holder_email` of the attendee.
🎥 screencast(s):
* Orderby --> https://recordit.co/G1g9mu3rTB
* Search --> https://recordit.co/rxQFXNnaDu
[ET-1591]: https://theeventscalendar.atlassian.net/browse/ET-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1591] Spotfix - Attendee REST API support for orderby `title` should search by full_name data

---

src/Tickets/Commerce/Module.php
src/Tribe/Attendee_Repository.php

[ET-1588] 
- We have added the possibility to check in attendees via the REST endpoint, but it wasn't completely handling the checkin/uncheckin (not removing metadata for example), and that was causing problems for the ET+ APP.
[ET-1588]: https://theeventscalendar.atlassian.net/browse/ET-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1588] Properly handle the check-in and uncheckin.

---

readme.txt
src/Tribe/REST/V1/Endpoints/Ticket_Archive.php
src/Tribe/Tickets_Handler.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/CapacityTest.php

[ETP-815] 
* Shared capacity sync error was causing the lowest capacity to be applied among all the shared capacity tickets irrespective of the own capped capacities.
🎥 screencast(s): https://d.pr/v/07xd6J
[ETP-815]: https://theeventscalendar.atlassian.net/browse/ETP-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-815] Fixed shared cap sync causing tickets to use lower capacity all the time.

---

readme.txt
src/Tickets/Commerce/Gateways/PayPal/Client.php
src/Tickets/Commerce/Gateways/PayPal/Merchant.php

[ET-1615] 
* As per PayPal recommendation we can remove the optional `locale` param to reduce JS SDK issues with this: https://d.pr/i/zRT5LX
* We have kept the `locale` method and added a new validation method in case anyone wants to use the `locale` param with  the `tec_tickets_commerce_gateway_paypal_js_sdk_url` filter.
[ET-1615]: https://theeventscalendar.atlassian.net/browse/ET-1615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1615] - Removed the locale param for PayPal JS SDK to avoid invalid local errors.

---

readme.txt
src/Tickets/Commerce/Cart.php

[ET-1629] 
* The `httponly` flag was not set to `true` while creating cookies, which causes issues in hosting environments where non `httponly` cookies are not saved resulting in an invalid cart.
Before: https://d.pr/i/MQQ1Xh
After: https://d.pr/i/CVCCGH
[ET-1629]: https://theeventscalendar.atlassian.net/browse/ET-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1629] Fix - Tickets Commerce cart cookie params missing `httponly` flag.

---

readme.txt
src/Tickets/Admin/Upsell.php

[CT-67] 
This change introduces the `is_admin()` method into `maybe_show_capacity_arf` and `maybe_show_manual_attendees`. Before this change the upsell was showing on Community Tickets. 
Before Change -
[CT-67]: https://theeventscalendar.atlassian.net/browse/CT-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CT-67] Remove upsell outside of dashboard

---

src/Tickets/Emails/Hooks.php

[ET-1547] 
- Returning early if the AJAX request is not for the email preview modal (if not it messes up with manual attendees)
[ET-1547]: https://theeventscalendar.atlassian.net/browse/ET-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1547] Return the content if is not requesting the email preview.

---

src/Tickets/Commerce/Cart.php
src/Tickets/Commerce/Cart/Unmanaged_Cart.php

[ETP-851] 
* We have updated the `Unmanaged_Cart::clear` method by setting the cart items to an empty array for consistency.
* But doing that broke cart adding process as we previously had the `clear_cart` method used within the `save` method.
* Removing the `clear_cart` call from the saving process fixes the issue.
* All tests regarding Cart are still passing along with the new tests.
[ETP-851]: https://theeventscalendar.atlassian.net/browse/ETP-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix - removed cart clear from cart save process to avoid empty cart.

---

src/Tickets/Emails/Admin/Preview_Modal.php
src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Failed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/Ticket.php
src/Tickets/Emails/Email_Abstract.php
src/Tickets/Emails/Email_Template.php
src/resources/js/admin/tickets-emails.js

[ET-1547] 
- Adding logic to have preview per email, rather than relying on just one email all the time.
- Inverting `get_html` parameters of the email template class, to make it consistent with the generic template class.
- Adding an abstract method to have preview data per email.
https://user-images.githubusercontent.com/252415/225935583-2886c8c8-f654-40fe-a634-e3dd6eef7d32.mov
[ET-1547]: https://theeventscalendar.atlassian.net/browse/ET-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1547] Tickets Emails: Preview per email

---

readme.txt
src/modules/elements/label-with-tooltip/__tests__/__snapshots__/element.test.js.snap
src/modules/elements/label-with-tooltip/element.js

[1674](https://theeventscalendar.atlassian.net/browse/ET-1674)
When you try to hover over the tooltip component in either of the RSVP or Tickets blocks, it crashes! I have simply refactored the Tooltip component directly into the LabelWithToolTip component to fix this.
[Screenshot1](https://drive.google.com/file/d/1jYD72N_ui0G1tTM2QBl4SM-UFKGT6DY8/view?usp=share_link)
[Screenshot2](https://drive.google.com/file/d/1arlDrHYQmYPSmoWbbH_eMPC6cwRWIRJI/view?usp=share_link)
[Screenshot3](https://drive.google.com/file/d/15Ni8nqy4f48c1vP8VTi_8ufu1VygAXKD/view?usp=share_link)
[Screencast](https://drive.google.com/file/d/114q7pAfa0h4LdEWDlNtO27ourP3v-IFF/view?usp=share_link)
- [] My code is tested. 
- [] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineer …

[ET-1674] Fix - Tickets/RSVP blocks crashing when hovering over their tooltips.

---

readme.txt
src/Tickets/Commerce/Attendee.php
tests/commerce_integration/TEC/Tickets/Attendees_ListTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/EventStockTest.php

[ET-1590] 
* Attendees created with TicketsCommerce didn't have the `post_title` data added.
* This caused the Attendee Table search to not work as expected.
* This will fix the Attendee Table search by title for new attendees.
[ET-1590]: https://theeventscalendar.atlassian.net/browse/ET-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1590] Enhancement - Add `post_title` data for created attendees using Tickets Commerce.

---

src/Tickets/Emails/Email_Abstract.php

[ET-1636] 
- Use the `get_placeholders` method for the format string method, so that we make use of the filtered value.
^ Test with the TEC integration.
[ET-1636]: https://theeventscalendar.atlassian.net/browse/ET-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tickets Emails > Use `get_placeholders` on the format string method to use filtered values

---

src/views/v2/emails/template-parts/header/head/styles.php

While testing the email system, we found that Gmail was stripping out all the styling. After researching, we found that Gmail is super strict about spacing and typos in the CSS and it will strip out any CSS that appears after any wrongly formatted styling code.
This PR contains some tweaks to the original styling that fixed the styling issues we were seeing in Gmail.
Gmail Before:
Gmail After:

Tickets Emails: CSS Tweaks for Gmail

---

readme.txt
src/Tickets/Commerce/Status/Pending.php
src/Tribe/Tickets.php

[1579](https://theeventscalendar.atlassian.net/browse/ET-1579)
Users are currently able to filter the unavailability message for a collection of tickets using the **event_tickets_unvailable_message** filter but unfortunately, this is not possible for Users using the Tickets Commerce provider. I have added logic so that those filters apply when TC is used.
- [] My code is tested. 
- [] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-1579] Fix - Ensure TC unavailable messages are filtered using event_tickets_unavailable_message filter.

---

readme.txt
src/Tickets/Commerce/Models/Order_Model.php

Turning the `tickets` element of the `Order_Model` into a `Lazy_Collection` for performance reasons.
Additionally, adding some checks to protect against unexpected values and return types.
@codingmusician - this is in draft mode because I am not sure how/where to test this. This code is the gist of what we'll probably want based on the error that was reported. I'll let you take it from here!
:ticket: [GTRIA-1001](https://theeventscalendar.atlassian.net/browse/GTRIA-1001)
[GTRIA-1001]: https://theeventscalendar.atlassian.net/browse/GTRIA-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make $tickets a Lazy_Collection in the Order_Model

---

readme.txt
src/Tickets/Admin/Glance_Items.php
src/Tickets/Admin/Provider.php

[ET-1698] 
* Make use of WP Schedule Events to calculate the attendee count in the background and display it only from saved transients to avoid loading the dashboard for heavy queries.
[ET-1698]: https://theeventscalendar.atlassian.net/browse/ET-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1698] Fix - Glance items attendee count performance issue.

---

src/Tickets/Emails/Email/RSVP.php
src/Tickets/Emails/Email/Ticket.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_rsvp_without_using_ticket_settings__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php

N/A
We're removing the 'plural' fields from both RSVP and Ticket emails. We're also setting the default subject and heading to use the plural word for tickets.
- `TE-5808` - https://share.cleanshot.com/w4P1m3PP
Demo of fix: https://www.loom.com/share/61fefdcccc7548baacdb87cb0cd20153

Tickets Emails: Remove Plural Settings and Set New Defaults

---

src/Tickets/Commerce/Gateways/Stripe/Gateway.php
src/Tickets/Emails/Admin/Preview_Modal.php
src/Tribe/RSVP.php
src/resources/js/admin/tickets-emails.js
tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set ari__1.php

[TICKET_ID] 
* Added a failsafe to avoid showing notices on RSVP submissions. [ET-1612]
* Solved showing notices on Gateway Order ID link generation for Stripe when order status is not valid.
* Add Live Preview handler for Attendee Registration Fields.
[ET-1612]: https://theeventscalendar.atlassian.net/browse/ET-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix - Misc php notices fixed.

---

readme.txt
src/Tribe/Editor/Warnings.php
src/resources/js/tickets.js
tests/wpunit/Tribe/Editor/WarningsTest.php
tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with all values filled__1.php
tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank additionalClasses__1.php
tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank condition__1.php
tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank depends_on__1.php
tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank message__1.php
tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank type__1.php

[ET-1696] 
The original ticket outlined that the warning "no providers displayed" wasn't showing. Upon inspection I found that the Jquery code found within `tickets.js` was hiding anything with the class `.ticket-editor-notice`. The issue was that both notifications that we display have this class. 
I have gone ahead and added an `$additionalClass` parameters to the function so that we can further pinpoint which warning message we want to target.
Displaying the proper message - 
Showing the additional classes added - 
Showing the messages when "Add More Events" for recurring events are clicked.
[ET-1696]: https://theeventscalendar.atlassian.net/browse/ET-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1696] 'No provider message' does not display properly when providers are disabled.

---

src/Tickets/Emails/Admin/Preview_Modal.php

[TE-31DB] 
* Live preview was not showing the adjusted contrast Text Color, but in the real email it shows up. Now the live preview matches with real email.

[TE-31DB] Fix - Apply contrast text color for live preview.

---

src/Tickets/Emails/Email/RSVP.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

TE-3389 
All of the RSVP settings were being used when the email was sent even when they should have been using the Ticket settings. I found that we weren't setting the context correctly.
https://www.loom.com/share/a170981e137440cb8cb82f55750afcd0

Tickets Emails: RSVP should use Ticket context when applicable

---

src/views/emails/rsvp-not-going/body.php
src/views/emails/template-parts/header/head/styles.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

TE-DECF 
The `RSVP Not Going` email got overlooked when working on this issue before. We just needed to add some padding below the 'Not Going' text, which appears above the Additional content.
Before:
After:

Tickets Emails Issue TE-DECF: Add Space Below Not Going Text

---

src/Tickets/Emails/Admin/Preview_Data.php
src/Tickets/Emails/Admin/Preview_Modal.php
src/Tickets/Emails/Email_Abstract.php

Feedback from David from DQA, led me to find this problem.
* `{site_address}` = `example.com/my-site`
* `{site_url}` = `https://example.com/my-site`

Improvements to site_address and site_url placeholders for Emails.

---

src/Tickets/Emails/Email/Completed_Order.php
src/Tickets/Emails/Email/Purchase_Receipt.php
src/Tickets/Emails/Email/RSVP_Not_Going.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php

TE-7ACB 
Only Ticket and RSVP had the additional content fields set to large. This PR sets them for the other 3 emails.
Before:
After:

TE-7ACB Tickets Emails: Set Additional Content Field Sizes to Large

---

readme.txt
src/Tribe/Cache/Abstract_Cache.php
tests/wpunit/Tribe/Cache/AbstractCacheTest.php

[ET-1774] 
The original issue was that the count on the "Ticketed" tab for events was incorrect. It was only looking for the old format of the meta_key. Since tickets commerce introduced a new format we add that to the query. 
[artifact-1774.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/15bc8580-8de4-4a92-87c8-b7b98872529b)
[ET-1774]: https://theeventscalendar.atlassian.net/browse/ET-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1774] Ticketed events don't show up under Ticketed tab in Dashboard Events List

---

readme.txt
src/Tickets/Integrations/Duplicate_Post.php
src/Tickets/Integrations/Integration_Abstract.php
src/Tickets/Integrations/Plugins/Yoast_Duplicate_Post/Duplicate_Post.php
src/Tickets/Integrations/Provider.php
src/Tickets/Provider.php
src/Tribe/Tickets.php

[ET-760] 
This pull request aims to enhance the existing functionality provided by the `Yoast Duplicate Post` plugin. In order to achieve this, we have made modifications to the `dp_duplicate_post` and `dp_duplicate_page hooks`, allowing for the tickets to be cloned into a new post. Additionally, we have introduced a new method called `clone_ticket_to_new_post`, which is essentially a modified version of the existing `duplicate_ticket` method.
[artifact-760.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/19757582-5773-4086-920b-a23cf55be56a)
[ET-760]: https://theeventscalendar.atlassian.net/browse/ET-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-760] Add Duplicate Post logic into ET/ET+

---

src/Tickets/Integrations/Plugins/Yoast_Duplicate_Post/Duplicate_Post.php

[ET-760]
During testing an issue was found when the event had a ticket and an RSVP. I moved the provider logic into the foreach so that when this scenario occurs it grabs the correct provider to clone the tickets.
Original PR - https://github.com/the-events-calendar/event-tickets/pull/2717
[ET-760]: https://theeventscalendar.atlassian.net/browse/ET-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-760] Provider issue with RSVP and Ticket

---

readme.txt
src/Tickets/Integrations/Provider.php
src/Tickets/Integrations/Themes/Divi/Provider.php

[ETP-864] 
When using the Divi theme on the Attendee registration page with `Dynamic CSS` and `Static CSS File Generation` enabled the page wasn't loading stylesheets correctly. I was able to find specific filters that disable all of the functionality that was breaking the page. 
With everything fixed we also had duplicate page titles on the page. So I disabled the one that displays via Divi by making it an empty string so that ours is the only heading on the page.
[artifact-etp-864.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/b81a4daf-b5be-4864-ba29-c513275c6910)
[ETP-864]: https://theeventscalendar.atlassian.net/browse/ETP-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETP-864] Divi broken on AR page

---

src/Tribe/Events/Views/V2/Models/Tickets.php

[ET-1830] 
Using PHP 7.4 these errors are showing up:
```[02-Aug-2023 14:31:47 UTC] PHP Fatal error:  Uncaught TypeError: Tribe\Tickets\Events\Views\V2\Models\Tickets::__serialize() must return an array in /Users/rafsuntaskin/Local Sites/et-local/app/public/wp-includes/class-wp-object-cache.php:641
Stack trace:
#0 /Users/rafsuntaskin/Local Sites/et-local/app/public/wp-includes/class-wp-object-cache.php(641): serialize(Array)
#1 /Users/rafsuntaskin/Local Sites/et-local/app/public/wp-content/plugins/debug-bar/panels/class-debug-bar-object-cache.php(18): WP_Object_Cache->stats()
#2 /Users/rafsuntaskin/Local Sites/et-local/app/public/wp-content/plugins/debug-bar/debug-bar.php(377): Debug_Bar_Object_Cache->render()
#3 /Users/rafsuntaskin/Local …
```

[ET-1830] Resolve fatal from __serialization methods

---

readme.txt
src/Tickets/Emails/Admin/Settings.php

[ET-1777] 
Sender name was being escaped twice, causing characters that were already entitized to be double-entitized which caused some crazy output in emails and attached event invites.
[ET-1777]: https://theeventscalendar.atlassian.net/browse/ET-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1777] Tickets Emails: Sender Name Being Double-Escaped

---

readme.txt
src/Tickets/Commerce/Gateways/PayPal/REST/Order_Endpoint.php
tests/wpunit/Tickets/Commerce/Gateways/PayPal/REST/OrderEndpointTest.php

[ET-1865] 
PayPal has a max Item Name length of 127 characters. https://developer.paypal.com/docs/api/orders/v2/#definition-item This change adds the logic to truncate the logic when it's above 127 characters  and adds the ellipses. 
[ET-1865]: https://theeventscalendar.atlassian.net/browse/ET-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1865] PayPal - Ticket names over 125 characters will now be truncated when sent to PayPal

---

readme.txt
src/resources/postcss/tickets-commerce/_checkout.pcss

[ET-1815] 
Some theme editors override the background styles for buttons. Some of our buttons shouldn't be overridden. This PR fixes a few of those that were found.
[ET-1815]: https://theeventscalendar.atlassian.net/browse/ET-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1815] buttons styling overrides

---

.github/workflows/tests-php-ct1.yml
codeception.dist.yml
composer.json
composer.lock
readme.txt
src/Tickets/Provider.php
src/Tribe/Admin/Move_Tickets.php
tests/_support/Traits/CT1/CT1_Fixtures.php
tests/ct1_integration.suite.dist.yml
tests/ct1_integration/Tribe/Tickets/Admin/Move_TicketsTest.php
tests/ct1_integration/_bootstrap.php

[ET-1862](https://theeventscalendar.atlassian.net/browse/ET-1862) 
This PR restores the functionality to allow moving Attendees between any Single Event on the site, whether the Single Event belongs, in the context of CT1, to a Series or not.
A note on the fix: the exclusion of recurring events was previously done incorrectly by leveraging the support in ECP for the `post__not_in_series` query var.
That would exclude not just Recurring Events (part of a Series by default) but Single Events part of a Series as well. Herein lies the issue.
In the PR I'm setting the `post__not_recurring` query var, hinting at its future support; it's currently not part of ECP code.
Since there is not `post__not_recurring` support to leverage, and to deal with an ECP support that might come later than the …

Restore possibility to move Tickets/Attendees to all Single Events

---

readme.txt
src/Tickets/Commerce/Module.php
src/Tickets/Commerce/Provider.php
src/Tribe/Commerce/PayPal/Main.php
src/Tribe/RSVP.php
src/Tribe/Service_Provider.php
src/Tribe/Ticket_Object.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/CapacityTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/EventStockTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/UpdateTest.php
tests/ct1_integration/Attendees_TableTest.php
tests/ct1_integration/MetaboxTest.php
tests/ct1_integration/_bootstrap.php
tests/integration/RSVP_Tickets_Test.php
tests/wpunit/Tribe/Tickets/Attendees_TableTest.php
tests/wpunit/Tribe/Tickets/__snapshots__/Attendees_TableTest__test_display__0.snapshot.html

[ET-1887](https://theeventscalendar.atlassian.net/browse/ET-1887)
This PR builds on the [Commmon PR](https://github.com/the-events-calendar/tribe-common/pull/1980) to add the Ticket, Attendee and Order post types managed by Event Tickets to the list of post types that should trigger a cache invalidation.
* [Screencast explaining the issue](https://share.cleanshot.com/JV1fySbn)
* Tests - there were already tests covering the cache invalidation issue or, rather, working around it invalidating cache to work. I've removed those work-arounds to make sure correct cache invalidation is correctly tested along with other functionality.
[ET-1887]: https://theeventscalendar.atlassian.net/browse/ET-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Invalidate Ticket Object caches correctly

---

readme.txt
src/Tickets/Commerce/Models/Order_Model.php
src/Tickets/Emails/Admin/Preview_Data.php
src/views/emails/template-parts/body/order/payment-info.php

[ET-1875] 
We were checking the status on a translatable string, which causes the status within some of the order emails to appear incorrectly. This fix adds a `status_slug` param to the order which isn't translatable and changes the logic to use the slug, instead.
https://www.loom.com/share/c65d920af6f44594a35e9df4c86d05a9?sid=3dffeda2-298a-4069-86f1-8c455e712b25
[ET-1875]: https://theeventscalendar.atlassian.net/browse/ET-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1875] Tickets Emails: Fix Status showing incorrectly in other languages

---

src/modules/elements/attendees-registration/style.pcss

When building the plugin for testing it was failing at creating the proper CSS because of the error 
```
ERROR in ./src/modules/elements/attendees-registration/style.pcss (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./src/modules/elements/attendees-registration/style.pcss)
Module build failed (from ./node_modules/postcss-loader/lib/index.js):
```
This removes the comment and fixes the build process.

Removing Comment to fix build process.

---

src/resources/postcss/my-tickets/_orders.pcss
src/resources/postcss/rsvp-v1.pcss
src/resources/postcss/tpp.pcss
src/views/tickets/my-tickets/tickets-list.php
src/views/tickets/orders-pp-tickets.php
src/views/tickets/orders-rsvp.php

[ET-1874] 
Design suggested moving the opt out checkbox to after the tickets list, so this PR makes that changes. It required adding a couple of new filters in the spot where the checkbox will be moved to.
[ET-1874]: https://stellarwp.atlassian.net/browse/ET-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1874] My Tickets Redesign: Move opt out checkbox after tickets list

---

src/resources/postcss/my-tickets/_orders.pcss
src/resources/postcss/rsvp-v1.pcss
src/views/tickets/my-tickets/attendee-label.php

[ETWP-46] 
We are injecting the Wallet Plus passes into the My Tickets page, but it required a little bit of a makeover to make it look the way we wanted it. These changes along with changed in ETWP and ETP make it look perfect.
[ETWP-46]: https://stellarwp.atlassian.net/browse/ETWP-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ETWP-46] Wallet Plus: Restyle My Tickets Page for Passes

---

src/Tickets/Commerce/Gateways/Contracts/Abstract_Requests.php
src/Tribe/Events/Views/V2/Models/Tickets.php

- N/A 
- Fixing a deprecation notice on the TC checkout page. Saw it while testing on Romine's sandbox.

Fix deprecated notice

---

src/Tickets/Commerce/Reports/Attendees.php
src/Tickets/Commerce/Reports/Orders.php
src/Tribe/Attendees.php
src/Tribe/Editor/Attendee_Registration.php

N/A
Fix PHP8.1 deprecation notices for [add_submenu_page](https://developer.wordpress.org/reference/functions/add_submenu_page/) only taking stings as first param.
First param is $parent_slug, which should be string.

Fix PHP8.1 deprecation notices for `add_submenu_page` only taking stings as first param.

---

src/resources/postcss/components/attendees-list/_attendees.pcss

N/A 
DQA found that on mobile devices, after RSVP registration to an event, the pass buttons overflow out of the container. This fix stacks the buttons on small devices.

Wallet Plus: DQA Fix - Pass buttons overflowing on mobile after RSVP registration

---

src/Tribe/RSVP.php
src/Tribe/Tickets_View.php
tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set opt-in__1.php

N/A 
WE found that the `$attendees` variable within the global context wasn't getting reset for the RSVP block and when the Attendee List block is placed on the same page, above the RSVP block, it causes issues.
Before:
After:

Fix attendees list for RSVP block

---

readme.txt
src/Tickets/Commerce/Shortcodes/Success_Shortcode.php
src/views/components/attendees-list/attendees.php

[ET-1924]  
The attendees array being passed over to the `Your Tickets` section wasn't properly ordered by ID. Therefore, it was displaying the attendees out of order from how they were being added.
For the artifact I followed the scenario listed in the original ticket -
When I visit the event page and I add 3 tickets to buy
- And for the attendee 1 I set the name to: Lionel Messi
- And for the attendee 2 I set the name to: Pablo Aimar
- And for the attendee 3 I set the name to: Enzo Fernandez
[artifact_et-1924.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/db08054b-2afc-41c1-8a5d-2e0d86fe6964)
[ET-1924]: https://stellarwp.atlassian.net/browse/ET-1924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1924] Fix order of attendees on success confirmation

---

readme.txt
src/Tribe/REST/V1/Endpoints/Single_Attendee.php

[ET-1935] 
Fixed compatability issue with php 8+.
[ET-1935]: https://stellarwp.atlassian.net/browse/ET-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1935] PHP 8+ compatibility for Implode in REST Endpoint

---

readme.txt
src/Tickets/Admin/Upsell.php
src/resources/postcss/tickets-admin/attendees/_table.pcss

[ET-1937] 
[ET-1938] 
We want to show ETWP upsells to users that don't currently have ETWP installed/activated. They are added to the Tickets Emails settings page and to the attendees page. In the case where ETP is also not installed/activated, on the attendees page, the upsell will evenly alternate between the Manual Attendees upsell and the ETWP upsell randomly.
[ET-1937]: https://stellarwp.atlassian.net/browse/ET-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-1938]: https://stellarwp.atlassian.net/browse/ET-1938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ETWP Upsells

---

src/resources/postcss/tickets-admin/attendees/_table.pcss
src/resources/postcss/tickets-report.pcss

[ET-1937] 
[ET-1938] 
We were experiencing an issue when building the plugin (`npm run build`) where the grid area names were getting re-written in the minified css files. I eventually realized that the `grid-area` setting needed to be within the same pcss file where the `grid-template-areas` are being set.
N/A
[ET-1937]: https://stellarwp.atlassian.net/browse/ET-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-1938]: https://stellarwp.atlassian.net/browse/ET-1938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1937] Fix `grid-area` names being renamed upon building

---

readme.txt
src/Tribe/Events/Views/V2/Models/Tickets.php

[ET-1949] 
Since PHP 8.1, there has been a Deprecation warning that is logged whenever you visit an event list (back end events or front end calendar).
```PHP Deprecated:  Return type of Tribe\Tickets\Events\Views\V2\Models\Tickets::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/wordpress/wp-content/plugins/event-tickets/src/Tribe/Events/Views/V2/Models/Tickets.php on line 242```
The issue is resolved when adding the `mixed` return type to the method.
N/A
[ET-1949]: https://stellarwp.atlassian.net/browse/ET-1949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1949] Resolve `offsetGet` deprecation warnings

---

src/template-tags/tickets.php
tests/ft_integration/Tribe/Tickets/MetaboxTest.php

[114](https://docs.google.com/spreadsheets/d/1PmKGre7-yrf8zbQVM97Zr6DKXIKCn5OQO5_closegwg/edit#gid=0&range=H19) 
* Show total event capacity count properly on Ticket Metabox when shared capacity series passes are added.

Fix - Total capacity not showing properly when Series Pass with Shared capacity is added.

---

src/Tickets/Flexible_Tickets/Series_Passes/Base.php
src/admin-views/editor/panel/list.php
src/admin-views/editor/panel/settings-button.php
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event without ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html

[ET-1987] 
🎥 screencast(s): https://www.loom.com/share/0598d0a658c44acdb09193e6f29f3796
[ET-1987]: https://stellarwp.atlassian.net/browse/ET-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1987] - Hide settings button from classic metabox if ETP is not enabled.

---

readme.txt
src/views/emails/template-parts/body/footer/credit.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

[ET-1971] 
We're adding a link to the site in the footer of the Tickets Emails template to reduce the amount of confusion as to where the tickets are being purchased from.
[ET-1971]: https://stellarwp.atlassian.net/browse/ET-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1971] Add site name and link to Tickets Emails footer

---

readme.txt
src/Tribe/Attendees.php

[ET-1883] 
The `order_status` column was being referenced incorrectly as `order_status_label`.
[Event-with-ARF-attendees(2).csv](https://github.com/the-events-calendar/event-tickets/files/13834762/Event-with-ARF-attendees.2.csv)
[ET-1883]: https://stellarwp.atlassian.net/browse/ET-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1883] ET > TC > Attendee List Export for Tickets Commerce does not populate order status

---

src/Tickets/Blocks/Controller.php

This PR makes sure the checks to avoid Block Editor assets being registered on non ticketable post types, ad admin UI concern, will not leak to the front-end.
[Demo](https://share.cleanshot.com/zWk19pJf)

fix(Blocks) ensure ticket block will show correctly on front-end

---

src/Tribe/Ticket_Object.php
tests/commerce_integration/TEC/Tickets/Commerce/Stock/SharedCapacity/SharedCapacityTest.php
tests/integration/Tribe/Tickets/Ticket_ObjectTest.php
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event without ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html

In the context of the work done to make sure Ticket inventory would be calculated correctly, I have set up the code to use the wrong key to exclude Attendees not for a specific post.
This PR fixes the issue where it was introduced, at the base level of the `Ticket__Object::inventory()` method.
Tests have been updated to better cover the fix and ensure they would fail when using the incorrect Attendee key (`product_id`) in place of the correct one (`event_id`).
[Demo](https://share.cleanshot.com/MgNxWLPv)

fix(Ticket_Object) correct key used to filter out Attendees

---

readme.txt
src/views/tickets/orders.php

[ET-1980] 
We found that when only Tickets appear on the My Tickets page, the update button only shows when IAC or ARF are in place. The update button does NOT show in the case where the user can opt attendees out of the public attendees list.
This PR adds that logic in the correct place.
[ET-1980]: https://stellarwp.atlassian.net/browse/ET-1980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1980] - Fix My Tickets Update Button When Only Opt-Out Form Shows

---

src/Tribe/Editor/Meta.php
tests/ft_integration/Tribe/Tickets/MetaboxTest.php
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__event__0.snapshot.html
tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__post__0.snapshot.html
tests/integration/Tribe/Tickets/MetaboxTest.php
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__event__0.snapshot.html
tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__post__0.snapshot.html

This PR fixes an issue related to an improper case class name, the `Tribe__Tickets__RSVP` one types all in lowercase (`tribe__tickets__rsvp`) and causing the `New Ticket` button to appear when no gateways are configured.
Artifacts:
* [Demo](https://share.cleanshot.com/yH7JJMNY)
* tests

fix(Metabox) use correct case for class name to count active providers

---

readme.txt
src/Tickets/Emails/Email_Abstract.php
src/Tickets/Emails/Provider.php

[ET-1988] 
It was found that when purchasing more than one ticket in an order and IAC is enabled, the wrong attendee name is being sent out to subsequent attendees (after the first one).
This PR ensures that each email class will not be used as a singleton and that newly assigned placeholders are merged into existing placeholder (not the other way around).
Order:
Before (email to 2nd attendee):
After (email to 2nd attendee):
[ET-1988]: https://stellarwp.atlassian.net/browse/ET-1988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1988] Wrong Attendee Name Being Used with Multiple Attendees

---

src/Tickets/Commerce/Custom_Tables/V1/Provider.php
src/modules/blocks/rsvp/container.js
src/modules/blocks/rsvp/template.js

Based on [Common PR](https://github.com/the-events-calendar/tribe-common/pull/2047)
[Demo](https://share.cleanshot.com/wbc04ntc)
This PR diversifies the block imposed on Recurring Events not to have tickets to more finely control Tickets and RSVPs.
By default, as was the case before, RSVPs and Tickets will **not** show on recurring events, but now the option for each type is filterable.

fix(Blocks/RSVP) do not show RSVP block on Recurring Events

---

src/Tickets/Site_Health/Subsections/Features/Tickets_Commerce_Subsection.php
src/Tickets/Site_Health/Subsections/Plugins/Plugin_Data_Subsection.php

[ET-1925] 
While testing Romine found that under certain scenarios the calculation for ticket averages was incorrect. This fixes the logic
[ET-1925]: https://stellarwp.atlassian.net/browse/ET-1925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-1925] Fix calculation issue on site health page

---

src/Tickets/Flexible_Tickets/Series_Passes/Series_Passes.php
src/Tribe/Tickets_View.php
src/views/shortcodes/my-attendance-list.php
tests/wpunit/Tribe/Tickets/Tickets_ViewTest.php
tests/wpunit/Tribe/Tickets/__snapshots__/Tickets_ViewTest__should_get_tickets_page_url__with valid event id__0.snapshot.html
tests/wpunit/Tribe/Tickets/__snapshots__/Tickets_ViewTest__should_get_tickets_page_url__with valid post id__0.snapshot.html
tests/wpunit/Tribe/Tickets/__snapshots__/Tickets_ViewTest__should_get_tickets_page_url_for_plain_permalink__with valid event id__0.snapshot.html
tests/wpunit/Tribe/Tickets/__snapshots__/Tickets_ViewTest__should_get_tickets_page_url_for_plain_permalink__with valid post id__0.snapshot.html

[ET-1993] 
* Fixed an issue where the My tickets page for Series post types was redirecting to the wrong URL on update.
* Now the fix is tested against regular `post`, `event` and `series` types and are working as expected.
* Changes are covered by these tests: [With Series Pass](https://github.com/the-events-calendar/event-tickets/blob/cc4650810fede21a82a592ed28c3529960c662f5/tests/ft_integration/Tribe/Tickets/MyTickets/MyTicketsTest.php#L17-L16) & [Without series Pass](https://github.com/the-events-calendar/event-tickets/blob/b11c409cd61a69371bc5838e544a3a960b05f997/tests/integration/Tribe/Tickets/MyTickets/MyTicketsTest.php#L14-L13)
🎥 screencast(s): https://www.loom.com/share/84ce624e3b254f48894761d88ae04768
[Test with and without series pass …

[ET-1993] Fixed incorrect redirect on updating tickets data from My tickets page.

---

src/Tickets/Site_Health/Subsections/Plugins/Plugin_Data_Subsection.php

When TEC was disabled a fatal was occurring due to `tribe( 'tickets.event-repository' )` not existing. We are removing the code and adding it back in a future release. I created the new ticket https://stellarwp.atlassian.net/browse/ET-2017

Remove Formatted Price fields from Site Health

---

src/Tickets/Flexible_Tickets/Series_Passes/Attendees.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/AttendeesTest.php

Tickets:
* [ET-1936](https://stellarwp.atlassian.net/browse/ET-1936)
* [ETPAPP-32](https://stellarwp.atlassian.net/browse/ETPAPP-32)
This PR fixes an issue where check-in requests for a Series Pass Attendee from the context of the Series ID itself would fail with `403` (should be `400` actually for "bad request") when there are actually 2+ candidate Events in the time frame.  
The correct response, see the added test, is HTTP `300` (Multiple Choices) to indicate the user should pick one of the candidate Events to check-in.
[ET-1936]: https://stellarwp.atlassian.net/browse/ET-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ETPAPP-32]: https://stellarwp.atlassian.net/browse/ETPAPP-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

fix(FT) handle check-in request from Series context correctly

---

readme.txt
src/Tickets/Emails/Dispatcher.php

[ET-2007]
It was reported the Ampersands were being encoded when an event (or post) title included one in its title and when using the `{event_name}` placeholder within the subject line of an email. We found that `wp_kses()` was causing this to occur. We are using `wp_specialchars_decode()` just before sending the email to prevent these characters from being sent out.
https://www.loom.com/share/e0918416a8a242fd893200d26713d04e
[ET-2007]: https://stellarwp.atlassian.net/browse/ET-2007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2007] Decode html entites in email subject string

---

src/Tickets/Flexible_Tickets/Series_Passes/Attendees.php
tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/AttendeesTest.php

[ET-1936]
Previously, cloned Attendees would, from the context of a check-in made with QR code, be incorrectly checked for already checked-in status.
If the Series Pass Attendee has an ID of 23, and the clone has an ID of 89, then the check for already checked-in status would be done,
incorrectly, on the Series Pass Attendee (never checked-in) and not on the cloned Attendee.
[Issue in action](https://share.cleanshot.com/Vr1fLTGX) -- I can check-in multiple times
[Issue fixed](https://share.cleanshot.com/TwpVSr7h) -- I cannot check-in after the first time
[ET-1936]: https://stellarwp.atlassian.net/browse/ET-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix - FT check-in SP Attendees once

---

readme.txt
src/Tribe/Repositories/Traits/Post_Tickets.php

[ET-2047]
```
PHP Fatal error:  Uncaught TEC\Common\Exceptions\Not_Bound_Exception: Error while making cache: count(): Argument #1 ($value) must be of type Countable|array, null given. in /.../wp-content/plugins/the-events-calendar/common/src/Common/Contracts/Container.php:27
```
It was found that on a fresh install of TEC/ET the Site Health page was throwing a fatal. Upon looking into the issue I found that the repository method `filter_by_has_tickets` was throwing an error due to `$meta_key_compare_clause` being empty. I refactored the code to build the join for times when `$meta_key_compare_clause` is empty.
This change is covered by the tests found within `tests/wpunit/Tribe/Tickets `.
[et_2047_artifact.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/c9b40ff3 …

 [ET-2047] Repository fatals when no providers enabled

---

readme.txt
src/views/emails/template-parts/body/post-description.php
tests/ft_integration/TEC/Tickets/Emails/__snapshots__/TicketsTest__test_tickets_email_for_series_pass__series with single series pass and 3 attached events__0.snapshot.html
tests/ft_integration/TEC/Tickets/Emails/__snapshots__/TicketsTest__test_tickets_email_for_series_pass__series with single series pass but no events__0.snapshot.html
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php

[ET-2006]
Prior to this, post excerpts have been displaying as the "post description" within emails, but if they had any line breaks, they were being stripped. This fix converts line breaks to `<br>` tags so that the line breaks will be preserved within the email content.
[ET-2006]: https://stellarwp.atlassian.net/browse/ET-2006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2006] Tickets Emails > Allow excerpts to display line breaks within emails

---

event-tickets.php
readme.txt
src/Tickets/Blocks/Tickets/app/editor/container/style.pcss
src/Tickets/Blocks/Tickets/app/editor/container/template.js

[ET-2046]
Within the block editor, tickets were getting deleted when opening the "Settings" view within the block. I found that we had made a change where the individual Ticket Blocks get removed instead of just hiding them, which was triggering the call to delete the ticket. Instead of removing the components, I used CSS to hide them instead, which avoids the tickets from being deleted.
https://www.loom.com/share/ffaa6354090b4ecaa68fdd5e5c7f8ab2?sid=cf25f923-e2ba-4d89-a455-d4de3483ba63
[ET-2046]: https://stellarwp.atlassian.net/browse/ET-2046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2046] Block Editor > Tickets Block > Tickets getting deleted when opening settings

---

readme.txt
src/Tribe/Attendees_Table.php

[ET-2005]
In a previous MR we implemented an export button for the attendees table next to the title of the event. However, at that point on the page the attendees data wasn't isn't prepared yet. We run `prepare_items` at this point, and again later during page load. However, this causes an issue because `prepare_items` expects to only be ran once per a page. 
To mitigate this issue I added caching into the method so that if it runs multiple times on a page it uses the original data and returns early.
[artifact_etp_2005.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/f544d166-3e4f-481f-94c0-8a37fa9cfcf2)
[ET-2005]: https://stellarwp.atlassian.net/browse/ET-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2005] Attendees Table being prepared twice

---

readme.txt
src/Tribe/Repositories/Traits/Post_Tickets.php

While testing ET-2017] with no providers it was found that the query wasn't being built correctly.  When this scenario occurs I put an early return which fixes the issue.

[ET-2017] ORM error with no providers

---

readme.txt
src/Tickets/Commerce/Settings.php

[ET-2015]
In a previous PR (https://github.com/the-events-calendar/event-tickets/pull/2403) we removed certain parts of the `is_licensed_plugin` logic due to its resource-intensive nature, especially noticeable on the checkout page when Stripe is enabled.  This PR reintroduces the logic with the idea of caching the revalidation of `id_current_license_valid`. 
Scenario - 
When $revalidate is true we need to check the most recent license. This happens [here](https://github.com/the-events-calendar/event-tickets/blob/master/src/Tickets/Commerce/Gateways/Stripe/Application_Fee.php#L34). This method is always called when you checkout for Stripe to see if the fee must be added.
I added in additional caching when `$revalidate` is true. The cache will only last an hour and will help alleviate …

[ET-2015] Adjusted the logic for calculating fees when using Stripe.

---

readme.txt
src/views/emails/template-parts/body/ticket/number-from-total.php
src/views/emails/template-parts/body/tickets-total.php

[ET-2020]
We found two strings that had `event_tickets` as the text domain rather than `event-tickets`, causing these strings to be unavailable for translating. This PR fixes those.
Berfore: https://github.com/the-events-calendar/event-tickets/blob/d1e364a09b97f243811e5272d463d65f4ea48dfb/src/views/emails/template-parts/body/tickets-total.php#L37
After: https://github.com/the-events-calendar/event-tickets/blob/f07c14c8b2b427a70b95131019f425442f7aa286/src/views/emails/template-parts/body/tickets-total.php#L37
Before: https://github.com/the-events-calendar/event-tickets/blob/d1e364a09b97f243811e5272d463d65f4ea48dfb/src/views/emails/template-parts/body/ticket/number-from-total.php#L38
After: https://github.com/the-events-calendar/event-tickets/blob/f07c14c8b2b427a70b95131019f425442f7aa286/src …

[ET-2020] Correct Text Domain

---

src/Tickets/Blocks/Ticket/Block.php
src/Tickets/Blocks/Ticket/app/editor/container-header/template.js
src/Tickets/Commerce/Hooks.php
src/resources/postcss/tickets/_block.pcss

A couple of fixes and a recommended change to the react block to ensure the 'On Sale' string is translatable.
Artifact:
Tested after these fixes:

Collie Changes: js and css tweaks

---

readme.txt
src/Tickets/Emails/Dispatcher.php

[ET-2061]
There was a strange issue where, when using a placeholder within the subject line, and an apostrophe was put into the subject line AFTER the placeholder, a slash would be inserted into the subject line right before the apostrophe in the subject line.
Before:
After:
[ET-2061]: https://stellarwp.atlassian.net/browse/ET-2061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2061] Remove slashes from Tickets Emails subject line

---

event-tickets.php
readme.txt
src/resources/postcss/components/buttons/_small.pcss

[ET-2068]
On `:active` and `:focus` states, the padding for the `Get Tickets` button was not consistent, causing the button to change in size sporadically.
https://www.loom.com/share/319a06b9b1a647d4beafda27d2b32ff6?sid=e13033fb-611a-4c6b-bd7b-1bf7d718f721
[ET-2068]: https://stellarwp.atlassian.net/browse/ET-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2068] Fix `Get Tickets` button padding on focus and active

---

readme.txt
src/Tribe/Main.php
src/resources/postcss/tickets/_block.pcss

[ET-2074]
There were reports that the font of the sale label was inheriting the font from different themes, but we want the font to be uniform with the rest of the elements in ET
https://www.loom.com/share/dc8895b1e5a7431eba5cbaf614072dd5?sid=c1e0ddcf-390b-46f3-89f4-9e10e066d8b0
[ET-2074]: https://stellarwp.atlassian.net/browse/ET-2074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2074] Add font family to Sale Label so it's uniform

---

readme.txt
src/Tickets/Commerce/Gateways/PayPal/Order.php

[ET-2076]
When displaying the PayPal payload link there was an extra slash when we concatenated the strings. This fixes the issue and cleans the code up a little bit.
[ET-2076]: https://stellarwp.atlassian.net/browse/ET-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2076] Paypal trailing slash

---

readme.txt
src/Tribe/Admin/Settings.php
src/Tribe/Attendees.php

[GTRIA-1268]
When viewing the Attendees table under Tickets -> Attendees a fatal would be thrown if the language was something other than English. 
Rafsun and I found that the issue occured because `Tickets` was being translated and was changing the slug to the translated value instead of `tickets-*`. 
[GTRIA-1268.webm](https://github.com/the-events-calendar/event-tickets/assets/12241059/111b354b-3f6c-4bbc-97bd-05f2c93b12a0)
[GTRIA-1268]: https://stellarwp.atlassian.net/browse/GTRIA-1268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GTRIA-1268] Corrected the Attendees page when languages other than English are used.

---

src/views/emails/template-parts/body/order/order-gateway-data.php
src/views/emails/template-parts/body/order/order-total.php
src/views/emails/template-parts/body/order/payment-info.php
tests/integration/TEC/Tickets/Emails/TemplateTest.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set free-completed-order__1.php
tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set free-purchase-receipt__1.php

[ET-2089]
Making some tweaks to a couple of emails.
- Completed Order - Remove the Gateway Order #, since it's the same as the main order #. Remove the "Payment completed with..." text when the Gateway label is blank.
- Purchase Receipt - Remove the "Payment completed with..." text when the Gateway label is blank.
Before: Note the redundancy of order ID and Gateway order ID, which are the same:
After:
[ET-2089]: https://stellarwp.atlassian.net/browse/ET-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2089] Free Tickets: Update emails to handle free orders

---

src/Tickets/Blocks/Ticket/app/editor/container-content/price/style.pcss
src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
tests/restv1/PayPal/SingleTicketCest.php

[ET-2078]
Aside from entering '0' into the price field, we want to allow ticket creators to leave the price field blank within the Block Editor much like we do within the Classic Editor. This means that we also need to remove the asterisk that tells the user it's a required field.
Before:
After:
[ET-2078]: https://stellarwp.atlassian.net/browse/ET-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2078] Allow Blank Price Field in Block Editor

---

src/Tribe/Attendees.php

Variables were missing from the docblock. This likely influenced that our documentation on this filter was incompolete. https://www.dropbox.com/scl/fi/qqgf8qvjetg8inw1bs18b/shot_240502_160124.jpg?rlkey=ctce8mev4d8bp56f75kgxxiu6&dl=0

Add variables to docblock

---

src/Tickets/Commerce/Gateways/Stripe/Signup.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
src/admin-views/settings/tickets-commerce/stripe/webhook-description.php
tests/commerce_integration/TEC/Gateways/Stripe/WebhooksTest.php

[ET-2104]
Additional feature of #3048 
Now webhook management will be skipped when tickets commerce is disabled or is in staging mode.
[ET-2104]: https://stellarwp.atlassian.net/browse/ET-2104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2104] Skip webhooks while on sandbox

---

src/Tickets/Seating/Admin/Tabs/Layout_Card.php
src/Tickets/Seating/Admin/Tabs/Layout_Edit.php
src/Tickets/Seating/Admin/Tabs/Map_Card.php
src/Tickets/Seating/Admin/Tabs/Map_Edit.php
src/Tickets/Seating/Service/Layouts.php
src/admin-views/seating/components/layouts/card.php
src/admin-views/seating/components/maps/card.php
src/admin-views/seating/tabs/layouts.php
tests/slr_integration/Admin/Maps_Layout_Homepage_Test.php
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_empty_layouts_tab__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing_with_1_layout__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_maps_tab_card_listing__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_maps_tab_card_listing_with_1_map__0.snapshot.html

[SL-148]
* Layout `Edit` link opens up iframe view to edit the layout.
* Changed the layout card text “No upcoming events” to “No associated events” when a layout has no associated events of any kind.
* Count and display the number of associated events when available and hide the `delete` button.
📷 screenshot(s): https://share.cleanshot.com/10qqbFBK
[SL-148]: https://stellarwp.atlassian.net/browse/SL-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-148] Layout listing updates

---

jest.config.js
jest.setup.js
package.json
src/Tickets/Seating/Service/Layouts.php
src/Tickets/Seating/app/service/service-api/externals.js
src/Tickets/Seating/app/service/service-api/index.js
src/Tickets/Seating/app/service/service-api/state.js
tests/slr_integration/Admin/Ajax_Test.php
tests/slr_jest/_bootstrap.js
tests/slr_jest/service-api.spec.js
tests/slr_jest/state.spec.js

The service will send messages in order to sync with the site.
The previous message queue implementation relied on the actions associated to the messages being all sync, thus processing them as soon as they arrived it made sense.
A sync message processing system is not able, though, to process sync and `async` handlers correctly though, as illustrated by this case:
1. The user edits a layout and clicks save.
2. The service sends the `LAYOUT_CREATED_UPDATED` message
3. The site message processing system fires the handler starting an AJAX request to the backend to trigger invalidation of the caches.  This call takes time and is done by an `async` handler waiting on the `fetch` response with `await fetch( ... )`
3. The service sends the `GO_TO_LAYOUTS_HOME` message
4. The site immediately …

SLR - fix Service message processing race condition

---

src/Tickets/Commerce/Admin/Orders_Page.php
src/resources/js/admin/orders/table.js
tests/commerce_integration/TEC/Tickets/Commerce/TicketTest.php
tests/integration/TEC/Tickets/Commerce/Admin/Orders_PageTest.php

[ET-2117]
Avoid Dependency on TEC. The date range dropdowns were only being initiated while TEC was active. Now ET can initiate those on its own.
[ET-2117]: https://stellarwp.atlassian.net/browse/ET-2117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Avoid TEC dependency in orders page

---

package-lock.json
readme.txt
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
src/Tickets/Commerce/Status/Status_Abstract.php
tests/commerce_integration/TEC/Gateways/Stripe/RefundTest.php
tests/integration/Deprecated_Test.php

[ET-2142]
We were facing 2 issues with Stripe refunds.
1. Refunds would never reflect in WP. Reason is that in part of fixing ET-1792 we introduced a new bug. In ET-1792 before processing an incoming webhook we would check if there was already a successful payment intent present in Stripe. Overcoming that way Race conditions. BUT webhooks for refunds always did have a successful payment intent and we were wrongly ignoring them. We are overcoming this one by also checking against the type of incoming webhook.
2. Multiple refunds from stripe would fail to be registered in WP. Reason was that the code was failing early because it could not update the order status from `refunded` to `refunded`. Fixing this by allowing explicitly this status update.
Pending/possible second PR
- Check the same …

Fix stripe refunds

---

.puprc
src/Tickets/Commerce/Admin_Tables/Orders_Table.php
src/resources/postcss/rsvp-v1.pcss
src/resources/postcss/tickets-admin/settings/_banners.pcss
src/resources/postcss/tickets-commerce/admin/orders/table.pcss
src/resources/postcss/tickets/_block-extras.pcss

[ET-2144]
Makes the ID wrap in cases where the column is too narrow to fit it.
Old (bad)
Proposal (good - wrap ID) 
Final (better - line break and font to offset)
[ET-2144]: https://stellarwp.atlassian.net/browse/ET-2144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ID column text wrap

---

src/Tickets/Seating/Admin/Ajax.php
src/Tickets/Seating/Frontend/Session.php
src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/Service/Layouts.php
src/Tickets/Seating/app/postcss/_iframe.pcss
tests/slr_integration/Admin/Ajax_Test.php
tests/slr_integration/Admin/__snapshots__/Ajax_Test__should_return_urls__0.snapshot.php
tests/slr_integration/TEC/Tickets/Seating/Frontend/Session_Test.php
tests/slr_integration/TEC/Tickets/Seating/Frontend/Timer_Test.php
tests/slr_integration/TEC/Tickets/Seating/Frontend/__snapshots__/Timer_Test__test_render_to_sync_with_previous_render__0.snapshot.html
tests/slr_integration/TEC/Tickets/Seating/Service/Layouts_Test.php

In this PR:
- **fix(Seating) print the new session token in all the timer instances on initial render**
- **fix(Seating) cs fixes**
- **refactor(Seating) on interrupt, remove token session from DB**
Follow-up on the work done for SL-92 to fix some issues with session persistence and window/tab re-use: going back to the same browser window to start a new seat-selection session would create inconsistent session data, this fixes it.
Also: on interrupt (i.e. when the timer runs out) remove the token session from the db instead of just emptying it.
[Demo](https://share.cleanshot.com/g5ZTY13C)

SLR - fix session persistence

---

src/admin-views/admin-welcome-message.php
tests/_data/ft_smoketest.sql
tests/ft_smoketest.suite.dist.yml

Removes VE from Tickets App shop page.
Also: This should be escape & underscore functions, not just escape.
This is the block removed from the ET welcome/home page:

Remove VE from app shop. Fix some broken translations.

---

package-lock.json
package.json
src/Tickets/Seating/app/frontend/ticketsBlock/index.js
tests/slr_jest/frontend/ticketsBlock.spec.js

This PR updates the `slr_jest` test code to use the `jest-fetch-mock` package to mock the `fetch` API in tests.
Currently, the `fetch` API is mocked on a per-test base, to make sure not mocked `fetch` requests will fail with an error making it apparent they should be mocked.
Adding the `fetch` mock fixes the previously not working tests.

SLR - Properly mock fetch requests

---

src/Tickets/Seating/Commerce/Controller.php
src/Tickets/Seating/Controller.php
src/Tickets/Seating/Frontend/Session.php
src/Tickets/Seating/Frontend/Timer.php
tests/slr_integration/TEC/Tickets/Seating/Commerce/Controller_Test.php
tests/slr_integration/TEC/Tickets/Seating/Frontend/Timer_Test.php
tests/slr_integration/TEC/Tickets/Seating/Frontend/__snapshots__/Timer_Test__test_render_with_args__0.snapshot.html

This fixes the timer appearing, and interrupting, during the TC checkout for posts and tickets that are not using ASC.
[Demo](https://share.cleanshot.com/dHnR6lh0)
The code is isolated to a TC dedicated controller, and covered by new tests.

SLR - no timer in TC checkout if not ASC tickets in cart

---

src/Tickets/Seating/Frontend/Session.php
src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/Tables/Sessions.php
src/Tickets/Seating/app/frontend/session/index.js
src/Tickets/Seating/app/service/api/index.js
tests/slr_integration/Admin/Ajax_Test.php
tests/slr_integration/TEC/Tickets/Seating/Frontend/Session_Test.php
tests/slr_integration/_bootstrap.php

Rebase of #3107.
[Demo](https://github.com/the-events-calendar/event-tickets/pull/3106)
Based on #3106, this PR fixes an issue where the session timer would be reset, thus granting infinite time, on each seat selection flow restart (see video for clarity).

SLR - Fix replay session issue

---

changelog/tweak-remove-etwp-upsell-notices
readme.txt
src/Tickets/Admin/Upsell.php
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket with multiple series pass from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__single ticket from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__ticket with series pass from an event__0.snapshot.html

[ET-2170]
After merging ETWP into ETP, we found two upsell notices for ETWP in ET. This PR modifies them to be ETP notices.
[ET-2170]: https://stellarwp.atlassian.net/browse/ET-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Old ETWP Upsell Notices

---

changelog/fix-ET-920-global-stock-being-reduced-on-unlimited-sales-tickets
src/Tickets/Commerce/Ticket.php

[ETP-920]
It was found that using Tickets Commerce and having shared capacity and unlimited capacity ticket on the same event/post, the global stock value was being decreased even when purchasing an unlimited ticket. Global stock should only be decreased on shared capacity tickets. I found that unlimited capacity tickets have their "ticket stock mode" set to either 'own' or a blank string. When a ticket is purchased, we weren't checking for the blank string before updating the global stock.
[Screencast](https://share.zight.com/2Nu8ng1P)
[ETP-920]: https://stellarwp.atlassian.net/browse/ETP-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Account for a blank global mode string

---

changelog/fix-ET-920-global-stock-being-reduced-on-unlimited-sales-tickets
src/Tickets/Commerce/Ticket.php

Reverts the-events-calendar/event-tickets#3145
This should have gone into chupacabra. Not centaur.
Replaced by https://github.com/the-events-calendar/event-tickets/pull/3151

Revert "Account for a blank global mode string"

---

changelog/fix-ETP-920-move-shared-capacity-logic-to-flag-action
src/Tickets/Commerce/Flag_Actions/Increase_Sales.php
src/Tickets/Commerce/Ticket.php

[ETP-920]
This [this PR](https://github.com/the-events-calendar/event-tickets/pull/3145), we added some logic to fix a bug. We then realized that the `$shared_capacity` param should have been a boolean value all along. To make things right, We're moving that logic into the `Increase_Sales::handle()` method so that `$shared_capacity` is a boolean value, as it should be.
[Screencast](https://share.zight.com/2Nu8ng1P)
[ETP-920]: https://stellarwp.atlassian.net/browse/ETP-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor logic for `Ticket::increase_ticket_sales_by` method

---

tests/commerce_integration/TEC/Tickets/Commerce/Stock/SharedCapacity/SharedCapacityTest.php

[ETP-920]
Created a test for a specific scenario that wasn't being tested before. In TC, when purchasing an unlimited capacity ticket, it was decreasing the global stock count for shared capacity tickets. It should not.
The bug fix PR is here: https://github.com/the-events-calendar/event-tickets/pull/3151
Note: No changelog needed as it was added in the above PR.
Failing test before the bugfix:
Passing test after the bugfix:
[ETP-920]: https://stellarwp.atlassian.net/browse/ETP-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Shared Capacity Test for Specific Scenario

---

src/Tickets/Commerce/Gateways/Stripe/Stripe_Elements.php
src/admin-views/settings/tickets-commerce/stripe/modal/signup-complete/content.php

[ETP-934]
When we select this option:
we load the simple `Card Element` from Stripe gateway.
When we select this option, but only the CC method:
we shouldn't load the full `Payment Element` from Stripe, but again the simple `Card Element`.
[ETP-934]: https://stellarwp.atlassian.net/browse/ETP-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Card Element option in Stripe Settings fix

---

src/Tickets/Seating/app/admin/maps/actions.js
tests/slr_jest/_bootstrap.js
tests/slr_jest/admin/maps/actions.spec.js

[SL-51]
The issue was that some variables being used were imported from the wrong location.
**NOTE:** I will rebase after merging #3183 to fix what is broken now.
[SL-51]: https://stellarwp.atlassian.net/browse/SL-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-51] Fixes undefined variables on delete map action

---

src/Tickets/Admin/Tickets/Assets.php
src/resources/postcss/tickets-admin-tickets.pcss

[ET-2180]
By default, WordPress hides the search and filters on mobile. We want to show them.
[ET-2180]: https://stellarwp.atlassian.net/browse/ET-2180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

All Tickets Page > Display Search and Filters on Mobile

---

changelog/feature-customize-stripe-checkout-filter
src/Tickets/Commerce/Gateways/Stripe/Assets.php
src/resources/js/commerce/gateway/stripe/checkout.js

[TECTRIA-295] 
There are a handful of options available in Stripe for [customizing the Compact Card Checkout](https://docs.stripe.com/js/elements_object/create_element?type=card#elements_create-options). By pulling out the `options` object as a variable we can allow our users to take advantage of the already existing `tec_tickets_commerce_stripe_checkout_localized_data` filter to add to these options. 
For example, to disable the Autofill Link option (by default this is enabled in Tickets Commerce), one could use this snippet:
```php
function my_custom_stripe_checkout_localized_data($data) {
// Modify the cardElementOptions or add properties as needed
$data['cardElementOptions']['hidePostalCode'] = true;
$data['cardElementOptions']['disableLink'] = true;
return $data;
} …
```

Allow filtering of options for`setupCompactCardElement`

---

changelog/tweak-tectria-303_settings_string_translatable
src/admin-views/settings/getting-started.php

[TECTRIA-303]
Clone of #3052 - props to @DAnn2012 
[TECTRIA-303]: https://stellarwp.atlassian.net/browse/TECTRIA-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TECTRA-303] Make string in `getting-started` translatable

---

src/Tickets/Commerce/Admin/Singular_Order_Page.php
src/Tickets/Commerce/Admin_Tables/Orders_Table.php

[ET-2186]
Copy to clipboard button was not working, the asset loader has a bug resolving root paths.
[ET-2186]: https://stellarwp.atlassian.net/browse/ET-2186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Renamed func.

---

src/Tickets/Commerce/Gateways/Stripe/Assets.php

[TECTRIA-295]
After PR #3193 was merged I realized that it breaks the Stripe checkout if no options are being filtered using a snippet - this fix adds a default property (`'disabled' => false`) to avoid that error 
[TECTRIA-295]: https://stellarwp.atlassian.net/browse/TECTRIA-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TECTRIA-295] Allow Filtering of Compact Card - Small Fix

---

.github/workflows/lint.yml
.github/workflows/tests-js.yml
.github/workflows/tests-php-ct1.yml
.github/workflows/tests-php-ft.yml
.github/workflows/tests-php.yml
.github/workflows/zip.yml

to avoid issues with deprecated artifact upload/download actions.
Add summary output to test skip check.
Requires: https://github.com/the-events-calendar/tribe-common/pull/2203

Update checkout action to v4

---

changelog/fix-gtria-1236_avoid_slow_queries
src/Tribe/Query.php

[GTRIA-1236]
A customer has added an index to their `post_meta` table on `meta_value` which is causing severe slowness on their site with a lot (200k+) orders when using ET, ETP, and WC. 
From [this Slack convo](https://lw.slack.com/archives/C0714HQSMEW/p1725568640637249), Matt says "The `CONCAT( p.ID, '' )` would incur a minor performance hit in many use cases, but for folks that have added an index to the `postmeta` table on `meta_value` (which doesn't come default), doing the `CONCAT()` operation would most likely speed things up.
Without the `CONCAT()`, MySQL will attempt to convert the meta_value to an `INT` implicitly, which would cause the index to be ignored and a full table scan to be done." 
This PR is in tandem with one for ETP that will change the `meta_value` from `%d` to …

[GTRIA-1236] Avoid Slow Queries 

---

src/Tickets/Seating/app/blockEditor/capacity-form/index.js

Issue 110 from gsheet.
This part of the codebase seems completely untested and currently i am not sure myself how to test event driven component functionality :(
If you can help Rafsun would be great, otherwise ill bring it back to Luca next week when he is back.
Demo: https://www.loom.com/share/8fad18da8ca24a3ea287c94132ffd58e

Fix SLR meta keys on post/event when user switches between GAC and ASC

---

src/Tickets/Commerce/Gateways/Stripe/Stripe_Elements.php
src/resources/js/commerce/gateway/stripe/checkout.js

[ETP-942]
What we change here: 
Even though we have the full Payment Element, we don't need to manually define the shipping fields on Payment Submit, as we do with the other advanced methods. When wallets, we omit that and let it on `auto` to be handled by Stripe.
Follow-up to https://github.com/the-events-calendar/event-tickets/pull/3237
[ETP-942]: https://stellarwp.atlassian.net/browse/ETP-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

When Apple/Google is selected, fallback to auto properties

---

src/Tickets/Admin/Tickets/List_Table.php

[ET-2212]
We found that calling `get_edit_post_link()` was making extra queries for each unique event that tickets were attached to, so we added more caching and also removed the ECP filter that the extra query was originating from.
N/A
[ET-2212]: https://stellarwp.atlassian.net/browse/ET-2212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tickets Home > Optimize Calls to `get_edit_post_link()` Function

---

changelog/bug-ET-2218-attendee-search-object-cache
src/Tribe/Attendees_Table.php
src/resources/js/v2/rsvp-block.js
src/resources/postcss/tickets-commerce/admin/orders/single.pcss

[ET-2218]
This updates the behavior of caching for the Attendees items.
It also adds the following new filters:
* `tec_tickets_search_attendees_default` – Filter the default search key
* `tec_tickets_attendees_table_cache_key` - Filter the cache key used for retrieving items
[ET-2218]: https://stellarwp.atlassian.net/browse/ET-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update attendee search cache behavior

---

src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Shortcodes/Success_Shortcode.php

[ET-2225]
This is a partial fix for the mentioned ticket. There are scenarios where there are more than one orders per payment intent. When fetching, we always want to return the latest one.
N/A
[ET-2225]: https://stellarwp.atlassian.net/browse/ET-2225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix fetching incorrect order by payment intent

---

changelog/fix-ET-2225-modify-webhook-handling
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Events.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php

[ET-2225]
I found that the `charge.failed` and `charge.succeeded` events can be replaced with `payment_intent.payment_failed` and `payment_intent.succeeded`. We were trying to handle both at the same time, which was causing issues with duplicate actions.
Screencast: https://share.zight.com/4guGlj7W
[ET-2225]: https://stellarwp.atlassian.net/browse/ET-2225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tickets Commerce > Stripe Gateway > Webhooks: Use Payment Intent Events rather than Charge Events

---

src/Tickets/Blocks/Ticket/app/editor/dashboard/container.js
src/Tickets/Seating/app/blockEditor/capacity-form/event-layout-select.js
src/Tickets/Seating/app/blockEditor/capacity-form/index.js
src/Tickets/Seating/app/blockEditor/filters.js
src/Tickets/Seating/app/blockEditor/hook-callbacks.js
src/Tickets/Seating/app/blockEditor/store/common-store-bridge.js
src/modules/data/blocks/ticket/selectors.js
tests/slr_jest/blockEditor/hook-callbacks.spec.js

Issue 111 from gsheet.
In the PR the create button of a ticket is enabled only when a layout AND a seat type are selected.
Refactors non asc ticket but without introducing any changes. Only makes reading it easier and introduces filters.
Makes sure we access the current layout property if its defined and adds a method in order to enable us to notify the common store that the ticket has changes.
https://www.loom.com/share/6c6832c1dd2344efa8f3f5d140a4432d

Disabled create button when ASC but not seat type selected

---

changelog/fix-duplication-of-global-stock-level
src/Tickets/Integrations/Plugins/Events_Pro/Duplicate_Post.php
src/modules/data/blocks/ticket/selectors.js
tests/ct1_integration/TEC/Tickets/Integrations/Plugins/Events_Pro/Duplicate_PostTest.php

[ET-2242]
We should not copy over the Global stock level. We should replace it with the original global stock level which is stored in key_capacity originally of the tickets handler..
[ET-2242]: https://stellarwp.atlassian.net/browse/ET-2242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2242] Fix duplication of global stock level

---

src/Tickets/Seating/Editor.php
src/Tickets/Seating/app/blockEditor/capacity-form/index.js
src/Tickets/Seating/app/blockEditor/hook-callbacks.js
tests/slr_integration/Admin/Events/Controller_Test.php
tests/slr_integration/Admin/Events/__snapshots__/Controller_Test__test_associated_events_list__Events with varying status with pagination__0.snapshot.html
tests/slr_integration/Editor_Test.php
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__existing event, not using meta set or layout set, with tickets__0.snapshot.json
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__existing post, not using meta set or layout set, with tickets__0.snapshot.json

Issue 127 from gsheet
Lock the layout when a GAC ticket is saved or when at least a ticket is present already.
Layout should not be able to change:
when a ticket is already present
when an ASC ticket has ever been part of the post/event and as a result a layout id is stored in the post's/event's meta.
https://www.loom.com/share/268bfe4af73c4ad8aa97632bbdc5f7d1

Lock layout when GAC tickets present

---

src/Tickets/Seating/Admin.php
src/Tickets/Seating/Editor.php
src/Tickets/Seating/Service/Service_Status.php
src/Tickets/Seating/app/blockEditor/hook-callbacks.js
src/Tickets/Seating/app/blockEditor/settings/outage.js
src/Tickets/Seating/app/blockEditor/settings/style.pcss
src/Tickets/Seating/app/blockEditor/settings/upSell.js
src/Tickets/Seating/app/blockEditor/settings/upsell.js
src/admin-views/seating/maps-layouts-home.php
src/admin-views/seating/service-error-tab.php
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_empty_layouts__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_empty_seating_configurations__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layout_edit__0.snapshot.html
tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_map_edit__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__layout edit tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__layouts tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__map edit tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__map new tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__maps tab__0.snapshot.html
tests/slr_integration/__snapshots__/Admin_Test__should_add_the_sub_menu_page__no tab__0.snapshot.html
tests/slr_jest/blockEditor/hook-callbacks.spec.js

[SL-124]
* Display seating upsell in Block editor settings.
* Rename `Seat Layout` menu to `Seating` - Issue - 143.
📷 screenshot(s): 
With no active license: https://share.cleanshot.com/v12H8L3B
With service down: https://share.cleanshot.com/LHZtLyCc
[SL-124]: https://stellarwp.atlassian.net/browse/SL-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-124] - Display seating upsell when seating is not active.

---

src/Tickets/Seating/Admin.php
tests/slr_integration/Admin_Test.php

Issues 77 and 78 from gsheet
Modifies the WP query used to find candidate events for receiving moved tickets or attendees.

Ignore ASC events from being canditates of receiving moved tickets or attendees

---

src/Tickets/Seating/Orders/Seats_Report.php
src/Tickets/Seating/Service/Error_Content.php
src/Tickets/Seating/Service/Service_Status.php
src/Tickets/Seating/app/blockEditor/capacity-form/service-error.js
src/Tickets/Seating/app/blockEditor/hook-callbacks.js
src/admin-views/commerce/reports/seats.php
tests/slr_integration/Editor_Test.php
tests/slr_integration/Frontend_Test.php
tests/slr_integration/Orders/Seats_Report_Test.php
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__expired license__0.snapshot.json
tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__expired license__0.snapshot.html
tests/slr_integration/__snapshots__/Frontend_Test__test_get_ticket_block_data__expired license__0.snapshot.json
tests/slr_integration/_bootstrap.php

[SL-124][SL-47]
Migrates the upsell features to use the Service Status interface in order to determine if they should render or not.
[SL-124]: https://stellarwp.atlassian.net/browse/SL-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Migrate Upsells appearance logic to use service status interface

---

src/Tickets/Seating/Assets.php
src/Tribe/Editor/Assets.php
webpack.config.js

This solves an issue where Block Editor code would be loaded in the
SLR application frontend as part of the `tribe-tickets-gutenberg-editor`
module.
Originally thought in backend context only, **all** the modules required
to compile the modules (block editor, admin, frontend) from the
`node_modules` directory would be compiled into the
`src/resources/js/app/vendor.js` file.
This file would be registered under the `tribe-tickets-gutenberg-editor`
handle in WordPress and, along with its entire set of requirements
(including React and Block Editor code).
Among those modules required are the Babel transpile utils that are
useful while writing modern JS code not only in backend context, but in
frontend context as well. For this reason the Seating frontend modules
would require the …

SLR - smaller frontend bundle, solve errors

---

src/Tickets/Seating/Admin/Ajax.php
src/Tickets/Seating/Commerce/Attendees.php
src/Tickets/Seating/Commerce/Controller.php
src/Tickets/Seating/Service/Seat_Types.php
src/Tickets/Seating/Tables/Seat_Types.php
tests/slr_integration/Commerce/Controller_Test.php
tests/slr_integration/Editor_Test.php
tests/slr_integration/Frontend/Timer_Test.php
tests/slr_integration/Service/Layouts_Test.php
tests/slr_integration/Service/Seat_Types_Test.php
tests/slr_integration/Truncates_Custom_Tables.php

This udpates the logic used to cross-sync the stock meta (`_stock`)
across Tickes with the same seat type to do it **before** the default
meta update logic takes place and handle it using custom logic.
Since Stock = Capacity - Attendees, this update relies on a query that
will count Attendees per-post, per-tickets by seat-type to make sure the
value will be consistent.
Since the default logic will take over other meta update systems, I've
modified other code handling similar updates to remove and add again the
meta handling logic.
Finally, I've updated the `slr_integration` tests to make sure that ASC
tickets will map to a Series Type and Attendees in the database.

fix(Seating) block stock updates, sync pre meta update

---

src/Tickets/Seating/Commerce/Controller.php
src/Tickets/Seating/Service/Seat_Types.php
tests/slr_integration/Commerce/Controller_Test.php

Issue 219 from gsheet
On top of the applied fix yesterday:
- Fixing a typo
- Preventing updates while service is down in different callback for both Tickets and Ticketable post types using Seating.

Prevent event capacity being updated while service is down

---

changelog.md
changelog/fix-ET-2256-duplicate-attendees-created
readme.txt
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Events.php
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
src/Tickets/Commerce/Order.php

[ET-2256]
This PR reverts some previous changes we made for a scenario where when a payment fails and is retried and succeeds, the successful order never gets its status changed to Complete.
This PR fixes the issue where multiple attendees are being created on orders.
N/A
[ET-2256]: https://stellarwp.atlassian.net/browse/ET-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add transient to prevent multiple status changes in a short period

---

changelog/fix-ET-2261-ar-page-on-fse-themes
src/Tribe/Attendee_Registration/Main.php
src/Tribe/Attendee_Registration/Template.php
tests/integration/Tribe/Attendee_Registration/Template_Test.php

[ET-2261]
This fixes an issue where being on a page with the AR shortcode wasn't being detected correctly.
https://share.zight.com/geuKB6b7
[ET-2261]: https://stellarwp.atlassian.net/browse/ET-2261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix AR Page on FSE Themes

---

src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/app/frontend/session/index.js
tests/slr_integration/Admin/Maps_Layout_Homepage_Test.php
tests/slr_integration/Frontend/Timer_Test.php
tests/slr_integration/Orders/Controller_Test.php
tests/slr_jest/frontend/session.spec.js

Remove the knowledge and concern of the AR page to let ET+ logic deal
with that. Update tests to follow.
[Releatet ET+ PR](https://github.com/the-events-calendar/event-tickets-plus/pull/1655)

SLR - Remove AR page concern

---

changelog.md
readme.txt
src/Tickets/Seating/Editor.php
tests/slr_integration/Editor_Test.php
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__expired license - new__0.snapshot.json
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__invalid license - new__0.snapshot.json
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__no license - new__0.snapshot.json
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__service down - new__0.snapshot.json
tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__service not connected - new__0.snapshot.json

[ET-2264]
The issue becomes apparent on the FE specifically by the method [isUsingAssignedSeating](https://github.com/the-events-calendar/event-tickets/blob/127d60be346fd2c19d4ba167297974faa9b0e733/src/Tickets/Seating/app/blockEditor/store/selectors.js#L5).
When there is no seating license the GAC vs Seating radio controller is not present in the FE. So there is no way to change that property, resulting in wrong evaluations of the `isDisabled` filter for the "Create Ticket" button. It is being evaluated as ASC ticket instead of GAC while the ASC controls are hidden.
For testing use the below's snippet possibilities to test creating a new ticketable post type. Make sure in every case the block gives you the posibility to create a new ticket.
```php
add_filter( …
```

Fix initial using seating state by considering license status

---

src/Tickets/Seating/Orders/Cart.php
src/Tickets/Seating/Orders/Controller.php
src/Tickets/Seating/Tables/Sessions.php
tests/slr_integration/Orders/Cart_Test.php

[SL-233](https://stellarwp.atlassian.net/browse/SL-233)
Artifacts:
* tests
* [before](https://share.cleanshot.com/TwJRcwDj)
* [after](https://share.cleanshot.com/PjkyDsQQ)
This updates the code around seat assigment to Attendees to take into
account different stock reduction flows, hence Attendee generation
flows.
Depending on when the stock should be reduced and the Attendee
generated, the data required to assign Attendees might still be in the
session or not.
This updates the code to handle both instances and warmup caches used by
the Cart to assign Attendees in either cases.
[SL-233]: https://stellarwp.atlassian.net/browse/SL-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLR - Fix Attendee seat assignment in some flows

---

changelog/sl-233-pass-2
src/Tickets/Seating/Frontend.php
src/Tickets/Seating/Frontend/Timer.php
src/Tickets/Seating/Tables/Sessions.php
src/Tickets/Seating/app/frontend/session/index.js
src/Tickets/Seating/app/frontend/session/localized-data.js
tests/slr_integration/Frontend/Timer_Test.php
tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_get_localized_data__0.snapshot.json
tests/slr_integration/Service/Tables/Sessions_Test.php
tests/slr_jest/_bootstrap.js
tests/slr_jest/frontend/session.spec.js

This updates the logic around session clearing on payment failure to make sure more edge cases are covered.
[SL-233](https://stellarwp.atlassian.net/browse/SL-233)
Artifacts:
* tests
* demo in Jira
[SL-233]: https://stellarwp.atlassian.net/browse/SL-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLR - more fixes to session clear

---

changelog/slr-fix-blob-db-delta-issue
src/Tickets/Seating/Tables/Sessions.php

Ticket: n/a
Remove the default entry from the `reservations` columns of the Sesssions table as it might cause issues in some systems.

SLR - Fix table update issue

---

changelog/fix-ET-2082-order-status-not-updating-on-asynchronous-payments
src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
tests/commerce_integration/TEC/Gateways/Stripe/Webhooks/PaymentIntentWebhookTest.php

[ET-2082]
[ET-2258]
There was an issue reported from users that were using Bancontact and/or iDEAL as payment methods through Stripe. The issue didn't turn out to be specific to those payment methods, but to asynchronous payment methods that were dependent on the Stripe webhook to update the order. This was a similar issue to when failed payments would be retried successfully within the same session. This fix addresses both issues.
https://share.zight.com/mXuQw6pj
[ET-2082]: https://stellarwp.atlassian.net/browse/ET-2082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-2258]: https://stellarwp.atlassian.net/browse/ET-2258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2082] Fix orders not updating on asynchronous/failed payments

---

src/Tickets/Commerce/Gateways/PayPal/WhoDat.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Abstract_Fees.php
src/Tickets/Commerce/Order_Modifiers/Modifier_Admin_Handler.php
src/Tickets/Commerce/Order_Modifiers/Values/Currency_Value.php
src/views/v2/commerce/checkout/order-modifiers/fees.php
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_complex_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_simple_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $10, Fee $5, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $15, Fee $2, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $20, Fee $3, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $50, Fee $10, Application Per__0.snapshot.html
tests/order_modifiers_integration/Modifier_Admin_Handler_Test.php

[TICKET_ID]
In the above screenshot, both tickets have 2 fees applied:
1. "All tickets fee" is $1 per ticket, applied 3 times
2. "A little fee for all tickets" is 0.5% per ticket. It is applied 3 times, but the amount is different based on the ticket amount it applies to. Thus, it is displayed 1 time for the ticket with quantity 1, and 2 times for the ticket with quantity 2.

Update the frontend display of fees

---

changelog/fix-sl-248-seating-license-check
src/Tickets/Seating/Settings.php
tests/slr_integration/Settings_Test.php
tests/slr_integration/__snapshots__/Settings_Test__test_seating_reservation_setting_not_included_with_invalid_license__0.snapshot.json
tests/slr_integration/__snapshots__/Settings_Test__test_seating_reservation_setting_not_included_with_no_license__0.snapshot.json

[SL-248]
* Hide seating reservation timer settings if seating license is not available or invalid.
🎥 screencast(s): https://share.cleanshot.com/fx7py2ZT
[SL-248]: https://stellarwp.atlassian.net/browse/SL-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SL-248] Hide seating settings when license is not valid.

---

uninstall.php

[ET-2192]
While testing the uninstall script, I noticed that schema options weren't removed from the database. This could hinder recreating the tables if the plugin is uninstalled and reinstalled.
I also noticed that there was an error when trying to drop the modifiers table related to foreign key checks, so I added queries before/and after the table deletion to disable/enable foreign key checks.
The different schema option names are obtained by combining `stellar_schema_version_` and the `$schema_slug` class property for the custom table class. For previous version options, it is `stellar_schema_previous_version_` plus the `$schema` class property.
[ET-2192]: https://stellarwp.atlassian.net/browse/ET-2192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

Update uninstall script to remove schema version options

---

src/Tickets/Commerce/Order_Modifiers/app/blockEditor/fees/checkbox-fee.js
src/Tickets/Commerce/Order_Modifiers/app/blockEditor/fees/style.pcss

Issue 15 from gsheet
Fixes appearance of fees into blockeditor.
Unfortunately we dont have yet JS tests for order modifiers.
the problem: https://www.loom.com/share/5f018ff1a441419193582c411ece9835
the solution:

Keep fees appearance consinsent in block editor

---

src/Tickets/Commerce/Order_Modifiers/Table_Views/Fee_Table.php

Dont display a list of tickets each fee applies to in the fees table. Instead simply display the fee type.
How it was
How it became

Dont display list of tickets where fee is active on fee table

---

changelog/tweak-ET-2269-enable-way-to-customize-cart-cookie-name
src/Tickets/Commerce/Cart.php
tests/commerce_integration/TEC/Tickets/Commerce/CartTest.php

[ET-2269]
Adding a filter to change the name of the Tickets Commerce Cart Hash Cookie. This will allow Pantheon users to be able to sell tickets via TC.
https://share.zight.com/yAugl61k
[ET-2269]: https://stellarwp.atlassian.net/browse/ET-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2269] Tickets Commerce: Add filter for cart hash cookie name

---

src/Tickets/Seating/Service/Layouts.php
src/Tickets/Seating/Service/Maps.php
src/Tickets/Seating/Service/Seat_Types.php
tests/slr_integration/Admin/Ajax_Test.php
tests/slr_integration/Admin/Maps_Layout_Homepage_Test.php
tests/slr_integration/Orders/Cart_Test.php
tests/slr_integration/Service/Seat_Types_Test.php

Updates to be ready to update to stellarwp/schema 1.1.8
The method is already as a dynamic method in [TCMN](https://github.com/the-events-calendar/tribe-common/blob/bucket/waitlists/src/Common/Integrations/Custom_Table_Abstract.php#L64)

Convert static calls of truncate to dynamic

---

changelog/feat-enrich-ticket-management-hooks
src/modules/data/blocks/ticket/sagas.js

Enriches ticket management hooks. As a result, external plugins can offer their functionality with hooks rather than needing access to an external API.
It is backwards compatible since only the waitlists feature ( which is unreleased ) is going to take advantage of the new parameters passed through the hooks for now.

Enriches ticket management hooks

---

changelog/fix-include-status-check-as-part-of-the-transaction
changelog/fix-include-status-check-as-part-of-the-transaction-2
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Status/Pending.php
src/Tickets/Commerce/Status/Refunded.php
src/Tickets/Commerce/Status/Status_Abstract.php
src/Tickets/Commerce/Status/Trashed.php
tests/_bootstrap.php
tests/commerce_integration/TEC/Tickets/Commerce/Order_Test.php
tests/commerce_integration/TEC/Tickets/Commerce/Status/Status_Test.php
tests/commerce_integration/_bootstrap.php
tests/ct1_integration/_bootstrap.php
tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event with a series pass and single ticket orders__0.snapshot.html
tests/ft_integration/_bootstrap.php
tests/integration/_bootstrap.php
tests/slr_integration/_bootstrap.php

[ET-2281]
I am thinking that including the can_apply method in the DB transaction is the correct approach here.
What i suspect was still happening:
1) 2 requests very close to each other - probably a diff of some ms.
2) both would evaluate that the status could_apply_to => true ( e.g. both of them from pending to completed )
3) Since they had a slight difference, each one of them would => lock the order, update the order status using wp_update_post which DOES NOT care if the status actually changed before triggering the post status transition sequence, unlock the order.
What i am trying to do over here:
1) Create a transaction - so all of the following queries fail or succeed together
2) Lock the order - will fail quietly if order already locked.
3) Select the current status of the locked …

Include status check as part of the transaction

---

src/Tickets/Commerce/Order_Modifiers/Controller.php
src/Tickets/Commerce/Order_Modifiers/Modifier_Admin_Handler.php
src/admin-views/order_modifiers/modifier-table.php
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_table_render_correctly__0.snapshot.html
tests/order_modifiers_integration/Fees/__snapshots__/Create_Fees_Modifiers_Test__does_table_render_correctly__0.snapshot.html
tests/order_modifiers_integration/_bootstrap.php

[ET-2198]
This re-enables the Coupons functionality without the use of a filter. It also deprecates the filter that controlled whether Coupons are enabled.
[ET-2198]: https://stellarwp.atlassian.net/browse/ET-2198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Re-enable Coupons

---

changelog/fix-increase-sales-action-to-idempotent
src/Tickets/Commerce/Flag_Actions/Increase_Sales.php
tests/commerce_integration/TEC/Tickets/Commerce/Order_Test.php

[ET-2286]
Makes the increase sales action idempotent.
As a result is self aware whether the current order has increased the sales for which tickets and how many times for each.
Avoiding redoing the same sales increase on every consecutive fire of said action.
[ET-2286]: https://stellarwp.atlassian.net/browse/ET-2286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make increase sales action idempotent

---

src/Tickets/Commerce/Order_Modifiers/API/Fees.php

[ET-2268]
This fixes an issue reported when smoketesting when selecting Fee(s) to apply to a ticket. Only Active fees should be shown, but instead Inactive and Draft fees are also shown.
This change updates the Fee API to accept a `status` parameter, and the default without passing the parameter is to show only fees with an active status.
[ET-2268]: https://stellarwp.atlassian.net/browse/ET-2268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add status parameter and default to Fee API

---

src/resources/js/tickets.js

[ET-2287]
Fixes the JavaScript for this ticket. We were getting the input wrong using the selector and we weren't forcing it to switch to RSVP when we needed to.
See original PR for changelog, artifacts, tests, etc:
https://github.com/the-events-calendar/event-tickets/pull/3497
[ET-2287]: https://stellarwp.atlassian.net/browse/ET-2287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2287] JavaScript fix to force RSVP provider being set

---

package.json
src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifier_Relationships.php
src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers.php
src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers_Meta.php
src/Tickets/Seating/Tables/Layouts.php
src/Tickets/Seating/Tables/Maps.php
src/Tickets/Seating/Tables/Seat_Types.php
src/Tickets/Seating/Tables/Sessions.php

[ETP-956]
Simply adding methods to our custom tables that the updated Abstract requires [here](https://github.com/the-events-calendar/tribe-common/pull/2372)
These changes are backwards compatible since the Abstract is not released yet. Will be released along with the Waitlist feature.
**No need for changelog this is part of the waitlist feature.**
[ETP-956]: https://stellarwp.atlassian.net/browse/ETP-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding get_columns method to all custom tables

---

changelog/tweak-move-ajax-response-for-events-out-of-ticketscommerce
src/Tickets/Commerce/Admin_Tables/Orders_Table.php
src/Tickets/Commerce/Hooks.php
src/Tickets/Hooks.php
tests/ft_integration/Tribe/Tickets/OrderReportTest.php
tests/integration/TEC/Tickets/Commerce/Admin_Tables/Orders_TableTest.php
tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_display__0.snapshot.html
tests/integration/Tribe/Admin/OrderReportTest.php

[ETP-976]
Move method `provide_events_results_to_ajax` one level higher so that it loads regardless of Tickets Commerce.
[ETP-976]: https://stellarwp.atlassian.net/browse/ETP-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move events ajax response to be outside of tickets commerce

---

src/Tribe/Ticket_Object.php

Support UTC timezone. I know offsets can be a serious pain. but UTC itself is not.
Also our tests work on UTC, and when its not supported for time sensitive tests its an issue.

Support UTC timezone

---

changelog/fix-update_product_taskmaster
package.json
src/Tickets/Blocks/Ticket/Block.php

[ET-2293]
This issue mainly occurred on versions of WordPress lower than 7.2. When you would edit an event on the block editor that contained the ticket block using ET 5.18, and then update ET to 5.19 and edit the same event, the block would throw an error.
```
Uncaught TypeError: modules[moduleId] is undefined
__webpack_require__ https://optimistic-rook-b2a876.instawp.xyz/wp-content/plugins/event-tickets/build/Tickets/Blocks/Ticket/editor.js?ver=6.5.2:80
```
Upon trying different scenarios, we were able to find out that `moment` was being loaded as an external dependency due to Taskmaster. By removing the requirement for `moment` here that fixes the issue in ET.
[Screencast from 02-06-2025 11:31:40 AM.webm](https://github.com/user-attachments/assets/c001d02b-5b71-4f6f-a7e1-2591161a81f8) …

[ET-2293] Remove Moment from product-taskmaster

---

changelog/fix-ET-2296-order-page-template-override-path-correction
src/views/tickets/orders.php

[ET-2296]
A user reported that the template override path is slightly off and `tribe-events` works while `tribe` is inaccurate. 
Using the previous template path:
Using the updated template path:
[ET-2296]: https://stellarwp.atlassian.net/browse/ET-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-2296] Correct template override path for My Tickets page

---

tests/_support/Commerce/Attendee_Maker.php

When running the unit test suite, I noticed that we had some deprecation notices from the Faker library. These were due to calling object properties instead of class methods. This PR fixes those deprecation issues that I saw, and tweaks a few other things about the test file I noticed while going through it.
[skip-changelog]

Fix Faker deprecation notices in test suite

---

src/Tickets/Admin/Tickets/List_Table.php
src/resources/postcss/tickets-admin-tickets.pcss

Fixing issues 8 and 10 from gsheet
Pushes the sold's column value a bit to the right.
Changed default state from Active tickets to All tickets.
This is an additional request which came along the waitlist feature.

Fix all tickets CSS and default state

---

src/Tickets/Ticket_Actions.php
tests/_support/Commerce/RSVP/Ticket_Maker.php

Continuing work of PRs:
1) https://github.com/the-events-calendar/event-tickets/pull/3532
2) https://github.com/the-events-calendar/event-tickets/pull/3551
I noticed that the RSVP would not create start/end actions during its initial creation. That was because for our code, the WP_Post that would was created it was not yet a Ticket_Object.
So i am sending every request to sync RSVP dates to be performed during the request's end.
The conditionals being removed are already happening in `sync_ticket_dates_actions` - so the only thing that is affected by said change is that more IDs would be eligible for date sync during the request's end. But they will be correctly be filtered based on if they are Tickets or not.
The reason is simple: order of meta keys is different for tests vs production. …

Amend listener for RSVP date start/end

---

src/admin-views/commerce/orders/single/order-items-coupons.php
src/admin-views/commerce/orders/single/order-items-metabox-item.php
src/admin-views/commerce/orders/single/order-items-metabox.php
tests/_support/Traits/With_Test_Orders.php
tests/integration/TEC/Tickets/Commerce/Admin/Singular_Order_PageTest.php
tests/integration/TEC/Tickets/Commerce/Admin/__snapshots__/Singular_Order_PageTest__it_should_match_order_items__0.snapshot.html
tests/integration/TEC/Tickets/Commerce/Admin/__snapshots__/Singular_Order_PageTest__it_should_render_coupons__0.snapshot.html

[ET-2247] (Part 1)
This PR adds coupons to the single order admin view. It adds a new template file tailored to displaying coupons attached to the order.
[ET-2247]: https://stellarwp.atlassian.net/browse/ET-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add coupons section to single order display

---

src/Tickets/Commerce/Order_Modifiers/Modifier_Admin_Handler.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Modifier_Abstract.php
tests/order_modifiers_integration/Modifier_Admin_Handler_Test.php

QA Issue spreadsheeet – item `#002`
This updates the messages that are displayed in the modifier admin area to use the actual modifier type (e.g. "Coupon" or "Fee").
I also did some cleanup of some of the logic in relevant places nearby in the codebase.
**Before:**
**After:**

Update modifier messages to use correct modifier type

---

src/Tickets/Commerce/Order_Modifiers/API/Coupons.php
src/views/v2/commerce/checkout/order-modifiers/coupons.php

QA Issue spreadsheet – Item `#003`
This PR adjusts the display of the coupon in the checkout to use the slug instead of the display name.
It also ensures the API only allows one coupon at a time in the cart.
**Before:**
**After:**

Use coupon code for display instead of coupon name

---

changelog.md
readme.txt
src/resources/js/commerce/gateway/stripe/checkout.js
src/views/v2/commerce/checkout.php
src/views/v2/commerce/gateway/stripe/container.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_not_on_sale_should_match_html__1.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket with multiple series pass from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__single ticket from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__ticket with series pass from an event__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_complex_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_simple_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $10, Fee $5, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $15, Fee $2, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $20, Fee $3, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $50, Fee $10, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_not_calculate_fees_for_free_tickets__0.snapshot.html

[ET-2327]
Replaced form element containing Tickets Commerce checkout with section. The form would result in form in form which is invalid html and every browser does its best to try to decide where each form ends. But it results into broken checkout with PP.
[ET-2327]: https://stellarwp.atlassian.net/browse/ET-2327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Paypal Checkout Fixes

---

src/resources/js/v2/tickets-commerce.js
src/resources/postcss/tickets-commerce/_checkout.pcss
src/resources/postcss/tickets-forms.pcss
src/views/v2/commerce/checkout/order-modifiers/coupons.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/__snapshots__/CartFooterTest__test_should_render_cart__0.snapshot.html
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/__snapshots__/CartTest__test_should_render_cart__0.snapshot.html
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_not_on_sale_should_match_html__1.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket with multiple series pass from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__single ticket from an event__0.snapshot.html
tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__ticket with series pass from an event__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Coupons_Test__it_should_calculate_coupons_simple_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_complex_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_simple_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $10, Fee $5, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $15, Fee $2, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $20, Fee $3, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $50, Fee $10, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_not_calculate_fees_for_free_tickets__0.snapshot.html

QA spreadsheeet – issue `#012`
This changes the coupon input field to be hidden initially, and a new link "Add coupon code" is displayed instead. Clicking this link will then show the coupon input as before.
https://github.com/user-attachments/assets/7dd745b4-7bed-48c1-b1e3-0f7f87da6e66

Use "Add coupon code" button before showing coupon input

---

src/Tickets/Commerce/Order_Modifiers/Modifiers/Coupon.php
src/admin-views/order_modifiers/coupon-edit.php
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Emojis in Name and Slug__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Excessively Large Amount__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Long Decimal Value__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Special Characters__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Flat Coupon__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Percent Coupon__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_with_no_data__0.snapshot.html

QA Issue `#033`
Update the coupon usage input field to error on negative numbers. It will also convert 0 to be an empty field, meaning no limit.
**Before:**
https://github.com/user-attachments/assets/b783c2cc-d3bd-47de-97a4-139ae88bbeff
**After:**
https://github.com/user-attachments/assets/e149805e-bb45-4cd4-ba3d-e9d05363fdd1

Validate coupon usage to be positive or empty

---

src/resources/js/admin/order-modifiers/amount-field.js

QA Issue `#034`
This updates the custom validation attached to the `amount` field for coupons and fees. Since we're overriding the normal validation, we need to also remove the `.tribe-validation-valid` class from the `<form>` element. This will ensure that the validation library prevents the Submit button from working until all validation passes. By extension, this also ensures that data which has already been entered isn't lost on page refresh.
**Before:** Page reloads on submit, even with invalid data.
https://github.com/user-attachments/assets/c9c2c8a8-4f20-4c8b-a2f9-cef785b52bb6
**After:** Page is prevented from reloading.
https://github.com/user-attachments/assets/a36b71dc-631b-48bc-8fe5-8c99f3c07f7f

Update JS validation to prevent submit when amount is invalid

---

src/Tickets/Commerce/Cart/Abstract_Cart.php
src/Tickets/Commerce/Order.php
src/Tickets/Commerce/Order_Modifiers/API/Coupons.php
src/resources/js/v2/tickets-commerce.js
tests/order_modifiers_integration/API/Coupons_Test.php
tests/order_modifiers_integration/Checkout/Coupons_Test.php
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_render_fees__0.snapshot.html

QA Issue `#036`
This ensures that orders and the cart value cannot be less than zero. 
[skip-changelog] *Skipping the changelog as this is fixing a bug in a new feature.*
The cause of this issue was the work done in #3612. In that PR, the coupon calculation was moved to the `get_cart_total()` method out of the `get_cart_subtotal()` method. At that point, I didn't include a check after the dynamic calculations to ensure the total wasn't less than zero.
While fixing that particular issue, I found that the Order creation process also has the wrong values set for new orders. Upon digging into the `Order` class, I found that it is doing its own calculations of totals entirely separate from the cart. So, this PR does the following:
1. Updates the `Abstract_Cart::get_cart_total()` method to …

Ensure cart and order values cannot be less than zero

---

changelog/fix-percent-input-display
src/Tickets/Commerce/Order_Modifiers/Controller.php
src/Tickets/Commerce/Values/Currency_Value.php
src/Tickets/Commerce/Values/Digit_Separators.php
src/Tickets/Commerce/Values/Percent_Value.php
tests/wpunit/TEC/Tickets/Order_Modifiers/Values/Currency_Value_Test.php
tests/wpunit/TEC/Tickets/Order_Modifiers/Values/Percent_Value_Test.php

QA issue `041`
This fixes the display and handling of Percent values in the "Amount" input field for Coupons and Fees. Previously, if the site settings use `,` for the decimal separator instead of `.`, the amount will not render correctly. For example, a `10%` value entered would be converted to `1000%` after saving.
The reason for this behavior is because the `Percent_Value` class wasn't handling number formats correctly, and was instead *always* using a `.` for the decimal separator (and `,` for the thousands separator).
This PR does the following to fix this issue:
1. Adds a new `Digit_Separators` trait that can be used across value classes
1. Applies the `Digit_Separators` trait to both `Currency_Value` and `Percent_Value`
1. Updates the `get_as_string()` method in `Percent_Value` to …

Fix input display for pecent to use correct thousand/decimal settings

---

src/Tickets/Commerce/Order_Modifiers/Checkout/Coupons.php
src/resources/postcss/tickets-commerce/_checkout.pcss
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_complex_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_calculate_fees_and_store_them_correctly_simple_math__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $10, Fee $5, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $15, Fee $2, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $20, Fee $3, Application All__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $50, Fee $10, Application Per__0.snapshot.html
tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_not_calculate_fees_for_free_tickets__0.snapshot.html

Related to QA `40`
This PR moves the position of the coupon input field in the checkout, and tweaks the styling to give it some more padding.
[skip-changelog] *No changelog needed; This is adjusting an unreleased feature.*
https://github.com/user-attachments/assets/fc8c8e0c-985f-46da-9b21-b09d8a3dd21d
https://github.com/user-attachments/assets/6c82aa21-4833-4964-b52d-dece16446d15

Update the position of the coupon field in checkout

---

src/Tickets/Commerce/Order_Modifiers/Modifier_Admin_Handler.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Coupon.php
src/admin-views/order_modifiers/coupon-edit.php
src/resources/js/admin/order-modifiers/amount-field.js
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Emojis in Name and Slug__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Excessively Large Amount__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Long Decimal Value__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Coupon - Special Characters__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Flat Coupon__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_correctly__Percent Coupon__0.snapshot.html
tests/order_modifiers_integration/Coupons/__snapshots__/Create_Coupon_Modifiers_Test__does_edit_screen_render_with_no_data__0.snapshot.html
tests/order_modifiers_integration/Modifier_Admin_Handler_Test.php

Related to QA item `#40`
This upates the validation logic for coupons. When a coupon is set to a percentage, it no longer allows for a value over 100%. This is handled both by JS validation and by PHP validation (in case the JS validation fails or is disabled somehow).
[skip-changelog] *No changelog needed; This is modifying an unreleased feature.*
https://github.com/user-attachments/assets/149827a9-3a4c-42c9-a684-eff9f8465019
https://github.com/user-attachments/assets/2ed2d410-5f09-4a6c-afe3-04465163fec1

Limit percent coupons to 100%

---

src/Tickets/Commerce/Cart/Abstract_Cart.php
src/Tickets/Commerce/Cart/Agnostic_Cart.php
src/Tickets/Commerce/Order_Modifiers/API/Coupons.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Abstract_Fees.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Coupons.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Fees.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Gateway/Stripe/Coupons.php
src/Tickets/Commerce/Order_Modifiers/Checkout/Gateway/Stripe/Fees.php
src/Tickets/Commerce/Order_Modifiers/Models/Coupon.php
src/Tickets/Commerce/Order_Modifiers/Modifiers/Modifier_Manager.php
src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
src/Tickets/Commerce/Values/Float_Value.php
tests/commerce_integration/TEC/Tickets/Commerce/Cart/Agnostic_CartTest.php
tests/commerce_integration/TEC/Tickets/Commerce/CartTest.php
tests/order_modifiers_integration/API/Coupons_Test.php
tests/order_modifiers_integration/Checkout/Fees_Test.php
tests/order_modifiers_integration/Checkout/Gateway/PayPal/Coupons_Test.php
tests/order_modifiers_integration/Checkout/Gateway/PayPal/PayPal_Fees_Test.php
tests/order_modifiers_integration/Checkout/Gateway/Stripe/Stripe_Fees_Test.php

Related to QA Item `#40`
This PR updates the logic for cart items. The end goal is to ensure that Coupons are applied to Fees in addition to other cart items.
Notable changes:
1. The `Abstrat_Cart` class has changes to how the subtotal and total are calculated:
1. There are 2 new filters:
1. `tec_tickets_commerce_get_cart_additional_values_total` – Fired inside `get_cart_total()`, this allows for adding items to the cart total calculations. These items are excluded from the cart subtotal.
1. `tec_tickets_commerce_get_cart_additional_values_subtotal` – Same as above, except it is fired within `get_cart_subtotal()`. It allows for items that should be included in the subtotal calculations.
1. Both of the filters utilize `Precision_Value` objects instead of `Value` objects.
1. Inside …

Adjust how coupons are applied to include fees

---

tests/_support/Commerce/OrderModifiers/Coupon_Creator.php
tests/_support/Traits/Tribe_URL.php
tests/commerce_integration/TEC/Tickets/Commerce/Cart/Agnostic_CartTest.php
tests/order_modifiers_integration/Checkout/Gateway/PayPal/Coupons_Test.php

This replaces `TBD` with the correct version `5.21.0` for the Colossus release.
[skip-changelog]

Replace TBD with correct version

---

changelog/fix-tc-support-for-etp-seating
src/Tickets/Seating/Commerce/Controller.php

[TICKET_ID]
* TicketsCommerce conditionals were directly used inside ETP, which caused Fatal errors when Seating with Woo is enabled without TicketsCommerce.
* This PR utilizes the filters provided by ETP to provide the data as needed thus avoiding a direct dependency.
🎥 screencast(s): https://share.cleanshot.com/JYB4ZK5f

Fix - Add TicketsCommerce support for ETP seating assets conditionals.

---

src/Tickets/Commerce/Ticket.php
src/Tribe/Tickets.php

No ticket.
Fixing waitlist snapshot tests failing from time to time by respecting the ticket menu order being provided.
The ticket order is set after the change - before all the tickets had -1 as their menu order.

Will now respect ticket order if provided

---

src/Tickets/Blocks/Ticket/Block.php
src/Tickets/Commerce/Order_Modifiers/Admin/Order_Modifier_Fee_Metabox.php
src/Tickets/Commerce/Order_Modifiers/Modifier_Admin_Handler.php
src/Tickets/Seating/Assets.php
src/Tickets/Seating/app/utils/index.js
src/Tribe/Editor/Assets.php
src/Tribe/Main.php
tests/order_modifiers_integration/Admin/Order_Modifier_Fee_Metabox_Test.php
tests/order_modifiers_integration/Modifier_Admin_Handler_Test.php
tests/slr_jest/_bootstrap.js

Fixes various asset issues after migation to Tyson.
Most important one was `tec.tickets.seating.utils` was being used as an object for webpack to expose AND
as a localized data entry from php.
One of the two was working only - so i changed the data that php was localizing data at.

Fix various issues after tyson migration

---

src/Tribe/Metabox.php

[ETP-963]
One of the tests failed with a "3 params needed, 2 submitted" error. The test does submit 2 params and the third should be defaulted to `null` but apparently that's not PHP 8+ compatible.
[ETP-963]: https://stellarwp.atlassian.net/browse/ETP-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make the ticket type optional for PHP 8+ compatibility

---

event-tickets.php
src/Tickets/Admin/Onboarding/Controller.php
src/Tickets/Admin/Onboarding/Tickets_Landing_Page.php
src/Tribe/Main.php
tests/ft_ct1_migration.suite.dist.yml
tests/ft_ct1_migration/_bootstrap.php

[ET-2358] [ET-2359]
This deprecates the `Main.php` instance of `Tribe__Admin__Activation_Page` and the function that instantiates it. Instead, it leverages the new Onboarding Wizard's controller to handle the redirect.
The redirect happens immediately on a standalone ET install. 
After a bulk activation of ET and other plugins, it will happen on the next ET admin page load.
https://www.loom.com/share/f185abe7917a4337a253e53cad8061bd?sid=77600b72-7236-46aa-9f2a-69d5df4535f3
https://www.loom.com/share/698a93974d0a4dc7aa5b5124d96cf2e3?sid=4e8f82f0-6b57-43d9-a53a-b68a8d3e93d9
[ET-2358]: https://stellarwp.atlassian.net/browse/ET-2358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-2359]: …

Deprecate the old landing page and redirect to the new one.

---

changelog/fix-ET-2409-seating-coupons
src/resources/js/v2/tickets-commerce.js

[ET-2409]
When using a ticket with Seating, and applying a coupon that reduces the price to zero (100% off), the cart contents would be cleared and the timer reset (in the seating JS code, this is an interrupt). This PR resolves that issue.
The primary change is an update to the JS code responsible for handling the coupon process. The Coupon JS will now communicate with the Seating JS to ensure that an interrupt is *not* performed, which will allow the timer to continue running as normal, and the checkout process should also be able to continue as normal.
https://github.com/user-attachments/assets/8c63843c-5223-4f93-93f3-f495bdaecae6
[ET-2409]: https://stellarwp.atlassian.net/browse/ET-2409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ensure 100% off coupons work correctly with Seating tickets

---

src/Tickets/Admin/Help_Hub/ET_Hub_Resource_Data.php
src/Tickets/Admin/Help_Hub/Provider.php
src/Tickets/Telemetry/Telemetry.php
src/Tribe/Admin/Provider.php
src/Tribe/Admin/Settings.php
tests/integration/TEC/Tickets/Admin/Help_Hub/Template_Test.php
tests/integration/TEC/Tickets/Admin/Help_Hub/__snapshots__/Template_Test__overall_template__0.snapshot.html
tests/integration/TEC/Tickets/Admin/Help_Hub/__snapshots__/Template_Test__section_rendering__0.snapshot.html
tests/slr_integration/__snapshots__/Settings_Test__test_seating_reservation_setting_is_included_after_login_requirements__0.snapshot.json
tests/slr_integration/__snapshots__/Settings_Test__test_seating_reservation_setting_not_included_with_invalid_license__0.snapshot.json
tests/slr_integration/__snapshots__/Settings_Test__test_seating_reservation_setting_not_included_with_no_license__0.snapshot.json

- New Help Hub page for Event Tickets
- Resource sections for Getting Started, Tickets & RSVPs, Attendee Management, and Email tutorials
- Integration with existing TEC Common Help Hub system

Updated Help Hub for ET.

---

src/Tickets/Admin/Onboarding/Controller.php
src/Tickets/Telemetry/Telemetry.php

[ET-2380]
[ET-2380]: https://stellarwp.atlassian.net/browse/ET-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ensure the telemetry modal is not shown on the onboarding landing page.

---

src/Tickets/Commerce/Gateways/Square/Order.php
src/Tickets/Commerce/Tables/Webhooks.php

This PR aims to fix possible differences between our local calculation and square calculation during the rounding phase.
For example lets assume we buy a ticket priced at 10$ with a fee of 1% and then we apply a coupon of 25%.
The math are: 10$ + 0.1$ = 10.1$
Coupon: 25% of 10.1 is 2.525 exactly.
Since USD/EUR has a precision of 2 decimals we need to adjust.
Our TC transform the 2.525 to 2.52, but Square transformst it to 2.53 which creates the issue.
We proactively use the calculate order endpoint in order to be able to adjust, with a discount or a fee based on the `square - local` total.

Account for square miscalculations

---

src/Tickets/Admin/Onboarding/Steps/Communication.php
src/Tickets/Admin/Onboarding/Steps/Events.php
src/Tickets/Admin/Onboarding/Steps/Settings.php
src/Tickets/Admin/Onboarding/Steps/Welcome.php

[TICKET_ID]
In our Ajax callback functions we returned errors with [add_fail_message()](https://github.com/the-events-calendar/tribe-common/blob/master/src/Common/Admin/Onboarding/Steps/Abstract_Step.php#L117C18-L117C34). That sent the `500` status code with the response, causing the flow to break without a way for the user to continue. Replacing it with the more general [add_message()](https://github.com/the-events-calendar/tribe-common/blob/master/src/Common/Admin/Onboarding/Steps/Abstract_Step.php#L95C18-L95C29) would allow user to complete the Wizard even if a step failed.

Gracefully handle error messages

---

changelog/fix-ET-2517-pages-my-tickets-link
src/Tribe/Tickets_View.php

[ET-2517]
WordPress treats posts and pages differently in both its canonical redirect system and conditional functions, so when trying to redirect users to the My Tickets page for tickets on a Page, the ticket parameters were not being preserved. This PR addresses this with two additions:
- Added `redirect_canonical` filter and `preserve_tickets_parameter_in_canonical_redirect` method to preserve ticket parameters during WordPress canonical redirects
- Updated conditional logic in `intercept_content()` method to properly handle pages
https://github.com/user-attachments/assets/2a7d650d-39ce-45b6-a256-b7126ed8b497
[ET-2517]: https://stellarwp.atlassian.net/browse/ET-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-2517 Fix link for My Tickets on Pages

---

changelog/fix-ET-2530-conditionally-show-more-info
src/views/v2/commerce/checkout/cart/item/details.php
src/views/v2/commerce/checkout/cart/item/details/toggle.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/ItemDetailsTest.php
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/__snapshots__/ItemDetailsTest__test_should_render_cart_item_details_without_toggle_when_no_description__0.snapshot.html
tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/__snapshots__/ItemDetailsTest__test_should_render_cart_item_details_without_toggle_when_show_description_false__0.snapshot.html
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_not_on_sale_should_match_html__1.php
tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php

[ET-2530]
The toggle for showing the description of a ticket was showing even if the ticket had no description. This adds a simple conditional to only show the toggle/description if there's something to show. 
https://github.com/user-attachments/assets/dde35674-95c1-46b2-b3a9-4ef7a8037035
[ET-2530]: https://stellarwp.atlassian.net/browse/ET-2530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-2530 Add conditional for ticket description

---

tests/_data/ft_blocks.sql
tests/_data/ft_ct1_migration/dump.sql
tests/_data/ft_ct1_migration/options_dump.sql
tests/_data/ft_smoketest.sql
tests/_data/seating.sql

This PR only updates the database dumps used in tests to make sure they
will be compatible with MySQL 5.5 that will be the default for PHP 7.4
builds in the next version of slic.
[See related slic PR](https://github.com/stellarwp/slic/pull/218)
Command used:
```bash
find ./tests -type f -name "*.sql" | xargs -I{} sed -i.bak 's/utf8mb4_unicode_520_ci/utf8mb4_unicode_ci/g' {} && find ./tests -name "*.sql.bak" -delete
```

Update db dumps for MySQL 5.5 compat

---

changelog/fix-TEC-5529-str_replace-deprecation-message
src/Tribe/Commerce/PayPal/Orders/Report.php

[TEC-5529]
The first parameter of `add_submenu_page()` was null, which was then passed to `str_replace()` and `str_pos()`, resulting in deprecation messages. Replacing `null` with an empty string `''` solves the issue and keeps the page hidden.
[Screenshot showing the deprecation messages](https://dl.dropboxusercontent.com/scl/fi/f4p507ns81bhz2aug71s0/shot_250708_171216.png?rlkey=4tqlcmbmpk6c1p6n6zwkk2fi8&dl=0)
[TEC-5529]: https://stellarwp.atlassian.net/browse/TEC-5529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TEC-5529 Fix add_submenu_page deprecation message
