- src/Tribe/RSVP.php
Ref: #92 
/cc @borkweb @zbtirrell
> add hooks for rsvp

- src/Tribe/Main.php
See [C#28582](https://central.tri.be/issues/28582) and [Core PR 521](https://github.com/moderntribe/the-events-calendar/pull/521) for context.
> Register with template updates checker | 28582

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#39791](https://central.tri.be/issues/39791)
> Bad Variable usage

- src/Tribe/Main.php
_Ref:_ [C#38122](https://central.tri.be/issues/38122)
> Add an HTML anchor

- src/Tribe/Tickets_Handler.php
Let custom columns added to the attendee list table carry over to CSV/email exports. Also simplifies the export columns logic a tad.
[C#30021](https://central.tri.be/issues/30021)
> Simplify attendee CSV export and support custom columns | 30021

- src/Tribe/RSVP.php
Related: https://github.com/moderntribe/event-tickets-plus/pull/75
See: https://central.tri.be/issues/34348
> Adding product_id into the Attendee data to support custom meta emails

- src/Tribe/RSVP.php
Related: https://github.com/moderntribe/event-tickets-plus/pull/78
See: https://central.tri.be/issues/43663
> Add new actions for each commerce engine that occur AFTER ticket save

- src/Tribe/RSVP.php
Reference PR: https://github.com/moderntribe/event-tickets/pull/105
> Fix inaccurate hook names that were added in #105

- src/Tribe/Tickets_Handler.php
See: https://central.tri.be/issues/43781
> Fix fatal that prevents the email modal from functioning on attendees

- src/Tribe/Global_Stock.php
- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets.php
- src/Tribe/Tickets_Handler.php
- src/admin-views/meta-box.php
- src/admin-views/rsvp-metabox-advanced.php
- src/resources/js/frontend-ticket-form.js
- src/resources/js/tickets.js
Adds facilities to work with global stock (but doesn't really swing into action unless a provider declares global stock support).
[C#18656](https://central.tri.be/issues/18656)
> Basis for global stock

- src/Tribe/Attendees_Table.php
Ticket https://central.tri.be/issues/23466
checkin those we want to check in, view order for those we shoud not be able to check in
> added check for order status

- src/Tribe/RSVP.php
_Ref:_ [C#42388](https://central.tri.be/issues/42388)
> Postpone Register Resources

- src/admin-views/rsvp-metabox-advanced.php
_Ref:_ [C#43494](https://central.tri.be/issues/43494)
> Add a non-admin message

- src/Tribe/RSVP.php
_Ref:_ [C#44922](https://central.tri.be/issues/44922)
> Forgot to change a variable... #fun

- readme.txt
- src/Tribe/Main.php
_Ref:_ [C#36246](https://central.tri.be/issues/36246)
> L10N Files using helper

- src/Tribe/Ticket_Object.php
- src/views/tickets/rsvp.php
My PullRequest comes originally comes from here:
https://theeventscalendar.com/support/forums/topic/no-message-end-date-for-sales-reached/
I think the user should be informed when tickets are no longer or not yet on sale. Also i added a message when there are no Tickets available for this event!. As this only comes up when Event Tickets is installed it should work out for the users of the plugin.
OLD PR:
https://github.com/moderntribe/event-tickets/pull/95
https://github.com/moderntribe/event-tickets/pull/94
Internal ticket reference: https://central.tri.be/issues/45467
> Messages to inform user of the availability of Tickets

- src/Tribe/Tickets.php
> Fix capability check problems #135

- src/Tribe/Main.php
- src/resources/css/tickets-embed.css
- src/resources/css/tickets-embed.min.css
Related: https://github.com/moderntribe/the-events-calendar/pull/647
See: https://central.tri.be/issues/43938
> Hook into the oembed template to inject a buy button for tickets

- src/Tribe/Shortcodes/User_Event_Confirmation_List.php
> Now using constant to prevent fatal on 5.2

- readme.txt
- src/Tribe/Tickets_Handler.php
- src/template-tags/tickets.php
- src/views/tickets/rsvp.php
See: https://central.tri.be/issues/46524
> changing the translation slug to match the plugin

- readme.txt
Stay in sync with changes in SVN repo.
> Add screenshot section to readme | spotfix

- src/Tribe/RSVP.php
- src/Tribe/Tickets.php
- src/Tribe/Tickets_View.php
- src/views/tickets/orders-rsvp.php
- src/views/tickets/rsvp.php
> RSVP + Meta for QA feedback

- src/Tribe/Tickets_View.php
> Forgot to Add the Check for active TEC

- src/Tribe/RSVP.php
- src/Tribe/Tickets.php
- src/admin-views/tribe-options-tickets.php
- src/views/tickets/rsvp.php
Updates to the way we handle RSVP/ticket purchase login requirements.
https://central.tri.be/issues/44347#note-22
> Revise ticket login requirements

- src/Tribe/Tickets.php
> Fix Notice on RSVP and Meta

- src/Tribe/RSVP.php
> One more bug, wasn't saving Meta + RSVP

- src/Tribe/RSVP.php
> Clean cache after adding new tickets.

- src/Tribe/Tickets_View.php
> One last conditional was failing for Meta Checking

- src/Tribe/Tickets_View.php
> Renaming the filters, now is the best time to make it right

- src/Tribe/Attendees_Table.php
_Ref:_ [C#46198](https://central.tri.be/issues/46198)
> When dealing with TB_iframe links we need to add_thickbox

- src/Tribe/Main.php
_Ref:_ [C#43595](https://central.tri.be/issues/43595)
> Remove and Deprecate

- src/Tribe/JSON_LD/Order.php
_Ref:_ [C#43595](https://central.tri.be/issues/43595)
> Check for Free usage on the JSON-lD prices

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#46198](https://central.tri.be/issues/46198)
> Resolving Attendees email

- src/Tribe/Tickets_View.php
- src/views/tickets/orders-rsvp.php
This is best reviewed via `?w=1`
Related: https://github.com/moderntribe/event-tickets-plus/pull/177
See: https://central.tri.be/issues/61955
> Group RSVPs by name/email combinations

- src/views/tickets/orders.php
https://central.tri.be/issues/62398
_Related:_ https://github.com/moderntribe/event-tickets-plus/pull/186
> update path for template part due to directory name change

- src/Tribe/RSVP.php
_Ref:_ [C#62442](https://central.tri.be/issues/62442) -- Add qr tickets id for RSVP Tickets Email
> QR Code Id for RSVP

- src/admin-views/rsvp-metabox-advanced.php
_Ref:_ [C#62321](https://central.tri.be/issues/62321)
_Rel:_ moderntribe/tribe-common#114
> Make sure Bumpdown is compatible with the new JS

- readme.txt
- src/admin-views/list.php
I'd like to revisit this as I think the graphical representation that B@rry mentioned in the ticket is a really neat way to solve the problem.  My only concern at this point is having the time to do it well.
https://central.tri.be/issues/61962
> removing description to eliminate overlap

- src/Tribe/RSVP.php
- src/admin-views/attendees.php
_Ref:_ [C#44799](https://central.tri.be/issues/44799)
> Front-End usage of Attendees for Community Usage

- readme.txt
- src/Tribe/Main.php
related PR: https://github.com/moderntribe/tribe-common/pull/128
See: https://central.tri.be/issues/63557
> init the ratings

- src/Tribe/CSV_Importer/Rows.php
- src/Tribe/Main.php
Related:
* https://github.com/moderntribe/the-events-calendar/pull/848
* https://github.com/moderntribe/event-tickets-plus/pull/210
See: https://central.tri.be/issues/61240#note-17
> Add support for EA CSV importing

- readme.txt
- src/Tribe/Tickets.php
_Ref:_ [C#62303 ](https://central.tri.be/issues/62303 ) Utilize new tribe_is_event_past() conditional to change tickets not available message.
> tribe_is_past_event conditional and ticket messages

- readme.txt
- src/Tribe/RSVP.php
Follow-up to: https://github.com/moderntribe/event-tickets/pull/244
See: https://central.tri.be/issues/65836
> Cleaning up some tr1b0t sniffs and adding changelog

- src/Tribe/Admin/Move_Tickets.php
- src/Tribe/Admin/Ticket_History.php
Improves audit trail messages, corrects docblock entry.
[#61724](https://central.tri.be/issues/61724)
> Move tickets: minor fixes

- src/Tribe/CSV_Importer/Rows.php
- src/Tribe/Main.php
- src/views/tickets/orders-rsvp.php
- src/views/tickets/rsvp.php
See: https://central.tri.be/issues/62458
Also updated the common hash
> add some translation context around "RSVP" usage

- readme.txt
- src/Tribe/CSV_Importer/RSVP_Importer.php
- src/views/tickets/orders-rsvp.php
See: https://central.tri.be/issues/62458
> once again, some translation improvements

- src/Tribe/Tickets.php
Ticket: https://central.tri.be/issues/63959
This PR adds a check to make sure TEC and PRO related actions are not attempted when the plugins are not active.
> conditionally update the ticket cache

- src/admin-views/rsvp-metabox-advanced.php
Ticket https://central.tri.be/issues/65617
Builds on https://github.com/moderntribe/tribe-common/pull/191
Pass the `bumpdown-class` over to the bumpdown code
> added tjhe `bumpdown-class` data attribute

- codeception.dist.yml
- composer.lock
- src/Tribe/RSVP.php
- src/Tribe/RSVP/Attendance_Totals.php
- src/Tribe/Tickets_View.php
- tests/integration/Tribe/Tickets/RSVPTest.php
- tests/integration/Tribe/Tickets/Tickets_ViewTest.php
Ticket: https://central.tri.be/issues/64669
This PR updates the RSVP tickets code to:
* not increase sales when an RSVP is Not Going
* increase sales when Going
* allow a robust filtering of the RSVP states with variable stock sizes
* tests for all the code (integration as it's as small as I could go)
* add some filters to prevent email and anywhere I felt we were lacking
> Implement support for RSVP and sales support

- package-whitelist.json
See: https://central.tri.be/issues/67011
> Include clipboard.js when packaging

- src/admin-views/admin-welcome-message.php
Tidy up the welcome message HTML.
> Remove stray angle bracket | spotfix

- src/admin-views/admin-welcome-message.php
minor language tweaks and some translation fixes
> fix the language and translations

- src/Tribe/CSV_Importer/RSVP_Importer.php
- src/Tribe/RSVP.php
Also adding some labels to the post type object for better messaging.
Related: https://github.com/moderntribe/the-events-calendar/pull/1059
See: https://central.tri.be/issues/67883
> Hook RSVP ticket imports into the Aggregator Record Activity counting

- src/Tribe/Metabox.php
> Allow localization of the decimal character to happen outside of the admin env | #67913

- readme.txt
- src/Tribe/Attendees_Table.php
https://central.tri.be/issues/66004
> Rejig attendee report columns

- src/admin-views/tribe-options-tickets.php
Avoid fatals when only ET is active and TEC is not
> check for TEC existenc to add settings

- readme.txt
- src/Tribe/Admin/Columns.php
- src/Tribe/Admin/Columns/Tickets.php
- src/Tribe/Cache/Abstract_Cache.php
- src/Tribe/Cache/Central.php
- src/Tribe/Main.php
- src/admin-views/tribe-options-tickets.php
Ticket: https://central.tri.be/issues/67176
This PR adds a non sortable (due to missing criteria) column the list table of any ticketing supporting post.
Note: a post can have 0+ tickets, each ticket can have a stock or have an unlimited stock; if just one ticket for a post has unlimited stock then the percentage will not render.
> Add at a glance attendee information.

- src/admin-views/rsvp-metabox-advanced.php
See: https://central.tri.be/issues/41396
Related: https://github.com/moderntribe/event-tickets-plus/pull/245
> improving tooltip text warning for recurring event tickets in CE

- package-whitelist.json
Builds on https://github.com/moderntribe/tribe-common/pull/266
> whitelist select2 script from common

- src/Tribe/Attendees_Table.php
[#69686/R125 findings](https://central.tri.be/issues/69686)
> Fix typo | spotfix

- src/Tribe/Main.php
- src/views/tickets/rsvp.php
_Ref:_ [C#65755](https://central.tri.be/issues/65755)
> Clean RSVP Template and Use new initialization for Common

- src/Tribe/Attendees_Table.php
- src/admin-views/attendees.php
https://central.tri.be/issues/70431
_related: https://github.com/moderntribe/events-community-tickets/pull/60_
> adding classes to reduce specificity when styling

- readme.txt
- src/views/shortcodes/my-attendance-list-logged-out.php
- src/views/shortcodes/my-attendance-list.php
- src/views/tickets/email-ticket-type-moved.php
- src/views/tickets/email-tickets-moved.php
- src/views/tickets/rsvp.php
https://central.tri.be/issues/68229
> Add theme override instructions | #68229

- src/Tribe/Tickets.php
_Ref:_ [C#70673](https://central.tri.be/issues/70673)
_Original:_ #311
> Attendees Filtering Improved

- readme.txt
- src/Tribe/Tickets.php
_Ref:_ [C#72812](https://central.tri.be/issues/72812)
> Remove the is_a from Tickets

- readme.txt
- src/views/tickets/email.php
Replacing https://github.com/moderntribe/event-tickets/pull/330
> Email: add State/Province & Zip to Venue's address

- src/views/tickets/email.php
To fix for https://central.tri.be/issues/72475#note-6
> Also check for _VenueStateProvince meta field

- src/views/tickets/email.php
See central ticket for screenshots
https://central.tri.be/issues/72475#note-11
> non-linked text no longer looks like a link

- readme.txt
- src/template-tags/tickets.php
- src/views/tickets/email-non-attendance.php
- src/views/tickets/email-ticket-type-moved.php
- src/views/tickets/email.php
See: https://central.tri.be/issues/72499
> Don't use TEC functions in ET unless we check for existence first

- readme.txt
- src/Tribe/Tickets_View.php
- src/template-tags/tickets.php
See: https://central.tri.be/issues/70485
> Only filter content on post types that have tickets enabled

- readme.txt
- src/Tribe/Tickets.php
Related: https://github.com/moderntribe/tribe-common/pull/332
See: https://central.tri.be/issues/70485
> Only execute attendee list logic if not found in the transient

- src/Tribe/Tickets.php
- src/template-tags/tickets.php
_Ref:_ [C#71094](https://central.tri.be/issues/71094) - Do not show Buy Now or Ticket Counts if No Tickets, but there is a cost field.
> #71094 - Add Support For Cost Field Without Tickets

- src/Tribe/Tickets_Handler.php
> Fixing language domain

- src/Tribe/RSVP.php
Added a couple filters. The idea came from our potential spotfixes ticket:https://central.tri.be/issues/75171
> Added filters to register post type args

- readme.txt
- src/admin-views/admin-welcome-message.php
_Ref:_ [C#75575](https://central.tri.be/issues/75575)
> 75575 | Fix Some Typos

- readme.txt
- src/Tribe/Main.php
- src/Tribe/Tickets.php
Ensure the ticket form anchor moves with the ticket form itself.
:ticket: [#77992](https://central.tri.be/issues/77992)
> Fix ticket form anchor issue | #77992

- src/template-tags/tickets.php
Fixes:
* check for tickets being on sale before showing CTAs
* change stock text for RSVPs
* fix the sold-out-html
* fix number formatting
See: https://central.tri.be/issues/79024
There are more fixes to be done for the associated ticket.
> Tweaks for Buy Now Buttons

- src/Tribe/Data_API.php
- src/Tribe/Tickets.php
_Ref:_ [C#70578](https://central.tri.be/issues/70578)
> #70578 - add documentation and cast event ids as int

- readme.txt
- src/Tribe/Admin/Columns/Tickets.php
- src/Tribe/Ticket_Object.php
* Add a new hook making it easier to disable the attendee (WP_List_Table) column
* Make it possible to supply ticket objects with a callback to lazily determine various values
:ticket: [#79683](https://central.tri.be/issues/79683)
> Tweaks and enhancements to potentially allow better performance | #79683

- src/Tribe/Main.php
- src/Tribe/Tickets.php
- src/views/tickets/rsvp.php
See: https://central.tri.be/issues/80142
> fixing anchor link

- src/Tribe/Ticket_Object.php
See: https://central.tri.be/issues/80281
> don't allow stock to be reported as negative

- src/Tribe/Main.php
- src/template-tags/tickets.php
_Ref:_ [C#80276](http://central.tri.be/issues/80276)
---
> Simplify and modify the display buy now button

- src/Tribe/Main.php
- src/Tribe/Tickets.php
- src/template-tags/tickets.php
_Ref:_ [C#80933](http://central.tri.be/issues/80933) [C#80934](http://central.tri.be/issues/80934)
---
> Improve behavior of Buy Now Button and Stock

- readme.txt
- src/views/tickets/email-ticket-type-moved.php
- src/views/tickets/email-tickets-moved.php
Further fix via Garrett Hyder (community translator).
:ticket: [#77196](https://central.tri.be/issues/77196)
> Spelling fixes (props @garrett-eclipse) | #77196

- src/Tribe/RSVP.php
_Ref:_ [C#80769](http://central.tri.be/issues/80769)
> 80769 | Fix PHP Notices on QR Code Check-in

- readme.txt
- src/Tribe/Shortcodes/User_Event_Confirmation_List.php
https://central.tri.be/issues/66141
> Feature/66141 User Event Confirmations shortcode add shortcode name to shortcode_atts call

- src/Tribe/Attendees_Table.php
https://central.tri.be/issues/69538
> Fix missing function closing key

- event-tickets.php
- lang/event-tickets-cs_CZ.po
- lang/event-tickets-de_DE.po
- lang/event-tickets-nl_NL.po
- lang/event-tickets.pot
- package.json
- readme.txt
- src/Tribe/Attendees_Table.php
- src/Tribe/Main.php
- src/Tribe/RSVP.php
- src/Tribe/Shortcodes/User_Event_Confirmation_List.php
- src/admin-views/attendees-email.php
- src/views/tickets/rsvp.php
I cannot push to the bucket branch so here's a PR 🐒 
This adds latest master and makes sure this bucket uses the same bucket for common to avoid confusion.
> Merge master to bucket

- readme.txt
Adding changelog entries for 81967, 82684, and 80861
> Update readme.txt with changelog entries

- readme.txt
- src/views/tickets/email.php
_Ref:_ [C#83227](http://central.tri.be/issues/83227)
> #83227 | Address PHP Notices

- src/Tribe/RSVP.php
- src/Tribe/Tickets.php
Get the bucket straight with master
linked: https://github.com/moderntribe/event-tickets-plus/pull/350
> Remove WP_Query from get_attendees 

- readme.txt
- src/admin-views/tribe-options-tickets.php
_Ref:_ [C#41649](http://central.tri.be/issues/41649)
> #41649 | Make QR Codes Optional

- event-tickets.php
- lang/event-tickets.pot
- package.json
- readme.txt
- src/Tribe/Main.php
- src/Tribe/Tickets.php
- src/template-tags/tickets.php
- src/views/tickets/email.php
Just updating to ensure we're testing against the latest and greatest :)
> Merge master

- src/admin-views/base_admin_panel.php
Ticket: https://central.tri.be/issues/80626
Linked PR: https://github.com/moderntribe/event-tickets-plus/pull/355
> Hide total capacity, view orders, and view attendees if no tickets

- src/Tribe/Tickets.php
> Filter is missing a closing parenthesis

- src/Tribe/Tickets_Handler.php
Ticket: https://central.tri.be/issues/80619
Requires: https://github.com/moderntribe/event-tickets-plus/pull/361
> Add rsvp row functions

- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets_Handler.php
and logic for capacity display in ticket table.
> Fix missing values on capacity table

- src/admin-views/edit_admin_panel.php
- src/admin-views/rsvp-metabox-capacity.php
per post-merge request
See https://github.com/moderntribe/event-tickets/pull/437
> Dependency === multiline format

- readme.txt
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#72126](http://central.tri.be/issues/72126)
> #72126 Tweak Attendees Link in List Table Row Actions

- readme.txt
- src/Tribe/RSVP.php
- src/Tribe/Tickets_View.php
- src/views/tickets/orders-link.php
_Ref:_ [C#73052](http://central.tri.be/issues/73052)
> #73052 Attendees and RSVP Lists on Custom Post Types

- src/views/tickets/orders-rsvp.php
Fixed mailto: url from "mailto:http://email@addre.ss" to the proper syntax.
https://central.tri.be/issues/85556
> Fixed mailto: url

- readme.txt
- src/Tribe/Tickets_View.php
_Ref:_ [C#87429](http://central.tri.be/issues/87429)
> #87429 Fix "Who's Attending?" List Reporting

- readme.txt
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#62976](http://central.tri.be/issues/62976)
> #62976 Unhook Email Content-Type Filter After Email is Sent

- readme.txt
- src/Tribe/Attendees_Table.php
_Ref:_ [C#70750](http://central.tri.be/issues/70750)
> #70750 Prevent Weird Chrome Error

- src/admin-views/base_admin_panel.php
- src/admin-views/list.php
_Ref:_ [C#81726](https://central.tri.be/issues/81726) - move hook and fix html
> #81726 - move hook and fix html

- src/Tribe/Tickets_Handler.php
Ticket: https://central.tri.be/issues/81284
Based on QA's findings in #note-11 of that ticket, we need to treat the 'post' type specially. Within `\WP_Screen::set_current_screen()` the $typenow gets set just prior to the `current_screen`, and it gets set to the current screen's post type. However, in every place I have found WP seems to expect $typenow to be empty when `post` is the post_type, presumably empty = default. I could likely fix this by modifying the `$_wp_real_parent_file` global but since that has the `_` prefix I think just resetting `$typenow` is a better call.
My apologies for how confusing this description is. The WP code surrounding these variables is impressively convoluted. See these files if you truly want to understand what's happening:
- …
> Filter current screen on the set_screen action

- readme.txt
- src/Tribe/Tickets_Handler.php
Per the #products-mr Slack chat we are undoing these two PRs until QA has more time to go through them:
- https://github.com/moderntribe/event-tickets/pull/481
- https://github.com/moderntribe/event-tickets/pull/477
> Undo changes in #81284 for release

- src/Tribe/Ticket_Object.php
_Ref:_ [C#89155](http://central.tri.be/issues/89155)
---
> Display the correct value when Shared Caps

- src/Tribe/RSVP.php
- src/views/tickets/rsvp.php
_Ref:_ [C#89247](http://central.tri.be/issues/89247)
---
> Fix the Description to the correct the front-end showing

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#81994](http://central.tri.be/issues/81994)
---
> Display warning when numbers don't match

- src/admin-views/edit_admin_panel.php
- src/admin-views/tickets-advanced.php
_Ref:_ [C#80632](http://central.tri.be/issues/80632)
---
> Remove error from end Date & Time

- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#89152](http://central.tri.be/issues/89152)
---
> Fix Total Capacity Calculation when dealing with Shared Capacity

- src/Tribe/Global_Stock.php
- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#90925](http://central.tri.be/issues/90925)
---
> Update how Available is calculated in general

- src/Tribe/Admin/Move_Ticket_Types.php
- src/Tribe/Admin/Move_Tickets.php
_Ref:_ [C#80652](http://central.tri.be/issues/80652) [C#69616](http://central.tri.be/issues/69616)
---
> Resolve Shared Capacity Move

- src/Tribe/Commerce/PayPal/Gateway.php
See: https://central.tri.be/issues/89788
> Decode HTML entities before urlencoding for PayPal

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#90915](http://central.tri.be/issues/90915)
---
> Resolve Shared Capacity without tickets

- src/Tribe/RSVP.php
- src/Tribe/Ticket_Object.php
_Ref:_ [C#90925](http://central.tri.be/issues/90925)
---
> Resolve Inventory problems

- readme.txt
- src/Tribe/Tickets_Handler.php
**Ticket:** [**#80563**](http://central.tri.be/issues/80563)
> #80563 Strip Line Breaks from Attendees Export CSV

- src/admin-views/edit_admin_panel.php
See: https://central.tri.be/issues/89058#note-11
> fixing text

- src/Tribe/Admin/Move_Tickets.php
_Ref:_ [C#80652](http://central.tri.be/issues/80652)
---
> Removed weird fatals in the code

- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#91132](http://central.tri.be/issues/91132)
---
> Inventory is now Event Aware

- src/Tribe/RSVP.php
- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets.php
_Ref:_ [C#89247](http://central.tri.be/issues/89247)
---
> Resolving the Show Description Ticket

- src/admin-views/tickets-advanced.php
See: https://central.tri.be/issues/89058
> small text change

- src/Tribe/Tickets.php
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#91132](http://central.tri.be/issues/91132) [C#91161](http://central.tri.be/issues/91161)
---
> Update Stock Levels for Event Shared Capacity

- src/Tribe/Assets.php
- src/template-tags/tickets.php
See: https://central.tri.be/issues/89058
> small text change: global stock is now shared capacity

- src/Tribe/Ticket_Object.php
_Ref:_ [C#69616](http://central.tri.be/issues/69616) [C#80652](http://central.tri.be/issues/80652) [C#91210](http://central.tri.be/issues/91210)
---
> If null fetch the value for Ticket Object

- src/Tribe/Tickets.php
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#90415](http://central.tri.be/issues/90415)
---
> Fix where Attendees list is saved

- src/Tribe/Ticket_Object.php
_Ref:_ [C#92245](http://central.tri.be/issues/92245)
---
> Coppied code resulted on typo for Ticket Object

- src/Tribe/Ticket_Object.php
- src/views/tickets/rsvp.php
_Ref:_ [C#92248](http://central.tri.be/issues/92248)
---
> Allow Unlimited RSVP to be submitted

- src/Tribe/Ticket_Object.php
- src/template-tags/tickets.php
- src/views/tickets/rsvp.php
_Ref:_ [C#92233](http://central.tri.be/issues/92233) [C#92242](http://central.tri.be/issues/92242)
---
>  New Stock Message for Capacity

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#92358](http://central.tri.be/issues/92358)
---
> Calculate correctly Event and Ticket Capacity

- src/template-tags/tickets.php
_Ref:_ [C#92233](http://central.tri.be/issues/92233)
---
> Makes sure we are only showing Attendee info when Existing

- src/Tribe/CSV_Importer/Column_Names.php
- src/Tribe/CSV_Importer/RSVP_Importer.php
_Ref:_ [C#92350](http://central.tri.be/issues/92350)
---
> Add capacity as a Import field

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#92358](http://central.tri.be/issues/92358)
---
> Add a migration for Global Capacity, which doesn't set local cap at all

- src/Tribe/Ticket_Object.php
_Ref:_ [C#92726](http://central.tri.be/issues/92726)
---
> Prevent RSVP with Not Going Status to decrease Inventory

- src/Tribe/Data_API.php
- src/Tribe/Tickets.php
_Ref:_ [C#92816](http://central.tri.be/issues/92816)
---
> Makes files PHP 5.2 compatible

- src/admin-views/admin-welcome-message.php
_Ref:_ [C#92813](http://central.tri.be/issues/92813)
---
> Implement the new Welcome page as per what was asked.

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#92835](http://central.tri.be/issues/92835)
---
> Only save Attendees List when Plus is active

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#93231](http://central.tri.be/issues/93231)
---
> Tickets/RSVP without Global Stock mode still migrates correctly

- src/template-tags/tickets.php
_Ref:_ [C#90507](http://central.tri.be/issues/90507) [C#91125](http://central.tri.be/issues/91125) 
---
> Add Delete Capacity function

- src/template-tags/tickets.php
_Ref:_ [C#92243](http://central.tri.be/issues/92243)
---
> When displaying available we should always use

- src/Tribe/Admin/Columns/Tickets.php
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#88047](http://central.tri.be/issues/88047) [C#92287](http://central.tri.be/issues/92287)
---
> Resolve the Attendees Column on Events

- src/Tribe/Admin/Columns/Tickets.php
- src/Tribe/Tickets_Handler.php
_Ref:_ [C#88047](http://central.tri.be/issues/88047)
---
> Attendees Column now with the correct calculation

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#93231](http://central.tri.be/issues/93231)
---
> Due to Bug bug RSVP needs special Treatment

- src/admin-views/editor/fieldset/advanced.php
_Ref:_ [C#93625](http://central.tri.be/issues/93625)
---
> Validation for Dates and setup properly the fields

- readme.txt
- src/Tribe/Ticket_Object.php
_Ref:_ [C#93439](http://central.tri.be/issues/93439)
---
> Respect times on date for sale of tickets

- src/admin-views/editor/list-row.php
Ticket: https://central.tri.be/issues/90972
ET+ PR: https://github.com/moderntribe/event-tickets-plus/pull/471
> Do the correct actions in the ticket list

- src/Tribe/Attendees_Table.php
Ticket: https://central.tri.be/issues/71118
ET+ PR: https://github.com/moderntribe/event-tickets-plus/pull/473
> avoid undefined index notices on strict PHP

- readme.txt
- src/admin-views/editor/panel/ticket.php
_Ref:_ [C#91758](http://central.tri.be/issues/91758)
---
> Default Provider Community Tickets

- src/Tribe/Attendees.php
**Ticket:** [**#93339**](http://central.tri.be/issues/93339)
**Related PR:** https://github.com/moderntribe/events-community-tickets/pull/100
> #93339 Spotfix: Add Filter Param

- src/Tribe/CSV_Importer/RSVP_Importer.php
_Ref:_ [C#92936](http://central.tri.be/issues/92936)
---
> Also format correctly RSVP

- src/Tribe/Tickets_Handler.php
_Ref:_ [C#95242](http://central.tri.be/issues/95242) [C#95243](http://central.tri.be/issues/95243)
---
> Prevent from ever having a warning when we dont have a default provider

- src/views/login-before-purchase.php
See: https://central.tri.be/issues/96659
> Use wp_registration_url rather than non-existent registration method

- src/Tribe/Commerce/PayPal/Gateway.php
- tests/wpunit/Tribe/Tickets/Commerce/PayPal/GatewayTest.php
See: https://central.tri.be/issues/96661
> Class should be referenced as PayPal rather than Paypal

- src/Tribe/Admin/Notices.php
Ticket: https://central.tri.be/issues/95481
Per note https://central.tri.be/issues/95481#note-8
> update the admin notice plus link utm values

- readme.txt
- src/Tribe/Attendees.php
- src/Tribe/Attendees_Table.php
- src/Tribe/RSVP.php
**Ticket:** [**#68831**](http://central.tri.be/issues/68831)
> #68831 Ensure "Low" Admin Roles (e.g. Contributor) Can't Manage Attendees

- readme.txt
- src/Tribe/RSVP.php
**Ticket:** [**#94724**](http://central.tri.be/issues/94724)
**Related PR:** https://github.com/moderntribe/event-tickets-plus/pull/484
> #94724 Hide Ticket Form When All End-Sale Dates are Passed

- src/Tribe/Attendees.php
- src/Tribe/Commerce/PayPal/Attendance_Totals.php
- src/Tribe/Commerce/PayPal/Endpoints/Success_Template.php
- src/Tribe/Commerce/PayPal/Handler/IPN.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Commerce/PayPal/Orders/Sales.php
- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets.php
- src/admin-views/tpp-orders.php
Tickets:
* https://central.tri.be/issues/96026
* https://central.tri.be/issues/96036
* https://central.tri.be/issues/96032
* https://central.tri.be/issues/96836
* https://central.tri.be/issues/81567
This PR fixes a bunch of issues related to stock/capacity and handling of those.
> Fix stock and attendees related issues

- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/Commerce/PayPal/Main.php
Tickets:
* https://central.tri.be/issues/81565
* https://central.tri.be/issues/81217
Base for: https://github.com/moderntribe/event-tickets-plus/pull/486
This PR fixes a number of issue that would prevent attendance and attendee information view, and update, from working.
> Fix attendance list and information

- src/views/login-before-purchase.php
- src/views/login-to-purchase.php
_Ref:_ [C#96894](http://central.tri.be/issues/96894)
---
> Change from Login to Log In

- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/Commerce/PayPal/Handler/IPN.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Commerce/PayPal/Orders/Sales.php
- src/Tribe/Commerce/PayPal/Orders/Table.php
- src/Tribe/Commerce/PayPal/Stati.php
- src/Tribe/Commerce/PayPal/Tickets_View.php
Ticket: https://central.tri.be/issues/96833
> Support and handle refunded orders

- src/Tribe/Commerce/PayPal/Handler/IPN.php
- src/Tribe/Commerce/PayPal/Handler/PDT.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Commerce/PayPal/Stati.php
- src/Tribe/Commerce/PayPal/Tickets_View.php
Ticket: https://central.tri.be/issues/81565
> add a shortcircuit for paypal checks and fix some status issues

- src/admin-views/tribe-options-tickets.php
Ticket: https://central.tri.be/issues/89905 
Relies on `common` PR: https://github.com/moderntribe/tribe-common/pull/602
> add ET+ upsell entries

- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Commerce/PayPal/Order.php
Support, in code,  easier order removal and management.
Needed for: https://github.com/moderntribe/tribe-cli/pull/11
> support easier order removal

- src/Tribe/Tickets.php
Ticket: https://central.tri.be/issues/97806
Support the generation and removal of orders including multiple tickets and posts
> allow for a more flexible ticket id search

- src/Tribe/Commerce/Currency.php
- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Main.php
- src/admin-views/tribe-options-tickets.php
Ticket: https://central.tri.be/issues/98073
Just some missing wiring of the container and callbacks.
> Rewire the Currency code code in place

- src/Tribe/Tickets.php
Ticket: https://central.tri.be/issues/96877
> Make sure start date is not set if not manually set

- src/views/tickets/tpp-success.php
Ticket:  https://central.tri.be/issues/97603
> change the success page text

- src/Tribe/Assets.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Commerce/PayPal/Order.php
- src/Tribe/Main.php
- src/admin-views/editor/fieldset/price.php
- src/admin-views/editor/panel/ticket.php
Ticket: https://central.tri.be/issues/96838
Depends on: https://github.com/moderntribe/tribe-common/pull/605
When dealing with PayPal tickets do not allow free tickets., see https://cl.ly/3J1m1b2q0H06
> No free PP tickets

- src/Tribe/Commerce/PayPal/Oversell/Admin_Notice_Decorator.php
See: https://central.tri.be/issues/98563
Screenshot: https://www.dropbox.com/s/k1aapkayw5jg9yw/Screenshot%202018-02-12%2009.25.22.png?dl=0
> updating message language

- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Tickets_Handler.php
Ticket: https://central.tri.be/issues/98251
Added a little more defense from notices in the code
> add some checks and casts to avoid notices

- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/RSVP.php
- src/admin-views/tribe-options-tickets.php
_Ref:_ [C#96857](http://central.tri.be/issues/96857)
---
_Rel:_ #621
> Revert code from Tribe Commerce Email feature

- src/Tribe/Commerce/PayPal/Main.php
**Ticket** https://central.tri.be/issues/96857
> Update source of the confirmation message

- src/Tribe/Commerce/Currency.php
**Ticket** https://central.tri.be/issues/70361
Hook into the filter for the cost if available to use providers
> Use providers if available to format cost

- composer.json
- composer.lock
- src/admin-views/tribe-options-tickets.php
Ticket: https://central.tri.be/issues/99958
> Update the KB article link

- src/Tribe/Commerce/Currency.php
Ticket: https://central.tri.be/issues/96777
> Fix currency symbol position in display

- src/Tribe/Tickets.php
Ticket: https://central.tri.be/issues/100277
This PR fixes the display of ticket stock and availability on the event listing gracefully handling unlimited stock representation.
> correctly handle unlimited capacity tickets

- event-tickets.php
Ticket: https://central.tri.be/issues/99872
> update plugin description

- src/Tribe/Tickets.php
Ticket: https://central.tri.be/issues/100398
This PR:
* fixes an issue in the function that would fetch the default ticket provider that would make it return an array when a string is expected
* fixes the check for the login requirements to make sure that the correct option slug is used
> Fix the login requirement issue with EDD and Woo tickets

- src/views/login-before-purchase.php
- src/views/login-to-purchase.php
- src/views/tickets/orders-pp-tickets.php
- src/views/tickets/orders.php
- src/views/tickets/rsvp.php
- src/views/tickets/tpp-success.php
- src/views/tickets/tpp.php
Ticket: n/a
Bumping/setting the version to `4.7`
> bump version to `4.7`

- readme.txt
- src/Tribe/Attendees.php
**Ticket**: https://central.tri.be/issues/90062
> Add dynamic parents when a venue or organizer has tickets

- src/Tribe/Tickets.php
- src/views/tickets/email.php
Ticket: https://central.tri.be/issues/101081
Related: https://github.com/moderntribe/event-tickets-plus/pull/505 and https://github.com/moderntribe/tribe-cli/pull/17
This PR restores the missing property value that would wreck havoc throughout anything using EDD tickets.
> Fix missing EDD attendee meta issue

- readme.txt
- src/views/tickets/orders-link.php
**Ticket**: https://central.tri.be/issues/88569
> Make sure slug for tickets are consistent

- readme.txt
- src/Tribe/Attendees.php
**Ticket**: https://central.tri.be/issues/93057
> Expanded the correct parent when visiting the list of attendees

- src/Tribe/RSVP.php
> Fixed a typo

- readme.txt
- src/Tribe/Attendees.php
**Ticket**: https://central.tri.be/issues/99979
> Make sure to send the context to the email template

- readme.txt
- src/Tribe/Tickets_Handler.php
**Ticket**: https://central.tri.be/issues/99601
> Prevent to overwrite the start date of a ticket if was already set

- src/Tribe/Attendees.php
Ticket: https://central.tri.be/issues/101801
> Prevent fatals on plugin activation

- readme.txt
- src/Tribe/JSON_LD/Order.php
- src/Tribe/JSON_LD/Type.php
- src/Tribe/Main.php
**Ticket**: https://central.tri.be/issues/95034
> Add JSON-LD for custom post types with support for tickets

- src/Tribe/Tickets_View.php
- src/views/tickets/orders-link.php
This PR does not require changelog due the changelog has been updated already, and the changes on this PR address feedback from first QA round.
**Ticket**: https://central.tri.be/issues/88569
> Update URL for tickets to work with plain permalink structure

- readme.txt
- src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
- src/Tribe/RSVP.php
- src/Tribe/Ticket_Object.php
**Ticket**: https://central.tri.be/issues/99721
Use the timezone from the ticket if any if not uses the timezone from
the global settings.
> Use timezones when comparing dates on a ticket

- src/Tribe/Ticket_Object.php
**Ticket**: https://central.tri.be/issues/69484
> Fallback to numbers if any fail to use DateTime object

- src/Tribe/Commerce/PayPal/Attendance_Totals.php
- src/Tribe/Commerce/PayPal/Main.php
**Ticket**: https://central.tri.be/issues/90672
> Prevent render two totals sections on the Attendanees tab

- src/template-tags/tickets.php
**Ticket**: https://central.tri.be/issues/99721
> Remove old logic with date_in_range call

- readme.txt
- src/Tribe/RSVP.php
Ticket: https://central.tri.be/issues/98203
For more details see: https://github.com/moderntribe/event-tickets-plus/pull/542
> Add an oportunity to render something if RSVP has expired

- readme.txt
- src/Tribe/Tickets.php
- src/Tribe/Tickets_View.php
Ticket: https://central.tri.be/issues/66072
> Avoid adding the RSVP form if disabled from settings

- readme.txt
- src/resources/js/tickets.js
Ticket: https://central.tri.be/issues/76320
> Honor the start of week for Datepickers of tickets

- readme.txt
- src/Tribe/CSV_Importer/Column_Names.php
- src/Tribe/CSV_Importer/RSVP_Importer.php
https://central.tri.be/issues/96162
> Add changelog for new filter `tribe_tickets_import_rsvp_data`

- readme.txt
- src/Tribe/Admin/Move_Tickets.php
- src/Tribe/Attendees_Table.php
Ticket: https://central.tri.be/issues/102498
> Make sure the current user can perform only actions under his role

- readme.txt
**Ticket:** [**⌗101908**](http://central.tri.be/issues/101908)
> 101908 Spotfix: Readme Tweaks

- readme.txt
Sportfix to adjust release date
> Adjust release date

- readme.txt
- src/Tribe/Admin/Columns/Tickets.php
https://central.tri.be/issues/102128
Display the correct number of attendees on the events list in the admin section.
> Display the correct number of attendees on the events list in the admin section

- readme.txt
- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/Ticket_Object.php
- src/views/tickets/rsvp.php
https://central.tri.be/issues/76683
Ensured that the ticket start and end sale date respect the event timezone (RSVP and PayPal)
> Ensure that the ticket start and end sale date respect the event timezone

- readme.txt
- src/Tribe/Ticket_Object.php
- src/template-tags/tickets.php
https://central.tri.be/issues/102081
Add methods to handle refunds for tickets and fix the attendees report accordingly.
> Add methods to handle refunds

- src/admin-views/attendees.php
Making "Search attendees" translatable
> Making "Search attendees" translatable

- readme.txt
- src/admin-views/tribe-options-tickets.php
**Ticket:** [**⌗41649**](http://central.tri.be/issues/41649)
**Companion _Event Tickets Plus_ PR:** https://github.com/moderntribe/event-tickets-plus/pull/567
> ⌗41649 Make QR Code Optional

- readme.txt
- src/admin-views/editor/fieldset/price.php
- src/template-tags/tickets.php
**Ticket:** [**⌗97583**](http://central.tri.be/issues/97583)
> ⌗97583 Better Handle Display of WC Membership Discounts on Tickets

- event-tickets.php
- package.json
- readme.txt
- src/Tribe/Main.php
We're releasing version 4.7.3 for M18.08, but haven't yet updated some of the version numbers.
Thanks to @barryhughes for flagging this!
> Spotfix: Bump Version Numbers for M18.08

- src/admin-views/tribe-options-tickets.php
**Ticket:** [**⌗41649**](http://central.tri.be/issues/41649)
**Code Review Note:** No changelog adjustments are needed for this.
**Companion _Event Tickets Plus_ PR:** https://github.com/moderntribe/event-tickets-plus/pull/569
> ⌗41649 Ensure QR Code Option Only Shows when Event Tickets Plus is Active

- src/Tribe/REST/V1/Main.php
> Fix missing headers issue

- src/Tribe/Commerce/PayPal/Gateway.php
Ticket: 107896
This PR:
* adds code to make sure the `setcookie` function will not be called if headers have been sent already
* adds tracking of issued invoice numbers in a transient based fashion to make sure invoice number are set and reset correctly in the context of asynchronous requests
> Add a fallback transient check to make sure invoice number is reset

- package-whitelist.json
🎫 https://central.tri.be/issues/107911
> Add files to whitelist

- readme.txt
- src/views/tickets/orders.php
Ref. https://central.tri.be/issues/89201
Display a notice if the user accesses the tickets page and doesn't have tickets.
> Add notice if user doesn't have tickets

- src/Tribe/RSVP.php
🎫 https://central.tri.be/issues/102634#note-25
> Ensure the stock/sales are updated upon deleting an attendee from the admin

- package-whitelist.json
🎫 https://central.tri.be/issues/107911
> Fix filename

- src/views/tickets/orders.php
Bump version number for `views/tickets/orders.php`
> Bump version number on `views/tickets/orders.php`

- readme.txt
> Update changelog date.

- readme.txt
- src/views/tickets/email.php
https://central.tri.be/issues/109102
props @jesseeproductions
> #109102 - fix fatal error when sending tickets other then woo

- src/Tribe/Main.php
> Version Bump for QA

- src/Tribe/RSVP.php
Ticket template needs to be called to display unavailability messaging
> Update RSVP.php for 81334

- readme.txt
- src/admin-views/tribe-options-tickets.php
🎫 https://central.tri.be/issues/73599
Removing the patch as discussed here: https://tribe.slack.com/archives/C0258NY1C/p1530282640000063
> Remove patch for #73599

- readme.txt
- src/Tribe/Main.php
- src/Tribe/Privacy.php
- src/admin-views/privacy.php
🎫 https://central.tri.be/issues/108456
> Add privacy policy guide for ET

- src/Tribe/Metabox.php
- src/Tribe/Tickets.php
_Ref:_ [C#109826](http://central.tri.be/issues/109826)
---
Moving filters to allow gutenberg compatibility, as well as changing protected method to public.
> Gutenberg Compatibility

- src/Tribe/Tickets.php
_Ref:_ [C#109826](http://central.tri.be/issues/109826)
---
> Move Capacity hook properly setup

- event-tickets.php
- package-lock.json
- package.json
- readme.txt
- src/Tribe/Commerce/PayPal/Custom_Argument.php
- src/Tribe/Privacy.php
- src/Tribe/REST/Interfaces/Post_Repository.php
- src/Tribe/REST/V1/Documentation/Ticket_Definition_Provider.php
- src/Tribe/REST/V1/Endpoints/Base.php
- src/Tribe/REST/V1/Endpoints/Swagger_Documentation.php
- src/Tribe/REST/V1/Headers/Base.php
- src/Tribe/REST/V1/Main.php
- src/Tribe/REST/V1/Messages.php
- src/Tribe/REST/V1/Post_Repository.php
- src/Tribe/REST/V1/Service_Provider.php
- src/Tribe/REST/V1/Settings.php
- src/Tribe/REST/V1/System.php
- src/Tribe/Ticket_Object.php
- src/Tribe/Tickets.php
- src/Tribe/Validator/Base.php
- src/Tribe/Validator/Interface.php
- src/functions/advanced-functions/rest-v1.php
Bump version number, and replace TBD refs.
> Bump version number, and replace TBD refs.

- src/Tribe/Tickets.php
_Ref:_ [C#109929](http://central.tri.be/issues/109929)
---
> Move filters back in to construct for some other stuff

- readme.txt
- src/Tribe/Commerce/Orders_Tabbed_View.php
https://central.tri.be/issues/109592
> Add post ID parameter to the_title filter in Tribe Commerce

- readme.txt
- src/Tribe/Attendees.php
https://central.tri.be/issues/109595
> Make attendee list browser title translatable

- readme.txt
- src/Tribe/Ticket_Object.php
🎫 https://central.tri.be/issues/107121
> Stop showing tickets for past events with no end sale date.

- src/Tribe/Attendee_Repository.php
- src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
- src/Tribe/REST/V1/Endpoints/Ticket_Archive.php
- src/Tribe/REST/V1/Repositories/Attendee_Read.php
- src/Tribe/REST/V1/Service_Provider.php
- src/Tribe/Validator/Base.php
- src/Tribe/Validator/Interface.php
- tests/_support/Commerce/Attendee_Maker.php
- tests/_support/Commerce/PayPal/Ticket_Maker.php
- tests/_support/Commerce/RSVP/Ticket_Maker.php
- tests/functional/Commerce/PayPal/ReturnToCartCest.php
- tests/integration/Tribe/Tickets/Commerce/PayPal/PayPalTest.php
- tests/restv1/AttendeeArchiveByProviderCest.php
- tests/restv1/AttendeeArchiveByRelatedPostCest.php
- tests/restv1/AttendeeArchiveCest.php
- tests/restv1/AttendeeArchiveSearchCest.php
- tests/restv1/PayPal/FlagsCest.php
- tests/restv1/PayPal/SingleTicketCest.php
- tests/restv1/PayPal/TicketArchiveByPostCest.php
- tests/restv1/RSVP/AttendeeArchiveCest.php
- tests/restv1/RSVP/FlagsCest.php
- tests/restv1/RSVP/SingleAttendeeCest.php
- tests/restv1/RSVP/SingleTicketCest.php
- tests/restv1/RSVP/TicketArchiveByPostCest.php
- tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/Tickets_FormTest.php
Ticket: https://central.tri.be/issues/109708 and https://central.tri.be/issues/109709
> Add Attendee archive query filters

- readme.txt
- src/Tribe/Commerce/PayPal/Main.php
https://central.tri.be/issues/104209
Also added docblocks for all filters
> Added parent post and order ID to a bunch of Tribe Commerce email filters

- src/Tribe/Privacy.php
Part of 🎫 https://central.tri.be/issues/108488
Adding some filters so we can hook custom fields in the data export, directly from ET+
> Adding filters  so ET+ can hook here and add custom fields for RSVPs and TPPs

- readme.txt
- src/views/tickets/email.php
https://central.tri.be/issues/79876
> Add a filter for the tickets email image

- readme.txt
- src/Tribe/Privacy.php
🎫 https://central.tri.be/issues/108490
Added exporter for orders: https://cloudup.com/cDXKD12-ii0
Added erasers for:
- RSVPs
- Orders
- Attendees
> GDPR: Added erasers & exporters

- src/Tribe/Privacy.php
🎫 https://central.tri.be/issues/108490
> GDPR Eraser: Add missing variables and early bail

- src/Tribe/Privacy.php
🎫 https://central.tri.be/issues/108490
🤦‍♂️ :
> GDPR: Fix var name

- readme.txt
- src/Tribe/Tickets.php
Central ticket 83857
Add start sale date and optionally time to tickets not yet available message; includes filters for both the date and time
> Jentheo patch 83857

- readme.txt
🎫 https://central.tri.be/issues/109618
> M18.11 Update release date

- readme.txt
- src/Tribe/Commerce/PayPal/Main.php
- src/admin-views/tpp-orders.php
_Ref:_ [C#110034](https://central.tri.be/issues/110034)
> #110034 - Sales by Ticket section to remove duplicate data

- readme.txt
- src/Tribe/Commerce/Currency.php
🎫 https://central.tri.be/issues/109434
> Fix default currency symbol inconsistency

- src/Tribe/REST/V1/Documentation/Attendee_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/Capacity_Details_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/Checkin_Details_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/Checkin_Report_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/Payment_Details_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/RSVP_Report_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/Ticket_Definition_Provider.php
- src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
- src/Tribe/REST/V1/Endpoints/Base.php
- src/Tribe/REST/V1/Endpoints/Single_Attendee.php
- src/Tribe/REST/V1/Endpoints/Single_Ticket.php
- src/Tribe/REST/V1/Endpoints/Swagger_Documentation.php
- src/Tribe/REST/V1/Endpoints/Ticket_Archive.php
- src/Tribe/REST/V1/Service_Provider.php
- tests/restv1/SwaggerDocumentationCest.php
Tickets: 
* https://central.tri.be/issues/108024
* https://central.tri.be/issues/109710
Based on: https://github.com/moderntribe/tribe-common/pull/756
This PR updates the endpoints code to make them generate valid and correct OpenApi 3.0 documentation: http://p.tri.be/e3mjEU
> Update Swagger documentation generation

- src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
- src/Tribe/REST/V1/Endpoints/Ticket_Archive.php
Ticket: https://central.tri.be/issues/108023
This PR makes sure that extra query args are removed from REST URLs in ET REST API
> prune extra query arguments from rest URL

- src/Tribe/Tickets.php
🎫 https://central.tri.be/issues/106572
Ensure available tickets are correctly represented in list view.
This replaces https://github.com/moderntribe/event-tickets/pull/856 - easier than trying to undo the do 😉
> Use $ticket->available, not $ticket->stock

- readme.txt
- src/Tribe/Tickets.php
**Ticket:** [**⌗102643**](http://central.tri.be/issues/102643)
**Related PR:** https://github.com/moderntribe/the-events-calendar/pull/2166
> ⌗102643 Don't Load Ticket Form if Password Required

- readme.txt
- src/views/shortcodes/my-attendance-list-logged-out.php
- src/views/shortcodes/my-attendance-list.php
**Ticket:** [**⌗112360**](http://central.tri.be/issues/112360)
> ⌗112360 Updating Internal Shortcode Template Path Docs

- src/views/shortcodes/my-attendance-list-logged-out.php
**Ticket:** [**⌗112360**](http://central.tri.be/issues/112360)
> Spotfix: Some Simple Text Changes

- readme.txt
- src/views/tickets/tpp.php
🎫 https://central.tri.be/issues/109510
> Make TribeCommerce tickets start/end sale dates respect event timezone

- src/Tribe/Metabox.php
_Ref:_ [C#116150](http://central.tri.be/issues/116150)
---
> Add the Metabox backwards compat argument for Gutenberg

- readme.txt
- src/admin-views/editor/fieldset/advanced.php
**Ticket:** [**⌗116853**](http://central.tri.be/issues/116853)
> ⌗116853 Show Correct End-Sale Date Tooltips Based on Post Type

- src/Tribe/Main.php
- src/Tribe/RSVP/Cart.php
🎫 https://central.tri.be/issues/116001
Not sure if applicable for that ticket, but this is a functional WIP of a Cart class for RSVPs in order to include them in intermediate pages or wherever we want, without depending on the `$_POST` submission only.
> RSVP Cart implementation

- src/views/registration/attendees/fields/checkbox.php
- src/views/registration/attendees/fields/radio.php
https://central.tri.be/issues/117191
Fix markup for checkbox (not closing input tag), using the same format as radio template
> Fix checkbox markup

- src/modules/data/blocks/rsvp/sagas.js
- src/modules/data/blocks/ticket/sagas.js
https://central.tri.be/issues/117844
https://central.tri.be/issues/117845
> Update RSVP and ticket block initial start date to be published date

- src/Tribe/Attendee_Registration/View.php
- src/views/registration/attendees/content.php
🎫 https://central.tri.be/issues/117902
https://www.useloom.com/share/593a6d4e76fb4948b65e5e26961993cc
> Show the tickets without fields in the attendee registration summary

- src/Tribe/Main.php
- src/modules/data/blocks/ticket/sagas.js
Requires: https://github.com/moderntribe/tribe-common/pull/830
Ticket: https://central.tri.be/issues/118118
> Import modules from the root of the package

- src/resources/js/views/rsvp.js
- src/resources/js/views/tickets.js
Ticket: https://central.tri.be/issues/118344
Ticket: https://central.tri.be/issues/118342
> Add missing asssets from migration for FE view

- src/modules/blocks/ticket/edit-container/content/capacity/template.js
🎫 https://central.tri.be/issues/117148
> Capitalize *Unlimited*

- src/modules/elements/action-button/style.pcss
- src/modules/elements/action-dashboard/style.pcss
🎫 https://central.tri.be/issues/118106
> Fix: Tickets & RSVP blocks > Attendee and Order links are underlined

- src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
- src/modules/blocks/ticket/index.js
🎫 https://central.tri.be/issues/118108
> Use tickets icon for child ticket block

- src/Tribe/Tickets.php
Introduces a new filter:
- `tribe_tickets_event_attendees_skip_empty_post` - `true` by default
In order to allow extensibility from third party or externals, by
default is going to skip the execution, creation of the cache of an
empty `$post_id` as when calling `get_event_attendees` with an empty
`$post_id` it fallbacks to the current global post ID wich leads to
unexpected results.
In the specifc case of Gutenberg multiple requests without a explicit ID
is trigger so an invalidation or a false positive is executed in that
case.
**Ticket:** https://central.tri.be/issues/118118
> Prevent to trigger the cache on empty $post_id

- src/modules/blocks/rsvp/attendee-registration/template.js
- src/modules/blocks/ticket/container-content/attendees-registration/template.js
For ticket: https://central.tri.be/issues/117854
> attendee registration opens in same window

- src/modules/blocks/attendees/template.js
🎫 https://central.tri.be/issues/117039
Show the subtitle in the BE preview. Will log a ticket to actually show the same info as the FT
> Show attendees block subtitle in the BE preview

- src/modules/blocks/tickets/container.js
- src/modules/blocks/tickets/template.js
- src/modules/data/blocks/ticket/selectors.js
Followup: https://github.com/moderntribe/event-tickets/pull/942#issuecomment-440557455
> Specify the type of header on Template level

- src/modules/blocks/attendees/template.js
🎫 https://central.tri.be/issues/117039
Fix text for the changes introduced in https://github.com/moderntribe/event-tickets/pull/946
> Fix text for #946

- src/modules/blocks/ticket/container/container.js
- src/modules/blocks/ticket/container/template.js
- src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
- src/modules/data/blocks/ticket/__tests__/selectors.test.js
- src/modules/data/blocks/ticket/selectors.js
🎫 https://central.tri.be/issues/115802
**📹 Screencast**
https://www.useloom.com/share/4f030baa968f44349483a8e29a5fa5e6
> Display the ticket icon according to the date of the event 

- src/modules/blocks/ticket/container/template.js
Fix missing attendee registration in ticket block.
> fix import to ticket container

- event-tickets.php
- package-lock.json
- package.json
- readme.txt
- src/Tribe/Main.php
🎫 https://central.tri.be/issues/117666
> Set release version number

- src/views/registration/attendees/fields/select.php
🎫 https://central.tri.be/issues/119007
> Attendee Registration > Fix select saved data

- src/modules/blocks/attendees/style.pcss
For ticket: https://central.tri.be/issues/ 118221
> fix styles for attendees block title

- src/styles/tickets/frontend.pcss
For ticket: https://central.tri.be/issues/ 116206
> add focus styles for add and remove buttons

- src/modules/data/blocks/ticket/sagas.js
Ticket: https://central.tri.be/issues/118680
> Set initial value of a ticket if has been created

- readme.txt
- src/Tribe/Main.php
_Ref:_ [C#119262](http://central.tri.be/issues/119262)
---
> Load PUE when having invalid versions

- src/Tribe/Editor/Blocks/Rsvp.php
- src/Tribe/Editor/Blocks/Tickets_Item.php
- src/views/blocks/tickets/item.php
_Ref:_ [C#119298](http://central.tri.be/issues/119298)
---
> Prevent RSVP from showing on Tickets List Block

- src/views/blocks/attendees/description.php
- src/views/blocks/rsvp/details/availability.php
- src/views/blocks/rsvp/form/email.php
- src/views/blocks/rsvp/form/error.php
- src/views/blocks/rsvp/form/name.php
- src/views/blocks/rsvp/form/opt-out.php
- src/views/blocks/rsvp/form/submit-button.php
- src/views/blocks/rsvp/form/submit-login.php
- src/views/blocks/rsvp/icon.php
- src/views/blocks/rsvp/messages/success.php
- src/views/blocks/rsvp/status/full.php
- src/views/blocks/rsvp/status/going.php
- src/views/blocks/rsvp/status/not-going.php
- src/views/blocks/tickets/extra-available-quantity.php
- src/views/blocks/tickets/extra-available-unlimited.php
- src/views/blocks/tickets/extra-available.php
- src/views/blocks/tickets/quantity-add.php
- src/views/blocks/tickets/quantity-remove.php
- src/views/blocks/tickets/quantity-unavailable.php
- src/views/blocks/tickets/registration/attendee/fields/select.php
- src/views/blocks/tickets/registration/summary/ticket-quantity.php
- src/views/blocks/tickets/registration/summary/title.php
- src/views/blocks/tickets/submit-button.php
- src/views/blocks/tickets/submit-login.php
🎫 https://central.tri.be/issues/119270
I've found that we haven't updated the textdomain for the templates, also added that.
> Fix > RSVP > Login is required for purchase not working> 

- src/modules/blocks/rsvp/container.js
- src/modules/data/blocks/rsvp/thunks.js
For ticket: https://central.tri.be/issues/119340
> fix rsvp is inactive check

- src/styles/rsvp/frontend.pcss
For ticket: https://central.tri.be/issues/116206
> add focus styles for rsvp add and remove buttons

- src/Tribe/Editor/Blocks/Tickets.php
- src/Tribe/Editor/Blocks/Tickets_Item.php
_Ref:_ [C#119497](http://central.tri.be/issues/119497)
---
📹 http://i.bordoni.me/df3cf7467c3c
> On Tickets Item block we prevent duplicated Items to the list

- readme.txt
- src/Tribe/Editor/Blocks/Tickets_Item.php
🎫 https://central.tri.be/issues/119628
> Display only tickets that are in date range

- readme.txt
- src/Tribe/Editor.php
- src/Tribe/Editor/Compatibility/Tickets.php
- src/Tribe/Editor/Provider.php
- src/Tribe/Editor/Template/Overwrite.php
- src/modules/blocks/tickets/index.js
Update tickets blocks when the editor is moved from Classic into Blocks and
viceversa
Ticket: https://central.tri.be/issues/119426
> Add actions to update the Event Tickets blocks

- readme.txt
- src/Tribe/Editor.php
- src/Tribe/Editor/Compatibility/Tickets.php
- src/Tribe/Editor/Provider.php
- src/Tribe/Editor/Template/Overwrite.php
- src/modules/blocks/tickets/index.js
_Ref:_ [C#119641](http://central.tri.be/issues/119641)
---
>  Blocks Inactive on TEC deactivated 

- src/Tribe/Editor.php
_Ref:_ [C#119659](http://central.tri.be/issues/119659)
---
> Prevent flush_blocks on older versions

- readme.txt
- src/Tribe/Main.php
- src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗117794**](http://central.tri.be/issues/117794)
**Code Review Note:** This replaces https://github.com/moderntribe/event-tickets/pull/1016
---
This PR is of a piece with these other two PRs:
* https://github.com/moderntribe/tribe-common/pull/890
* https://github.com/moderntribe/the-events-calendar/pull/2342
> ⌗117794 TEC and ET Welcome Page Refreshes

- readme.txt
**Ticket:** [**⌗119644**](http://central.tri.be/issues/119644)
> ⌗119644 ET Spotfix — Increase "Tested Up To" Value to 5.0

- src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗117795**](http://central.tri.be/issues/117795)
> M18.19 Spotfix — Change Help Desk Links

- readme.txt
- src/admin-views/admin-welcome-message.php
_Ref:_ [C#117795](http://central.tri.be/issues/117795)
---
> Revert the new Welcome pages, they included external JS, not good for WP.org

- readme.txt
- src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗117794**](http://central.tri.be/issues/117794)
> ⌗117794 Restoring ET Welcome Page Refresh Code

- src/Tribe/Editor/REST/Compatibility.php
- src/Tribe/REST/V1/Post_Repository.php
🎫 https://central.tri.be/issues/119427
Also cleaned up a white space issue in `Post_Repository.php` while I was digging around in there to figure things out.
> Add rest-enabled filters to compatibility file for RSVP meta

- src/Tribe/Status/Manager.php
- tests/wpunit/Tribe/Tickets/Status/TTPManagerTest.php
This is a fix for the Feature Branch Only
It changes when TSM loads due to the changes in PDC
_Ref:_ [C#116745](https://central.tri.be/issues/116745)
> #116745 - fix tsm loading issue due to pdc

- src/admin-views/admin-welcome-message.php
🎫 https://central.tri.be/issues/117794
Requires: https://github.com/moderntribe/tribe-common/pull/926
Note: I did not change the common branch requirement so we don't run into issues later - so this can't be tested until both are merged!
> Change H2s to more sematic H4s

- readme.txt
- src/Tribe/Attendee_Registration/Template.php
🎫 https://central.tri.be/issues/119680
> Change the priority on the rewrite to ensure it happens after TEC

- readme.txt
- src/Tribe/Data_API.php
https://central.tri.be/issues/119608
For immediate addition to the FR bucket as well!
Correct an issue where we do "lazy" string to array conversion - fatals on php > 7.0
> Make code comaptible with php 7.1+

- src/Tribe/Status/Abstract_Commerce.php
- src/admin-views/tpp-orders.php
_Ref:_ [C#121984](https://central.tri.be/issues/121984)
> #121984 - update order language to clarify numbers

- src/Tribe/Status/Abstract_Commerce.php
_Ref:_ [C#121984](https://central.tri.be/issues/121984)
> #121984 - remove pural translation

- readme.txt
_Ref:_ [C#121577](https://central.tri.be/issues/121577)
> #122099 - update readme and common

- src/modules/blocks/rsvp/duration/style.pcss
- src/modules/blocks/ticket/container-content/capacity/style.pcss
Fix for ticket: https://central.tri.be/issues/122442
> fix asterisk position

- src/Tribe/Attendee_Registration/Template.php
- src/admin-views/tribe-options-tickets.php
🎫 https://central.tri.be/issues/120195
A few tweaks via QA: make conditional on ETP and fiddle with the settings additions
> Tweak settings locations, make settings conditional on ETP

- src/admin-views/tribe-options-tickets.php
🎫 https://central.tri.be/issues/120195
related: https://github.com/moderntribe/event-tickets-plus/pull/717
> Remove ETP options from ET

- readme.txt
- src/Tribe/Attendees.php
- src/Tribe/Attendees_Table.php
- src/Tribe/RSVP.php
🎫 https://central.tri.be/issues/123070
Requires https://github.com/moderntribe/events-community-tickets/pull/145
> Add filter to manage attendees permissions 

- src/admin-views/tribe-options-tickets.php
https://central.tri.be/issues/119910
> Adjust text for tickets left threshold option

- src/Tribe/Attendee_Registration/Template.php
🎫 https://central.tri.be/issues/119777
> Add filter for content limit

- src/views/registration/attendees/fields/checkbox.php
https://central.tri.be/issues/123053
https://central.tri.be/issues/121592
Related: https://github.com/moderntribe/event-tickets-plus/pull/718
> Send a hidden empty field to ensure empty saves work for AJAX

- src/Tribe/Attendee_Registration/Template.php
🎫 https://central.tri.be/issues/123181
> Add logic for themes w/o page.php

- src/views/registration/attendees/loader.php
- src/views/registration/attendees/success.php
For ticket: https://central.tri.be/issues/120196
> add template override paths for other AR templates

- src/Tribe/Tickets.php
https://central.tri.be/issues/123327
> Prevent fatal on new method

- readme.txt
🎫 https://central.tri.be/issues/123458
> Correct readme requirements

- src/Tribe/REST/V1/Post_Repository.php
See: https://central.tri.be/issues/123425
> returning the proper field for ticket description

- readme.txt
- src/Tribe/RSVP.php
🎫 https://central.tri.be/issues/123124
> Show RSVP in list view when it's the only ticket

- src/Tribe/RSVP.php
🎫 https://central.tri.be/issues/123756
> It's $attendee_id, not $ticket_id

- .huskyrc.sample
🎫 https://central.tri.be/issues/120854
Adds a `.huskyrc.sample` file with sample command
> Add sample file

- build.md
🎫 https://central.tri.be/issues/120854
> Add proposed build instructions

- src/Tribe/Attendee_Registration/Template.php
Also added a local convenience wrapper for `tribe( 'tickets.attendee_registration' )->is_on_page()`
🎫 https://central.tri.be/issues/123065
> Add filter for archive title

- readme.txt
> Fix readme

- readme.txt
- src/views/tickets/orders.php
🎫 https://central.tri.be/issues/114111
Requires: https://github.com/moderntribe/event-tickets-plus/pull/739
> Make submit button dependent on presence of editable meta data

- readme.txt
- src/Tribe/Attendees.php
🎫 https://central.tri.be/issues/122274
> Remove the "Primary Info" column from the email and csv export

- readme.txt
- src/Tribe/Attendee_Registration/Template.php
🎫 https://central.tri.be/issues/123613
> Change to get_stylesheet_directory() to honor child themes

- src/Tribe/Attendee_Registration/Template.php
https://central.tri.be/issues/123613
> Fix template validation logic

- src/resources/js/rsvp-block.js
- src/resources/js/tickets-block.js
🎫 https://central.tri.be/issues/121073
Do same to RSVP, make the two files match.
> Fix rsvp js, make both match.

- readme.txt
- src/Tribe/Promoter_Observer.php
- src/Tribe/RSVP.php
Ticket: https://central.tri.be/issues/124118
> Update hooks attached to the tickets & events

- src/Tribe/Attendee_Registration/Main.php
🎫 https://central.tri.be/issues/123044
Else we get issues in some admin tables
> Better test for empty

- readme.txt
- src/admin-views/tribe-options-tickets.php
https://central.tri.be/issues/122745
> Let email sender be empty

- readme.txt
- src/Tribe/Editor/REST/V1/Service_Provider.php
- src/Tribe/REST/V1/Post_Repository.php
- tests/integration/Tribe/Tickets/Commerce/PayPal/PayPalTest.php
- tests/restv1/PayPal/SingleTicketCest.php
- tests/restv1/RSVP/SingleTicketCest.php
https://central.tri.be/issues/117668
> Only show attendees in REST API ticket data if the event has attendee information set to show

- readme.txt
- src/Tribe/Promoter_Observer.php
- src/Tribe/RSVP.php
Ticket: https://central.tri.be/issues/124118
> Update hooks used by Promoter

- src/Tribe/Attendee_Registration/Shortcode.php
🎫 https://central.tri.be/issues/123044
Missed allowing "action" - so form won't forward to checkout.
> Missed "action"

- src/resources/postcss/tickets-registration-page.pcss
- src/views/registration/button-checkout.php
Fix styling around AR submit button - remove class that adds float so that other blocks don't
overlap/collapse around it.
:ticket: https://central.tri.be/issues/123044#note-25
> fix(attendee reg): Remove float on submit button.

- readme.txt
- src/admin-views/tribe-options-tickets.php
Move all the IPN settings and the sandbox checkbox to just below the TPP settings as they make
better sense there.
:ticket: https://central.tri.be/issues/122333
Also note - I rearranged the changelog entries to the new fix->tweak->other layout
> fix(ticket settings): Move the IPN settings togther for better UI.

- readme.txt
- src/modules/data/blocks/ticket/selectors.js
Add a check for zero price and only validate it if the ticket provider is NOT tribe-commerce.
🎫 https://central.tri.be/issues/123835
>  fix(tribe-commerce): Add a check for zero price to ticket validation. 

- src/Tribe/Tickets.php
- src/admin-views/editor/list-row.php
- src/resources/postcss/tickets-tables.pcss
Add action hook for plugins/extensions to show warning tooltips in the admin ticket table.
:ticket: https://central.tri.be/issues/120856
Image with https://github.com/moderntribe/event-tickets-plus/pull/770 to show working hooks:
> feat(tickets table): Add warning tooltip action.

- readme.txt
- src/Tribe/Admin/Move_Tickets.php
Update the sales on source and target ticket when a ticket is moved from one type to another.
:ticket: https://central.tri.be/issues/102636
> feat(ticket capacity): Ensure capacity changes when moving tickets.

- readme.txt
- src/modules/data/blocks/ticket/constants.js
_Ref:_ [C#121440](https://central.tri.be/issues/121440)
> #121440 - add edd orders link to block editor ticket block

- src/admin-views/order-available.php
Yikes! Fixes a typo in the tooltip!
> spotfix - typo

- readme.txt
- src/modules/blocks/rsvp/attendee-registration/template.js
- src/modules/blocks/ticket/container-content/attendees-registration/template.js
- src/modules/blocks/ticket/container-header/title/template.js
Correct "Attendee Registration" to "Attendee Information" in some tooltips and headers.
:ticket: https://central.tri.be/issues/126038
> fix(attendee registration): Correct verbiage to match in a few places.

- src/Tribe/Ticket_Object.php
- tests/acceptance.suite.dist.yml
- tests/functional.suite.dist.yml
- tests/restv1.suite.dist.yml
Make sure we're using the test database, user, etc in all cases.
> test(local testing): Fix yml files so that acceptance tests don't overwite local dB.

- readme.txt
- src/Tribe/Ticket_Object.php
Calculation of (event) shared capacity referred to the ticket in question when checking stock mode
instead of the ticket we were potentially adding.
:ticket: https://central.tri.be/issues/119844
> fix(ticket counts): Fix calculation of shared capacity.

- src/modules/blocks/ticket/container-header/quantity/template.js
Change `<i>` tag to `<span>` in ticket block tooltip so it doesn't appear as italic.
:ticket: https://central.tri.be/issues/121992#note-29
> fix(ticket block): Correct `<i>` in ticket block tooltip

- readme.txt
- src/Tribe/Attendee_Registration/Shortcode.php
- src/resources/js/tickets-registration-page.js
Ensure that the shortcode enqueues the correct assets when the toggle is off. Only on the short-coded
page. Only when the page is active (option set)
:ticket: https://central.tri.be/issues/125964 && https://central.tri.be/issues/126779
~On hold because I want to check into one more item before merging.~
> fix(attendee registration shortcode): Correct asset enqueue for shortcode

- src/Tribe/Attendee_Repository.php
https://central.tri.be/issues/128020
> Fix optout ORM logic

- src/Tribe/Attendee_Repository.php
- tests/wpunit/Tribe/Tickets/Attendees_TableTest.php
https://central.tri.be/issues/128021
> Fix RSVP by Order ORM filtering

- dev/functions.sh
- src/Tribe/Tickets_View.php
https://central.tri.be/issues/128035
> Fix attendees count user logic

- src/Tribe/Attendee_Repository.php
- src/Tribe/REST/V1/Attendee_Repository.php
- src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
- src/Tribe/RSVP.php
- src/Tribe/RSVP/Attendance_Totals.php
- src/Tribe/Repositories/Attendee/Commerce.php
- src/Tribe/Repositories/Attendee/RSVP.php
https://central.tri.be/issues/128071
* Fixes rsvp_status queries
* Sets proper orm_provider for RSVP class
* Only show attendance totals in Attendees admin view for RSVPs if post has RSVP tickets OR has RSVP counts to show (don't show if they never had RSVP tickets OR never had any attendees RSVP)
> Fix RSVP queries

- src/Tribe/Commerce/PayPal/Endpoints/Success_Template.php
https://central.tri.be/issues/128299
> Fix attendees by order error

- src/Tribe/Admin/Move_Tickets.php
https://central.tri.be/issues/128658
> Fix moving attendee notifications

- readme.txt
- src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
- src/views/tickets/tpp.php
https://central.tri.be/issues/130748
> Fix the date_in_range() logic upstream

- src/Tribe/Tickets.php
https://central.tri.be/issues/107997#note-19
> Removed hooking into nonexistent filter

- readme.txt
- src/views/blocks/attendees/order-links.php
- src/views/blocks/rsvp.php
- src/views/blocks/tickets.php
https://central.tri.be/issues/128512
> Rearrange code to remove a conditional

- composer.json
- composer.lock
- phpcs.xml
This bakes in PHPCS rules into the repo.
> Include PHPCS and rules via composer

- .travis.yml
- src/Tribe/Attendees.php
- src/Tribe/Attendees_Table.php
- src/Tribe/Commerce/PayPal/Orders/Table.php
- src/admin-views/attendees.php
- src/admin-views/tpp-orders.php
- src/resources/postcss/tickets-report-print.pcss
- src/resources/postcss/tickets-report.pcss
- tests.md
Also renamed some files as the names would lead you to think they only apply in one place when they apply to all ticket report tables/pages.
Related: 
https://github.com/moderntribe/events-community-tickets/pull/243 
and 
https://github.com/moderntribe/event-tickets-plus/pull/823
> fix(list_table styles): Modify our tables and their styles as we are showing them on the front end.

- src/Tribe/Attendees.php
🎫 https://central.tri.be/issues/131430#note-27
> Fix the checkin functionality

- src/admin-views/tpp-orders.php
🎫 https://central.tri.be/issues/131430#note-27
Related/required:
moderntribe/event-tickets-plus#824
https://github.com/moderntribe/events-community-tickets/pull/246
> Add in filterable title for order report(s)

- src/admin-views/tpp-orders.php
- src/resources/postcss/tickets-report.pcss
:ticket: https://central.tri.be/issues/131430
Required:
https://github.com/moderntribe/event-tickets-plus/pull/825
https://github.com/moderntribe/events-community-tickets/pull/249
> fix(report lists): Use lists where appropriate.

- readme.txt
- src/resources/postcss/tickets-report.pcss
:ticket: https://central.tri.be/issues/133195
> fix(table styles): Fix text wrapping in report table.

- readme.txt
- src/Tribe/Main.php
- src/admin-views/tribe-options-tickets.php
Add new modal toggle setting.
Add version check.
Requires: https://github.com/moderntribe/tribe-common/pull/1122
Related: https://github.com/moderntribe/event-tickets-plus/pull/835
🎫 https://central.tri.be/issues/133048
> feat(ticket settings): Organize the settings as we did for CE/CT. 

- readme.txt
- src/Tribe/Attendee_Registration/View.php
- src/admin-views/editor/fieldset/price.php
- src/views/registration/button-cart.php
🎫 https://central.tri.be/issues/129450
https://github.com/moderntribe/event-tickets/pull/1319 should clean up that commit history a good bit.
> feat(cart url): Make function detect EDD cart if available and return correct URL.

- event-tickets.php
- readme.txt
- src/Tribe/Attendees.php
- src/Tribe/Main.php
- tests/_support/Commerce/Attendee_Maker.php
- tests/wpunit/Tribe/Tickets/Attendees_Test.php
https://central.tri.be/issues/133550
> Prevent formulas from being exported when exporting attendees to CSV

- event-tickets.php
- readme.txt
- src/Tribe/Attendees.php
- src/Tribe/Main.php
- tests/_support/Commerce/Attendee_Maker.php
- tests/wpunit/Tribe/Tickets/Attendees_Test.php
https://central.tri.be/issues/133550
> Fix usage of sanitize_csv_rows in maybe_generate_csv

- src/Tribe/Commerce/PayPal/Main.php
https://central.tri.be/issues/126734
> Fix cancelled / sold calculation

- .gitignore
- src/Tribe/Attendees_Table.php
- src/resources/postcss/tickets-report.pcss
- tests/wpunit/Tribe/Tickets/Attendees_Test.php
And add VSCode to .gitignore
Also fix weird text wrap on checkin button
> Remove extra column.

- src/admin-views/tribe-options-tickets.php
https://central.tri.be/issues/133076
> change tooltip per ticket

- readme.txt
- src/views/registration/content.php
https://central.tri.be/issues/131896
> Add action hooks at beginning and end of AR page

- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/REST/V1/Endpoints/Cart.php
- src/Tribe/REST/V1/Service_Provider.php
- tests/restv1/BaseRestCest.php
- tests/restv1/PayPal/CartCest.php
- tests/restv1/PayPal/CartUpdateCest.php
https://central.tri.be/issues/132181
> Remove post ID from cart endpoint

- package-whitelist.json
See also: https://github.com/moderntribe/event-tickets-plus/pull/855
> Fix build issues

- src/Tribe/Commerce/PayPal/Cart/Interface.php
- src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/REST/V1/Endpoints/Cart.php
- src/Tribe/REST/V1/Messages.php
- tests/_support/Commerce/Attendee_Maker.php
- tests/restv1/BaseRestCest.php
- tests/restv1/PayPal/CartCest.php
- tests/restv1/PayPal/CartUpdateCest.php
- tests/wpunit/Tribe/Tickets/Commerce/PayPal/Cart/UnmanagedTest.php
https://central.tri.be/issues/132442
> Support exceptions in cart/meta update, check if ticket exists, check if ticket has capacity, add optout

- readme.txt
- src/Tribe/Tickets_View.php
https://central.tri.be/issues/134583
> Fix intercepting of template to override silence.php used by TEC

- src/Tribe/Tickets_View.php
https://central.tri.be/issues/134583
> Additional tweaks for My Tickets / My RSVPs areas

- src/Tribe/Attendee_Registration/Main.php
- src/Tribe/REST/V1/Endpoints/Cart.php
- src/Tribe/Tickets.php
https://central.tri.be/issues/134630
> Add support for cart REST check; Bypass AR screen redirect if in cart REST

- .gitignore
- codeception.dist.yml
- tests.md
https://central.tri.be/issues/134867
https://github.com/moderntribe/tribe-common/pull/1160
https://github.com/moderntribe/the-events-calendar/blob/master/tests.md#setup
> update to .env.testing.local

- src/views/registration/content.php
_Ref:_ [C#133399](https://central.tri.be/issues/133399)
> G19.12 - Update View Version and @Since

- composer.lock
- src/Tribe/Assets.php
- src/Tribe/Attendee_Registration/Modal.php
- src/Tribe/Tickets.php
- src/Tribe/Tickets_View.php
- src/resources/js/tickets-block.js
- src/resources/js/tickets-registration-page.js
- src/resources/postcss/components/_all.pcss
- src/resources/postcss/components/_loader.pcss
- src/resources/postcss/reset.pcss
- src/resources/postcss/tickets-registration-page.pcss
- src/resources/postcss/tickets.pcss
- src/views/blocks/rsvp/form/opt-out.php
- src/views/blocks/tickets/extra-available-quantity.php
- src/views/blocks/tickets/submit-button-modal.php
- src/views/components/loader.php
- src/views/modal/cart.php
- src/views/modal/registration-js.php
- src/views/registration-js/attendees/content.php
- src/views/registration-js/content.php
- src/views/registration-js/mini-cart.php
- src/views/registration/summary/title.php
**Fixed** incorrect calcs and rounding errors.
**Fixed** PHP notice about class_name at line 40 in mini-cart.php
**Fixed** PHP fatal boolean problem at line 48 in mini-cart.php
**Fixed** When loading qty from cart to tickets block, a sold out event gets that qty loaded and lets you set quantity (if you had a ticket for that sold out event in your cart before it was sold out)
**Fixed** Text at bottom of AR Page shows "There are X other tickets" message but the X is way wrong and varied in how wrong it is.
**Fixed** The message at the bottom of the page should not show if the number is 0
**Fixed** The number does not update if you remove items from the modal cart.
**Changed** optout text.
**Feature** Adds loader in footer of all event pages but only activates it (via js) on ticket (single …
> Loaders and Tweaks

- src/Tribe/Attendee_Registration/Main.php
- src/Tribe/Main.php
- src/Tribe/RSVP.php
- src/views/registration-js/content.php
https://central.tri.be/issues/135249
> Fix fatal errors and adjust formatting

- composer.lock
- package-lock.json
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Editor/Blocks/Rsvp.php
- src/Tribe/Editor/Blocks/Tickets.php
- src/Tribe/Main.php
- src/Tribe/REST/V1/Post_Repository.php
- src/Tribe/Ticket_Object.php
- src/Tribe/Ticket_Repository.php
- src/Tribe/Tickets.php
- src/views/tickets/tpp.php
- tests/_support/Testcases/Ticket_Object_TestCase.php
- tests/wpunit/Tribe/Tickets/Commerce/PayPal/Main/AmericaTest.php
- tests/wpunit/Tribe/Tickets/Commerce/PayPal/Main/AustraliaTest.php
- tests/wpunit/Tribe/Tickets/Commerce/PayPal/Main/UTCTest.php
- tests/wpunit/Tribe/Tickets/Main/Event/AmericaTest.php
- tests/wpunit/Tribe/Tickets/Main/Event/AustraliaTest.php
- tests/wpunit/Tribe/Tickets/Main/Event/UTCTest.php
- tests/wpunit/Tribe/Tickets/Main/Post/AmericaTest.php
- tests/wpunit/Tribe/Tickets/Main/Post/AustraliaTest.php
- tests/wpunit/Tribe/Tickets/Main/Post/UTCTest.php
- tests/wpunit/Tribe/Tickets/MainTest.php
- tests/wpunit/Tribe/Tickets/Ticket_Object/AmericaTest.php
- tests/wpunit/Tribe/Tickets/Ticket_Object/AustraliaTest.php
- tests/wpunit/Tribe/Tickets/Ticket_Object/UTCTest.php
- tests/wpunit/Tribe/Tickets/Ticket_ObjectTest.php
- tests/wpunit/Tribe/Tickets/Tickets/AmericaTest.php
- tests/wpunit/Tribe/Tickets/Tickets/AustraliaTest.php
- tests/wpunit/Tribe/Tickets/Tickets/UTCTest.php
- tests/wpunit/Tribe/Tickets/TicketsTest.php
*Note:* This PR will not be merged until it passes QA. It is ready to be code reviewed.
https://central.tri.be/issues/134741
> Fix timezone problems and add tests

- src/Tribe/Main.php
- src/admin-views/tribe-options-tickets.php
🎫 https://central.tri.be/issues/133048
> Correct bad version test.

- src/Tribe/Tickets_View.php
- src/resources/js/tickets-block.js
- src/resources/postcss/common/components/_all.pcss
- src/resources/postcss/common/components/_loader.pcss
- src/resources/postcss/components/_loader.pcss
- src/resources/postcss/tickets.pcss
- src/views/blocks/tickets.php
- src/views/blocks/tickets/footer.php
- src/views/blocks/tickets/item.php
- src/views/blocks/tickets/submit-button-modal.php
- src/views/components/loader.php
- src/views/modal/cart.php
- src/views/modal/registration-js.php
- src/views/registration-js/attendees/content.php
- src/views/tickets/orders.php
- src/views/tickets/tpp-success.php
REF: https://tribe.slack.com/archives/CETKBUDV3/p1570537268011100
🎥 http://p.tri.be/aXU8bp
> Implement the new loader and move the loader to inside the tickets-block.

- package.json
- src/Tribe/Attendee_Registration/View.php
- src/Tribe/Editor/Blocks/Tickets.php
- src/admin-views/editor/panel/ticket.php
- src/resources/js/tickets-block.js
- src/resources/js/tickets-registration-page.js
- src/resources/postcss/components/_notice.pcss
- src/views/blocks/tickets/extra-available-quantity.php
- src/views/blocks/tickets/item.php
- src/views/registration-js/content.php
- src/views/registration-js/mini-cart.php
🎫 https://central.tri.be/issues/134944
Adds handling of API errors - reuses the notices already on the page.
Currently only on the single-event. Will update to include AR page.
Includes/based off: https://github.com/moderntribe/event-tickets/pull/1382
> API error notices

- src/resources/js/tickets-block.js
- src/resources/postcss/tickets.pcss
- src/views/blocks/tickets/submit-button-modal.php
🎫 https://central.tri.be/issues/129443#note-25
🎥 http://p.tri.be/BZTijy
🎥 http://p.tri.be/1XoutH
Requires https://github.com/moderntribe/tribe-common/pull/1182
> Fix  issues around "0" tickets in modal.

- src/Tribe/Tickets_View.php
- src/views/blocks/tickets.php
https://central.tri.be/issues/135135
> Fix RSVP/Tickets view links

- src/resources/js/tickets-block.js
- src/resources/postcss/tickets.pcss
Fix modal selector specificity.
Add loader on Modal submit.
> Handle back button and reloading data.

- src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
https://central.tri.be/issues/135135
> Tweak cart handling to always handle cart from session properly

- src/resources/js/tickets-block.js
- src/resources/postcss/tickets.pcss
🎥  http://p.tri.be/CYsMeZ
Scroll to error message, not top of modal.
🎥  http://p.tri.be/XZiGKs
> Add invalid style to radio/checkboxes.

- composer.lock
- src/resources/js/tickets-block.js
- src/resources/js/tickets-registration-page.js
This PR does one thing:
- Sends empty values to REST API /cart/ updates from AR Modal and AR Page
https://central.tri.be/issues/129188
> Fix AR flow handling of AR meta being up to date

- src/resources/js/tickets-block.js
- src/resources/js/tickets-registration-page.js
- src/resources/postcss/tickets-registration-page.pcss
- src/views/blocks/tickets.php
- src/views/components/loader.php
- src/views/modal/cart.php
- src/views/modal/registration.php
- src/views/registration-js/content.php
Update the loader to avoid variable conflicts. 
Implement loader on AR page. 
Add loader to API calls where the user has to wait for it to finish before proceeding.
:ticket: https://central.tri.be/issues/136096
> feat(API loader): Add loader indicator for all API calls.

- src/views/registration-js/content.php
https://central.tri.be/issues/131896
> Add quantity notice action to new content template

- src/resources/postcss/common/base/typography/_body.pcss
- src/resources/postcss/tickets.pcss
- src/views/blocks/tickets/content-description.php
Fix font size on description.
Fix disabled button styles.
Add new body-text class.
> A few style fixes from @niconerd 's spreadsheet.

- src/Tribe/Editor/Provider.php
- src/Tribe/Tickets_View.php
This works with latest core as well.
🎫 https://central.tri.be/issues/136322
📷 http://p.tri.be/vZBA7Q (no error)
> On older (4.7) WP tribe() fails here - let's not use it.

- src/resources/postcss/tickets.pcss
- src/views/registration-js/attendees/fields.php
🎫 https://central.tri.be/issues/129452
📷 http://p.tri.be/srxHdm
📷 http://p.tri.be/MPJuWg
📸 http://p.tri.be/jlTAc9
> A few spacing tweaks via mattcr

- composer.lock
- src/resources/js/tickets-block.js
🎫 https://central.tri.be/issues/132181
🎥 http://p.tri.be/6i71H4
🎥 http://p.tri.be/ELL0Gq (non-modal)
> Remove js that disables TCC tickets when one is selected.

- src/admin-views/editor/panel/ticket.php
🎫 https://central.tri.be/issues/135359
📸 http://p.tri.be/V0nBkc
> Add block for tickets/rsvps with correct text.

- readme.txt
- src/Tribe/Editor/Blocks/Tickets.php
🎫 https://central.tri.be/issues/122334
📷 http://p.tri.be/AlKgwE (errors)
📸  http://p.tri.be/F2w5rA (look ma, no errors!)
See also (requires): https://github.com/moderntribe/tribe-common/pull/1195
> Add some sanity checks.

- composer.lock
- src/Tribe/Assets.php
- src/Tribe/Editor/Blocks/Tickets.php
- src/resources/js/tickets-block.js
One note: I changed the `TribeTickets` param to prevent collisions/overwriting with the same param in `src/Tribe/Assets.php`
🎫 https://central.tri.be/issues/136607 (reduce availability calls)
🎫 https://central.tri.be/issues/136608 (make initial cart load optional)
> Some tweaks per Slack convo about reducing API calls.

- src/Tribe/Assets.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Editor/Blocks/Tickets.php
- src/resources/js/tickets-block.js
🎫 https://central.tri.be/issues/136610
Add localized vars in `src/Tribe/Editor/Blocks/Tickets.php`
Also comment out the filter we don't want folks using yet.
Hook in with dummy data in `src/Tribe/Commerce/PayPal/Main.php`
Fix a docblock in `src/Tribe/Assets.php`
Add a temp check in `src/resources/js/tickets-block.js`
📸 http://p.tri.be/Wcia5U (localized vars logged, includes https://github.com/moderntribe/event-tickets-plus/pull/893 )
> Add localizing of cart and checkout urls.

- src/Tribe/Attendee_Registration/Modal.php
🎫 https://central.tri.be/issues/136609
> Remove commented out line

- composer.lock
- package.json
- src/Tribe/Commerce/Cart.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Main.php
- src/Tribe/REST/V1/Endpoints/Base.php
- src/Tribe/REST/V1/Endpoints/Cart.php
- src/Tribe/Tickets_Handler.php
- tests/restv1/PayPal/CartCest.php
- tests/restv1/PayPal/CartUpdateCest.php
https://central.tri.be/issues/136611
> Update Cart handling so it's not just REST context only

- src/Tribe/Main.php
https://central.tri.be/issues/136611
> Run hooks for cart so that we can check if the $_POST request is happening

- src/resources/js/tickets-block.js
🎫 https://central.tri.be/issues/136594
Different but related issue, original issue appears to be corrected.
> Correct total calcs in modal ticket block.

- src/template-tags/tickets.php
https://central.tri.be/issues/123365#note-30
> only send numerics to number format

- src/Tribe/Attendee_Registration/Main.php
...to include the custom slug and/or custom page.
Ensure that the AR page body class is applied.
🎫 https://central.tri.be/issues/136096 (need body class for loader styles to work)
> Tweak the logic that determines if we are on the AR page 

- src/Tribe/Commerce/Cart.php
https://central.tri.be/issues/136611
> Fix AR page saving so it is not additive; Redirect to AR Page if meta not up to date for TC

- src/resources/js/tickets-registration-page.js
- src/resources/postcss/tickets-registration-page.pcss
- src/views/modal/registration-js.php
- src/views/registration-js/content.php
🎫 https://central.tri.be/issues/136609
Also some style adjustments for the mini-cart.
> Alter AR page so we do a regular form submit.

- src/resources/js/tickets-block.js
- src/resources/postcss/tickets.pcss
🎫 https://central.tri.be/issues/129452
> Style tweaks and a patch for price calcs

- src/views/v2/day/event/cost.php
- src/views/v2/list/event/cost.php
- src/views/v2/map/event-cards/event-card/event/actions/cost.php
- src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
- src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
- src/views/v2/photo/event/cost.php
- src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
- src/views/v2/week/mobile-events/day/event/cost.php
🎫 https://central.tri.be/issues/137260
🎥 https://www.loom.com/share/162f79190b514bfc827b8456c027fe7e
> VR > ET Integration

- composer.lock
- src/modules/blocks/rsvp/attendee-registration/container.js
🎫 https://central.tri.be/issues/137394
> Hotfix - Add same for RSVP

- src/functions/views/provider.php
Prevents re-defining method in ET, we should use the function from TEC.
> Definition of Views V2 should rely on Events Function

- src/Tribe/Assets.php
- src/resources/postcss/tickets.pcss
🎫 https://central.tri.be/issues/137533
Bad: https://screencast.com/t/0iuTntyU8kG
Good: http://p.tri.be/g5U0xf
> Fixes missing admin stylesheet.

- src/Tribe/Attendee_Registration/Main.php
- src/Tribe/Attendee_Registration/View.php
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Tickets.php
- src/views/blocks/tickets/item.php
- src/views/registration-js/attendees/fields/checkbox.php
https://central.tri.be/issues/137356
This PR:
* Use current object instead of tribe() AR object in AR object method
* Fix tickets in cart filter and make it uniform
* Only return tickets in cart if provider matches (Tribe Commerce)
* Use correct field name for checkboxes in AR Modal / AR Page
* Pass provider into tickets in cart filter and update it so it's uniform
Screencast of AR page flow: https://p199.p4.n0.cdn.getcloudapp.com/items/RBu0j2dN/Screen+Recording+2019-11-19+at+10.30+AM.mov
Screenshot of Attendee Information in Attendees List (admin):
https://p199.p4.n0.cdn.getcloudapp.com/items/xQuv2mAy/Screen+Shot+2019-11-19+at+10.32.58+AM.png?v=fdf2a20485c04d0600ffea5beacc2998
> Fix ARI checkbox saving from AR Modal / AR Page

- .gitignore
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Tickets.php
🎫 https://central.tri.be/issues/129452#note-36
Requires https://github.com/moderntribe/event-tickets-plus/pull/905
> Fix missing block on ticketed page.

- src/Tribe/Attendee_Registration/View.php
- src/Tribe/Tickets.php
- src/views/blocks/tickets/quantity-number.php
https://central.tri.be/issues/136258
This PR:
* Fixes a typo
* Don't send quantity_X anymore
* Detect provider from current class if not set..
* Fix old logic for AR page redirects
* No longer redirect with 307 which forwards POST data and tries to reprocess it
> Fix EDD cart bugs and redirect problems

- src/views/v2/day/event/cost.php
- src/views/v2/list/event/cost.php
- src/views/v2/map/event-cards/event-card/event/actions/cost.php
- src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
- src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
- src/views/v2/photo/event/cost.php
- src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
- src/views/v2/week/mobile-events/day/event/cost.php
- tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Day_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
- tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/List_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
- tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_with_cost__1.php
_Ref:_ [C#137580](http://central.tri.be/issues/137580)
---
📹 https://i.bordoni.me/nOuWZNgD
> Past RSVP no longer breaks views

- composer.lock
- src/Tribe/Tickets.php
:ticket: https://central.tri.be/issues/129452
🎥 http://p.tri.be/PXJyPU
> Fix tests for showing blocks vs. non-block templates.

- src/Tribe/Attendee_Registration/Main.php
- src/admin-views/tribe-options-tickets.php
ensure modal doesn't get triggered if ET+ not enabled.
🎫 https://central.tri.be/issues/137613
🎥 http://p.tri.be/Vl8CP5
Requires https://github.com/moderntribe/event-tickets-plus/pull/907
> Move all attendee options to ET+, 

- src/resources/js/frontend-ticket-form.js
- src/resources/js/tickets-block.js
BAD: http://p.tri.be/7vjWut
GOOD: http://p.tri.be/WFvzWR
https://central.tri.be/issues/137691
> Ensure that session storage is cleared on successful submit of modal.

- src/resources/js/tickets-block.js
- src/resources/js/tickets-registration-page.js
https://central.tri.be/issues/137708
📸 http://p.tri.be/MylMFV
> Correct number format handling on AR page.

- src/resources/js/tickets-block.js
- src/resources/js/tickets-registration-page.js
🎫 https://central.tri.be/issues/137708
📸 http://p.tri.be/hE5hjz
> Fix getPrice() - stop using parseFloat for money!

- src/views/registration-js/content.php
https://central.tri.be/issues/137750
> Don't output extra hdiden inputs for each event

- readme.txt
- src/resources/js/rsvp-block.js
- src/resources/postcss/rsvp.pcss
- src/styles/rsvp/frontend.pcss
- src/template-tags/tickets.php
- src/views/blocks/rsvp.php
- src/views/blocks/rsvp/loader.php
- src/views/blocks/tickets.php
🎫 https://central.tri.be/issues/135660
📸 http://p.tri.be/ClD8Dm
>  Use the same loading icon for the RSVP block that we're using for the tickets block.

- readme.txt
- src/modules/blocks/rsvp/header-image/container.js
Correct the RSVP hader-image module so that the image gets attached correctly.
:ticket: https://central.tri.be/issues/137243
🎥 http://p.tri.be/rgw2x8
> fix(rsvp image): Fix rsvp header image attachment.

- src/Tribe/Attendee_Registration/View.php
- src/Tribe/Commerce/Cart.php
- src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/Commerce/PayPal/Main.php
- src/views/registration-js/content.php
https://central.tri.be/issues/137998
Screencast: https://p199.p4.n0.cdn.getcloudapp.com/items/4guxAzG9/Screen+Recording+2019-12-03+at+10.17+AM.mov
> Fix Tribe Commerce AR meta flow handling (non-AR modal)

- src/Tribe/Commerce/Cart.php
- src/Tribe/Commerce/PayPal/Main.php
- src/template-tags/tickets.php
- src/views/registration-js/content.php
https://central.tri.be/issues/137988
> Fix additive handling for Tribe Commerce coming from ticket block

- src/Tribe/Attendee_Registration/View.php
- src/Tribe/Commerce/Cart.php
- src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
- src/Tribe/Commerce/PayPal/Gateway.php
- src/Tribe/Commerce/PayPal/Main.php
- src/template-tags/tickets.php
- src/views/registration-js/content.php
> Bucket merge

- composer.lock
- package-lock.json
- tests/_support/Commerce/PayPal/Ticket_Maker.php
https://central.tri.be/issues/138103
> Update ticket maker for PayPal to set ticket provider field on post

- readme.txt
- src/Tribe/Editor/Meta.php
https://central.tri.be/issues/137875
Screencast: https://p199.p4.n0.cdn.getcloudapp.com/items/6quL0R19/Screen+Recording+2019-12-09+at+10.48+PM.mov
> Fix RSVP saving of capacity and not going fields

- src/views/blocks/tickets/registration/attendee/submit.php
:ticket: https://central.tri.be/issues/138035
📷 http://p.tri.be/IR3Zil (old)
📸 http://p.tri.be/JNiXIo (new)
> refactor(change button text): Change text of AR page submit button.

- composer.lock
- event-tickets.php
- readme.txt
- src/Tribe/Attendee_Registration/View.php
- src/Tribe/Commerce/Currency.php
- src/Tribe/Editor/Blocks/Tickets.php
- src/Tribe/Main.php
- src/Tribe/Tickets.php
https://central.tri.be/issues/138390
Screenshot of all currencies always loading currency formatting info instead of querying first: https://p199.p4.n0.cdn.getcloudapp.com/items/wbukepLO/Screen+Shot+2019-12-11+at+3.17.37+PM.png?v=7674f2fdfea52697dc8f608d0be82f1e (post in question only has one WC ticket)
> When setting up assets, don't load all tickets on every page

- readme.txt
- src/styles/tickets/frontend.pcss
See: https://tribe.slack.com/archives/C0258NG6N/p1576254625003500
https://central.tri.be/issues/138558
> improve sizing on +/- for tickets

- src/Tribe/Tickets_Handler.php
- src/views/blocks/rsvp/details/availability.php
- src/views/blocks/tickets/extra-available.php
- src/views/tickets/rsvp.php
- src/views/tickets/tpp.php
https://central.tri.be/issues/137875
> Enforce string when getting capacity amount and fix threshold restriction

- readme.txt
- src/Tribe/Editor/Blocks/Tickets.php
🎫 https://central.tri.be/issues/138646
📸 http://p.tri.be/jNTpeb
> Don't try to laod RSVPs into the tickets block

- composer.lock
- readme.txt
- src/Tribe/Editor/Blocks/Attendees.php
- src/Tribe/Tickets_Handler.php
- src/resources/js/frontend-ticket-form.js
- src/resources/js/tickets-block.js
- src/views/blocks/tickets/item.php
🎫 https://central.tri.be/issues/138620
🎥 (bad) http://p.tri.be/Ky7jFR
🎥 (good) http://p.tri.be/VXwieu
**Hold:** Pending the next release, **DO NOT merge into G19.15!**
> Correct shared cap and tweak keyboad controls on ticket block.

- src/Tribe/Tickets_View.php
🎟 [TEC-3076](https://moderntribe.atlassian.net/browse/TEC-3076)
---
📹 https://i.bordoni.me/Jru7x5Z1
> Properly make filtering for Tickets page for V2

- readme.txt
- src/template-tags/tickets.php
- src/views/blocks/tickets.php
Reverts moderntribe/event-tickets#1523
Merged into the wrong branch
> Revert "[ETP-51] 138725 work even if post only has RSVPs"

- readme.txt
- src/views/blocks/attendees.php
[ET-589]
[ET-589]: https://moderntribe.atlassian.net/browse/ET-589
> ET-589 close open div

- src/views/blocks/attendees.php
The div wasn't closed and then we closed it incorrectly. This "fixes the fix". No readme needed,
handled by original PR.
🐫 http://p.tri.be/OXdo9x
📷 http://p.tri.be/cZSFcf
:ticket: [ET-589]
[ET-589]: https://moderntribe.atlassian.net/browse/ET-589
> fix(attendees block): fix div closure

- readme.txt
- src/Tribe/Views/V2/Models/Tickets.php
- src/template-tags/tickets.php
- src/views/blocks/tickets.php
[ETP-51] https://share.getcloudapp.com/kpumOGEl
[ETP-51]: https://moderntribe.atlassian.net/browse/ETP-51
> ETP-51: back to #tribe-tickets

- readme.txt
- src/Tribe/Commerce/Currency.php
5min demo: https://share.getcloudapp.com/04ugQn8e
[ETP-33] 
[ETP-33]: https://moderntribe.atlassian.net/browse/ETP-33
> WooCommerce price suffix

- composer.lock
- src/resources/js/tickets-block.js
Eslint fixes wound up breaking the site due to a syntax error, this corrects the error in a way that also mollifies eslint.
> fix(ticket-block.js): Correct js issues due to eslint fixes.

- src/Tribe/Editor/Blocks/Tickets.php
- src/Tribe/Tickets_View.php
[ET-608] (which is not yet ready, having a question in the ticket comment)... BUT this PR is just formatting
[ET-608]: https://moderntribe.atlassian.net/browse/ET-608
> ET-608 formatting as part of QA repair

- src/resources/postcss/tickets.pcss
without a var (for IE 11).
:ticket: [ET-619]
[ET-619]: https://moderntribe.atlassian.net/browse/ET-619
> fix(modal background): Override the modal background in ET 

- src/resources/js/tickets-block.js
- src/resources/js/tickets-registration-page.js
- src/views/blocks/tickets/extra-price.php
Add a wrapper to the actual price (default or sale price) to better target for js
calculations/updates.
Great catch @jesseeproductions !
:ticket: [etp-47]
> fix(sale calcs): Fix calculations with sale prices.

- readme.txt
- src/resources/js/tickets-block.js
🎫 https://moderntribe.atlassian.net/browse/ETP-43
🎥 https://www.loom.com/share/82d912da8cea458f91b15e54536d2e1f
> ET > Fix: Hitting enter change quantities.

- readme.txt
- src/views/v2/day/event/cost.php
- src/views/v2/list/event/cost.php
- src/views/v2/map/event-cards/event-card/actions/cost.php
- src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
- src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
- src/views/v2/photo/event/cost.php
- src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
- src/views/v2/week/mobile-events/day/event/cost.php
🎫 https://moderntribe.atlassian.net/browse/ET-713
🎥 not required.
> VR > Update docblocks for views

- readme.txt
- src/Tribe/Attendee_Registration/View.php
- src/views/registration-js/content.php
[ET-716]
Screencast: https://share.getcloudapp.com/9ZuAv98R
[ET-716]: https://moderntribe.atlassian.net/browse/ET-716
> Resolve potential fatal errors when an object is passed to determine a CSS class where we had expected a string

- readme.txt
- src/Tribe/Commerce/PayPal/Gateway.php
Fixes [ET-714]
Unblocks testing for [ET-717]
**Screencast:** https://share.getcloudapp.com/xQugKZ8D
[ET-714]: https://moderntribe.atlassian.net/browse/ET-714
[ET-717]: https://moderntribe.atlassian.net/browse/ET-717
> Fix Tribe Commerce PayPal redirects to prevent TEC taking over

- readme.txt
- src/Tribe/Tickets.php
[ET-714]
[ET-714]: https://moderntribe.atlassian.net/browse/ET-714
> Better detect the post ID to use on normal pages for Tribe Commerce

- src/Tribe/Commerce/PayPal/Gateway.php
[ET-714]
[ET-714]: https://moderntribe.atlassian.net/browse/ET-714
> Add tribe_redirected to one more spot

- readme.txt
- src/Tribe/Attendee_Registration/Template.php
- src/Tribe/Main.php
- src/Tribe/Theme_Compatibility.php
🎫 https://moderntribe.atlassian.net/browse/ETP-156
🎥 https://www.loom.com/share/346c2e6a7dd142588e6830060b2affa5
Related
🎫 https://github.com/moderntribe/tribe-common/pull/1287
> AR Modal > Add theme compatibility for overlaps.

- readme.txt
- src/resources/js/tickets-registration-page.js
🎫 https://moderntribe.atlassian.net/browse/ETP-220
🎥 https://www.loom.com/share/d9d20cec12984ec7a2a3fcd6e459dfbf
> AR > Fix broken AR page in IE11

- readme.txt
- src/Tribe/Tickets.php
[ET-730]
Screencast: https://share.getcloudapp.com/7KuRJRb1
[ET-730]: https://moderntribe.atlassian.net/browse/ET-730
> When Classic Editor plugin is activated, prevent ticket availability AJAX errors by temporarily disabling the AJAX requests

- readme.txt
- src/Tribe/Assets.php
- src/Tribe/Main.php
🎫 https://moderntribe.atlassian.net/browse/ET-725
🎥 https://www.loom.com/share/3822e1263afe44209ad61f4e75977c2b
> ET > Fix common styles dependency

- readme.txt
- src/Tribe/Attendee_Registration/Main.php
- src/Tribe/Attendee_Registration/Template.php
- src/resources/postcss/tickets-registration-page.pcss
- src/views/registration-js/content.php
🎫 https://moderntribe.atlassian.net/browse/ETP-42
🎥 https://www.loom.com/share/6759f34b44b64829b1d064805311a97d
🗒 Notes
- The templates were fine, we need to add some compatibility fixes for supported themes. Like the one I added for twentytwenty.
> AR > Page > Redirection, template, title.

- readme.txt
- src/Tribe/Tickets_View.php
[ET-735]
Screencast: https://share.getcloudapp.com/WnuNK06L
[ET-735]: https://moderntribe.atlassian.net/browse/ET-735
> Resolve problems where "View My Tickets" (or RSVPs) page would be blank or not load

- readme.txt
- src/views/blocks/tickets/content-description.php
- src/views/blocks/tickets/extra.php
- src/views/blocks/tickets/quantity-add.php
- src/views/blocks/tickets/quantity-remove.php
🎫 https://moderntribe.atlassian.net/browse/ET-725
🎥 https://www.loom.com/share/7e2eabd82383497fb6736448c8b12bd0
> ET > Use common a11y classes

- readme.txt
- src/Tribe/Commerce/PayPal/Main.php
- src/Tribe/Global_Stock.php
- src/Tribe/Tickets_Handler.php
[ET-737]
Screencast: https://share.getcloudapp.com/NQuZbz5R
[ET-737]: https://moderntribe.atlassian.net/browse/ET-737
> Save initial shared capacity value for global stock correctly on first Tribe Commerce ticket so availability shows as expected instead of zero

- src/resources/js/tickets-registration-page.js
[ET-740]
No readme.txt changelog needed (regression)
Screencast: https://share.getcloudapp.com/WnuNEbAj
[ET-740]: https://moderntribe.atlassian.net/browse/ET-740
> Fix JS selector

- src/Tribe/RSVP.php
- src/Tribe/Tickets.php
Remove non required variable `$product`
Make sure docblocks are upto date
> Cleanup code for `get_event_for_ticket`

- src/Tribe/Data_API.php
- src/views/blocks/rsvp/form/attendee-meta.php
- src/views/blocks/rsvp/form/details.php
- src/views/blocks/rsvp/form/quantity.php
[ETP-149] (but not really)
[ETP-149]: https://moderntribe.atlassian.net/browse/ETP-149
> docblock corrections and array() to []

- .travis.yml
- tests/_support/Testcases/REST/V1/BaseTicketEditorCest.php
- tests/_support/Testcases/RSVPBlock_TestCase.php
- tests/_support/Testcases/TicketsBlock_TestCase.php
- tests/wpunit/Tribe/Tickets/Partials/Tickets/ContentDescriptionTest.php
- tests/wpunit/Tribe/Tickets/Partials/Tickets/ExtraTest.php
- tests/wpunit/Tribe/Tickets/Partials/Tickets/SubmitTest.php
Attempt to fix the URL problems in the same way we did for Views V2.
> Resolve URL problems with snapshots on travis

- src/Tribe/Editor/Blocks/Tickets.php
- src/resources/js/tickets-block.js
- src/views/blocks/tickets/quantity-number.php
[ETP-149] (but really [GTRIA-116] and probably also [GTRIA-118])
2min demo video of it working and of what it was like when not working: https://share.getcloudapp.com/2NuBzKGJ
[ETP-149]: https://moderntribe.atlassian.net/browse/ETP-149
[GTRIA-116]: https://moderntribe.atlassian.net/browse/GTRIA-116
[GTRIA-118]: https://moderntribe.atlassian.net/browse/GTRIA-118
> Fix for tickets block changing displayed qty available

- readme.txt
- src/resources/js/tickets-block.js
🎫 ET-758
🎥 https://www.loom.com/share/f86bee2f22a842b8873a674a851e75ee
> Capacity > Shared capacity reset in Safari.

- readme.txt
[ETP-149]
Removed duplicate-ish line (with incorrect filter name) and grouped Fixes and Tweaks
[ETP-149]: https://moderntribe.atlassian.net/browse/ETP-149
> readme corrections

- src/resources/js/rsvp-block.js
[ETP-149]
Also adds the Tickets Block stepUp() repair from https://github.com/moderntribe/event-tickets/pull/1621 [ET-758] so it won't occur here too
**Screencast:** https://share.getcloudapp.com/Z4u57g0Z 
[ETP-149]: https://moderntribe.atlassian.net/browse/ETP-149
[ET-758]: https://moderntribe.atlassian.net/browse/ET-758
> Fix quantity validation for the RSVP block

- readme.txt
- src/Tribe/Tickets.php
🎫 https://moderntribe.atlassian.net/browse/ETP-302
Move action after the ticket was created, so it works also on ticket creation.
> Tickets > Move action to proper place.

- readme.txt
- src/resources/js/tickets-block.js
🎫 https://moderntribe.atlassian.net/browse/ETP-231
🎥 https://www.loom.com/share/9f9498acf4ff4508bb4b7484dce07a86
> Tickets block > handle value when there are empty decimal/separators

- src/views/modal/registration-js.php
🎫 https://moderntribe.atlassian.net/browse/ETP-233
🎥 https://www.loom.com/share/e8eb7a9585774c83963757ef02f5bb03
> Tickets > Remove "Whoops" from AR modal.

- readme.txt
- src/resources/postcss/tickets.pcss
- src/views/blocks/tickets/quantity-add.php
- src/views/blocks/tickets/quantity-remove.php
- tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/QuantityAdd__test_render_quantity__1.php
- tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/QuantityRemove__test_render_quantity__1.php
- tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/Quantity__test_should_render_quantity_available__1.php
🎫 https://moderntribe.atlassian.net/browse/ETP-224
🎥 https://www.loom.com/share/5c87563c7a8b4966a847c6859e24694d
> Tickets > Quantity markup

- readme.txt
- src/Tribe/Events/Views/V2/Models/Tickets.php
- src/views/v2/day/event/cost.php
- src/views/v2/list/event/cost.php
- src/views/v2/map/event-cards/event-card/actions/cost.php
- src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
- src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
- src/views/v2/photo/event/cost.php
- src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
- src/views/v2/week/mobile-events/day/event/cost.php
🎫 https://moderntribe.atlassian.net/browse/ET-764
🎥 https://www.loom.com/share/186af3ca76104d1a8943e95ebed92d95
> VR > Sold out message for views.

- readme.txt
[ET-773]
[ET-773]: https://moderntribe.atlassian.net/browse/ET-773
> correct ticket# and consistent quoting

- src/resources/postcss/tickets-registration-page.pcss
🎫 https://moderntribe.atlassian.net/browse/GTRIA-166
🎥 https://www.loom.com/share/97b7bb7b377a451da50f5f9001d44c99
[ETP-315]
[ETP-315]: https://moderntribe.atlassian.net/browse/ETP-315
> [ETP-315] AR > Set margins for the mini cart title.

- readme.txt
- src/Tribe/Attendees_Table.php
- src/Tribe/Commerce/Orders_Tabbed_View.php
- src/admin-views/attendees.php
Event name, each Ticket name, and each Attendee
- 8min before/after demo: https://share.getcloudapp.com/8Luj12OA
- 1min supplemental before/after demo for duplicate Attendee ID removed from Status column for RSVPs: https://share.getcloudapp.com/d5uvnB86
> Append IDs like [#___] to Attendees Report

- readme.txt
- src/views/blocks/attendees/view-link.php
- src/views/tickets/orders-pp-tickets.php
- src/views/tickets/orders-rsvp.php
- src/views/tickets/orders.php
- src/views/tickets/view-link.php
[ET-787]
(This was discovered when implementing ETP shortcodes.)
[ET-787]: https://moderntribe.atlassian.net/browse/ET-787
> fixes and changelog

- readme.txt
- src/Tribe/Events/Views/V2/Models/Tickets.php
- src/views/blocks/tickets.php
- src/views/blocks/tickets/content-inactive.php
- src/views/blocks/tickets/submit-button.php
Replace hard-coded Tickets label with function to get the label so that it can be filtered
[ETP-119]
[ETP-119]: https://moderntribe.atlassian.net/browse/ETP-119
> Update content-inactive.php for [ETP-119]

- src/views/blocks/tickets/submit-button-modal.php
Use function to get ticket label
> Update submit-button-modal.php for ETP-119

- event-tickets.php
- readme.txt
- src/Tribe/Events/Views/V2/Models/Tickets.php
- src/Tribe/Main.php
[ET-836]
[ET-836]: https://moderntribe.atlassian.net/browse/ET-836
> [ET-836] Hotfix double quote issue

- readme.txt
- src/views/tickets/email.php
This adds a hook that Virtual Events depends on to add the virtual link/zoom info to the ticket emails.
[VE-46]
[ET-844]
:camera: http://p.tri.be/EsQ6Ly
RE: https://github.com/moderntribe/events-virtual/pull/59
[VE-46]: https://moderntribe.atlassian.net/browse/VE-46
[ET-844]: https://moderntribe.atlassian.net/browse/ET-844
> [ET-844] Feature(virtual events): Add hook for VE in email template.

- readme.txt
- src/resources/postcss/tickets.pcss
- src/views/registration-js/attendees/fields/birth.php
Ticket: https://moderntribe.atlassian.net/browse/ET-835
> [ET-835] Fix CSS in Birth Date Field not applying in all contexts

- src/resources/postcss/tickets.pcss
[ET-835] QA repair
2min demo of it working (before vs after): https://share.getcloudapp.com/6qu221zr
[ET-835]: https://moderntribe.atlassian.net/browse/ET-835
> don’t cutoff text

- src/Tribe/Tickets_View.php
- src/views/v2/rsvp-kitchen-sink.php
- src/views/v2/rsvp-kitchen-sink/ari.php
- src/views/v2/rsvp-kitchen-sink/default-full.php
- src/views/v2/rsvp-kitchen-sink/default-must-login.php
- src/views/v2/rsvp-kitchen-sink/default-no-description.php
- src/views/v2/rsvp-kitchen-sink/default-unlimited.php
- src/views/v2/rsvp-kitchen-sink/default.php
- src/views/v2/rsvp-kitchen-sink/form-going.php
- src/views/v2/rsvp-kitchen-sink/form-not-going.php
- src/views/v2/rsvp-kitchen-sink/success.php
- src/views/v2/rsvp/details/availability.php
📹 https://www.loom.com/share/16c82282814b413dba022167a49710d9
> Add RSVP Kitchen sink

- readme.txt
> Add me to the contributors list.

- src/resources/postcss/common-responsive.pcss
- src/resources/postcss/rsvp/_actions.pcss
- src/resources/postcss/rsvp/_attendee-registration.pcss
- src/resources/postcss/rsvp/_details.pcss
- src/resources/postcss/rsvp/_messages.pcss
- src/views/v2/rsvp/actions/rsvp.php
- src/views/v2/rsvp/actions/rsvp/going.php
- src/views/v2/rsvp/actions/rsvp/not-going.php
- src/views/v2/rsvp/actions/success.php
- src/views/v2/rsvp/ari/sidebar/guest-list.php
- src/views/v2/rsvp/ari/sidebar/quantity.php
- src/views/v2/rsvp/details/attendance.php
- src/views/v2/rsvp/details/availability.php
- src/views/v2/rsvp/details/description.php
- src/views/v2/rsvp/details/title.php
Design QA changes for the new RSVP FE.
📹 https://www.loom.com/share/300ebe82f09b4645a2b32e7747bc73cd
> RSVP FE DQA

- src/Tribe/Main.php
- src/Tribe/Service_Providers/Customizer.php
🎫 https://moderntribe.atlassian.net/browse/ET-824
📹 https://www.loom.com/share/d3cdbb39618647ad91e92b46f82e8522
> RSVP > Customizer

- src/resources/postcss/components/_loader.pcss
- src/views/v2/components/loader/loader.php
- src/views/v2/rsvp.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/LoaderTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/__snapshots__/LoaderTest__test_should_render_loader__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/__snapshots__/LoaderTest__test_should_render_loader_with_custom_classes__1.php
🎫 https://moderntribe.atlassian.net/browse/ET-866
📹 https://www.loom.com/share/6313010c47854c27891e2e5b8850e6d8
> V2 > Loader component

- src/Tribe/RSVP.php
- src/admin-views/rsvp-metabox-not-going.php
[ET-808]
Screencast: https://share.skc.dev/4gujp87Q
[ET-808]: https://moderntribe.atlassian.net/browse/ET-808
> [ET-808] Add "Not Going" option to classic editor if using new RSVP views

- readme.txt
[ET-877]
[ET-877]: https://moderntribe.atlassian.net/browse/ET-877
> Updated WordPress.org tags

- readme.txt
- src/resources/postcss/tickets.pcss
- src/views/registration-js/attendees/fields/birth.php
[ET-875]
8min demo of it working: https://share.getcloudapp.com/X6uojv4o
[ET-875]: https://moderntribe.atlassian.net/browse/ET-875
> ET-875 DOB Field Tweaks

- readme.txt
Update the previous change log entry in order to improve the context
around triggered based messages.
> Update change log entries

- readme.txt
- src/Tribe/Commerce/Currency.php
- src/Tribe/Editor/Blocks/Tickets.php
- src/Tribe/Tickets.php
- src/Tribe/Tickets_Handler.php
- src/Tribe/Tickets_View.php
- src/admin-views/editor/fieldset/settings-provider.php
- src/template-tags/tickets.php
- src/views/registration-js/content.php
- src/views/registration-js/mini-cart.php
- src/views/tickets/orders.php
- tests/wpunit/Tribe/Tickets/TicketsTest.php
[ET-843]
[ETP-333]
Screencast: https://share.skc.dev/p9uPWk0A
[ET-843]: https://moderntribe.atlassian.net/browse/ET-843
[ETP-333]: https://moderntribe.atlassian.net/browse/ETP-333
> [ET-843] [ETP-333] Add get_event_ticket_provider_object() and adjust usages of get_event_ticket_provider()

- src/views/registration-js/mini-cart.php
[ET-880]
Fixes usage of the provider class var and checking. No changelog needed as it fixes an item that already had a changelog. Also, it's worth noting that the screenshot is bugged with a style issue we're investigating separately.
**Original problem where minicart was empty:** https://share.getcloudapp.com/bLuj4jkG
**Screenshot:**
[ET-880]: https://moderntribe.atlassian.net/browse/ET-880
> [ET-880] Check against the class name like we do everywhere else

- src/Tribe/Assets.php
- src/resources/postcss/tickets.pcss
[ET-883]
🎥 https://www.loom.com/share/1438e13d83fb481e81676a8b9299f8fd
[ET-883]: https://moderntribe.atlassian.net/browse/ET-883
> [ET-883] Spotfix/g20.07 findings

- src/Tribe/Admin/Display_Settings.php
- src/template-tags/tickets.php
[ET-841]
Screencast: https://p199.p4.n0.cdn.getcloudapp.com/items/2Nu5oEOO/Screen%20Recording%202020-07-10%20at%2003.15.07%20PM.mp4
We should hold on this PR until we know the feature will be complete in time for G20.07 to ship. If it doesn't make it, we can just put this PR forward for G20.08
[ET-841]: https://moderntribe.atlassian.net/browse/ET-841
> [ET-841] Enable the opt-in setting

- src/resources/js/v2/rsvp-manager.js
🎫 ET-833
🎥 https://www.loom.com/share/aa518461be6e47a3ba36104a051ded5d
> Add error handler to the RSVP manager.

- src/Tribe/RSVP.php
[ET-857]
Screencast: https://share.skc.dev/NQurdZz7
[ET-857]: https://moderntribe.atlassian.net/browse/ET-857
> [ET-857] Handle RSVP processing for attendees with new ticket input structure

- src/views/v2/rsvp/ari/form/fields.php
- src/views/v2/rsvp/ari/form/fields/email.php
- src/views/v2/rsvp/ari/form/fields/meta.php
- src/views/v2/rsvp/ari/form/fields/name.php
- tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/Actions/__snapshots__/SuccessTest__test_should_render_success_message__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/Form/__snapshots__/FormTest__test_should_render_form_going__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/Form/__snapshots__/FormTest__test_should_render_form_not_going__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/Messages/__snapshots__/MustLoginTest__test_should_render_must_login__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/__snapshots__/ActionsTest__test_should_render_success__1.php
- tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set ari__1.php
- tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set going__1.php
- tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set not going__1.php
🎫 ET-833
🎥 https://www.loom.com/share/e604c99dc2a1432ea88c9c41bba144dc
> Add name an email to main guest for ARi

- src/Tribe/RSVP.php
- src/views/v2/rsvp/actions.php
- src/views/v2/rsvp/ari/form.php
- src/views/v2/rsvp/messages/success.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block with data set 0__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block with data set 1__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block with data set 2__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 0__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 1__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 2__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 3__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 4__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 5__1.php
[ET-857]
Screencast: https://share.skc.dev/geuz0Wye
[ET-857]: https://moderntribe.atlassian.net/browse/ET-857
> [ET-857] Add RSVP ticket_id and order_status for ARI

- src/Tribe/Editor/Compatibility/Tickets.php
- src/Tribe/Editor/Template/Overwrite.php
- src/Tribe/Tickets.php
[ET-889] ... but not really... no artifact needed
[ET-889]: https://moderntribe.atlassian.net/browse/ET-889
> ET-889 - formatting

- src/resources/js/v2/rsvp-ari.js
📹 https://www.loom.com/share/5257006682074ebe90dca4164cfe077b
> RSVP > Fix cancel bind on ARI

- src/resources/js/v2/rsvp-ari.js
🎥 https://www.loom.com/share/acce7779d7cd45bcb2e1a991ff8f19db
> RSVP > IE11 issues - Fix default parameter for ES5

- src/resources/postcss/forms.pcss
- src/resources/postcss/rsvp/_attendee-registration.pcss
- src/resources/postcss/rsvp/_form.pcss
🎫 ET-863
🎥 https://www.loom.com/share/be6ee0c9e7f242a889d991d19257220b
> RSVP > DQA

- src/resources/postcss/forms.pcss
- src/resources/postcss/tickets.pcss
🎫 no ticket
🎥 https://www.loom.com/share/5d728be8d0d845f69f47618452bed59e
Fix ET labels to work with the current version and the new common styles:  https://github.com/moderntribe/tribe-common/pull/1420
> Fix form labels to work with current version and new common styles.

- src/Tribe/RSVP.php
- src/Tribe/Tickets_View.php
[ET-809]
Screenshot: https://p199.p4.n0.cdn.getcloudapp.com/items/lluY2dzB/Screen%20Shot%202020-08-15%20at%2011.52.52%20AM.png?v=b94fdd70f0bedf6cc2871e30f2332a03
[ET-809]: https://moderntribe.atlassian.net/browse/ET-809
> [ET-809] Ensure proper actions are used before new RSVP FE views

- event-tickets.php
- package.json
- readme.txt
- src/Tribe/Editor/Blocks/Tickets.php
- src/Tribe/Editor/Blocks/Tickets_Item.php
- src/Tribe/Main.php
- src/Tribe/RSVP.php
[ET-901]
Hold on merge
Screencast: https://share.skc.dev/GGuRzY2D
[ET-901]: https://moderntribe.atlassian.net/browse/ET-901
> [ET-901] G20.09.1 Hotfix for AR Modal problems

- readme.txt
- src/Tribe/Tickets.php
🎫 [ET-899] bail if valid Post object with ID of zero
No test because only edited a non-public method.
1min demo: https://share.getcloudapp.com/jkuZAD15
[ET-899]: https://moderntribe.atlassian.net/browse/ET-899
> [ET-899] bail if valid Post object with ID of zero

- readme.txt
- src/views/tickets/view-link.php
- tests/_support/Testcases/TicketsBlock_TestCase.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block with data set 0__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block with data set 1__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block with data set 2__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 0__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 1__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 2__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 3__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 4__1.php
- tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockTest__test_should_render_ticket_block_after_update with data set 5__1.php
- tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set opt-in__1.php
- tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set success__1.php
[ET-910]
Fix failing tests from G20.09 and G20.08 work and the view links template errors in testing suite.
Screenshot
[ET-910]: https://moderntribe.atlassian.net/browse/ET-910
> [ET-910] Fix failing tests and view link template problem

- src/views/v2/attendee-registration/button/back-to-cart.php
- src/views/v2/attendee-registration/button/submit.php
- tests/_support/Partials/V2TestCase.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Attendee_Registration/Button/Back_To_CartTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Attendee_Registration/Button/SubmitTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Attendee_Registration/Button/__snapshots__/Back_To_CartTest__test_should_render_nothing_if_cart_and_checkout_url_match__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Attendee_Registration/Button/__snapshots__/Back_To_CartTest__test_should_render_nothing_if_cart_url_is_empty__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Attendee_Registration/Button/__snapshots__/Back_To_CartTest__test_should_render_successfully__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Attendee_Registration/Button/__snapshots__/SubmitTest__test_should_render_successfully__1.php
[ETP-471]
[ETP-471]: https://moderntribe.atlassian.net/browse/ETP-471
> [ETP-471] v2 tests for Attendee Registration

- src/Tribe/Assets.php
- src/resources/js/v2/rsvp-manager.js
- src/resources/js/v2/tickets-loader.js
🎫 ETP-455
🎥 https://www.loom.com/share/536e9d639b084a53ab8581660967e335 
This code was already reviewed here: https://github.com/moderntribe/event-tickets/pull/1774
> [ETP-455] Tickets views V2 > Componetize loader library.

- src/views/v2/tickets/item/extra/available.php
- src/views/v2/tickets/item/extra/available/quantity.php
- src/views/v2/tickets/item/extra/available/unlimited.php
- src/views/v2/tickets/item/extra/price.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/QuantityTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/UnlimitedTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/QuantityTest__test_should_not_render_quantity_block_if_threshold_smaller_than_available_quantity__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/QuantityTest__test_should_render_quantity_block__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/QuantityTest__test_should_render_quantity_block_if_threshold_greater_than_available_quantity__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/UnlimitedTest__test_should_not_render_if_available_quantity_is_not_unlimited__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/UnlimitedTest__test_should_not_render_if_show_unlimited_is_false__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/UnlimitedTest__test_should_render_unlimited_text__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/AvailableTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Description_ToggleTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/PriceTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/AvailableTest__test_should_not_render_available_block_if_is_mini__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/AvailableTest__test_should_render_available_block__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_is_mini__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_is_modal__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_ticket_description_is_empty__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_ticket_show_description_is_false__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_render_if_is_not_modal_or_mini_and_has_description__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/PriceTest__test_should_render_price_block_for_product_on_sale__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/PriceTest__test_should_render_price_block_for_regular_product__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/PriceTest__test_should_render_price_block_with_price_suffix__1.php
[ETP-473]
Adding Tests for 'Ticket/Item/Extra'
Adding more tests over the previous PR #1787
[ETP-473]: https://moderntribe.atlassian.net/browse/ETP-473
> [ETP-473] Tests/v2 snapshots Part 3

- readme.txt
- src/views/blocks/attendees/title.php
- src/views/blocks/attendees/view-link.php
- src/views/blocks/tickets/registration/summary/ticket-price.php
- src/views/tickets/view-link.php
🎫 [ET-919] No artifact
[ET-919]: https://moderntribe.atlassian.net/browse/ET-919
> [ET-919] correct some template override comments

- src/views/v2/tickets/item/content/title.php
🎫 [ET-918]
no artifact needed
[ET-918]: https://moderntribe.atlassian.net/browse/ET-918
> [ET-918] don't escape the title

- src/Tribe/Assets.php
🎫 ETP-459
🎥 https://www.loom.com/share/aa65f147c2d94befb29ed06a163eae22
Keep and use only the V1 of AR page styleesheet in ET.
For V2 we're moving the AR Page stylesheet to ET+ ➡️ https://github.com/moderntribe/event-tickets-plus/pull/1046
> [ETP-459] Use ET AR page stylesheet only for V1.

- src/Tribe/Editor/Blocks/Tickets.php
- src/Tribe/Tickets_View.php
🎫 no ticket
🎥 https://www.loom.com/share/c88cc394b1054b6eb5f3586e4127dbf8
> Tickets V2 Block > Use tickets view logic for rendering.

- readme.txt
- src/resources/postcss/tickets-v1.pcss
🎫 https://moderntribe.atlassian.net/browse/ET-922
🎥 https://www.loom.com/share/4bca8dede5fe44b596f78e7bc0b54cb1
> [ET-922] Fix specificity on the V1 stylesheet for radios and checkboxes.

- src/views/v2/tickets/item/content/description-toggle.php
- src/views/v2/tickets/item/content/description.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/DescriptionTest__test_should_render_if_not_is_mini_and_valid_ticket__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/Description_ToggleTest__test_should_render_if_is_modal_and_valid_ticket__1.php
- tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php
🎫 https://moderntribe.atlassian.net/browse/ET-921
🎥 https://www.loom.com/share/ee80c5c4d23a49a683ea09d43594539a
Ref: https://github.com/moderntribe/event-tickets/pull/1792#discussion_r498717959
> [ET-921] Fix ternary on string concatenation.

- src/resources/js/tickets.js
[ETP-389]
Dependency for PR: https://github.com/moderntribe/event-tickets-plus/pull/1052
[ETP-389]: https://moderntribe.atlassian.net/browse/ETP-389
> Send `select` type data over Ajax for saving ticket meta box info

- src/admin-views/attendees.php
[ETP-395]
Dependency for: https://github.com/moderntribe/event-tickets-plus/pull/1062
No artifacts are available for this. Check the PR linked above for details.
[ETP-395]: https://moderntribe.atlassian.net/browse/ETP-395
> [ETP-395] Add entry point for IAC support

- src/views/tickets/orders.php
[ETP-437]
No artifacts.
[ETP-437]: https://moderntribe.atlassian.net/browse/ETP-437
> [ETP-437] Disable resend of emails using filters on attendee email update

- src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/template.js
[ETP-551]
[ETP-551]: https://moderntribe.atlassian.net/browse/ETP-551
> [ETP-551] Updated IAC settings helper text on Block Editor

- src/Tribe/Commerce/Cart.php
- src/Tribe/Commerce/PayPal/Main.php
[ETP-402]
Filtered by the work done in: https://github.com/moderntribe/event-tickets-plus/pull/1069
Screenshot of it working as intended:
[ETP-402]: https://moderntribe.atlassian.net/browse/ETP-402
> [ETP-402] IAC > Include initial IAC information for tickets in cart
